
/*
CREATE TABLE AUXPRODXFORN
(
	CODPROD 	VARCHAR(15),
	CODPRODFORN	VARCHAR(100)
)
*/


DELETE FROM AUXPRODXFORN

		
	BULK 
INSERT AUXPRODXFORN
        FROM 'C:\TEMP\update.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO



UPDATE SA5010 SET A5_CODPRF = PXF.CODPRODFORN
FROM SB1010 SB1
LEFT JOIN SA5010 SA5 ON SA5.D_E_L_E_T_ = '' AND SA5.A5_PRODUTO = SB1.B1_COD
LEFT JOIN AUXPRODXFORN PXF ON PXF.CODPROD = SB1.B1_COD 
WHERE 1=1
AND SB1.D_E_L_E_T_ = '' 
AND PXF.CODPROD <> ''


SELECT 
SB1.B1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SA5.A5_CODPRF,
PXF.CODPRODFORN
FROM SB1010 SB1
LEFT JOIN SA5010 SA5 ON SA5.D_E_L_E_T_ = '' AND SA5.A5_PRODUTO = SB1.B1_COD 
LEFT JOIN AUXPRODXFORN PXF ON PXF.CODPROD = SB1.B1_COD 
WHERE 1=1
AND SB1.D_E_L_E_T_ = '' 
AND PXF.CODPROD <> ''





