/*
SB2 - ACERTO DE SALDOS DE RESERVA 

POR: EDUARDO / ALEXANDRE 
EM: 02/07/2020

OBS: DELETAR SC9 E SC0 E SC1  DO ATENDIMENTO/ORÇAMENTO EM QUESTÃO (D_E_L_E_T_ = '*'),
	 ZERAR O CAMPO DE RESERVA REFERENTE AO ATENDIMENTO/ORÇAMENTO EM QUESTAO (B2_RESERVA = 0) 
*/

SELECT 
B.B2_FILIAL 	AS FILIAL_SALDO,
A.B1_COD 		AS CODPROD,
A.B1_DESC		AS PRODUTO,
B.B2_LOCAL 		AS ARMZ,
B.B2_QATU		AS SLD_FIS,
B.B2_RESERVA	AS QTD_RES,
B.B2_QATU - B.B2_RESERVA AS SLD_DISP,
ISNULL(( SELECT SUM(C9_QTDLIB)  FROM SC9010 WHERE D_E_L_E_T_ = '' AND C9_FILIAL = B.B2_FILIAL AND C9_PRODUTO = A.B1_COD AND C9_LOCAL = B.B2_LOCAL AND C9_NFISCAL = '' AND C9_QTDLIB <> 0 AND C9_BLEST = ''),0) AS QTD_SC9,
ISNULL(( SELECT SUM(C1_QTDORIG) FROM SC1010 WHERE D_E_L_E_T_ = '' AND C1_FILIAL = B.B2_FILIAL AND C1_PRODUTO = A.B1_COD AND C1_LOCAL = B.B2_LOCAL AND C1_PEDIDO = '' AND C1_QUANT <> 0),0) AS QTD_SC1,
ISNULL(( SELECT SUM(C9_QTDLIB)  FROM SC9010 WHERE D_E_L_E_T_ = '' AND C9_FILIAL = B.B2_FILIAL AND C9_PRODUTO = A.B1_COD AND C9_LOCAL = B.B2_LOCAL AND C9_NFISCAL = '' AND C9_QTDLIB <> 0 AND C9_BLEST = ''),0) + ISNULL(( SELECT SUM(C1_QTDORIG)   FROM SC1010 WHERE D_E_L_E_T_ = '' AND C1_FILIAL = B.B2_FILIAL AND C1_PRODUTO = A.B1_COD AND C1_LOCAL = B.B2_LOCAL AND C1_PEDIDO = '' AND C1_QUANT <> 0),0) AS SOMA

--UPDATE SB2010 SET B2_RESERVA = 0
--UPDATE SB2010 SET B2_RESERVA = ISNULL(( SELECT SUM(C9_QTDLIB)  FROM SC9010 WHERE D_E_L_E_T_ = '' AND C9_FILIAL = B.B2_FILIAL AND C9_PRODUTO = A.B1_COD AND C9_LOCAL = B.B2_LOCAL AND C9_NFISCAL = '' AND C9_QTDLIB <> 0 AND C9_BLEST = ''),0) + ISNULL(( SELECT SUM(C1_QUANT)   FROM SC1010 WHERE D_E_L_E_T_ = '' AND C1_FILIAL = B.B2_FILIAL AND C1_PRODUTO = A.B1_COD AND C1_LOCAL = B.B2_LOCAL AND C1_PEDIDO = '' AND C1_QUANT <> 0),0)
FROM SB1010 A
LEFT JOIN SB2010 B ON B.D_E_L_E_T_ = '' AND A.B1_COD = B.B2_COD
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.B2_LOCAL = '01'
AND SUBSTRING(A.B1_GRUPO,1,2) = 'MR'
--AND B.B2_RESERVA <> 0 
AND A.B1_COD  = 'LB012F'

