
/*
ALTER DATABASE PROTHEUS_ZANOTTI_TESTE SET COMPATIBILITY_LEVEL = 130

SELECT * FROM ZZ6010

*/

DECLARE @JSON VARCHAR(MAX)
DECLARE @DATA VARCHAR(MAX)
DECLARE @IDPIPE VARCHAR(MAX)
DECLARE @ATM VARCHAR(MAX)
DECLARE @QUALIFICADOR VARCHAR(MAX)
DECLARE @VALOR	FLOAT
DECLARE @STATUS VARCHAR(MAX)
DECLARE @USER_ID VARCHAR(MAX)
DECLARE @VENDEDOR VARCHAR(MAX)

SET @JSON = 		ISNULL((SELECT CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX),ZZ6_RGPIPE)) AS JSON FROM ZZ6010 WHERE 1=1 AND D_E_L_E_T_ = '' AND ZZ6_IDPIPE  = '015656'),'')
SET @DATA = 		ISNULL((SELECT value FROM OpenJson(@JSON) WHERE [key] = 'data'),'')
SET @USER_ID = 		ISNULL((SELECT value FROM OpenJson(@DATA) WHERE [key] = 'user_id'),'')
SET @IDPIPE = 		ISNULL((SELECT value FROM openjson(@DATA) WHERE [key] = 'id'),'')
SET @ATM = 			ISNULL((SELECT value FROM openjson(@DATA) WHERE [key] = 'd222517f532966fa58ba76038ec4c4a4d18cdda3'),'')
SET @QUALIFICADOR = ISNULL((SELECT value FROM openjson(@DATA) WHERE [key] = '031eba7fc1130de70097f4025537c43c4b30c07e'),'')
SET @VALOR = 		ISNULL((SELECT value FROM openjson(@DATA) WHERE [key] = 'value'),'')
SET @STATUS = 		ISNULL((SELECT value FROM openjson(@DATA) WHERE [key] = 'status'),'')
SET @VENDEDOR = 	ISNULL((SELECT value FROM OpenJson(@USER_ID) WHERE [key] = 'name'),'')

SELECT 
@IDPIPE AS IDPIPE,
@ATM AS ATM,
@QUALIFICADOR AS QUALIFICADOR, 
@VENDEDOR AS VENDEDOR,
@VALOR AS VALOR,
@STATUS AS STATUS,
@JSON AS JSON

