
/*
Inserir produtos na tabela SB5 com as dimenssões
cadastradas na tabela Auxiliar
*/

DECLARE @RECNO INT
DECLARE @CONT  INT
DECLARE @MAX   INT

SET @CONT  = 1
SET @RECNO = ISNULL((SELECT MAX(R_E_C_N_O_) + 1 FROM SB5010),0)
SET @MAX   = ISNULL((SELECT COUNT(*) FROM AUX_PAINEL),0)


WHILE @CONT <= @MAX
BEGIN

INSERT INTO SB5010 
(
B5_FILIAL, 
B5_COD, 
B5_CEME, 
B5_UMIND, 
B5_PROTOTI, 
B5_INTDI, 
B5_LARG, 
B5_COMPR, 
R_E_C_N_O_
)

SELECT
'0101'		AS B5_FILIAL,
CODPROD		AS B5_COD,
DESC_REDU	AS B5_CEME,
'1'			AS B5_UMIND,
'F'			AS B5_PROTOTI,
'2'			AS B5_INTDI,
COMPRIMENTO	AS B5_LARG,
LARGURA		AS B5_COMPR,
@RECNO		AS R_E_C_N_O_
FROM AUX_PAINEL
WHERE 1=1
AND IDENT = @CONT


SET @CONT = @CONT + 1
SET @RECNO = @RECNO + 1

END

