

/*---------------------- CADASTRO 1 ----------------------*/

SELECT 
CONCAT(A.CODIGO, ' - ', A.NOME) AS PRODUTO,
COUNT(CONCAT(A.CODIGO,' - ',A.NOME)) QTD_CAD
FROM PD_PRODUTOS A
WHERE 1=1
--AND NOME LIKE '%DIPIRONA%' 
--AND CODIGO = 30847 /*MAIOR DESCRICAO EVER*/
GROUP BY 
A.CODIGO,
A.NOME

