
SELECT 
A.CODIGO			AS COD_PROD,
A.NOME				AS PRODUTO,
C.EMPRESA			AS EMPRESA,
C.FILIAL			AS FILIAL,
C.NOME				AS ALMOXARIFADO,
B.ESTOQUEDISPONIVEL	AS QTD,
D.NOME				AS UNIDADE
FROM PD_PRODUTOS A
LEFT JOIN PD_ALMOXARIFADOPRODUTOS B ON B.PRODUTO = A.HANDLE
LEFT JOIN PD_ALMOXARIFADOS C ON C.HANDLE = B.ALMOXARIFADO
LEFT JOIN CM_UNIDADESMEDIDA D ON D.HANDLE = B.UNIDADEESTOCAGEM
WHERE 1=1
AND B.ESTOQUEDISPONIVEL > 0

