


--"VARIAVEL TOTAL UT"*((100- "VARIAVEL TAXA" )/100)
--"VARIAVEL TOTAL EQ"*((100- "VARIAVEL TAXA" )/100)

SELECT
MAPA_VENDA.FILIAL,
MAPA_VENDA.SERIE,
MAPA_VENDA.DOC,
MAPA_VENDA.COD_VEND,
MAPA_VENDA.VENDEDOR,
ISNULL((SELECT MEN_TAXADM FROM MEN010 WHERE D_E_L_E_T_ = '' AND MEN_CODADM = ISNULL((SELECT TOP 1 E3_CODCLI FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND AND E3_TIPO IN ('CC','CD')),'')  AND MEN_PARFIN >= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'') AND MEN_PARINI <= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'')),0) AS TAXA,
ISNULL((SELECT TOP 1 E3_TIPO FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND AND E3_TIPO IN ('CC','CD')),'') AS MAX_PARC,
MAPA_VENDA.TOTAL_UT * ((100 - ISNULL((SELECT MEN_TAXADM FROM MEN010 WHERE D_E_L_E_T_ = '' AND MEN_CODADM = ISNULL((SELECT TOP 1 E3_CODCLI FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND AND E3_TIPO IN ('CC','CD')),'')  AND MEN_PARFIN >= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'') AND MEN_PARINI <= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'')),0)) / 100) AS UT,
MAPA_VENDA.TOTAL_EQ * ((100 - ISNULL((SELECT MEN_TAXADM FROM MEN010 WHERE D_E_L_E_T_ = '' AND MEN_CODADM = ISNULL((SELECT TOP 1 E3_CODCLI FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND AND E3_TIPO IN ('CC','CD')),'')  AND MEN_PARFIN >= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'') AND MEN_PARINI <= ISNULL((SELECT MAX(E3_PARCELA) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'')),0)) / 100) AS EQ,
ISNULL((SELECT SUM(E3_BASE) FROM SE3010 WHERE D_E_L_E_T_ = '' AND E3_FILIAL = MAPA_VENDA.FILIAL AND E3_SERIE = MAPA_VENDA.SERIE AND E3_NUM = MAPA_VENDA.DOC AND E3_VEND = MAPA_VENDA.COD_VEND),'') AS BASE
FROM
(
SELECT
SL2.L2_FILIAL AS FILIAL,
SL2.L2_NUM	  AS NUM_ORC,
CASE
	WHEN SL2.L2_DOC <> ''
THEN SL2.L2_SERIE
	WHEN SL2.L2_DOCPED <> ''
THEN SL2.L2_SERPED
ELSE ''
END AS SERIE,
CASE
	WHEN SL2.L2_DOC <> ''
THEN SL2.L2_DOC
	WHEN SL2.L2_DOCPED <> ''
THEN SL2.L2_DOCPED
ELSE ''
END AS DOC,
SL1.L1_EMISNF AS DTFIN,
SL1.L1_VEND	  AS COD_VEND,
SA3.A3_NOME	  AS VENDEDOR,
SL2.L2_PRODUTO AS CODPROD,
SL2.L2_ITEM		AS ITEM,
SL2.L2_QUANT	QTD,
SL2.L2_VRUNIT	AS VLR_UNIT,
SL2.L2_VLRITEM AS VLR_ITEM,
SB1.B1_GRUPO	AS GRUPO,
ISNULL((
SELECT 
SUM(A.L2_VLRITEM) 
FROM 
SL2010 A
LEFT JOIN SB1010 B ON B.D_E_L_E_T_ = '' AND A.L2_PRODUTO = B.B1_COD
WHERE 1=1
AND A.D_E_L_E_T_ = '' 
AND A.L2_FILIAL = SL2.L2_FILIAL 
AND A.L2_NUM = SL2.L2_NUM 
AND B.B1_GRUPO = 'MRUT'
),0) AS TOTAL_UT,
ISNULL((
SELECT 
SUM(A.L2_VLRITEM) 
FROM 
SL2010 A
LEFT JOIN SB1010 B ON B.D_E_L_E_T_ = '' AND A.L2_PRODUTO = B.B1_COD
WHERE 1=1
AND A.D_E_L_E_T_ = '' 
AND A.L2_FILIAL = SL2.L2_FILIAL 
AND A.L2_NUM = SL2.L2_NUM 
AND B.B1_GRUPO <> 'MRUT'
),0) AS TOTAL_EQ
FROM SL1010 SL1
LEFT JOIN SL2010 SL2 ON SL2.D_E_L_E_T_ = '' AND SL2.L2_FILIAL = SL1.L1_FILIAL AND SL2.L2_NUM = SL1.L1_NUM
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SL1.L1_VEND
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SL2.L2_PRODUTO
WHERE 1=1
AND SL1.D_E_L_E_T_ = '' 
AND SL1.L1_VEND = '000030'
AND YEAR(SL1.L1_EMISNF) = 2021
AND MONTH(SL1.L1_EMISNF) = 04
--AND SL2.L2_NUM = '005157'
AND SL2.L2_NUM = '005135'
) AS MAPA_VENDA
GROUP BY
MAPA_VENDA.FILIAL,
MAPA_VENDA.SERIE,
MAPA_VENDA.DOC,
MAPA_VENDA.COD_VEND,
MAPA_VENDA.VENDEDOR,
MAPA_VENDA.TOTAL_EQ,
MAPA_VENDA.TOTAL_UT