
/* USUARIOS */
SELECT * FROM SYS_USR

/* PRIVILEGIOS */
SELECT * FROM SYS_RULES

/* GRUPOS */
SELECT * FROM SYS_GRP_GROUP

/* RELACIONAMENTOS */
SELECT * FROM SYS_USR_GROUPS
SELECT * FROM SYS_RULES_USR_RULES


SELECT 
B.USR_ID,
B.USR_CODIGO,
C.RL__CODIGO
FROM SYS_RULES_USR_RULES A
LEFT JOIN SYS_USR B ON B.D_E_L_E_T_ = '' AND B.USR_ID = A.USER_ID
LEFT JOIN SYS_RULES C ON C.D_E_L_E_T_ = '' AND C.RL__ID = A.USR_RL_ID
WHERE 1=1
AND A.D_E_L_E_T_ = ''


SELECT * 
FROM SYS_USR_GROUPS A
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND A.USR_GRUPO IN ('000002','000003')


