
SELECT 
LEFT(UPPER(A.NOME), 50) 	AS NOME,
REPLACE(REPLACE(A.CPF, '.', ''),'-','')	AS CPF,
'I' 	AS OPERACAO

FROM K_CN_CONTRATOBENEFICIARIOS A
LEFT JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO 
LEFT JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO AND C.STATUS = 1
LEFT JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE 1=1
/*VIDAS ATIVAS*/		AND A.STATUS = 1
/*TEM ATENDIMENTO*/		AND A.TEMATENDIMENTO = 'S'
/*CONTRATOS ATIVOS*/	AND B.STATUS = 2
--/*TIPOS CONTRATOS*/ 	AND C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55) 
/*EMPRESAS FILTRADAS*/	AND D.HANDLE IN (1, 2, 3, 5, 17, 18)
/*DATA INCLUSAO VIDA*/	AND A.DATAINCLUIU <= CONVERT(DATE,'2023-03-13')
AND A.CPF NOT IN ('','. . -', '..-', '.   .   -', '   .   .   -', '.  .  -', '0','RG: 20070236229','PASAPORTE: 667738380','O 	SOLTEIRO','O 	NÃO INFORMA','NO	NÃO INFORMA')



/* CADASTROS LISTADOS */
/*
-- EMPRESAS
SELECT * FROM EMPRESAS

-- TIPOS DE CONTRATOS
SELECT * FROM CN_TIPOSCONTRATOS WHERE STATUS = 1
*/