/*-----------------------VARIAVEIS-------------------------*/

DECLARE @cDatIni VARCHAR(8)
DECLARE @cDatFim VARCHAR(8)
DECLARE @ANOINI INT;
DECLARE @ANOFIM INT;
DECLARE @MESINI INT;
DECLARE @MESFIM INT;
DECLARE @SALDO VARCHAR(15);
DECLARE @CUSTO VARCHAR(15);
SET @ANOINI = 2018
SET @ANOFIM = 2018
SET @MESINI = 01
SET @MESFIM = 12
SET @cDatIni = ISNULL(( SELECT CONCAT(@ANOINI,'0' ,@MESINI ,'01') AS SALDO  ),0) 
SET @cDatFim = ISNULL(( SELECT CONCAT(@ANOINI,'0' ,@MESINI ,'31') AS SALDO  ),0) 


	SET @SALDO =	ISNULL(( SELECT CONCAT( 'Z', @ANOINI, @MESINI) AS SALDO  ),0) 
	SET @CUSTO = 	ISNULL(( SELECT CONCAT( 'ZCUST', @ANOINI, @MESINI) AS CUSTO  ),0)
	SELECT @cDatIni, @cDatFim
	SELECT @SALDO, @CUSTO    


/--------------------------CREAT TABLE #PRINCIPAL------------------------/


CREATE TABLE #SALDO_ESTOQUE_MENSAL
    (
     SEM_CODPROD VARCHAR(15),
   	 SEM_PRODUTO VARCHAR(70),
	 SEM_UND	 VARCHAR(2),
	 SEM_CUSTPROD FLOAT,
     Z20181 FLOAT,
     ZCUST20181 FLOAT,
     Z20182 FLOAT,
     ZCUST20182 FLOAT,
     Z20183 FLOAT,
     ZCUST20183 FLOAT,
     Z20184 FLOAT,
     ZCUST20184 FLOAT,
     Z20185 FLOAT,
     ZCUST20185 FLOAT,
     Z20186 FLOAT,
     ZCUST20186 FLOAT,
     Z20187 FLOAT,
     ZCUST20187 FLOAT,
     Z20188 FLOAT,
     ZCUST20188 FLOAT,
     Z20189 FLOAT,
     ZCUST20189 FLOAT,
     Z201810 FLOAT,
     ZCUST201810 FLOAT,
     Z201811 FLOAT,
     ZCUST201811 FLOAT,
     Z201812 FLOAT,
     ZCUST201812 FLOAT,
     Z20191 FLOAT,
     ZCUST20191 FLOAT,
     Z20192 FLOAT,
     ZCUST20192 FLOAT,
     Z20193 FLOAT,
     ZCUST20193 FLOAT,
     Z20194 FLOAT,
     ZCUST20194 FLOAT,
     Z20195 FLOAT,
     ZCUST20195 FLOAT,
     Z20196 FLOAT,
     ZCUST20196 FLOAT,
     Z20197 FLOAT,
     ZCUST20197 FLOAT,
     Z20198 FLOAT,
     ZCUST20198 FLOAT,
     Z20199 FLOAT,
     ZCUST20199 FLOAT,
     Z201910 FLOAT,
     ZCUST201910 FLOAT,
     Z201911 FLOAT,
     ZCUST201911 FLOAT,
     Z201912 FLOAT,
     ZCUST201912 FLOAT,
     Z20201 FLOAT,
     ZCUST20201 FLOAT,
     Z20202 FLOAT,
     ZCUST20202 FLOAT,
     Z20203 FLOAT,
     ZCUST20203 FLOAT,
     Z20204 FLOAT,
     ZCUST20204 FLOAT
    )
    
/--------------------------CREAT TABLE #AUX------------------------/


CREATE TABLE #AUX
    (
     CODPROD VARCHAR(15),
   	 PRODUTO VARCHAR(70),
	 UND	 VARCHAR(2),
	 CUSTPROD FLOAT,
     SALDO_FINAL FLOAT,
     CUSTO_FINAL FLOAT,
	)


/*-------------------------------INSERT #AUX---------------------------------------*/


INSERT INTO #AUX (CODPROD, PRODUTO, UND, CUSTPROD, SALDO_FINAL, CUSTO_FINAL) 

SELECT *,
(SELECT_PRINCIPAL.SALDO_FINAL * SELECT_PRINCIPAL.CUSTO_PROD) AS CUSTO_FINAL
FROM(
SELECT 
SALDO.COD_PROD,
SALDO.PRODUTO,
SALDO.UND,
SALDO.CUSTO_PROD,
--SALDO.SLD_INI_SB9,
--SALDO.QTD_ENT_SD1,
--SALDO.QTD_SAI_SD2,
--SALDO.QTD_ENT_SD3,
--SALDO.QTD_SAI_SD3,
SALDO.SLD_INI_SB9 + ( SALDO.QTD_ENT_SD1 + SALDO.QTD_ENT_SD3 ) - ( SALDO.QTD_SAI_SD2 + SALDO.QTD_SAI_SD3 ) AS SALDO_FINAL
FROM (
SELECT 	A.B1_COD  AS COD_PROD,
		A.B1_DESC AS PRODUTO,
		A.B1_UM   AS UND,
		A.B1_CUSTD AS CUSTO_PROD,
		ISNULL(( SELECT SUM(B9_QINI)  FROM SB9010 WHERE D_E_L_E_T_ = '' AND B9_COD = A.B1_COD AND YEAR(B9_DATA) = 2017),0) AS SLD_INI_SB9,
		ISNULL(( SELECT SUM(D1_QUANT) FROM SD1010 AS SD1, SF4010 AS SF4 WHERE SD1.D_E_L_E_T_ = '' AND SF4.D_E_L_E_T_ = '' AND SD1.D1_COD = A.B1_COD AND SD1.D1_DTDIGIT BETWEEN @cDatIni AND @cDatFim AND SD1.D1_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_ENT_SD1,
		ISNULL(( SELECT SUM(D2_QUANT) FROM SD2010 AS SD2, SF4010 AS SF4 WHERE SD2.D_E_L_E_T_ = '' AND SF4.D_E_L_E_T_ = '' AND SD2.D2_COD = A.B1_COD AND SD2.D2_EMISSAO BETWEEN @cDatIni AND @cDatFim AND SD2.D2_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_SAI_SD2,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010  WHERE D_E_L_E_T_ = '' AND D3_COD = A.B1_COD AND D3_TM <= '499' AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_ENT_SD3,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010  WHERE D_E_L_E_T_ = '' AND D3_COD = A.B1_COD AND D3_TM >= '500' AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_SAI_SD3	
FROM SB1010 A
LEFT JOIN SD1010 B ON A.B1_COD = B.D1_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD2010 C ON A.B1_COD = C.D2_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SD3010 D ON A.B1_COD = D.D3_COD AND D.D_E_L_E_T_ = ''
LEFT JOIN SB9010 E ON A.B1_COD = E.B9_COD AND E.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
--AND A.B1_GRUPO = 'MPCH'
--AND A.B1_COD = 'LB012F'
GROUP BY A.B1_COD, A.B1_DESC, A.B1_UM, A.B1_CUSTD
) AS SALDO
) AS SELECT_PRINCIPAL


/-----------------INSERT NA TABELA PRINCIPAL----------------------/


INSERT INTO #SALDO_ESTOQUE_MENSAL (SEM_CODPROD, SEM_PRODUTO, SEM_UND, SEM_CUSTPROD, Z20181, ZCUST20181) 
SELECT * FROM #AUX


/*----------------------UPDATE TABELA PRINCIPAL-------------------------*/


UPDATE
    #SALDO_ESTOQUE_MENSAL
SET
    #SALDO_ESTOQUE_MENSAL.Z201802 = #AUX.SALDO_FINAL,
    #SALDO_ESTOQUE_MENSAL.ZCUST201802 = #AUX.CUSTO_FINAL
FROM
    #SALDO_ESTOQUE_MENSAL
INNER JOIN
    #AUX
ON
    #SALDO_ESTOQUE_MENSAL.SEM_CODPROD = #AUX.CODPROD








/*--------------------------SELECT------------------------------------------*/

SELECT * FROM #SALDO_ESTOQUE_MENSAL
SELECT * FROM #AUX

/*------------------------------DROP--------------------------------------*/

DROP TABLE #SALDO_ESTOQUE_MENSAL
DROP TABLE #AUX

