
DECLARE @cDatIni VARCHAR(8)
DECLARE @cDatFim VARCHAR(8)
DECLARE @ANOINI INT;
DECLARE @ANOFIM INT;
DECLARE @MESINI INT;
DECLARE @MESFIM INT;
DECLARE @SALDO VARCHAR(15);
DECLARE @CUSTO VARCHAR(15);
DECLARE @N INT;
SET @ANOINI = 2018
SET @ANOFIM = 2018
SET @MESINI = 02
SET @MESFIM = 12
SET @N = 1

	
WHILE  @N <= 12
BEGIN
			
SET @cDatIni = 	ISNULL(( SELECT CONCAT(@ANOINI,'0' ,@MESINI ,'01') AS SALDO  ),0) 
SET @cDatFim = 	ISNULL(( SELECT CONCAT(@ANOINI,'0' ,@MESINI ,'31') AS SALDO  ),0) 
SET @SALDO =	ISNULL(( SELECT CONCAT( 'Z', @ANOINI, '0', @MESINI) AS SALDO  ),0) 
SET @CUSTO = 	ISNULL(( SELECT CONCAT( 'ZCUST', @ANOINI, '0', @MESINI) AS CUSTO  ),0)
IF @MESINI >= 10
SET @cDatIni = 	ISNULL(( SELECT CONCAT(@ANOINI, @MESINI ,'01') AS SALDO  ),0) 
SET @cDatFim = 	ISNULL(( SELECT CONCAT(@ANOINI, @MESINI ,'31') AS SALDO  ),0) 
SET @SALDO =	ISNULL(( SELECT CONCAT( 'Z', @ANOINI, @MESINI) AS SALDO  ),0) 
SET @CUSTO = 	ISNULL(( SELECT CONCAT( 'ZCUST', @ANOINI, @MESINI) AS CUSTO  ),0)


--SELECT @cDatIni, @cDatFim, @SALDO, @CUSTO
	  


UPDATE
    #SALDO_ESTOQUE_MENSAL
SET
    #SALDO_ESTOQUE_MENSAL.+@SALDO+ = #AUX.SALDO_FINAL,
    #SALDO_ESTOQUE_MENSAL.+@CUSTO+ = #AUX.CUSTO_FINAL
FROM
    #SALDO_ESTOQUE_MENSAL
INNER JOIN
    #AUX
ON
    #SALDO_ESTOQUE_MENSAL.SEM_CODPROD = #AUX.CODPROD




SET @MESINI = @MESINI + 1;   
SET @N = @N + 1

END;  



