
SELECT 
SA1.A1_COD		AS COD_CLI,
SA1.A1_NOME		AS NOME,
SA1.A1_EMAIL	AS EMAIL,
dbo.formatarCNPJCPF(SA1.A1_CGC) AS CNPJ_CPF,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
ISNULL((SELECT SUM(A.L1_VLRTOT)  FROM SL1010 A WHERE A.D_E_L_E_T_ = '' AND A.L1_CLIENTE = SA1.A1_COD AND A.L1_LOJA = SA1.A1_LOJA AND A.L1_EMISNF <> '' AND A.L1_ORCRES = ''),0) AS VALOR_FIN,
ISNULL((SELECT MIN(A.L1_EMISNF)  FROM SL1010 A WHERE A.D_E_L_E_T_ = '' AND A.L1_CLIENTE = SA1.A1_COD AND A.L1_LOJA = SA1.A1_LOJA AND A.L1_EMISNF <> '' AND A.L1_ORCRES = ''),'') AS PRIMEIRO_FIN,
ISNULL((SELECT MAX(A.L1_EMISNF)  FROM SL1010 A WHERE A.D_E_L_E_T_ = '' AND A.L1_CLIENTE = SA1.A1_COD AND A.L1_LOJA = SA1.A1_LOJA AND A.L1_EMISNF <> '' AND A.L1_ORCRES = ''),'') AS ULTIMO_FIN,
ISNULL((SELECT SUM(A.F2_VALBRUT) FROM SF2010 A WHERE A.D_E_L_E_T_ = '' AND A.F2_CLIENTE = SA1.A1_COD AND A.F2_LOJA = SA1.A1_LOJA),0) AS VALOR_NF,
ISNULL((SELECT MIN(A.F2_EMISSAO) FROM SF2010 A WHERE A.D_E_L_E_T_ = '' AND A.F2_CLIENTE = SA1.A1_COD AND A.F2_LOJA = SA1.A1_LOJA),'') AS PRIMEIRO_NF,
ISNULL((SELECT MAX(A.F2_EMISSAO) FROM SF2010 A WHERE A.D_E_L_E_T_ = '' AND A.F2_CLIENTE = SA1.A1_COD AND A.F2_LOJA = SA1.A1_LOJA),'') AS ULTIMO_NF,
ISNULL((SELECT COUNT(CONCAT(A.F2_FILIAL, A.F2_SERIE, A.F2_DOC, A.F2_CLIENTE, A.F2_LOJA)) FROM SF2010 A WHERE A.D_E_L_E_T_ = '' AND A.F2_CLIENTE = SA1.A1_COD AND A.F2_LOJA = SA1.A1_LOJA),0) AS QTD_NF
FROM SA1010 SA1
WHERE 1=1
AND SA1.D_E_L_E_T_ = ''
AND SA1.A1_COD NOT IN 
(
'021950',
'022105',
'020518',
'001798'
)