
/*///////////////////////////////////////////////////
/													/
/													/
/			         DETALHADO	 					/
/													/
/													/
*////////////////////////////////////////////////////


SELECT 
SUA.UA_FILIAL	AS FILIAL,
SUA.UA_NUM		AS ATEDNIMENTO,
SL1.L1_VALMERC	AS VALOR_PROD,
SL1.L1_VALBRUT	AS VALOR_VENDA,
SUA.UA_CLIENTE	AS COD_CLI,
SA1.A1_NOME		AS CLIENTE,
SUA.UA_VEND		AS COD_VEND,
SA3.A3_NOME		AS VENDEDOR,
SL1.L1_EMISNF 	AS DATA,
CASE
	WHEN SL1.L1_DOC <> ''
THEN SL1.L1_SERIE
ELSE SL1.L1_SERPED
END AS PREFIXO,
CASE
	WHEN SL1.L1_DOC <> ''
THEN SL1.L1_DOC
ELSE SL1.L1_DOCPED
END AS TITULO
FROM SUA010 SUA
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
WHERE 1=1
AND SUA.D_E_L_E_T_ = '' 
AND SL1.L1_EMISNF <> ''
AND SL1.L1_EMISNF BETWEEN '20210101' AND '20210131'


/*///////////////////////////////////////////////////
/													/
/													/
/			     SOMA POR VENDEDOR 					/
/													/
/													/
*////////////////////////////////////////////////////

SELECT 
SUA.UA_VEND		AS COD_VEND,
SA3.A3_NOME		AS VENDEDOR,
SUM(SL1.L1_VALMERC)	AS VALOR_PROD,
SUM(SL1.L1_VALBRUT)	AS VALOR_VENDA
FROM SUA010 SUA
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
WHERE 1=1
AND SUA.D_E_L_E_T_ = '' 
AND SL1.L1_EMISNF <> ''
AND SL1.L1_EMISNF BETWEEN '20210101' AND '20210131'
GROUP BY
SUA.UA_VEND,
SA3.A3_NOME