
SELECT
/*PRODUTOS*/
SUB.UB_PRODUTO,
SB1.B1_COD,	
SC6A.C6_PRODUTO AS PROD_TROCADO,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN SC6A.C6_PRODUTO
	WHEN SC6A.C6_PRODUTO IS NULL
THEN SB1.B1_COD
END AS CODPROD_REAL,
/*SUA*/
SUA.UA_FILIAL,
SUA.UA_NUM,
SUA.UA_CLIENTE,
SUA.UA_LOJA,
SUA.UA_CODCONT, 
SUA.UA_VEND,
/*SUB*/
SUB.UB_FILIAL,
SUB.UB_NUM,
/*SB1*/
SB1.B1_PROC,
SB1.B1_LOJPROC,
SB1.B1_GRUPO,
/*SA1*/
SA1.A1_COD,
SA1.A1_LOJA,
/*SU5*/
SU5.U5_CODCONT,
/*SA2*/
SA2.A2_COD,
SA2.A2_LOJA,
/*SA3*/
SA3.A3_COD,
SA3.A3_ZSITVND,
/*SC0*/
SC0.C0_FILRES,
SUBSTRING(SC0.C0_OBS,8,6) AS SUBSTRING_SC0_OBS,
SC0.C0_PRODUTO,
/*SL1*/
SL1.L1_FILIAL,
SL1.L1_NUM,
SL1.L1_NUMATEN,
SL1.L1_ORCRES,
/*SL2 PAI*/
SL2A.L2_FILIAL 	AS L2_FILIAL_PAI,
SL2A.L2_FILRES 	AS L2_FILRES_PAI,
SL2A.L2_NUM		AS L2_NUM_PAI,
SL2A.L2_PRODUTO AS L2_PRODUTO_PAI, 
SL2A.L2_ITEM	AS L2_ITEM_PAI,
SL2A.L2_SOLCOM	AS L2_SOLCOM_PAI,
SL2A.L2_ORCRES	AS L2_ORCRES_PAI,
SL2A.L2_PEDRES	AS L2_PEDRES_PAI,
/*SL2 FILHO*/
SL2B.L2_FILIAL 	AS L2_FILIAL_FILHO,
SL2B.L2_FILRES 	AS L2_FILRES_FILHO,
SL2B.L2_NUM		AS L2_NUM_FILHO,
SL2B.L2_PRODUTO AS L2_PRODUTO_FILHO, 
SL2B.L2_ITEM	AS L2_ITEM_FILHO,
SL2B.L2_SOLCOM	AS L2_SOLCOM_FILHO,
SL2B.L2_ORCRES	AS L2_ORCRES_FILHO,
SL2B.L2_PEDRES	AS L2_PEDRES_FILHO,
/*SC6*/
CASE 
	WHEN SC6X.C6_FILIAL <> ''
THEN SC6X.C6_FILIAL
	WHEN SC6A.C6_FILIAL <> ''
THEN SC6A.C6_FILIAL
ELSE SC6.C6_FILIAL
END AS C6_FILIAL,
CASE 
	WHEN SC6X.C6_NUM <> ''
THEN SC6X.C6_NUM
	WHEN SC6A.C6_NUM <> ''
THEN SC6A.C6_NUM
ELSE SC6.C6_NUM
END AS C6_NUM,
CASE 
	WHEN SC6X.C6_ITEM <> ''
THEN SC6X.C6_ITEM
	WHEN SC6A.C6_ITEM <> ''
THEN SC6A.C6_ITEM
ELSE SC6.C6_ITEM
END AS C6_ITEM,
CASE 
	WHEN SC6X.C6_PRODUTO <> ''
THEN SC6X.C6_PRODUTO
	WHEN SC6A.C6_PRODUTO <> ''
THEN SC6A.C6_PRODUTO
ELSE SC6.C6_PRODUTO
END AS C6_PRODUTO,
CASE 
	WHEN SC6X.C6_SOLCOM <> ''
THEN SC6X.C6_SOLCOM
	WHEN SC6A.C6_SOLCOM <> ''
THEN SC6A.C6_SOLCOM
ELSE SC6.C6_SOLCOM
END AS C6_SOLCOM
/*------------------RELACIONAMENTOS---------------------*/
/*ATENDIMENTO*/	FROM SUA010 SUA
/*PRODUTOS ATM*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ = ''  AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
/*CAD PROD*/   	LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ = ''  AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/    LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*CONTATO*/		LEFT JOIN SU5010 SU5  ON SU5.D_E_L_E_T_ = ''  AND SU5.U5_CODCONT = SUA.UA_CODCONT 
/*FORNECEDOR*/  LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/    LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*SL1 PAI*/	   	LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ = ''  AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
/*SL2 PAI*/	   	LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SL1.L1_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO 
/*SL2 FILHO*/	LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO
/*SC0 RES MANU*/LEFT JOIN SC0010 SC0  ON SC0.D_E_L_E_T_ = ''  AND SC0.C0_FILRES = SL2A.L2_FILIAL AND SUBSTRING(SC0.C0_OBS,8,6) = SL2A.L2_NUM AND SC0.C0_PRODUTO = SL2A.L2_PRODUTO 
/*--------------------PADRAO-----------------------*/
/*SC6 PV*/		LEFT JOIN SC6010 SC6  ON SC6.D_E_L_E_T_ = ''  AND SC6.C6_FILIAL = SL2B.L2_FILIAL AND SC6.C6_NUM = SL2B.L2_PEDRES AND SC6.C6_PRODUTO = SL2B.L2_PRODUTO AND SC6.C6_ITEM = SL2B.L2_ITEM 
/*--------------------TROCA-----------------------*/
/*SC6 PV TROCA*/LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2B.L2_FILIAL AND SC6A.C6_NUM = SL2B.L2_PEDRES AND SC6A.C6_ITEM = SL2B.L2_ITEM AND SC6A.C6_PRODUTO <> SL2B.L2_PRODUTO 
/*--------------------MANUAL-----------------------*/
/*SC6 PV MANUA*/LEFT JOIN SC6010 SC6X ON SC6X.D_E_L_E_T_ = '' AND SC6X.C6_FILIAL = SL1.L1_FILIAL AND SC6X.C6_NUM = SL1.L1_ZLNK720 AND SC6X.C6_PRODUTO = SL2A.L2_PRODUTO AND SC6X.C6_ITEM = SL2A.L2_ITEM AND SL2A.L2_TES = '720'
/*--------------------CONDIÇÕES----------------------*/
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_OPER   <> '3' 
AND YEAR(SUA.UA_EMISSAO) IN (2019, 2020)
AND SA3.A3_ZSITVND IN ('1','2')
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
--AND SUA.UA_NUMSL1 <> ''
--AND SUA.UA_FILIAL = '0103'
--AND SB1.B1_COD = 'EP198I'
--AND SC6.C6_NUM = '009877'
--AND SUA.UA_NUM = '028405'
/*---------------ORDER BY------------------*/
ORDER BY SUA.UA_FILIAL, SUA.UA_NUM