
SELECT 

/*--------------------ATENDIMENTO----------------------------*/

SUA.UA_FILIAL			AS FILIAL_ATM,
SUA.UA_NUM				AS NUM_ATM,	
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS DT_EMI_ATM,			

/*----------------------PRODUTO----------------------------*/

CPT1.Z_UB_PRODUTO		AS CODPROD,
CPT1.Z_PROD_TROCADO		AS CODPROD_TROCADO,
CPT1.Z_CODPROD_REAL		AS CODPROD_REAL,
SB1.B1_DESC				AS PRODUTO,
SB1.B1_ZDESRDZ			AS PRODUTO_REDU,
SB1.B1_ZAPRES1			AS COD_APRE	,
SB1.B1_UM				AS UND,

/*-----------------------SALDOS----------------------------*/

ISNULL((SELECT SUM(B2_QATU) FROM SB2010 WHERE D_E_L_E_T_ = '' AND B2_LOCAL = '01' AND B2_COD = CPT1.Z_CODPROD_REAL),0) AS SLD_FIS,
ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE D_E_L_E_T_ = '' AND B2_LOCAL = '01' AND B2_COD = CPT1.Z_CODPROD_REAL),0) AS SLD_FIS,
ISNULL((SELECT SUM(B2_QATU - B2_RESERVA) FROM SB2010 WHERE D_E_L_E_T_ = '' AND B2_LOCAL = '01' AND B2_COD = CPT1.Z_CODPROD_REAL),0) AS SLD_FIS,

/*------------------CLIENTE/FORNECEDOR/VENDEDOR/OUTROS-----------------------*/
	
SA1.A1_COD	   		  			AS COD_CLI,
SA1.A1_NOME 			  	   	AS NOME_CLI,
SA1.A1_NREDUZ					AS NOME_CLI_REDU,
dbo.formatarCNPJCPF(SA1.A1_CGC) AS CNPJ_CPF,
SA1.A1_INSCR					AS I_E,
CASE
	WHEN SA1.A1_CONTRIB = '1'
THEN 'S'
	WHEN SA1.A1_CONTRIB = '2'
THEN 'N'
ELSE ''
END AS CONTRIBUINTE,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SU5.U5_CODCONT					AS COD_CONTAT, 
SUBSTRING(SU5.U5_CONTAT,1,15) 	AS CONTATO,
SU5.U5_DDD						AS DDD, 
SU5.U5_FONE						AS FONE, 
SU5.U5_CELULAR					AS CELULAR,
SA3.A3_COD 		      			AS COD_VEND,
SA3.A3_NOME 			  		AS VENDEDOR,
SA2.A2_COD						AS COD_FOR,
SA2.A2_NOME						AS FORNECEDOR,
SA2.A2_NREDUZ					AS NOME_FOR_REDU,
CAST(SB1.B1_PE AS DECIMAL(3,0)) AS PRZ_FOR_DIAS,
SUA.UA_VLRLIQ					AS VLR_TOTAL_ATM,
SL2A.L2_ZCSTREP					AS CST_REP_L2,
SB1.B1_CUSTD					AS CUSTD_B1,
SC6.C6_PRCVEN 					AS VLR_UNI_PV,
CASE
	WHEN SUA.UA_ZTIPVND = '1'
THEN 'VENDA VAREJO'
	WHEN SUA.UA_ZTIPVND = '2'
THEN 'VENDA PROJETO'
	WHEN SUA.UA_ZTIPVND = '3'
THEN 'VENDA INDUSTRIA'
ELSE ''
END AS TIPO_VENDA,
SUA.UA_OPER						AS OPER_ATM,
SUA.UA_NUMSL1					AS NUMSL1_ATM,
SUA.UA_STATUS					AS STATUS_ATM,
SUA.UA_CANC						AS CANCEL_ATM,

/*----------------------FINANCEIRO--------------------------*/

CASE
	WHEN YEAR(SUA.UA_ZDTLBFT) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SUA.UA_ZDTLBFT AS DATETIME),103)
END AS DT_LIB_FAT,	
CASE
	WHEN YEAR(SL1.L1_EMISNF) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103) 
END AS DATA_FAT,
SL1.L1_SERPED 					AS SERIE_700,
SL1.L1_DOCPED 					AS DOC_700,
SL1.L1_ZLNK720 					AS LINK_720,


/*--------------------RESERVA MANUAL----------------------------*/

SC0.C0_NUM    					AS NUM_RESERVA_MANU,

/*-----------------------ORC PAI-------------------------*/

SL2A.L2_FILIAL 					AS FILIAL_ORC_PAI,
SL2A.L2_NUM	  					AS NUM_ORC_PAI,	
SL2A.L2_SERIE 					AS SERIE_ORC_PAI,
SL2A.L2_DOC	  					AS DOC_ORC_PAI, 
SL2A.L2_TES						AS TES_ORC_PAI,
CASE
	WHEN YEAR(SL2A.L2_EMISSAO) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL2A.L2_EMISSAO AS DATETIME),103) 
END AS DT_EMI_ORCPAI,

/*-------------------ORC FILHO---------------------------*/

SL2B.L2_FILIAL 					AS FILIAL_ORC_FILHO,
SL2B.L2_NUM	   					AS NUM_ORC_FILHO,
SL2B.L2_SERIE  					AS SERIE_ORC_FILHO,
SL2B.L2_DOC	   					AS DOC_ORC_FILHO,
CASE
	WHEN YEAR(SL2B.L2_EMISSAO) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL2B.L2_EMISSAO AS DATETIME),103) 
END AS DT_EMI_ORCFILHO,


/*----------------------SOLICITAÇÃO DE COMPRAS--------------------------*/

CASE
	WHEN SC1X.C1_FILIAL <> ''
THEN SC1X.C1_FILIAL 
ELSE SC1.C1_FILIAL 
END AS FILIAL_SC,
CASE
	WHEN SC1X.C1_NUM <> ''
THEN SC1X.C1_NUM 
ELSE SC1.C1_NUM  
END AS NUM_SC,
CASE
	WHEN SC1X.C1_QUANT <> ''
THEN SC1X.C1_QUANT 
ELSE SC1.C1_QUANT  
END AS QTD_SC,
CASE
	WHEN SC1X.C1_EMISSAO <> ''
THEN CONVERT(VARCHAR,CAST(SC1X.C1_EMISSAO AS DATETIME),103) 
ELSE CONVERT(VARCHAR,CAST(SC1.C1_EMISSAO AS DATETIME),103) 
END AS DT_EMI_SC,

/*------------------------PEDIDO DE COMPRAS------------------------*/

CASE
	WHEN SC7X.C7_FILIAL <> ''
THEN SC7X.C7_FILIAL 
ELSE SC7.C7_FILIAL  
END AS FILIAL_PC,
CASE
	WHEN SC7X.C7_NUM <> ''
THEN SC7X.C7_NUM 
ELSE SC7.C7_NUM  
END AS NUM_PC,
CASE
	WHEN SC7X.C7_QUANT <> ''
THEN SC7X.C7_QUANT 
ELSE SC7.C7_QUANT  
END AS QTD_PC,
CASE
	WHEN SC7X.C7_QUJE <> ''
THEN SC7X.C7_QUJE 
ELSE SC7.C7_QUJE  
END AS QTDJE_PC,
CASE
	WHEN SC7X.C7_EMISSAO <> ''
THEN CONVERT(VARCHAR,CAST(SC7X.C7_EMISSAO AS DATETIME),103) 
ELSE CONVERT(VARCHAR,CAST(SC7.C7_EMISSAO AS DATETIME),103)  
END AS DT_EMI_PC,

/*-----------------------PEDIDO DE VENDA-------------------------*/

SC6.C6_FILIAL		AS FILIAL_PV,
SC6.C6_NUM			AS NUM_PV,
SC6.C6_ITEM			AS ITEM_PV,
SC6.C6_QTDVEN		AS QTD_PV,
SC9.C9_QTDLIB		AS QTD_LIB,
SC9.C9_BLEST		AS C9_BLEST,
SC6.C6_BLQ			AS C6_BLQ,

/*------------------------DOC DE SAIDA------------------------*/

SC9.C9_SERIENF		AS SERIE_SAIDA,
SC9.C9_NFISCAL		AS NOTA_SAIDA,
SD2.D2_EMISSAO		AS DT_NOTA_SAIDA,

/*------------------------DOC DE ENTRADA------------------------*/

SD1.D1_SERIE		AS SEIRE_ENTRADA,
SD1.D1_DOC			AS NOTA_ENTRADA,
SD1.D1_DTDIGIT		AS DT_NOTA_ENTRADA,

/*-----------------------PRAZOS E DATAS-------------------------*/

CASE
	WHEN SC7X.C7_DATPRF <> ''
THEN CONVERT(VARCHAR,CAST(SC7X.C7_DATPRF AS DATETIME),103)
ELSE CONVERT(VARCHAR,CAST(SC7.C7_DATPRF AS DATETIME),103)
END AS PRZ_ENT_FOR,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT AS DATETIME),103) AS DT_ENT_CLI,
CAST(SUA.UA_ZPRZENT AS DECIMAL(3,0)) AS PRZ_ENT_CLI,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CASE
	WHEN
	 	SC7X.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT >= SC7X.C7_DATPRF 	
THEN 'N'
	WHEN
		SC7X.C7_DATPRF IS NULL
	AND	SC7.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT >= SC7.C7_DATPRF 	
THEN 'N'
	WHEN
	 	SC7X.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT < SC7X.C7_DATPRF 	
THEN 'S'
	WHEN
		SC7X.C7_DATPRF IS NULL
	AND	SC7.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT < SC7.C7_DATPRF 	
THEN 'S'
END AS ATRASADO

/*------------------RELACIONAMENTOS---------------------*/

/*ATENDIMENTO*/		FROM SUA010 SUA
/*PRINCIPAL*/     	LEFT JOIN CUBO_PT1_BETA CPT1 ON CPT1.Z_UA_FILIAL = SUA.UA_FILIAL AND CPT1.Z_UA_NUM = SUA.UA_NUM
/*SB1 CAD. PROD*/ 	LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ = ''  AND SB1.B1_COD = CPT1.Z_CODPROD_REAL
/*CLIENTRE*/ 	  	LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ = ''  AND SA1.A1_COD = CPT1.Z_A1_COD AND SA1.A1_LOJA = CPT1.Z_A1_LOJA
/*CONTATO*/		  	LEFT JOIN SU5010 SU5  ON SU5.D_E_L_E_T_ = ''  AND SU5.U5_CODCONT = CPT1.Z_U5_CODCONT
/*FORNECEDOR*/	  	LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = CPT1.Z_A2_COD AND SA2.A2_LOJA = CPT1.Z_A2_LOJA
/*VENDEDOR*/	  	LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ = ''  AND SA3.A3_COD = CPT1.Z_A3_COD
/*SL1 PAI*/		  	LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ = ''  AND SL1.L1_FILIAL = CPT1.Z_L1_FILIAL AND SL1.L1_NUM = CPT1.Z_L1_NUM AND SL1.L1_ORCRES = ''
/*SL2 PAI*/		  	LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = CPT1.Z_L2_FILIAL_PAI AND SL2A.L2_NUM = CPT1.Z_L2_NUM_PAI AND SL2A.L2_PRODUTO = CPT1.Z_L2_PRODUTO_PAI AND SL2A.L2_ITEM = CPT1.Z_L2_ITEM_PAI  
/*SL2 FILHO*/	  	LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = CPT1.Z_L2_FILIAL_FILHO AND SL2B.L2_NUM = CPT1.Z_L2_NUM_FILHO AND SL2B.L2_PRODUTO = CPT1.Z_L2_PRODUTO_FILHO AND SL2B.L2_ITEM = CPT1.Z_L2_ITEM_FILHO  
/*SC0 RES MANU*/  	LEFT JOIN SC0010 SC0  ON SC0.D_E_L_E_T_ = ''  AND SC0.C0_FILIAL = CPT1.Z_C0FILRES AND SUBSTRING(SC0.C0_OBS,8,6) = CPT1.Z_SUBSTIRNG_SC0_OBS AND SC0.C0_PRODUTO = CPT1.Z_C0_PRODUTO
/*SC6 PV*/        	LEFT JOIN SC6010 SC6  ON SC6.D_E_L_E_T_ = ''  AND SC6.C6_FILIAL = CPT1.Z_C6_FILIAL AND SC6.C6_NUM = CPT1.Z_C6_NUM AND SC6.C6_PRODUTO = CPT1.Z_CODPROD_REAL AND SC6.C6_ITEM = CPT1.Z_C6_ITEM 
/*SC1 SC PADRAO*/ 	LEFT JOIN SC1010 SC1  ON SC1.D_E_L_E_T_ = ''  AND SC1.C1_FILENT = CPT1.Z_L2_FILIAL_PAI AND SC1.C1_NUM = CPT1.Z_L2_SOLCOM_PAI AND SC1.C1_ORCAM = CPT1.Z_L2_NUM_PAI  AND SC1.C1_PRODUTO = CPT1.Z_L2_PRODUTO_PAI AND SC1.C1_ZITMORC = CPT1.Z_L2_ITEM_PAI
/*SC1 SC MANUAL*/ 	LEFT JOIN SC1010 SC1X ON SC1X.D_E_L_E_T_ = '' AND SC1X.C1_ZFILPV = SC6.C6_FILIAL AND SC1X.C1_ZNUMPV = SC6.C6_NUM AND SC1X.C1_PRODUTO = SC6.C6_PRODUTO AND SC1X.C1_ZITMPV = SC6.C6_ITEM
/*SC7 PC PADRAO*/ 	LEFT JOIN SC7010 SC7  ON SC7.D_E_L_E_T_ = ''  AND SC7.C7_FILIAL = SC1.C1_FILIAL AND SC7.C7_NUM = SC1.C1_PEDIDO AND SC7.C7_PRODUTO = SC1.C1_PRODUTO AND SC7.C7_NUMSC = SC1.C1_NUM AND SC7.C7_ITEMSC = SC1.C1_ITEM
/*SC7 PC MANUAL*/	LEFT JOIN SC7010 SC7X ON SC7X.D_E_L_E_T_ = '' AND SC7X.C7_FILIAL = SC1X.C1_FILIAL AND SC7X.C7_NUM = SC1X.C1_PEDIDO AND SC7X.C7_PRODUTO = SC1X.C1_PRODUTO AND SC7X.C7_NUMSC = SC1X.C1_NUM AND SC7X.C7_ITEMSC = SC1X.C1_ITEM
/*SD1 D.E. PADRAO*/ LEFT JOIN SD1010 SD1  ON SD1.D_E_L_E_T_ = ''  AND SD1.D1_FILIAL = SC7.C7_FILENT AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_COD = SC7.C7_PRODUTO AND SD1.D1_ITEMPC = SC7.C7_ITEM
/*SD1 D.E. MANUAL*/ LEFT JOIN SD1010 SD1X ON SD1X.D_E_L_E_T_ = '' AND SD1X.D1_FILIAL = SC7X.C7_FILENT AND SD1X.D1_PEDIDO = SC7X.C7_NUM AND SD1X.D1_COD = SC7X.C7_PRODUTO AND SD1X.D1_ITEMPC = SC7X.C7_ITEM
/*SC9 LIB/SAIDA*/	LEFT JOIN SC9010 SC9  ON SC9.D_E_L_E_T_ = ''  AND SC9.C9_FILIAL = SC6.C6_FILIAL AND SC9.C9_PEDIDO = SC6.C6_NUM AND SC9.C9_ITEM = SC6.C6_ITEM AND SC9.C9_PRODUTO = SC6.C6_PRODUTO
/*SD2 DOC. SAI*/	LEFT JOIN SD2010 SD2  ON SD2.D_E_L_E_T_ = ''  AND SD2.D2_SERIE = SC9.C9_SERIENF AND SD2.D2_DOC = SC9.C9_NFISCAL AND SD2.D2_COD = SC9.C9_PRODUTO AND SD2.D2_ITEMPV = SC9.C9_ITEM 

/*--------------------CONDIÇÕES----------------------*/

WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_OPER   <> '3' 
AND YEAR(SUA.UA_EMISSAO) IN (2019, 2020)
AND SA3.A3_ZSITVND IN ('1','2')
--AND SC6.C6_BLQ IS NULL
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
--AND SUA.UA_FILIAL = '0101'
--AND SUA.UA_NUM = '028405'
--AND SUA.UA_NUM = '008145'
--AND SUA.UA_NUM = '028087'

/*---------------ORDER BY------------------*/

ORDER BY SUA.UA_FILIAL, SUA.UA_NUM