

SELECT
*,
CASE 
	WHEN
		Z_OPER_ATM = '4'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL 
	AND Z_DOC700 IS NULL 	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL
	AND Z_DOC700 IS NULL	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM <> ''
	AND Z_SER700 = ''
	AND Z_DOC700 = ''	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA  IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA  = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '4'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
   	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
  	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA =''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
		WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''
	AND Z_SERIE_PAI <> ''
	AND Z_NOTA_PAI <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '6'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
    AND Z_PROD_TROCADO IS NULL
THEN '6'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '6'
ELSE ''
END AS ESTAGIO,
CASE 
	WHEN
		Z_OPER_ATM = '4'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL 
	AND Z_DOC700 IS NULL 	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL
	AND Z_DOC700 IS NULL	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM <> ''
	AND Z_SER700 = ''
	AND Z_DOC700 = ''	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA  IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA  = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRADO NO PRAZO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRADO NO PRAZO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
   	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
  	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA =''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
		WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''
	AND Z_SERIE_PAI <> ''
	AND Z_NOTA_PAI <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO FATURADO'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
    AND Z_PROD_TROCADO IS NULL
THEN 'PRODUTO FATURADO'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO FATURADO (PROD. TROCADO)'
ELSE ''
END AS SITUACAO
FROM CUBO_PT2_BETA
WHERE 1=1
AND Z_OPER_ATM <> '3'
AND Z_BLQ_C6 IS NULL OR Z_BLQ_C6 <> 'R'
--AND Z_NUM_ATM = '027146'
--AND Z_PROD_REAL = 'IC137F'


