

/*

DROP TABLE ZANALISECOMPRAS

CREATE TABLE ZANALISECOMPRAS
(
	ZAC_CODPROD			VARCHAR(15),
	ZAC_PRODUTO			VARCHAR(40),
	ZAC_CODAPRE			VARCHAR(18),
	ZAC_GRUPO			VARCHAR(4),
	ZAC_CODFORN			VARCHAR(6),
	ZAC_FORNECEDOR		VARCHAR(40),
	ZAC_FORNREDU		VARCHAR(20),
	ZAC_CODFAM			VARCHAR(6),
	ZAC_FAMILIA			VARCHAR(30),
	ZAC_DATA	  		VARCHAR(8),
	ZAC_QTD				FLOAT,
	ZAC_FINANCEIRO		FLOAT,
	ZAC_FATURADO		FLOAT,
	ZAC_ENTRADA			FLOAT,
	ZAC_PEDIDOCOMPRA	FLOAT
)

*/