
/* LANCAMENTO CONTABIL */

SELECT 
A.CT2_FILIAL		AS FILIAL,
A.CT2_DATA			AS DTLANC,
A.CT2_DEBITO		AS CTADEB,
A.CT2_CREDIT		AS CTACRD,
A.CT2_VALOR			AS VALOR,
A.CT2_HIST			AS HISTORICO,
A.CT2_ROTINA		AS ROTINA,
CASE
	WHEN A.CT2_ROTINA = 'FINA460' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,15,3), ' - ', SUBSTRING(A.CT2_KEY,18,9))
	WHEN A.CT2_ROTINA = 'FINA040' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,15,3), ' - ', SUBSTRING(A.CT2_KEY,18,9))
	WHEN A.CT2_ROTINA = 'FINA330' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,7,3), ' - ',  SUBSTRING(A.CT2_KEY,10,12))
	WHEN A.CT2_ROTINA = 'FINA050' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,7,3), ' - ',  SUBSTRING(A.CT2_KEY,10,12))
	WHEN A.CT2_ROTINA = 'FINA070' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'FINA200' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'FINA370' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'FINA470' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'FINA100' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'FINA080' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ',  SUBSTRING(A.CT2_KEY,12,10))
	WHEN A.CT2_ROTINA = 'CTBANFS' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,16,3), ' - ', SUBSTRING(A.CT2_KEY,7,9))
	WHEN A.CT2_ROTINA = 'MATA103' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,16,3), ' - ', SUBSTRING(A.CT2_KEY,7,9))
	WHEN A.CT2_ROTINA = 'CTBANFE' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,16,3), ' - ', SUBSTRING(A.CT2_KEY,7,9))
	WHEN A.CT2_ROTINA = 'FINA290' THEN CONCAT( SUBSTRING(A.CT2_KEY,1,6), ' - ', SUBSTRING(A.CT2_KEY,9,3), ' - ', SUBSTRING(A.CT2_KEY,12,10))
	ELSE ''
END 						AS TITULO,
CASE
	WHEN SUBSTRING(CT2_CREDIT,1,1) = '3' AND CTCR.CT1_NORMAL = '2' THEN 'RECEBER - SE1'
	WHEN SUBSTRING(CT2_DEBITO,1,1) = '4' AND CTCR.CT1_NORMAL = '1' THEN 'PAGAR - SE2'
	WHEN SUBSTRING(CT2_DEBITO,1,1) = '3' AND CTCR.CT1_NORMAL = '1' THEN 'PAGAR - SE2'
	WHEN SUBSTRING(CT2_DEBITO,1,1) = '1' AND CTCR.CT1_NORMAL = '1' THEN 'RECEBER - SE1'
	WHEN SUBSTRING(CT2_CREDIT,1,1) = '2' AND CTCR.CT1_NORMAL = '2' THEN 'PAGAR - SE2'
ELSE ''
END AS IDENT,
CASE
	WHEN SUBSTRING(CT2_DEBITO,1,1) = '3' AND CTCR.CT1_NORMAL = '2' THEN 'RECEBER - SE1'
	WHEN SUBSTRING(CT2_CREDIT,1,1) = '4' AND CTCR.CT1_NORMAL = '1' THEN 'PAGAR - SE2'
	WHEN SUBSTRING(CT2_CREDIT,1,1) = '3' AND CTCR.CT1_NORMAL = '1' THEN 'PAGAR - SE2'
	WHEN SUBSTRING(CT2_CREDIT,1,1) = '1' AND CTCR.CT1_NORMAL = '1' THEN 'RECEBER - SE1'
	WHEN SUBSTRING(CT2_DEBITO,1,1) = '2' AND CTCR.CT1_NORMAL = '2' THEN 'PAGAR - SE2'
ELSE ''
END AS IDENTCANC
FROM CT2010 A
LEFT JOIN CT1010 CTCR ON CTCR.D_E_L_E_T_ = '' AND CTCR.CT1_CONTA = CT2_CREDIT
LEFT JOIN CT1010 CTDB ON CTDB.D_E_L_E_T_ = '' AND CTDB.CT1_CONTA = CT2_DEBITO
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND CONCAT(CT2_CLVLDB,CT2_CLVLCR) = ''
AND A.CT2_ROTINA NOT IN ('ATFA050')


/* SE1 - RECEBER */

SELECT 
CONCAT(A.E1_FILIAL, ' - ', A.E1_PREFIXO, ' - ', A.E1_NUM) AS CHAVERECEBER,
CASE
	WHEN B.D2_CCUSTO <> '' THEN B.D2_CCUSTO
	ELSE A.E1_CCUSTO
END AS CC,
CASE
	WHEN B.D2_CLVL <> '' THEN B.D2_CLVL
	ELSE A.E1_CLVL
END AS CLVL
FROM SE1010 A 
LEFT JOIN SD2010 B ON B.D_E_L_E_T_ = '' AND B.D2_FILIAL = A.E1_FILIAL AND B.D2_SERIE = A.E1_PREFIXO AND B.D2_DOC = A.E1_NUM AND B.D2_CLIENTE = A.E1_CLIENTE AND B.D2_LOJA = A.E1_LOJA
WHERE 1=1
AND A.D_E_L_E_T_ = ''
GROUP BY 
A.E1_FILIAL,
A.E1_PREFIXO,
A.E1_NUM,
A.E1_CCUSTO,
A.E1_CLVL,
B.D2_CCUSTO,
B.D2_CLVL


/* SE2 - PAGAR */

SELECT 
CONCAT(A.E2_FILIAL, ' - ', A.E2_PREFIXO, ' - ', A.E2_NUM) AS CHAVEPAGAR,
CASE
	WHEN B.D1_CC <> '' THEN B.D1_CC
	ELSE A.E2_CCUSTO
END AS CC,
CASE
	WHEN B.D1_CLVL <> '' THEN B.D1_CLVL
	ELSE A.E2_CLVL
END AS CLVL
FROM SE2010 A 
LEFT JOIN SD1010 B ON B.D_E_L_E_T_ = '' AND B.D1_FILIAL = A.E2_FILIAL AND B.D1_SERIE = A.E2_PREFIXO AND B.D1_DOC = A.E2_NUM AND B.D1_FORNECE = A.E2_FORNECE AND B.D1_LOJA = A.E2_LOJA
WHERE 1=1
AND A.D_E_L_E_T_ = ''
GROUP BY 
A.E2_FILIAL,
A.E2_PREFIXO,
A.E2_NUM,
A.E2_CCUSTO,
A.E2_CLVL,
B.D1_CC,
B.D1_CLVL


