
SELECT 
SUA.UA_FILIAL		AS FILIAL_ATM,
SUA.UA_NUM			AS ATENDIMENTO,
CASE
	WHEN cast(SUM((SB5.B5_LARG * SB5.B5_COMPR) * SUB.UB_QUANT) AS NUMERIC(10,2)) IS NULL
THEN 0
ELSE cast(SUM((SB5.B5_LARG * SB5.B5_COMPR) * SUB.UB_QUANT) AS NUMERIC(10,2))
END AS M2_TOTAL,
CASE
	WHEN cast(SUM((SB5.B5_LARG * SB5.B5_COMPR * SB5.B5_ALTURA) * SUB.UB_QUANT) AS NUMERIC(10,2)) IS NULL
THEN 0
ELSE cast(SUM((SB5.B5_LARG * SB5.B5_COMPR * SB5.B5_ALTURA) * SUB.UB_QUANT) AS NUMERIC(10,2))
END AS M3_TOTAL,
CASE
	WHEN SC5.C5_NOTA <> ''
THEN SC5.C5_FILIAL
	WHEN SL1A.L1_DOC <> ''
THEN SL1A.L1_FILIAL
ELSE ''
END AS FILIAL_NF,
CASE
	WHEN SC5.C5_SERIE <> ''
THEN SC5.C5_SERIE
	WHEN SL1A.L1_SERIE <> ''
THEN SL1A.L1_SERIE
ELSE ''
END AS SERIE,
CASE
	WHEN SC5.C5_NOTA <> ''
THEN SC5.C5_NOTA
	WHEN SL1A.L1_DOC <> ''
THEN SL1A.L1_DOC
ELSE ''
END AS NF
FROM SUA010 SUA 
LEFT JOIN SL1010 SL1A ON SL1A.D_E_L_E_T_ = '' AND SL1A.L1_FILIAL = SUA.UA_FILIAL AND SL1A.L1_NUMATEN = SUA.UA_NUM AND SL1A.L1_ORCRES = ''
LEFT JOIN SL1010 SL1B ON SL1B.D_E_L_E_T_ = '' AND SL1B.L1_FILRES = SL1A.L1_FILIAL AND SL1B.L1_ORCRES = SL1A.L1_NUM 
LEFT JOIN SC5010 SC5 ON SC5.D_E_L_E_T_ = '' AND SC5.C5_FILIAL = SL1B.L1_FILIAL AND SC5.C5_NUM = SL1B.L1_PEDRES
LEFT JOIN SUB010 SUB ON SUB.D_E_L_E_T_ = '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
LEFT JOIN SB5010 SB5 ON SB5.D_E_L_E_T_ = '' AND SB5.B5_COD = SUB.UB_PRODUTO
WHERE 1=1
AND SUA.D_E_L_E_T_ = '' 
--AND SUA.UA_EMISSAO BETWEEN '20210101' AND GETDATE()
--AND CONCAT(SL1A.L1_DOC,SC5.C5_NOTA) <> ''
AND SUA.UA_FILIAL = '0103'
AND SUA.UA_NUM = '008968'
GROUP BY
SUA.UA_FILIAL,
SUA.UA_NUM,
SC5.C5_NOTA,
SC5.C5_FILIAL,
SL1A.L1_DOC,
SL1A.L1_FILIAL,
SC5.C5_SERIE,
SL1A.L1_SERIE,
SC5.C5_NUM

