
SELECT 
SE2.E2_FILIAL	AS FILIAL,
CONCAT(SA2.A2_COD, ' - ',SA2.A2_NOME) AS COD_NOME_FOR,
dbo.formatarCNPJCPF(SA2.A2_CGC) AS CNPJ,
CONCAT(SE2.E2_PREFIXO, ' - ', SE2.E2_NUM, ' - ', SE2.E2_PARCELA) AS PRF_TITULO_PARCELA,
SE2.E2_TIPO	AS TIPO,
CONVERT(VARCHAR,CAST(SE2.E2_EMISSAO AS DATETIME), 103 )	AS EMISSAO,
CONVERT(VARCHAR,CAST(SE2.E2_VENCTO AS DATETIME), 103 )	AS DATA_VENCTO,
CONVERT(VARCHAR,CAST(SE2.E2_VENCREA AS DATETIME), 103 ) AS VENCTO_REAL,
SE2.E2_VALOR	AS VALOR_ORIGINAL,
SE2.E2_VALLIQ	AS VALOR_NOMINAL,
SE2.E2_HIST		AS HISTORICO
FROM SE2010 SE2
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SE2.E2_FORNECE AND SA2.A2_LOJA = SE2.E2_LOJA
WHERE 1=1
AND SE2.D_E_L_E_T_ = ''
AND SE2.E2_VENCREA >= '20210101'