
SELECT 
SE1.E1_FILIAL	AS FILIAL,
CONCAT(SA1.A1_COD, ' - ',SA1.A1_NOME) AS COD_NOME_FOR,
dbo.formatarCNPJCPF(SA1.A1_CGC) AS CNPJ,
CONCAT(SE1.E1_PREFIXO, ' - ', SE1.E1_NUM, ' - ', SE1.E1_PARCELA) AS PRF_TITULO_PARCELA,
SE1.E1_TIPO	AS TIPO,
CONVERT(VARCHAR,CAST(SE1.E1_EMISSAO AS DATETIME), 103 )	AS EMISSAO,
CONVERT(VARCHAR,CAST(SE1.E1_VENCTO AS DATETIME), 103 )	AS DATA_VENCTO,
CONVERT(VARCHAR,CAST(SE1.E1_VENCREA AS DATETIME), 103 ) AS VENCTO_REAL,
SE1.E1_VALOR	AS VALOR_ORIGINAL,
SE1.E1_VALLIQ	AS VALOR_NOMINAL,
SE1.E1_HIST		AS HISTORICO
FROM SE1010 SE1
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SE1.E1_CLIENTE AND SA1.A1_LOJA = SE1.E1_LOJA
WHERE 1=1
AND SE1.D_E_L_E_T_ = ''
AND SE1.E1_VENCREA >= '20210101'