/*-----------------------UPDATE CUBAGE-----------------------*/


UPDATE SB1010 SET B1_ZCUBAGE = (B.B5_ALTURA * B.B5_LARG * B.B5_COMPR)
FROM SB1010 A, SB5010 B
WHERE 1=1
AND A.B1_COD = B.B5_COD
--AND A.B1_ZCUBAGE = 0


/*----------------------SELECT DE TESTE----------------------*/


SELECT 
B5_COD,
B5_ALTURA,
B5_LARG,
B5_COMPR,
(B5_ALTURA * B5_LARG * B5_COMPR) AS CUBAGE,
B.B1_ZCUBAGE
FROM SB5010 A, SB1010 B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = '' 
AND A.B5_COD = B.B1_COD
AND A.B5_COD = 'IC293F '


SELECT * FROM PESOS_MEDIDAS