
CREATE TABLE TMP
    (
     PEM_CODPROD VARCHAR(15),
     --PEM_CODAPRE VARCHAR(40),
     PEM_ALTURA FLOAT,
     PEM_LARGURA FLOAT,
     PEM_COMPRIMENTO FLOAT,
     --PEM_CUBAGE	FLOAT,
     PEM_PESO FLOAT,    
	)

/*-----------------------------------------*/

	BULK 
INSERT TMP
        FROM 'C:\TEMP\UPDATE.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO

/*-------------------------------------------*/

UPDATE SB1010 SET B1_PESBRU = A.PEM_PESO , B1_ZCUBAGE = A.PEM_CUBAGE
FROM TMP A, SB1010 B
WHERE A.PEM_CODPROD = B.B1_COD


UPDATE SB5010 SET B5_ALTURA = A.PEM_ALTURA, B5_COMPR = A.PEM_COMPRIMENTO , B5_LARG = A.PEM_LARGURA 
FROM TMP A, SB5010 B
WHERE A.PEM_CODPROD = B.B5_COD

/*------------------------------------------*/

SELECT 
A.PEM_CODPROD,
B.B5_COD,
B.B5_ALTURA,
B.B5_COMPR,
B.B5_LARG,
A.PEM_ALTURA,
A.PEM_COMPRIMENTO AS COMPRIMENTO,
A.PEM_LARGURA,
C.B1_PESBRU AS PESO
FROM TMP A, SB5010 B , SB1010 C
WHERE A.PEM_CODPROD = B.B5_COD
AND A.PEM_CODPROD = C.B1_COD

/*-------------------------------------------*/

SELECT * FROM TMP

UPDATE TMP SET PEM_CODAPRE = '' WHERE PEM_CODAPRE IS NULL

DROP TABLE TMP


