/*---------------TABELA TEMPORARIA-------------------*/

CREATE TABLE #TMP
    (
     PEM_CODPROD VARCHAR(15),
     PEM_CODAPRE VARCHAR(40),
     PEM_ALTURA FLOAT,
     PEM_LARGURA FLOAT,
     PEM_COMPRIMENTO FLOAT,
     PEM_PESO FLOAT,
     R_E_C_N_O_ INT IDENTITY(1,1),     
	)


	BULK 
INSERT #TMP
        FROM 'C:\TEMP\Pesos e Medidas.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO


/*------------------UPDATE SB5---------------------*/

DECLARE @N	   	INT
DECLARE @COUNT 	INT 
DECLARE @PROD 	VARCHAR(15)
DECLARE @ALTURA FLOAT
DECLARE @COMP 	FLOAT
DECLARE @LARG 	FLOAT
DECLARE @PESO	FLOAT

SET @N = 	 ISNULL((SELECT COUNT(*) FROM SB5010 WHERE D_E_L_E_T_ = ''),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD 	= ISNULL((SELECT B5_COD FROM SB5010 WHERE R_E_C_N_O_ = @COUNT),0)
SET @ALTURA = ISNULL((SELECT PEM_ALTURA FROM #TMP WHERE PEM_CODPROD = @PROD),0)
SET @COMP	= ISNULL((SELECT PEM_PROFUNDIDADE FROM #TMP WHERE PEM_CODPROD = @PROD),0)
SET @LARG 	= ISNULL((SELECT PEM_LARGURA FROM #TMP WHERE PEM_CODPROD = @PROD),0)

UPDATE SB5010
SET 
B5_ALTURA = @ALTURA,
B5_COMPR = @COMP, 
B5_LARG = @LARG
WHERE  
B5_COD = @PROD

SET @COUNT = @COUNT + 1

END;

/*------------------------UPDATE SB1----------------------------*/

DECLARE @N	   	INT
DECLARE @COUNT 	INT 
DECLARE @PROD 	VARCHAR(15)
DECLARE @PESO	FLOAT

SET @N = 	 ISNULL((SELECT COUNT(*) FROM SB1010 WHERE D_E_L_E_T_ = ''),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD 	= ISNULL((SELECT B1_COD FROM SB1010 WHERE R_E_C_N_O_ = @COUNT),0)
SET @PESO   = ISNULL((SELECT PEM_PESO FROM #TMP WHERE PEM_CODPROD = @PROD),0)

UPDATE SB1010
SET B1_PESBRU = @PESO
WHERE  
B1_COD = @PROD

SET @COUNT = @COUNT + 1

END;

/*-----------------------------------------------------*/

SELECT * FROM #TMP

DROP TABLE #TMP

SELECT B5_COD,B5_CEME, B5_ALTURA ,B5_LARG, B5_COMPR, B5_ESPESS, R_E_C_N_O_ FROM SB5010 WHERE D_E_L_E_T_ = ''

SELECT B1_COD, B1_DESC, B1_ZCUBAGE, B1_PESBRU FROM SB1010 WHERE D_E_L_E_T_ = ''


SELECT
A.B5_COD,
A.B5_CEME,
A.B5_ALTURA,
A.B5_COMPR,
A.B5_LARG,
B.B1_ZCUBAGE,
B.B1_PESBRU
FROM SB5010 A, SB1010 B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.B5_COD = B.B1_COD
AND A.B5_COD = 'LB012F'


/*------------------------------------------------------------*/

SELECT * FROM PESOS_MEDIDAS



SELECT DISTINCT * FROM #TMP ORDER BY 



SELECT PEM_CODPROD, Count(PEM_CODPROD) FROM #TMP
GROUP BY PEM_CODPROD
HAVING Count(*) > 1

