

SELECT  A.PEM_CODPROD, B.B1_COD , A.PEM_PESO 
--UPDATE SB1010 SET B1_PESBRU = A.PEM_PESO
FROM TMP A, SB1010 B
WHERE A.PEM_CODPROD = B.B1_COD

/*-------------------------------------------*/

UPDATE SB1010 SET B1_PESBRU = A.PEM_PESO
FROM TMP A, SB1010 B
WHERE A.PEM_CODPROD = B.B1_COD


UPDATE SB5010 SET B5_ALTURA = A.PEM_ALTURA, B5_COMPR = A.PEM_PROFUNDIDADE , B5_LARG = A.PEM_LARGURA 
FROM TMP A, SB5010 B
WHERE A.PEM_CODPROD = B.B5_COD

/*------------------------------------------*/

SELECT 
A.PEM_CODPROD,
B.B5_COD,
B.B5_ALTURA,
B.B5_COMPR,
B.B5_LARG,
A.PEM_ALTURA,
A.PEM_PROFUNDIDADE AS COMPRIMENTO,
A.PEM_LARGURA
FROM TMP A, SB5010 B
WHERE A.PEM_CODPROD = B.B5_COD
AND B.B5_COD = 'EP083R'


