CREATE PROCEDURE FECHAESTQFILIAL AS

/*
//////////////////////////////////////////////////////////////////////////////
//                                                                          //
//  		        FECHAMENTO DE ESTOQUE POR FILIAL 						//
//							/*EDUARDO JORGE*/ 	                            //
//                                                                          //
//    Fechamento de estoque separado por filiais com todos os armazens      //
//                                                                          //
//////////////////////////////////////////////////////////////////////////////
*/


DECLARE @SQL1 VARCHAR(MAX)
DECLARE @SQL2 VARCHAR(MAX)
DECLARE @SQL3 VARCHAR(MAX)
DECLARE @cDatIni VARCHAR(8)
DECLARE @cDatFim VARCHAR(8)
DECLARE @F4ESTOQUE VARCHAR(8)
DECLARE @BRANCO VARCHAR(8)
DECLARE @ANOINI INT;
DECLARE @ANOFIM INT;
DECLARE @MESINI INT;
DECLARE @MESFIM INT;
DECLARE @ANO_ANT INT;
DECLARE @MES_ANT INT;
DECLARE @ANO INT;
DECLARE @MES INT;
DECLARE @CUSTO_INI FLOAT;
DECLARE @CUSTO_ATU FLOAT;
DECLARE @DTSLD VARCHAR(6);
DECLARE @DIA_ATU VARCHAR(2);
DECLARE @MES_ATU VARCHAR(2);
DECLARE @ANO_ATU VARCHAR(4);
DECLARE @RECNO INT;
DECLARE @PROD VARCHAR(15);
DECLARE @FILIAL VARCHAR(4);
DECLARE @N_FILIAL INT;


SET @DIA_ATU =  ISNULL((SELECT SUBSTRING(CONVERT(varchar, GETDATE(), 23),9,2)),0) 
SET @MES_ATU =  ISNULL((SELECT SUBSTRING(CONVERT(varchar, GETDATE(), 23),6,2)),0) 
SET @ANO_ATU =  ISNULL((SELECT SUBSTRING(CONVERT(varchar, GETDATE(), 23),1,4)),0) 
SET @ANOINI = 2018
SET @ANOFIM = 2020
SET @MESINI = 1
SET @MESFIM = 12
SET @ANO_ANT = 2017
SET @RECNO = 0
SET @F4ESTOQUE = 'S'
SET @BRANCO = ''
SET @PROD = 'LB016F' 
SET @cDatIni = '2018/01/01'
SET @N_FILIAL = 1
SET @FILIAL = ISNULL((SELECT CONCAT('010',@N_FILIAL)),0)


DELETE FROM TMPAUXFILIAL
DELETE FROM ZZ5010
DBCC CHECKIDENT('TMPAUXFILIAL', RESEED, 0)
--DBCC CHECKIDENT('ZZ4010', RESEED, 0)


WHILE @N_FILIAL <= 3
BEGIN

WHILE @ANOINI <= @ANOFIM
BEGIN

WHILE @MESINI <= @MESFIM
BEGIN

IF @MESINI < 10	
BEGIN
   SET @DTSLD 	  =     ISNULL(( SELECT CONCAT(@ANOINI, 0,@MESINI) AS SALDO  ),0) 
-- SET @cDatIni   = 	ISNULL(( SELECT CONCAT(@ANOINI, 0,@MESINI,01) AS SALDO  ),0) 
   SET @cDatFim   = 	ISNULL(( SELECT CONCAT(@ANOINI, 0,@MESINI,31) AS SALDO  ),0) 
END 
ELSE
BEGIN
   SET @DTSLD 	  = 	  	ISNULL(( SELECT CONCAT(@ANOINI, @MESINI) AS SALDO  ),0) 
-- SET @cDatIni   = 		ISNULL(( SELECT CONCAT(@ANOINI, @MESINI,01) AS SALDO  ),0) 
   SET @cDatFim   = 		ISNULL(( SELECT CONCAT(@ANOINI, @MESINI,31) AS SALDO  ),0) 
END

IF @MESINI = 1
BEGIN
SET @MES_ANT = 12
SET @ANO_ANT =  @ANOINI - 1
SET @ANO 	 =  @ANO_ANT
SET @MES     =  @MES_ANT
END
ELSE
BEGIN
SET @ANO = @ANOINI
SET @MES = @MESINI
END


INSERT INTO TMPAUXFILIAL (AUX_FILIAL, AUX_CODPROD, AUX_ANOMES, AUX_SLD_MES, AUX_CUST_UNI, AUX_CST_MES, R_E_C_D_E_L_) 



SELECT 
@FILIAL AS FILIAL, 
SELECT_PRINCIPAL.COD_PROD AS COD_PROD, 
@DTSLD AS ANO_MES, 
SELECT_PRINCIPAL.SALDO_FINAL AS SALDO_MES, 
SELECT_PRINCIPAL.CUSTO_ATT AS CUSTO_UNI,  
(SELECT_PRINCIPAL.SALDO_FINAL * SELECT_PRINCIPAL.CUSTO_ATT) AS CUSTO_MES,
0
FROM( SELECT 
SALDO.COD_PROD,
SALDO.PRODUTO,
SALDO.UND, 
SALDO.COD_FOR,
SALDO.LOJA_FOR,
SALDO.GRUPO_PROD,
SALDO.COD_LINHA,
SALDO.COD_FAM,
SALDO.CUSTO_INI,
SALDO.CUSTO_ATU,
SALDO.ULT_CUSTO,
CASE WHEN SALDO.CUSTO_ATU <> 0 THEN SALDO.CUSTO_ATU   
  	 WHEN SALDO.ULT_CUSTO <> 0 THEN SALDO.ULT_CUSTO      	  
  	 ELSE SALDO.CUSTO_INI 	   END AS CUSTO_ATT,
--SALDO.SLD_INI_SB9,
--SALDO.QTD_ENT_SD1,
--SALDO.QTD_SAI_SD2,
--SALDO.QTD_ENT_SD3,
--SALDO.QTD_SAI_SD3,
SALDO.SLD_INI_SB9 + ( SALDO.QTD_ENT_SD1 + SALDO.QTD_ENT_SD3 ) - ( SALDO.QTD_SAI_SD2 + SALDO.QTD_SAI_SD3 ) AS SALDO_FINAL
FROM ( SELECT  
		A.B1_COD   	  AS COD_PROD,
		A.B1_DESC  	  AS PRODUTO,
		A.B1_UM    	  AS UND,
		A.B1_PROC  	  AS COD_FOR,
		A.B1_LOJPROC  AS LOJA_FOR,
		A.B1_GRUPO    AS GRUPO_PROD,
		A.B1_ZCODLIN  AS COD_LINHA,
		A.B1_ZCODFAM  AS COD_FAM,		
		ISNULL(( SELECT SUM(B9_QINI)  FROM SB9010 WHERE D_E_L_E_T_ = '' AND B9_FILIAL = @FILIAL AND B9_COD = A.B1_COD AND YEAR(B9_DATA) = 2017),0) AS SLD_INI_SB9,
		ISNULL(( SELECT SUM(D1_QUANT) FROM SD1010 AS SD1, SF4010 AS SF4 WHERE SD1.D_E_L_E_T_ = '' AND SD1.D1_FILIAL = @FILIAL AND SF4.D_E_L_E_T_ = '' AND SD1.D1_COD = A.B1_COD AND SD1.D1_DTDIGIT BETWEEN @cDatIni AND @cDatFim AND SD1.D1_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_ENT_SD1,
		ISNULL(( SELECT SUM(D2_QUANT) FROM SD2010 AS SD2, SF4010 AS SF4 WHERE SD2.D_E_L_E_T_ = '' AND SD2.D2_FILIAL = @FILIAL AND SF4.D_E_L_E_T_ = '' AND SD2.D2_COD = A.B1_COD AND SD2.D2_EMISSAO BETWEEN @cDatIni AND @cDatFim AND SD2.D2_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_SAI_SD2,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010 WHERE D_E_L_E_T_ = '' AND D3_FILIAL = @FILIAL AND D3_COD = A.B1_COD AND D3_TM <= 499 AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_ENT_SD3,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010 WHERE D_E_L_E_T_ = '' AND D3_FILIAL = @FILIAL AND D3_COD = A.B1_COD AND D3_TM >= 500 AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_SAI_SD3,	
	 	ISNULL((SELECT TOP 1 B9_CUSTD FROM SB9010 WHERE D_E_L_E_T_ = '' AND B9_FILIAL = @FILIAL AND B9_COD = A.B1_COD AND  YEAR(B9_DATA) = 2017 AND MONTH(B9_DATA) = 12),0) AS CUSTO_INI,								
		ISNULL((SELECT SQL.CUSTO FROM (
		SELECT TOP 1 MAX(TAB1.ZZ2_DATA)AS  DATA, TAB2.ZZ3_CODPRD AS PRODUTO, TAB2.ZZ3_CUSTD AS CUSTO
		FROM ZZ2010 TAB1, ZZ3010 TAB2
		WHERE TAB1.D_E_L_E_T_ 	=  ''
		AND TAB2.D_E_L_E_T_ 	=  ''
		AND TAB2.ZZ3_COD = TAB1.ZZ2_CODIGO
		AND TAB2.ZZ3_CUSTD <> 0
		AND YEAR(TAB1.ZZ2_DATA) =  @ANOINI
		AND MONTH(TAB1.ZZ2_DATA) = @MESINI
		AND TAB2.ZZ3_CODPRD = A.B1_COD
		GROUP BY TAB1.ZZ2_DATA, TAB2.ZZ3_CODPRD, TAB2.ZZ3_CUSTD 
		ORDER BY TAB1.ZZ2_DATA DESC)AS SQL
		),0) AS CUSTO_ATU,
	  	ISNULL((SELECT SQL.CUSTO FROM (
		SELECT TOP 1 MAX(TAB1.ZZ2_DATA)AS  DATA, TAB2.ZZ3_CODPRD AS PRODUTO, TAB2.ZZ3_CUSTD AS CUSTO
		FROM ZZ2010 TAB1, ZZ3010 TAB2
		WHERE TAB1.D_E_L_E_T_ = ''
		AND TAB2.D_E_L_E_T_ = ''
		AND TAB2.ZZ3_COD = TAB1.ZZ2_CODIGO
		AND TAB2.ZZ3_CUSTD <> 0
		AND YEAR(TAB1.ZZ2_DATA) = @ANO 
		AND MONTH(TAB1.ZZ2_DATA) <= @MES 
		AND TAB2.ZZ3_CODPRD = A.B1_COD
		GROUP BY TAB1.ZZ2_DATA, TAB2.ZZ3_CODPRD, TAB2.ZZ3_CUSTD 
		ORDER BY TAB1.ZZ2_DATA DESC)AS SQL
		),(
		SELECT SQL.CUSTO FROM (
		SELECT TOP 1 MAX(TAB1.ZZ2_DATA)AS  DATA, TAB2.ZZ3_CODPRD AS PRODUTO, TAB2.ZZ3_CUSTD AS CUSTO
		FROM ZZ2010 TAB1, ZZ3010 TAB2
		WHERE TAB1.D_E_L_E_T_ = ''
		AND TAB2.D_E_L_E_T_ = ''
		AND TAB2.ZZ3_COD = TAB1.ZZ2_CODIGO
		AND TAB2.ZZ3_CUSTD <> 0
		AND YEAR(TAB1.ZZ2_DATA) = @ANO - 1
		AND MONTH(TAB1.ZZ2_DATA) <= 12
		AND TAB2.ZZ3_CODPRD = A.B1_COD
		GROUP BY TAB1.ZZ2_DATA, TAB2.ZZ3_CODPRD, TAB2.ZZ3_CUSTD 
		ORDER BY TAB1.ZZ2_DATA DESC)AS SQL
		)) AS ULT_CUSTO		
FROM SB1010 A 
LEFT JOIN SD1010 B ON A.B1_COD = B.D1_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD2010 C ON A.B1_COD = C.D2_COD AND C.D_E_L_E_T_ = '' 
LEFT JOIN SD3010 D ON A.B1_COD = D.D3_COD AND D.D_E_L_E_T_ = '' 
LEFT JOIN SB9010 E ON A.B1_COD = E.B9_COD AND E.D_E_L_E_T_ = '' 
WHERE 1=1
AND A.D_E_L_E_T_ = ''
--AND A.B1_COD IN ('LB016F' , 'LB012F')
GROUP BY A.B1_COD, A.B1_DESC, A.B1_UM, A.B1_PROC, A.B1_LOJPROC, A.B1_GRUPO, A.B1_ZCODLIN, A.B1_ZCODFAM 
) AS SALDO
) AS SELECT_PRINCIPAL


SET @MESINI =  @MESINI  + 1;
IF @ANOINI  =  @ANO_ATU
BEGIN
   SET @MESFIM  = @MES_ATU
END;

END;

SET @ANOINI = @ANOINI + 1
SET @MESINI = 1

END;

PRINT @FILIAL
SET @N_FILIAL = @N_FILIAL + 1
SET @FILIAL = ISNULL((SELECT CONCAT('010',@N_FILIAL)),0)
SET @MESINI = 1
SET @MESFIM = 12
SET @ANOINI = 2018

END;



INSERT INTO ZZ5010(ZZ5_FILIAL, ZZ5_CODPRD, ZZ5_ANOMES, ZZ5_SLDMES, ZZ5_CSTUNI, ZZ5_CSTMES, R_E_C_N_O_, R_E_C_D_E_L_)  	
SELECT AUX_FILIAL, AUX_CODPROD, AUX_ANOMES, AUX_SLD_MES, AUX_CUST_UNI, AUX_CST_MES, R_E_C_N_O_, R_E_C_D_E_L_ FROM TMPAUXFILIAL

GO
