
DEFINE @V VARCHAR(4)
DEFINE @ATM VARCHAR(6)

DECLARE @V VARCHAR(4)
DECLARE @ATM VARCHAR(6)

SET @V = $(@V)
SET @ATM = $(@ATM)


SELECT
SUA.UA_NUM 			  			AS NUM_ATM,
SUA.UA_FILIAL 		  			AS FILIAL_ATM,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS DT_EMI_ATM,
SUB.UB_PRODUTO 		  			AS CODPROD,
SC6C.C6_PRODUTO					AS PROD_TROCADO_PAI,
SC6D.C6_PRODUTO					AS PROD_TROCADO_FILHO,
SB1.B1_DESC 			  	   	AS PRODUTO,
SB1.B1_ZDESRDZ					AS PROD_DESC_REDU,
SB1.B1_ZAPRES1					AS COD_APRE, 
SUB.UB_QUANT 			  	   	AS QTD,
SB1.B1_UM					   	AS UND,
SUA.UA_CLIENTE		  			AS COD_CLI,
SA1.A1_NOME 			  	   	AS NOME_CLI,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SA3.A3_COD 		      			AS COD_VEND,
SA3.A3_NOME 			  		AS VENDEDOR,
SA2.A2_COD						AS COD_FOR,
SA2.A2_NOME						AS FORNECEDOR,
SA2.A2_NREDUZ					AS NOME_FOR_REDU,
CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103) AS DATA_FAT,
SL1.L1_DOCPED				   	AS DOC700,
SL1.L1_SERPED				   	AS SER700,
SL2A.L2_FILIAL					AS FILIAL_PAI,
SL2A.L2_NUM			  			AS NUM_ORC_PAI,
SL2A.L2_SERIE					AS SERIE_PAI,
SL2A.L2_DOC						AS NOTA_PAI	,
SL2B.L2_FILIAL					AS FILIAL_FILHO,
SL2B.L2_NUM			  			AS NUM_ORC_FILHO,
SL2B.L2_SERIE					AS SERIE_FILHO,
SL2B.L2_DOC						AS NOTA_FILHO,
SC1A.C1_FILIAL					AS FILIAL_SC_PAI,
SC1A.C1_NUM						AS NUM_SOLCOM_PAI,
SC7A.C7_FILIAL					AS FILIAL_PC_PAI,
SC7A.C7_NUM						AS NUM_PEDCOMP_PAI,
SC1B.C1_FILIAL					AS FILIAL_SC_FILHO,
SC1B.C1_NUM						AS NUM_SOLCOM_FILHO,
SC7B.C7_FILIAL					AS FILIAL_PC_FILHO,
SC7B.C7_NUM						AS NUM_PEDCOMP_FILHO,
SC6A.C6_FILIAL					AS FILIAL_PV_PAI,
SC6A.C6_NUM						AS NUM_PV_PAI,
CONVERT(VARCHAR,CAST(SC6A.C6_ENTREG AS DATETIME),103) AS DATA_DOCSAI_PAI,
SC6A.C6_SERIE					AS SERIE_C6_PAI,
SC6A.C6_NOTA					AS NOTA_C6_PAI,
SC6B.C6_FILIAL					AS FILIAL_PV_FILHO,
SC6B.C6_NUM						AS NUM_PV_FILHO,
CONVERT(VARCHAR,CAST(SC6B.C6_ENTREG AS DATETIME),103) AS DATA_DOCSAI_FILHO,
SC6B.C6_SERIE					AS SERIE_C6_FILHO,
SC6B.C6_NOTA					AS NOTA_C6_FILHO,
CONVERT(VARCHAR,CAST(SC6C.C6_ENTREG AS DATETIME),103) AS DATA_DOCSAI_PAI_TROCA,
SC6C.C6_SERIE					AS SERIE_C6_PAI_TROCA,
SC6C.C6_NOTA					AS NOTA_C6_PAI_TRPCA,
CONVERT(VARCHAR,CAST(SC6D.C6_ENTREG AS DATETIME),103) AS DATA_DOCSAI_FILHO_TROCA,
SC6D.C6_SERIE					AS SERIE_C6_FILHO_TROCA,
SC6D.C6_NOTA					AS NOTA_C6_FILHO_TROCA,
CONVERT(VARCHAR,CAST(SD1A.D1_DTDIGIT AS DATETIME),103) AS DT_NOTA_ENTRADA_PAI,
SD1A.D1_SERIE					AS SERIE_ENTRADA_PAI,
SD1A.D1_DOC				    	AS DOC_ENTRADA_PAI,
CONVERT(VARCHAR,CAST(SD1B.D1_DTDIGIT AS DATETIME),103) AS DT_NOTA_ENTRADA_FILHO,
SD1B.D1_SERIE					AS SERIE_ENTRADA_FILHO,
SD1B.D1_DOC				    	AS DOC_ENTRADA_FILHO,
CONVERT(VARCHAR,CAST(SC7A.C7_DATPRF AS DATETIME),103) AS PRZ_ENT_FOR_PAI,
CONVERT(VARCHAR,CAST(SC7B.C7_DATPRF AS DATETIME),103) AS PRZ_ENT_FOR_FILHO,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT AS DATETIME),103) AS DT_ENT_CLI,
DIFDIAS_FORCLI_PAI=(CASE WHEN SC7A.C7_DATPRF = '' OR SUA.UA_ZDTAENT = '' THEN 0 ELSE DATEDIFF(DAY,SUA.UA_ZDTAENT,SC7A.C7_DATPRF) END),
DIFDIAS_FORHJ_PAI=(CASE WHEN SC7A.C7_DATPRF =  '' OR SD1A.D1_DTDIGIT = '' THEN 0 ELSE DATEDIFF(DAY,GETDATE(),SC7A.C7_DATPRF) END),
DIFDIAS_FORCLI_FILHO=(CASE WHEN SC7B.C7_DATPRF = '' OR SUA.UA_ZDTAENT = '' THEN 0 ELSE DATEDIFF(DAY,SUA.UA_ZDTAENT,SC7B.C7_DATPRF) END),
DIFDIAS_FORHJ_FILHO=(CASE WHEN SC7B.C7_DATPRF =  '' OR SD1B.D1_DTDIGIT = '' THEN 0 ELSE DATEDIFF(DAY,GETDATE(),SC7B.C7_DATPRF) END),
DIFDIAS_HJCLI=(CASE WHEN SUA.UA_ZDTAENT = '' OR SD1A.D1_DTDIGIT = '' THEN 0 ELSE DATEDIFF(DAY,GETDATE(),SUA.UA_ZDTAENT) END),


CASE 
	WHEN
	SL1.L1_SERPED  = '' 	  
AND SL1.L1_DOCPED  = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES = ''  
AND SL2A.L2_PEDRES = ''  
AND SL2A.L2_SOLCOM = ''   
THEN 'ESTAGIO 0'
    WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''   
AND SL2B.L2_PEDRES  = ''   	
AND SL2B.L2_SOLCOM  = ''		
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = '' 
THEN 'ESTAGIO 0'     
    WHEN      
	SL1.L1_SERPED   = '' 	  
AND SL1.L1_DOCPED   = ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES  = ''
AND SL2A.L2_PEDRES  = ''  	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	= '' 
AND SC1A.C1_COTACAO = ''
AND	SC1A.C1_FORNECE = ''
AND	SC1A.C1_LOJA    = ''
AND	SC1A.C1_QUJE	= 0
AND	SC1A.C1_QTDREEM = 0
THEN 'ESTAGIO 1' 
   WHEN      
	SL1.L1_SERPED   = '' 	  
AND SL1.L1_DOCPED   = ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES  = ''
AND SL2A.L2_PEDRES  <> ''  	
AND SL2A.L2_SOLCOM  <> '' 
AND SC1A.C1_PEDIDO	= '' 
AND SC1A.C1_COTACAO = ''
AND	SC1A.C1_FORNECE = ''
AND	SC1A.C1_LOJA    = ''
AND	SC1A.C1_QUJE	= 0
AND	SC1A.C1_QTDREEM = 0
AND SC6A.C6_SERIE   = ''
AND SC6A.C6_NOTA    = ''
THEN 'ESTAGIO 1' 
 	WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''
AND SL2B.L2_PEDRES = ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = ''   
AND SC1B.C1_PEDIDO  = '' 
AND SC1B.C1_COTACAO = ''
AND	SC1B.C1_FORNECE = ''
AND	SC1B.C1_LOJA    = ''
AND	SC1B.C1_QUJE	= 0
AND	SC1B.C1_QTDREEM = 0	  
THEN 'ESTAGIO 1' 
 	WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''
AND SL2B.L2_PEDRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = ''   
AND SC1B.C1_PEDIDO  = '' 
AND SC1B.C1_COTACAO = ''
AND	SC1B.C1_FORNECE = ''
AND	SC1B.C1_LOJA    = ''
AND	SC1B.C1_QUJE	= 0
AND	SC1B.C1_QTDREEM = 0
AND SC6B.C6_SERIE   = ''	   
AND SC6B.C6_NOTA    = '' 	  
THEN 'ESTAGIO 1'    
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT	 
THEN 'ESTAGIO 2' 
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT	 
AND SC6A.C6_SERIE   = ''	   
AND SC6A.C6_NOTA    = '' 		
THEN 'ESTAGIO 2' 
 WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SL2B.L2_ORCRES = '' 
AND SL2B.L2_PEDRES = ''
AND SL2B.L2_SOLCOM <> ''
AND SC1B.C1_PEDIDO	<> ''
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		
THEN 'ESTAGIO 2' 
 WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SL2B.L2_ORCRES = ''
AND SL2B.L2_PEDRES <> '' 
AND SL2B.L2_SOLCOM <> ''
AND SC1B.C1_PEDIDO	<> '' 
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		
THEN 'ESTAGIO 2'   
   WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> ''
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF <= SUA.UA_ZDTAENT		
THEN 'ESTAGIO 3'
   WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> ''
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF <= SUA.UA_ZDTAENT  
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = '' 		
THEN 'ESTAGIO 3'
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_PEDRES = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF <= SUA.UA_ZDTAENT	   
THEN 'ESTAGIO 3'
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_PEDRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''
AND SC1B.C1_PEDIDO	<> '' 
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF <= SUA.UA_ZDTAENT	   
THEN 'ESTAGIO 3'
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''   	
AND SL2A.L2_SOLCOM = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = '' 	
AND SL2A.L2_PEDRES <> ''  	
THEN 'ESTAGIO 4'  
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''   	
AND SL2A.L2_SOLCOM = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> '' 	
AND SL2A.L2_PEDRES <> '' 
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = ''   	
THEN 'ESTAGIO 4'  
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES = ''   	
AND SL2B.L2_SOLCOM = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
THEN 'ESTAGIO 4' 
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES <> ''   	
AND SL2B.L2_SOLCOM = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
THEN 'ESTAGIO 4'     
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = ''   	
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> ''
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_SERIE <> ''				   
AND SD1A.D1_DOC <> ''
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = '' 
THEN 'ESTAGIO 4'
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = ''   	
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> ''
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_SERIE <> ''				   
AND SD1A.D1_DOC <> ''
THEN 'ESTAGIO 4'  
	WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES = '' 		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  	
AND SL2B.L2_SOLCOM <> '' 
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_SERIE <> ''				   
AND SD1B.D1_DOC <> ''  
THEN 'ESTAGIO 4'      
 	WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES <> '' 		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  	
AND SL2B.L2_SOLCOM <> '' 
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_SERIE <> ''				   
AND SD1B.D1_DOC <> ''  
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
THEN 'ESTAGIO 4' 
    WHEN      
    SC6A.C6_SERIE <> ''	   
AND SC6A.C6_NOTA  <> '' 	   
THEN 'ESTAGIO 5' 
    WHEN      
    SC6B.C6_SERIE <> ''	   
AND SC6B.C6_NOTA  <> '' 	   
THEN 'ESTAGIO 5' 
    WHEN 
	SL2A.L2_SERIE  <> ''   
AND SL2A.L2_DOC    <> ''   
THEN 'ESTAGIO 5'
	WHEN      
	SC6C.C6_PRODUTO IS NOT NULL
THEN 'ESTAGIO 6'
	WHEN      
	SC6D.C6_PRODUTO IS NOT NULL
THEN 'ESTAGIO 6'
ELSE 'OUTROS - (ALGUM ERRO DE PROCESSO OU DE RELACIONAMENTO)'
END AS ESTAGIO,
CASE 
	WHEN
	SL1.L1_SERPED  = '' 	  
AND SL1.L1_DOCPED  = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES = ''  
AND SL2A.L2_PEDRES = ''  
AND SL2A.L2_SOLCOM = ''   
THEN 'FATURAMENTO ABERTO S/FIN'
    WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''   
AND SL2B.L2_PEDRES  = ''   	
AND SL2B.L2_SOLCOM  = ''		
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = '' 
THEN 'FATURAMENTO ABERTO C/FIN'     
    WHEN      
	SL1.L1_SERPED   = '' 	  
AND SL1.L1_DOCPED   = ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES  = ''
AND SL2A.L2_PEDRES  = ''  	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	= '' 
AND SC1A.C1_COTACAO = ''
AND	SC1A.C1_FORNECE = ''
AND	SC1A.C1_LOJA    = ''
AND	SC1A.C1_QUJE	= 0
AND	SC1A.C1_QTDREEM = 0
THEN 'COMPRA PENDENTE S/FIN S/PV' 
   WHEN      
	SL1.L1_SERPED   = '' 	  
AND SL1.L1_DOCPED   = ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES  = ''
AND SL2A.L2_PEDRES  <> ''  	
AND SL2A.L2_SOLCOM  <> '' 
AND SC1A.C1_PEDIDO	= '' 
AND SC1A.C1_COTACAO = ''
AND	SC1A.C1_FORNECE = ''
AND	SC1A.C1_LOJA    = ''
AND	SC1A.C1_QUJE	= 0
AND	SC1A.C1_QTDREEM = 0
AND SC6A.C6_SERIE   = ''
AND SC6A.C6_NOTA    = ''
THEN 'COMPRA PENDENTE S/FIN C/PV' 
 	WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''
AND SL2B.L2_PEDRES = ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = ''   
AND SC1B.C1_PEDIDO  = '' 
AND SC1B.C1_COTACAO = ''
AND	SC1B.C1_FORNECE = ''
AND	SC1B.C1_LOJA    = ''
AND	SC1B.C1_QUJE	= 0
AND	SC1B.C1_QTDREEM = 0	  
THEN 'COMPRA PENDENTE C/FIN S/PV' 
 	WHEN      
	SL1.L1_SERPED  <> '' 	  
AND SL1.L1_DOCPED  <> ''   
AND SL2A.L2_SERIE   = ''   
AND SL2A.L2_DOC     = ''  
AND SL2A.L2_ORCRES <> ''
AND SL2B.L2_PEDRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_SERIE   = ''   	
AND SL2B.L2_DOC     = ''   
AND SC1B.C1_PEDIDO  = '' 
AND SC1B.C1_COTACAO = ''
AND	SC1B.C1_FORNECE = ''
AND	SC1B.C1_LOJA    = ''
AND	SC1B.C1_QUJE	= 0
AND	SC1B.C1_QTDREEM = 0
AND SC6B.C6_SERIE   = ''	   
AND SC6B.C6_NOTA    = '' 	  
THEN 'COMPRA PENDENTE C/FIN C/PV'    
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT	 
THEN 'COMPRA COM ATRASO S/FIN S/PV' 
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT	 
AND SC6A.C6_SERIE   = ''	   
AND SC6A.C6_NOTA    = '' 		
THEN 'COMPRA COM ATRASO S/FIN C/PV' 
 WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SL2B.L2_ORCRES = '' 
AND SL2B.L2_PEDRES = ''
AND SL2B.L2_SOLCOM <> ''
AND SC1B.C1_PEDIDO	<> ''
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		
THEN 'COMPRA COM ATRASO C/FIN S/PV' 
 WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = '' 
AND SL2A.L2_ORCRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SL2B.L2_ORCRES = ''
AND SL2B.L2_PEDRES <> '' 
AND SL2B.L2_SOLCOM <> ''
AND SC1B.C1_PEDIDO	<> '' 
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		
THEN 'COMPRA COM ATRASO C/FIN C/PV'   
   WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> ''
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF <= SUA.UA_ZDTAENT		
THEN 'COMPRA DENTRO DO PRAZO S/FIN S/PV'
   WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> '' 
AND SC1A.C1_PEDIDO	<> ''
AND SD1A.D1_PEDIDO IS NULL
AND SC7A.C7_DATPRF <= SUA.UA_ZDTAENT  
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = '' 		
THEN 'COMPRA DENTRO DO PRAZO S/FIN C/PV'
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_PEDRES = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF <= SUA.UA_ZDTAENT	   
THEN 'COMPRA DENTRO DO PRAZO C/FIN S/PV'
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''    	
AND SL2B.L2_SOLCOM <> '' 
AND SL2B.L2_PEDRES <> ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''
AND SC1B.C1_PEDIDO	<> '' 
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
AND SD1B.D1_PEDIDO IS NULL
AND SC7B.C7_DATPRF <= SUA.UA_ZDTAENT	   
THEN 'COMPRA DENTRO DO PRAZO C/FIN C/PV'
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''   	
AND SL2A.L2_SOLCOM = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES = '' 	
AND SL2A.L2_PEDRES <> ''  	
THEN 'PRODUTO EM ESTOQUE S/FIN S/PV'  
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''   	
AND SL2A.L2_SOLCOM = ''  
AND SL2A.L2_ORCRES = '' 
AND SL2A.L2_PEDRES <> '' 	
AND SL2A.L2_PEDRES <> '' 
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = ''   	
THEN 'PRODUTO EM ESTOQUE S/FIN C/PV'  
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES = ''   	
AND SL2B.L2_SOLCOM = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
THEN 'PRODUTO EM ESTOQUE C/FIN S/PV' 
    WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES <> ''   	
AND SL2B.L2_SOLCOM = ''		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
THEN 'PRODUTO EM ESTOQUE C/FIN C/PV'     
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = ''   	
AND SL2A.L2_PEDRES <> ''   	
AND SL2A.L2_SOLCOM <> ''
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_SERIE <> ''				   
AND SD1A.D1_DOC <> ''
AND SC6A.C6_SERIE = ''	   
AND SC6A.C6_NOTA  = '' 
THEN 'PRODUTO EM ESTOQUE (JA COMPRADO) S/FIN C/PV'
    WHEN      
	SL1.L1_SERPED = '' 	  
AND SL1.L1_DOCPED = ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES = ''   	
AND SL2A.L2_PEDRES = ''   	
AND SL2A.L2_SOLCOM <> ''
AND SC1A.C1_PEDIDO	<> '' 
AND SD1A.D1_SERIE <> ''				   
AND SD1A.D1_DOC <> ''
THEN 'PRODUTO EM ESTOQUE (JA COMPRADO) S/FIN S/PV'  
	WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES = '' 		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  	
AND SL2B.L2_SOLCOM <> '' 
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_SERIE <> ''				   
AND SD1B.D1_DOC <> ''  
THEN 'PRODUTO EM ESTOQUE (JA COMPRADO) C/FIN S/PV'      
 	WHEN      
	SL1.L1_SERPED <> '' 	  
AND SL1.L1_DOCPED <> ''   
AND SL2A.L2_SERIE  = ''   
AND SL2A.L2_DOC    = ''  
AND SL2A.L2_ORCRES <> ''   	
AND SL2B.L2_PEDRES <> '' 		
AND SL2B.L2_SERIE  = ''   	
AND SL2B.L2_DOC    = ''  	
AND SL2B.L2_SOLCOM <> '' 
AND SC1B.C1_PEDIDO	<> '' 
AND SD1B.D1_SERIE <> ''				   
AND SD1B.D1_DOC <> ''  
AND SC6B.C6_SERIE = ''	   
AND SC6B.C6_NOTA  = '' 
THEN 'PRODUTO EM ESTOQUE (JA COMPRADO) C/FIN C/PV' 
    WHEN      
    SC6A.C6_SERIE <> ''	   
AND SC6A.C6_NOTA  <> '' 	   
THEN 'FATURADO (NO PV S/FIN)' 
    WHEN      
    SC6B.C6_SERIE <> ''	   
AND SC6B.C6_NOTA  <> '' 	   
THEN 'FATURADO (NO PV C/FIN)' 
    WHEN 
	SL2A.L2_SERIE  <> ''   
AND SL2A.L2_DOC    <> ''   
THEN 'FATURADO (VENDA DIRETA)'
	WHEN      
	SC6C.C6_PRODUTO IS NOT NULL
THEN 'TROCA DE PRODUTO DE: ' + RTRIM(SL2A.L2_PRODUTO) + ' | PARA: ' + SC6C.C6_PRODUTO
	WHEN      
	SC6D.C6_PRODUTO IS NOT NULL
THEN 'TROCA DE PRODUTO DE: ' + RTRIM(SL2B.L2_PRODUTO) + ' | PARA: ' + SC6D.C6_PRODUTO
	ELSE 'OUTROS - (ALGUM ERRO DE PROCESSO OU DE RELACIONAMENTO)'
END AS SITUAÇÃO


FROM SUA010 SUA/*ATENDIMENTO CABEÇARIO*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ =  '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM 		
/*ATENDIMENTO ITEMS*/  	 LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ =  '' AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/			 LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*FORNECEDOR*/			 LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/	   	     LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*ORC SL1 (PAI)*/		 LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ =  '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM
/*ORC SL2 PAI*/	         LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SUA.UA_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO
/*ORC SL2 FILHO*/		 LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO
/*PV SC6 (PAI)*/   		 LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2A.L2_FILIAL AND SC6A.C6_NUM = SL2A.L2_PEDRES AND SC6A.C6_ITEM = SL2A.L2_ITEM AND SC6A.C6_PRODUTO = SL2A.L2_PRODUTO
/*PV SC6 (FILHO)*/  	 LEFT JOIN SC6010 SC6B ON SC6B.D_E_L_E_T_ = '' AND SC6B.C6_FILIAL = SL2B.L2_FILIAL AND SC6B.C6_NUM = SL2B.L2_PEDRES AND SC6B.C6_ITEM = SL2B.L2_ITEM AND SC6B.C6_PRODUTO = SL2B.L2_PRODUTO
/*SC SC1 (PAI)*/ 		 LEFT JOIN SC1010 SC1A ON SC1A.D_E_L_E_T_ = '' AND SC1A.C1_FILENT = SL2A.L2_FILIAL AND SC1A.C1_NUM = SL2A.L2_SOLCOM AND SC1A.C1_PRODUTO = SL2A.L2_PRODUTO
/*SC SC1 (FILHO)*/ 		 LEFT JOIN SC1010 SC1B ON SC1B.D_E_L_E_T_ = '' AND SC1B.C1_FILIAL = SL2B.L2_FILIAL AND SC1B.C1_NUM = SL2B.L2_SOLCOM AND SC1B.C1_PRODUTO = SL2B.L2_PRODUTO
/*PC SC7 (PAI)*/		 LEFT JOIN SC7010 SC7A ON SC7A.D_E_L_E_T_ = '' AND SC7A.C7_FILIAL = SC1A.C1_FILIAL AND SC7A.C7_NUMSC = SC1A.C1_NUM AND SC7A.C7_ITEMSC = SC1A.C1_ITEM AND SC7A.C7_PRODUTO = SC1A.C1_PRODUTO
/*PC SC7 (FILHO)*/ 		 LEFT JOIN SC7010 SC7B ON SC7B.D_E_L_E_T_ = '' AND SC7B.C7_FILIAL = SC1B.C1_FILIAL AND SC7B.C7_NUMSC = SC1B.C1_NUM AND SC7B.C7_ITEMSC = SC1B.C1_ITEM AND SC7B.C7_PRODUTO = SC1B.C1_PRODUTO
/*DOC.ENTR SD1(PAI)*/    LEFT JOIN SD1010 SD1A ON SD1A.D_E_L_E_T_ = '' AND SD1A.D1_FILIAL = SC7A.C7_FILENT AND SD1A.D1_PEDIDO = SC7A.C7_NUM AND SD1A.D1_COD = SC7A.C7_PRODUTO AND SD1A.D1_ITEMPC = SC7A.C7_ITEM
/*DOC.ENTR SD1(FILHO)*/  LEFT JOIN SD1010 SD1B ON SD1B.D_E_L_E_T_ = '' AND SD1B.D1_FILIAL = SC7B.C7_FILENT AND SD1B.D1_PEDIDO = SC7B.C7_NUM AND SD1B.D1_COD = SC7B.C7_PRODUTO AND SD1B.D1_ITEMPC = SC7B.C7_ITEM
/*TROOC.PROD (PAI)*/	 LEFT JOIN SC6010 SC6C ON SC6C.D_E_L_E_T_ = '' AND SC6C.C6_FILIAL = SL2A.L2_FILIAL AND SC6C.C6_NUM = SL2A.L2_PEDRES AND SC6C.C6_ITEM = SL2A.L2_ITEM AND SC6C.C6_PRODUTO <> SL2A.L2_PRODUTO
/*TROOC.PROD (FILHO)*/	 LEFT JOIN SC6010 SC6D ON SC6D.D_E_L_E_T_ = '' AND SC6D.C6_FILIAL = SL2B.L2_FILIAL AND SC6D.C6_NUM = SL2B.L2_PEDRES AND SC6D.C6_ITEM = SL2B.L2_ITEM AND SC6D.C6_PRODUTO <> SL2B.L2_PRODUTO
WHERE 1=1
/*----------------SUA - ATENDIMENTO----------------*/

AND SUA.D_E_L_E_T_ = ''	 -- SUA ATENDIMENTO
AND SUA.UA_OPER <> '3'	 -- SUA ATENDIMENTO
AND SUA.UA_NUMSL1 <> ''	 -- SUA ATENDIMENTO

/*---------------SL1 - (700 OU NAO)----------------*/

--AND SL1.L1_SERPED <> '' 	  -- FINANCEIRO (700)
--AND SL1.L1_DOCPED <> ''     -- FINANCEIRO (700) 
  AND SL1.L1_PEDRES = ''

/*----------------SL2 - (ORC PAI)------------------*/  

--AND SL2A.L2_FILRES = ''   -- SL2 PAI
--AND SL2A.L2_PEDRES = ''   -- SL2 PAI
--AND SL2A.L2_ORCRES <> ''  -- SL2 PAI
--AND SL2A.L2_SERPED = ''   -- SL2 PAI
--AND SL2A.L2_DOCPED = ''   -- SL2 PAI
--AND SL2A.L2_SOLCOM = ''	-- SL2 PAI
--AND SL2A.L2_SERIE  = ''   -- SL2 PAI
--AND SL2A.L2_DOC    = ''   -- SL2 PAI
--AND SL2A.L2_NUM IS NOT NULL

/*----------------SL2 - (ORC FILHO)----------------*/ 

--AND SL2B.L2_FILRES  = ''   	-- SL2 FILHO
--AND SL2B.L2_PEDRES <> ''   	-- SL2 FILHO
--AND SL2B.L2_ORCRES  = ''   	-- SL2 FILHO
--AND SL2B.L2_SERPED  = ''   	-- SL2 FILHO
--AND SL2B.L2_DOCPED  = ''	  	-- SL2 FILHO
--AND SL2B.L2_SOLCOM <> ''		-- SL2 FILHO	
--AND SL2B.L2_SERIE  = ''   	-- SL2 FILHO
--AND SL2B.L2_DOC    = ''   	-- SL2 FILHO
--AND SL2B.L2_NUM IS NOT NULL  -- UTILIZAR ESSE FILTRO PARA ATENDIMENTOS QUE ESTAJAM COM SERIE_PAI E NOTA_PAI EM BRANCO		

/*--------SC6 - (PEDIDO DE VENDA/RESERVA)----------*/ 

--AND SC6A.C6_SERIE = ''	 	-- SC6 PV (PAI)
--AND SC6A.C6_NOTA  = '' 	 	-- SC6 PV (PAI)
--AND SC6B.C6_SERIE = ''	 	-- SC6 PV (FILHO)
--AND SC6B.C6_NOTA  = '' 	 	-- SC6 PV (FILHO)

/*--------SC1 - (SOLICITAÇÃO DE COMPRA)-----------*/
 
--AND SC1A.C1_PEDIDO	<> ''	-- SC1 SC (PAI)
--AND SC1B.C1_PEDIDO	<> ''	-- SC1 SC (FILHO)

/*----------SC7 - (PEDIDO DE COMPRA)-------------*/
 
--AND SC7A.C7_NUMSC = ''		-- SC7 PC (PAI)
--AND SC7A.C7_NUM   = ''		-- SC7 PC (PAI)
--AND SC7B.C7_NUMSC = ''		-- SC7 PC (FILHO)
--AND SC7B.C7_NUM   = ''		-- SC7 PC (FILHO)

/*----------FILTROS GERAIS-------------*/

--AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT		-- ATRASADO (PAI)
--AND SC7A.C7_DATPRF < SUA.UA_ZDTAENT		-- NO PRAZO (PAI)
--AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		-- ATRASADO (FILHO)
--AND SC7B.C7_DATPRF < SUA.UA_ZDTAENT		-- NO PRAZO (FILHO)
--AND SL2A.L2_NUM IS NOT NULL
AND YEAR(SUA.UA_EMISSAO) IN(2020)
--AND MONTH(SUA.UA_EMISSAO) IN(6,7)
--AND MONTH(SUA.UA_EMISSAO) = 12	 
AND SA3.A3_ZSITVND IN ('1','2')
--AND SA3.A3_COD = '000064'		
--AND SUA.UA_NUM = '025840'
--  AND SUA.UA_FILIAL = '0101'
--  AND SUA.UA_NUM = '024039'
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
  AND SUA.UA_FILIAL = @V
  AND SUA.UA_NUM = @ATM