
SELECT 
SUA.UA_FILIAL 		  			AS FILIAL_ATM,
SUA.UA_NUM 			  			AS NUM_ATM,
SUA.UA_VLRLIQ					AS VLR_TOTAL


/*ATENDIMENTO*/	FROM SUA010 SUA
/*PRODUTOS ATM*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ = ''  AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
/*CAD PROD*/   	LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ = ''  AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/    LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*CONTATO*/		LEFT JOIN SU5010 SU5  ON SU5.D_E_L_E_T_ = ''  AND SU5.U5_CODCONT = SUA.UA_CODCONT 
/*FORNECEDOR*/  LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/    LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*SL1 PAI*/	   	LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ = ''  AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
/*SL2 PAI*/	   	LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SL1.L1_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO 
/*SL2 FILHO*/	LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO
/*SC0 RES MANU*/LEFT JOIN SC0010 SC0  ON SC0.D_E_L_E_T_ = ''  AND SC0.C0_FILRES = SL2A.L2_FILIAL AND SUBSTRING(SC0.C0_OBS,8,6) = SL2A.L2_NUM AND SC0.C0_PRODUTO = SL2A.L2_PRODUTO 

/*--------------------PADRAO-----------------------*/

/*SC1 SC*/	    LEFT JOIN SC1010 SC1  ON SC1.D_E_L_E_T_ = ''  AND SC1.C1_FILENT = SL2A.L2_FILIAL AND SC1.C1_NUM = SL2A.L2_SOLCOM AND SC1.C1_ORCAM = SL2A.L2_NUM AND SC1.C1_PRODUTO = SL2A.L2_PRODUTO AND SC1.C1_ZITNORC = SL2A.L2_ITEM
/*SC7 PC*/		LEFT JOIN SC7010 SC7  ON SC7.D_E_L_E_T_ = ''  AND SC7.C7_FILIAL = SC1.C1_FILIAL AND SC7.C7_NUM = SC1.C1_PEDIDO AND SC7.C7_PRODUTO = SC1.C1_PRODUTO AND SC7.C7_NUMSC = SC1.C1_NUM AND SC7.C7_ITEMSC = SC1.C1_ITEM
/*SC6 PV*/		LEFT JOIN SC6010 SC6  ON SC6.D_E_L_E_T_ = ''  AND SC6.C6_FILIAL = SL2B.L2_FILIAL AND SC6.C6_NUM = SL2B.L2_PEDRES AND SC6.C6_PRODUTO = SL2B.L2_PRODUTO AND SC6.C6_ITEM = SL2B.L2_ITEM 
/*SC5 PV*/		LEFT JOIN SC5010 SC5  ON SC5.D_E_L_E_T_ = ''  AND SC5.C5_FILIAL = SC6.C6_FILIAL AND SC5.C5_NUM = SC6.C6_NUM
/*SD1 DOC.ENTR*/LEFT JOIN SD1010 SD1  ON SD1.D_E_L_E_T_ = ''  AND SD1.D1_FILIAL = SC7.C7_FILENT AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_COD = SC7.C7_PRODUTO AND SD1.D1_ITEMPC = SC7.C7_ITEM
/*SD2 DOC. SAI*/LEFT JOIN SD2010 SD2  ON SD2.D_E_L_E_T_ = ''  AND SD2.D2_FILIAL = SC6.C6_FILIAL AND SD2.D2_PEDIDO = SC6.C6_NUM AND SD2.D2_COD = SC6.C6_PRODUTO AND SD2.D2_ITEMPV = SC6.C6_ITEM 
/*SC9 LIBERA*/	LEFT JOIN SC9010 SC9  ON SC9.D_E_L_E_T_ = ''  AND SC9.C9_FILIAL = SC6.C6_FILIAL AND SC9.C9_PEDIDO = SC6.C6_NUM AND SC9.C9_ITEM = SC6.C6_ITEM AND SC9.C9_PRODUTO = SC6.C6_PRODUTO


/*--------------------TROCA-----------------------*/

/*SC6 PV TROCA*/LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2B.L2_FILIAL AND SC6A.C6_NUM = SL2B.L2_PEDRES AND SC6A.C6_ITEM = SL2B.L2_ITEM AND SC6A.C6_PRODUTO <> SL2B.L2_PRODUTO
/*SC1 TROCA*/ 	LEFT JOIN SC1010 SC1A ON SC1A.D_E_L_E_T_ = '' AND SC1A.C1_ZFILPV = SC6A.C6_FILIAL AND SC1A.C1_ZNUMPV = SC6A.C6_NUM AND SC1A.C1_PRODUTO = SC6A.C6_PRODUTO AND SC1A.C1_ZITMPV = SC6A.C6_ITEM
/*SC7 PC TROCA*/LEFT JOIN SC7010 SC7A ON SC7A.D_E_L_E_T_ = '' AND SC7A.C7_FILIAL = SC1A.C1_FILIAL AND SC7A.C7_NUM = SC1A.C1_PEDIDO AND SC7A.C7_PRODUTO = SC1A.C1_PRODUTO AND SC7A.C7_NUMSC = SC1A.C1_NUM AND SC7A.C7_ITEMSC = SC1A.C1_ITEM
/*SC5 PV TROCA*/LEFT JOIN SC5010 SC5A ON SC5A.D_E_L_E_T_ = '' AND SC5A.C5_FILIAL = SC6A.C6_FILIAL AND SC5A.C5_NUM = SC6A.C6_NUM
/*SD1 DOC.ENTR*/LEFT JOIN SD1010 SD1A ON SD1A.D_E_L_E_T_ = '' AND SD1A.D1_FILIAL = SC7A.C7_FILENT AND SD1A.D1_PEDIDO = SC7A.C7_NUM AND SD1A.D1_COD = SC7A.C7_PRODUTO AND SD1A.D1_ITEMPC = SC7A.C7_ITEM
/*SD2DOC.SAI.T*/LEFT JOIN SD2010 SD2A ON SD2A.D_E_L_E_T_ = '' AND SD2A.D2_FILIAL = SC6A.C6_FILIAL AND SD2A.D2_PEDIDO = SC6A.C6_NUM AND SD2A.D2_COD = SC6A.C6_PRODUTO AND SD2A.D2_ITEMPV = SC6A.C6_ITEM 
/*SC9 LIBERA T*/LEFT JOIN SC9010 SC9A ON SC9A.D_E_L_E_T_ = '' AND SC9A.C9_FILIAL = SC6A.C6_FILIAL AND SC9A.C9_PEDIDO = SC6A.C6_NUM AND SC9A.C9_ITEM = SC6A.C6_ITEM AND SC9A.C9_PRODUTO = SC6A.C6_PRODUTO

WHERE 1=1

/*--------------------CONDIÇÕES----------------------*/

AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_OPER   <> '3' 
AND YEAR(SUA.UA_EMISSAO) IN (2019,2020)
AND SA3.A3_ZSITVND IN ('1','2')
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
--AND SUA.UA_NUMSL1 <> ''
--AND SUA.UA_FILIAL = '0101'
--AND SUA.UA_NUM = '007495'
--AND SC6.C6_NUM = '009785'

/*---------------GROUP BY------------------*/

GROUP BY  SUA.UA_NUM, SUA.UA_FILIAL, SUA.UA_VLRLIQ

/*---------------ORDER BY------------------*/

ORDER BY SUA.UA_FILIAL, SUA.UA_NUM