CREATE PROCEDURE Z_CUBO AS


	EXEC UPDATE_ITEM_SL2_SC6_SC1
	DROP TABLE ZCUBO
	DROP TABLE AUXZCUBO
	
/*---------------------------------------------TABELA AUXILIAR--------------------------------------------------------*/


CREATE TABLE AUXZCUBO
    (
	Z_NUM_ATM			VARCHAR(6),
	Z_FILIAL_ATM		VARCHAR(4),
	Z_DT_EMI_ATM		VARCHAR(30),
	Z_CODPROD			VARCHAR(15),
	Z_PROD_TROCADO		VARCHAR(15),
	Z_PROD_REAL			VARCHAR(15),
	Z_PRODUTO			VARCHAR(70),
	Z_PROD_DESC_REDU	VARCHAR(40),
	Z_COD_APRE			VARCHAR(18),
	Z_QTD				FLOAT,
	Z_UND				VARCHAR(2),
	Z_SLD_FIS			FLOAT,
	Z_SLD_RES			FLOAT,
	Z_SLD_DISP			FLOAT,
	Z_COD_CLI			VARCHAR(6),
	Z_NOME_CLI			VARCHAR(70),
	Z_NOME_CLI_REDU		VARCHAR(20),
	Z_CNPJ_CPF			VARCHAR(18),
	Z_IE				VARCHAR(18),
	Z_CONTRIBU			VARCHAR(1),
	Z_CIDADE_UF			VARCHAR(63),
	Z_COD_CONTAT		VARCHAR(6),
	Z_CONTATO			VARCHAR(15),
	Z_DDD				VARCHAR(3),
	Z_FONE				VARCHAR(15),
	Z_CELULAR			VARCHAR(15),	
	Z_COD_VEND			VARCHAR(6),
	Z_VENDEDOR			VARCHAR(40),
	Z_COD_FOR			VARCHAR(6),
	Z_FORNECEDOR		VARCHAR(40),
	Z_NOME_FOR_REDU		VARCHAR(20),
	Z_PRZ_FOR_DIAS		INT,
	Z_VLR_TOTAL_ATM		FLOAT,	
	Z_CSTREP_L2			FLOAT,
	Z_CUSTD_B1			FLOAT,
	Z_VLR_UNI_UB		FLOAT,
	Z_VLR_UNI_PV		FLOAT,
	Z_TIPO_VENDA		VARCHAR(15),	
	Z_OPER_ATM			VARCHAR(1),   
	Z_NUMSL1_ATM		VARCHAR(6),
	Z_STATUS_ATM		VARCHAR(3),
	Z_CANCEL_ATM		VARCHAR(1),
	Z_DT_LIB_FAT		VARCHAR(30),
	Z_DATA_FAT			VARCHAR(30),
	Z_SER700			VARCHAR(3),
	Z_DOC700			VARCHAR(9),
	Z_NUM_RES_MANU		VARCHAR(6),
	Z_FILIAL_PAI		VARCHAR(4),
	Z_NUM_ORC_PAI		VARCHAR(6),
	Z_SERIE_PAI			VARCHAR(3),
	Z_NOTA_PAI			VARCHAR(9),
	Z_EMI_PAI			VARCHAR(30),
	Z_FILIAL_FILHO		VARCHAR(4),
	Z_NUM_ORC_FILHO 	VARCHAR(6),
	Z_SERIE_FILHO		VARCHAR(3),
	Z_NOTA_FILHO		VARCHAR(9),
	Z_EMI_FILHO			VARCHAR(30),
	Z_FILIAL_SC			VARCHAR(4),
	Z_NUM_SC			VARCHAR(6),
	Z_QTD_SC			FLOAT,
	Z_EMI_SC			VARCHAR(30),
	Z_FILIAL_PC			VARCHAR(4),		
	Z_NUM_PC			VARCHAR(6),
	Z_QTD_PC			FLOAT,
	Z_EMI_PC			VARCHAR(30),
	Z_FILIAL_PV			VARCHAR(4),
	Z_NUM_PV			VARCHAR(6),
	Z_ITEM_PV			VARCHAR(2),
	Z_QTD_PV			FLOAT,
	Z_QTD_LIB			FLOAT,
	Z_BLEST_C9			VARCHAR(2),
	Z_BLQ_C6			VARCHAR(2),
	Z_EMI_PV			VARCHAR(30),
	Z_SERIE_SAIDA		VARCHAR(3),
	Z_NOTA_SAIDA		VARCHAR(9),
	Z_DT_NOTA_SAIDA		VARCHAR(30),
	Z_SERIE_ENTRADA		VARCHAR(3),
	Z_NOTA_ENTRADA    	VARCHAR(9),
	Z_DT_NOTA_ENTRADA	VARCHAR(30),
	Z_PRZ_ENT_FOR		VARCHAR(30),
	Z_DT_ENT_CLI      	VARCHAR(30),
	Z_PRZ_ENT_CLI		INT,
	Z_DT_HJ				VARCHAR(30),
	Z_ATRASADO			VARCHAR(1),
    R_E_C_N_O_ 			INT IDENTITY(1,1),
	)
	
	
INSERT INTO AUXZCUBO(
	Z_NUM_ATM			,
	Z_FILIAL_ATM		,
	Z_DT_EMI_ATM		,
	Z_CODPROD			,
	Z_PROD_TROCADO		,
	Z_PROD_REAL			,
	Z_PRODUTO			,
	Z_PROD_DESC_REDU	,
	Z_COD_APRE			,
	Z_QTD				,
	Z_UND				,
	Z_SLD_FIS			,
	Z_SLD_RES			,
	Z_SLD_DISP			,
	Z_COD_CLI			,
	Z_NOME_CLI			,
	Z_NOME_CLI_REDU		,
	Z_CNPJ_CPF			,
	Z_IE				,
	Z_CONTRIBU			,
	Z_CIDADE_UF			,
	Z_COD_CONTAT		,
	Z_CONTATO			,
	Z_DDD				,
	Z_FONE				,
	Z_CELULAR			 ,	
	Z_COD_VEND			,
	Z_VENDEDOR			,
	Z_COD_FOR			,
	Z_FORNECEDOR		,
	Z_NOME_FOR_REDU		,
	Z_PRZ_FOR_DIAS		,
	Z_VLR_TOTAL_ATM		 ,	
	Z_CSTREP_L2			,
	Z_CUSTD_B1			,	
	Z_VLR_UNI_UB		,
	Z_VLR_UNI_PV		,
	Z_TIPO_VENDA	   ,
	Z_OPER_ATM			,
	Z_NUMSL1_ATM		,
	Z_STATUS_ATM		,
	Z_CANCEL_ATM		,
	Z_DT_LIB_FAT		,
	Z_DATA_FAT			,
	Z_SER700			,
	Z_DOC700			,
	Z_NUM_RES_MANU		,
	Z_FILIAL_PAI		,
	Z_NUM_ORC_PAI		,
	Z_SERIE_PAI			,
	Z_NOTA_PAI			,
	Z_EMI_PAI			,
	Z_FILIAL_FILHO		,
	Z_NUM_ORC_FILHO 	,
	Z_SERIE_FILHO		,
	Z_NOTA_FILHO		,
	Z_EMI_FILHO			,
	Z_FILIAL_SC		    ,
	Z_NUM_SC		    ,
	Z_QTD_SC			,	
	Z_EMI_SC		    ,
	Z_FILIAL_PC		   	,
	Z_NUM_PC		    ,
	Z_QTD_PC			,
	Z_EMI_PC		    ,
	Z_FILIAL_PV			,
	Z_NUM_PV			,
	Z_ITEM_PV			,
	Z_QTD_PV			,
	Z_QTD_LIB			,
	Z_BLEST_C9			,
	Z_BLQ_C6			,
	Z_EMI_PV			,
	Z_SERIE_SAIDA		,
	Z_NOTA_SAIDA		,
	Z_DT_NOTA_SAIDA		,
	Z_SERIE_ENTRADA		,
	Z_NOTA_ENTRADA    	,
	Z_DT_NOTA_ENTRADA	,
	Z_PRZ_ENT_FOR	    ,
	Z_DT_ENT_CLI        ,
	Z_PRZ_ENT_CLI	    ,
	Z_DT_HJ			    ,
	Z_ATRASADO	
)



SELECT 

/*----------------------ATENDIMENTO--------------------------*/

SUA.UA_NUM 			  			AS NUM_ATM,
SUA.UA_FILIAL 		  			AS FILIAL_ATM,
CASE
	WHEN YEAR(SUA.UA_EMISSAO) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) 
END AS DT_EMI_ATM,

/*----------------------PRODUTOS----------------------------*/

SUB.UB_PRODUTO 		  			AS CODPROD,
SC6A.C6_PRODUTO 				AS CODPROD_TROCADO,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN SC6A.C6_PRODUTO
	WHEN SC6A.C6_PRODUTO IS NULL
THEN SB1.B1_COD
END AS CODPROD_REAL,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT B1_DESC FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SC6A.C6_PRODUTO),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT B1_DESC FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SB1.B1_COD),0)
END AS PRODUTO,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT B1_ZDESRDZ FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SC6A.C6_PRODUTO),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT B1_ZDESRDZ FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SB1.B1_COD),0)
END AS PROD_DESC_REDU,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT B1_ZAPRES1 FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SC6A.C6_PRODUTO),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT B1_ZAPRES1 FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SB1.B1_COD),0)
END AS COD_APRE, 
SUB.UB_QUANT AS QTD,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT B1_UM FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SC6A.C6_PRODUTO),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT B1_UM FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = SB1.B1_COD),0)
END AS UND,

/*--------------------SALDOS DE ESTOQUE----------------------------*/

CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT SUM(B2_QATU) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SC6A.C6_PRODUTO AND B2_LOCAL = '01'),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT SUM(B2_QATU) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SB1.B1_COD AND B2_LOCAL = '01'),0)
END AS SLD_FIS,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SC6A.C6_PRODUTO AND B2_LOCAL = '01'),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SB1.B1_COD AND B2_LOCAL = '01'),0) 
END AS SLD_RES,
CASE 
	WHEN SC6A.C6_PRODUTO <> ''
THEN ISNULL((SELECT SUM(B2_QATU - B2_RESERVA) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SC6A.C6_PRODUTO AND B2_LOCAL = '01'),0)
	WHEN SC6A.C6_PRODUTO IS NULL
THEN ISNULL((SELECT SUM(B2_QATU - B2_RESERVA) FROM SB2010 WHERE 1=1 AND D_E_L_E_T_ = '' AND B2_COD = SB1.B1_COD AND B2_LOCAL = '01'),0)
END AS SLD_DISP,

/*--------------------CLIENTE/FORNECEDOR/VENDEDOR----------------------------*/

SUA.UA_CLIENTE		  			AS COD_CLI,
SA1.A1_NOME 			  	   	AS NOME_CLI,
SA1.A1_NREDUZ					AS NOME_CLI_REDU,
dbo.formatarCNPJCPF(SA1.A1_CGC) AS CNPJ_CPF,
SA1.A1_INSCR					AS I_E,
CASE
	WHEN SA1.A1_CONTRIB = '1'
THEN 'S'
	WHEN SA1.A1_CONTRIB = '2'
THEN 'N'
ELSE ''
END AS CONTRIBUINTE,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SU5.U5_CODCONT					AS COD_CONTAT, 
SUBSTRING(SU5.U5_CONTAT,1,15) 	AS CONTATO,
SU5.U5_DDD						AS DDD, 
SU5.U5_FONE						AS FONE, 
SU5.U5_CELULAR					AS CELULAR,
SA3.A3_COD 		      			AS COD_VEND,
SA3.A3_NOME 			  		AS VENDEDOR,
SA2.A2_COD						AS COD_FOR,
SA2.A2_NOME						AS FORNECEDOR,
SA2.A2_NREDUZ					AS NOME_FOR_REDU,
CAST(SB1.B1_PE AS DECIMAL(3,0)) AS PRZ_FOR_DIAS,
SUA.UA_VLRLIQ					AS VLR_TOTAL_ATM,
SL2A.L2_ZCSTREP					AS CST_REP_L2,
SB1.B1_CUSTD					AS CUSTD_B1,
SUB.UB_VRUNIT					AS VLR_UNI_UB,
CASE
	WHEN SC6.C6_PRCVEN = SC6A.C6_PRCVEN
THEN SC6.C6_PRCVEN
	WHEN SC6.C6_PRCVEN <> SC6A.C6_PRCVEN
THEN SC6A.C6_PRCVEN
	WHEN SC6.C6_PRCVEN IS NULL
THEN SC6A.C6_PRCVEN
	WHEN SC6A.C6_PRCVEN IS NULL
THEN SC6.C6_PRCVEN
ELSE ''
END AS VLR_UNI_PV,

CASE
	WHEN SUA.UA_ZTIPVND = '1'
THEN 'VENDA VAREJO'
	WHEN SUA.UA_ZTIPVND = '2'
THEN 'VENDA PROJETO'
	WHEN SUA.UA_ZTIPVND = '3'
THEN 'VENDA INDUSTRIA'
ELSE ''
END AS TIPO_VENDA,
SUA.UA_OPER						AS OPER_ATM,
SUA.UA_NUMSL1					AS NUMSL1_ATM,
SUA.UA_STATUS					AS STATUS_ATM,
SUA.UA_CANC						AS CANCEL_ATM,

/*----------------------FINANCEIRO--------------------------*/

CASE
	WHEN YEAR(SUA.UA_ZDTLBFT) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SUA.UA_ZDTLBFT AS DATETIME),103)
END AS DT_LIB_FAT,	
CASE
	WHEN YEAR(SL1.L1_EMISNF) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103) 
END AS DATA_FAT,
SL1.L1_SERPED 					AS SERIE_700,
SL1.L1_DOCPED 					AS DOC_700,

/*--------------------RESERVA MANUAL----------------------------*/

SC0.C0_NUM    					AS NUM_RESERVA_MANU,

/*-----------------------ORC PAI-------------------------*/

SL2A.L2_FILIAL 					AS FILIAL_ORC_PAI,
SL2A.L2_NUM	  					AS NUM_ORC_PAI,	
SL2A.L2_SERIE 					AS SERIE_ORC_PAI,
SL2A.L2_DOC	  					AS DOC_ORC_PAI, 
CASE
	WHEN YEAR(SL2A.L2_EMISSAO) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL2A.L2_EMISSAO AS DATETIME),103) 
END AS DT_EMI_ORCPAI,

/*-------------------ORC FILHO---------------------------*/

SL2B.L2_FILIAL 					AS FILIAL_ORC_FILHO,
SL2B.L2_NUM	   					AS NUM_ORC_FILHO,
SL2B.L2_SERIE  					AS SERIE_ORC_FILHO,
SL2B.L2_DOC	   					AS DOC_ORC_FILHO,
CASE
	WHEN YEAR(SL2B.L2_EMISSAO) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SL2B.L2_EMISSAO AS DATETIME),103) 
END AS DT_EMI_ORCFILHO,

/*----------------------SOLICITAÇÃO DE COMPRAS--------------------------*/

CASE 
	WHEN
		SC1A.C1_FILIAL IS NULL
	AND SC1X.C1_FILIAL IS NULL
THEN SC1.C1_FILIAL 
	WHEN
	 SC1X.C1_FILIAL <> ''
THEN SC1X.C1_FILIAL 
ELSE SC1A.C1_FILIAL
END AS FILIAL_SC,
CASE 
	WHEN
		SC1A.C1_NUM IS NULL
	AND SC1X.C1_NUM IS NULL
THEN SC1.C1_NUM 
	WHEN
	 SC1X.C1_NUM <> ''
THEN SC1X.C1_NUM 
ELSE SC1A.C1_NUM
END AS NUM_SC,
CASE 
	WHEN
		SC1A.C1_QUANT IS NULL
	AND SC1X.C1_QUANT IS NULL
THEN SC1.C1_QUANT 
	WHEN
	 SC1X.C1_QUANT <> ''
THEN SC1X.C1_QUANT 
ELSE SC1A.C1_QUANT
END AS QTD_SC,
CASE 
	WHEN
		SC1A.C1_EMISSAO IS NULL
	AND SC1X.C1_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC1.C1_EMISSAO AS DATETIME),103) 
	WHEN
	 SC1X.C1_EMISSAO <> ''
THEN CONVERT(VARCHAR,CAST(SC1X.C1_EMISSAO AS DATETIME),103) 
ELSE CONVERT(VARCHAR,CAST(SC1A.C1_EMISSAO AS DATETIME),103) 
END AS DT_EMI_SC,


/*------------------------PEDIDO DE COMPRAS------------------------*/

CASE 
	WHEN
		SC7A.C7_FILIAL IS NULL
	AND SC7X.C7_FILIAL IS NULL
THEN SC7.C7_FILIAL 
	WHEN
	 SC7X.C7_FILIAL <> ''
THEN SC7X.C7_FILIAL 
ELSE SC7A.C7_FILIAL
END AS FILIAL_PC,
CASE 
	WHEN
		SC7A.C7_NUM IS NULL
	AND SC7X.C7_NUM IS NULL
THEN SC7.C7_NUM 
	WHEN
	 SC7X.C7_NUM <> ''
THEN SC7X.C7_NUM 
ELSE SC7A.C7_NUM
END AS NUM_PC,
CASE 
	WHEN
		(SC7A.C7_QUANT - SC7A.C7_QUJE) IS NULL
	AND (SC7X.C7_QUANT - SC7X.C7_QUJE) IS NULL
THEN (SC7.C7_QUANT - SC7.C7_QUJE)
	WHEN
	 (SC7X.C7_QUANT - SC7X.C7_QUJE) <> ''
THEN (SC7X.C7_QUANT - SC7X.C7_QUJE)
ELSE (SC7A.C7_QUANT - SC7A.C7_QUJE)
END AS QTD_PC,
CASE 
	WHEN
		SC7A.C7_EMISSAO IS NULL
	AND SC7X.C7_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC7.C7_EMISSAO AS DATETIME),103) 
	WHEN
	 SC7X.C7_EMISSAO <> ''
THEN CONVERT(VARCHAR,CAST(SC7X.C7_EMISSAO AS DATETIME),103) 
ELSE CONVERT(VARCHAR,CAST(SC7A.C7_EMISSAO AS DATETIME),103) 
END AS DT_EMI_PC,


/*-----------------------PEDIDO DE VENDA-------------------------*/

CASE
	WHEN SC6.C6_FILIAL = SC6A.C6_FILIAL
THEN SC6.C6_FILIAL
	WHEN SC6.C6_FILIAL <> SC6A.C6_FILIAL
THEN SC6A.C6_FILIAL
	WHEN SC6.C6_FILIAL IS NULL
THEN SC6A.C6_FILIAL
	WHEN SC6A.C6_FILIAL IS NULL
THEN SC6.C6_FILIAL
ELSE ''
END AS FILIAL_PV,
CASE
	WHEN SC6.C6_NUM = SC6A.C6_NUM
THEN SC6.C6_NUM
	WHEN SC6.C6_NUM <> SC6A.C6_NUM
THEN SC6A.C6_NUM
	WHEN SC6.C6_NUM IS NULL
THEN SC6A.C6_NUM
	WHEN SC6A.C6_NUM IS NULL
THEN SC6.C6_NUM
ELSE ''
END AS NUM_PV,
CASE
	WHEN SC6.C6_ITEM = SC6A.C6_ITEM
THEN SC6.C6_ITEM
	WHEN SC6.C6_ITEM <> SC6A.C6_ITEM
THEN SC6A.C6_ITEM
	WHEN SC6.C6_ITEM IS NULL
THEN SC6A.C6_ITEM
	WHEN SC6A.C6_ITEM IS NULL
THEN SC6.C6_ITEM
ELSE ''
END AS ITEM_PV,
CASE
	WHEN SC6.C6_QTDVEN = SC6A.C6_QTDVEN
THEN SC6.C6_QTDVEN
	WHEN SC6.C6_QTDVEN <> SC6A.C6_QTDVEN
THEN SC6A.C6_QTDVEN
	WHEN SC6.C6_QTDVEN IS NULL
THEN SC6A.C6_QTDVEN
	WHEN SC6A.C6_QTDVEN IS NULL
THEN SC6.C6_QTDVEN
ELSE ''
END AS QTD_PV,
CASE
	WHEN SC9.C9_QTDLIB = SC9A.C9_QTDLIB
THEN SC9.C9_QTDLIB
	WHEN SC9.C9_QTDLIB <> SC9A.C9_QTDLIB
THEN SC9A.C9_QTDLIB
	WHEN SC9.C9_QTDLIB IS NULL
THEN SC9A.C9_QTDLIB
	WHEN SC9A.C9_QTDLIB IS NULL
THEN SC9.C9_QTDLIB
ELSE ''
END AS QTD_LIB,
CASE
	WHEN SC9.C9_BLEST = SC9A.C9_BLEST
THEN SC9.C9_BLEST
	WHEN SC9.C9_BLEST <> SC9A.C9_BLEST
THEN SC9A.C9_BLEST
	WHEN SC9.C9_BLEST IS NULL
THEN SC9A.C9_BLEST
	WHEN SC9A.C9_BLEST IS NULL
THEN SC9.C9_BLEST
END AS C9_BLQEST,
CASE
	WHEN SC6.C6_BLQ = SC6A.C6_BLQ
THEN SC6.C6_BLQ
	WHEN SC6.C6_BLQ <> SC6A.C6_BLQ
THEN SC6A.C6_BLQ
	WHEN SC6.C6_BLQ IS NULL
THEN SC6A.C6_BLQ
	WHEN SC6A.C6_BLQ IS NULL
THEN SC6.C6_BLQ
END AS C6_BLQ,



CASE
	WHEN SC5.C5_EMISSAO = SC5A.C5_EMISSAO
THEN CONVERT(VARCHAR,CAST(SC5.C5_EMISSAO AS DATETIME),103) 
	WHEN SC5.C5_EMISSAO <> SC5A.C5_EMISSAO
THEN CONVERT(VARCHAR,CAST(SC5A.C5_EMISSAO AS DATETIME),103) 
	WHEN SC5.C5_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC5A.C5_EMISSAO AS DATETIME),103) 
	WHEN SC5A.C5_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC5.C5_EMISSAO AS DATETIME),103) 
ELSE ''
END AS DT_EMI_PV,

/*------------------------DOC DE SAIDA------------------------*/

CASE
	WHEN SC9.C9_SERIENF = SC9A.C9_SERIENF
THEN SC9.C9_SERIENF
	WHEN SC9.C9_SERIENF <> SC9A.C9_SERIENF
THEN SC9A.C9_SERIENF
	WHEN SC9.C9_SERIENF IS NULL
THEN SC9A.C9_SERIENF
	WHEN SC9A.C9_SERIENF IS NULL
THEN SC9.C9_SERIENF
ELSE ''
END AS SERIE_SAIDA,
CASE
	WHEN SC9.C9_NFISCAL = SC9A.C9_NFISCAL
THEN SC9.C9_NFISCAL
	WHEN SC9.C9_NFISCAL <> SC9A.C9_NFISCAL
THEN SC9A.C9_NFISCAL
	WHEN SC9.C9_NFISCAL IS NULL
THEN SC9A.C9_NFISCAL
	WHEN SC9A.C9_NFISCAL IS NULL
THEN SC9.C9_NFISCAL
ELSE ''
END AS NOTA_SAIDA,
CASE
	WHEN SD2.D2_EMISSAO = SD2A.D2_EMISSAO
THEN CONVERT(VARCHAR,CAST(SD2.D2_EMISSAO AS DATETIME),103) 
	WHEN SD2.D2_EMISSAO <> SD2A.D2_EMISSAO
THEN CONVERT(VARCHAR,CAST(SD2A.D2_EMISSAO AS DATETIME),103) 
	WHEN SD2.D2_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SD2A.D2_EMISSAO AS DATETIME),103) 
	WHEN SD2A.D2_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SD2.D2_EMISSAO AS DATETIME),103) 
ELSE ''
END AS DT_NOTA_SAIDA,


/*------------------------DOC DE ENTRADA------------------------*/


CASE 
	WHEN
		SD1A.D1_SERIE IS NULL
	AND SD1X.D1_SERIE IS NULL
THEN SD1.D1_SERIE
	WHEN
	 SD1X.D1_SERIE <> ''
THEN SD1X.D1_SERIE 
ELSE SD1A.D1_SERIE
END AS SERIE_ENTRADA,
CASE 
	WHEN
		SD1A.D1_DOC IS NULL
	AND SD1X.D1_DOC IS NULL
THEN SD1.D1_DOC
	WHEN
	 SD1X.D1_DOC <> ''
THEN SD1.D1_DOC
ELSE SD1A.D1_DOC
END AS NOTA_ENTRADA,
CASE 
	WHEN
		SD1A.D1_DTDIGIT IS NULL
	AND SD1X.D1_DTDIGIT IS NULL
THEN CONVERT(VARCHAR,CAST(SD1.D1_DTDIGIT AS DATETIME),103) 
	WHEN
	 SD1X.D1_DTDIGIT <> ''
THEN CONVERT(VARCHAR,CAST(SD1X.D1_DTDIGIT AS DATETIME),103)
ELSE CONVERT(VARCHAR,CAST(SD1A.D1_DTDIGIT AS DATETIME),103)
END AS DT_NOTA_ENTRADA,

 
/*-----------------------PRAZOS E DATAS-------------------------*/

CASE 
	WHEN
		SC7A.C7_DATPRF IS NULL
	AND SC7X.C7_DATPRF IS NULL
THEN CONVERT(VARCHAR,CAST(SC7.C7_DATPRF AS DATETIME),103) 
	WHEN
	 SC7X.C7_DATPRF <> ''
THEN CONVERT(VARCHAR,CAST(SC7X.C7_DATPRF AS DATETIME),103)
ELSE CONVERT(VARCHAR,CAST(SC7A.C7_DATPRF AS DATETIME),103)
END AS PRZ_ENT_FOR,
CASE
	WHEN YEAR(SUA.UA_ZDTAENT) = 1900
THEN ''
ELSE CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT AS DATETIME),103) 
END AS DT_ENT_CLI,
CAST(SUA.UA_ZPRZENT AS DECIMAL(3,0)) AS PRZ_ENT_CLI,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CASE
	WHEN 	
		SC7A.C7_DATPRF IS NULL
	AND SC7X.C7_DATPRF IS NULL
	AND SUA.UA_ZDTAENT >= SC7.C7_DATPRF 
THEN 'N'
	WHEN
		SC7X.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT >= SC7X.C7_DATPRF 	
THEN 'N'
	WHEN
		SUA.UA_ZDTAENT >= SC7A.C7_DATPRF 		
THEN 'N'
	WHEN 	
		SC7A.C7_DATPRF IS NULL
	AND SC7X.C7_DATPRF IS NULL
	AND SUA.UA_ZDTAENT < SC7.C7_DATPRF 
THEN 'S'
	WHEN
		SC7X.C7_DATPRF <> ''
	AND SUA.UA_ZDTAENT < SC7X.C7_DATPRF 	
THEN 'S'
	WHEN
	   SUA.UA_ZDTAENT < SC7A.C7_DATPRF 		
THEN 'S'
END AS ATRASADO



/*------------------RELACIONAMENTOS---------------------*/

/*ATENDIMENTO*/	FROM SUA010 SUA
/*PRODUTOS ATM*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ = ''  AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
/*CAD PROD*/   	LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ = ''  AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/    LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*CONTATO*/		LEFT JOIN SU5010 SU5  ON SU5.D_E_L_E_T_ = ''  AND SU5.U5_CODCONT = SUA.UA_CODCONT 
/*FORNECEDOR*/  LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/    LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*SL1 PAI*/	   	LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ = ''  AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
/*SL2 PAI*/	   	LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SL1.L1_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO 
/*SL2 FILHO*/	LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO
/*SC0 RES MANU*/LEFT JOIN SC0010 SC0  ON SC0.D_E_L_E_T_ = ''  AND SC0.C0_FILRES = SL2A.L2_FILIAL AND SUBSTRING(SC0.C0_OBS,8,6) = SL2A.L2_NUM AND SC0.C0_PRODUTO = SL2A.L2_PRODUTO 

/*--------------------PADRAO-----------------------*/

/*SC1 SC*/	    LEFT JOIN SC1010 SC1  ON SC1.D_E_L_E_T_ = ''  AND SC1.C1_FILENT = SL2A.L2_FILIAL AND SC1.C1_NUM = SL2A.L2_SOLCOM AND SC1.C1_ORCAM = SL2A.L2_NUM AND SC1.C1_PRODUTO = SL2A.L2_PRODUTO AND SC1.C1_ZITMORC = SL2A.L2_ITEM
/*SC7 PC*/		LEFT JOIN SC7010 SC7  ON SC7.D_E_L_E_T_ = ''  AND SC7.C7_FILIAL = SC1.C1_FILIAL AND SC7.C7_NUM = SC1.C1_PEDIDO AND SC7.C7_PRODUTO = SC1.C1_PRODUTO AND SC7.C7_NUMSC = SC1.C1_NUM AND SC7.C7_ITEMSC = SC1.C1_ITEM
/*SC6 PV*/		LEFT JOIN SC6010 SC6  ON SC6.D_E_L_E_T_ = ''  AND SC6.C6_FILIAL = SL2B.L2_FILIAL AND SC6.C6_NUM = SL2B.L2_PEDRES AND SC6.C6_PRODUTO = SL2B.L2_PRODUTO AND SC6.C6_ITEM = SL2B.L2_ITEM 
/*SC5 PV*/		LEFT JOIN SC5010 SC5  ON SC5.D_E_L_E_T_ = ''  AND SC5.C5_FILIAL = SC6.C6_FILIAL AND SC5.C5_NUM = SC6.C6_NUM
/*SD1 DOC.ENTR*/LEFT JOIN SD1010 SD1  ON SD1.D_E_L_E_T_ = ''  AND SD1.D1_FILIAL = SC7.C7_FILENT AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_COD = SC7.C7_PRODUTO AND SD1.D1_ITEMPC = SC7.C7_ITEM
/*SC9 LIBERA*/	LEFT JOIN SC9010 SC9  ON SC9.D_E_L_E_T_ = ''  AND SC9.C9_FILIAL = SC6.C6_FILIAL AND SC9.C9_PEDIDO = SC6.C6_NUM AND SC9.C9_ITEM = SC6.C6_ITEM AND SC9.C9_PRODUTO = SC6.C6_PRODUTO
/*SD2 DOC. SAI*/LEFT JOIN SD2010 SD2  ON SD2.D_E_L_E_T_ = ''  AND SD2.D2_SERIE = SC9.C9_SERIENF AND SD2.D2_DOC = SC9.C9_NFISCAL AND SD2.D2_COD = SC9.C9_PRODUTO AND SD2.D2_ITEMPV = SC9.C9_ITEM 

/*--------------------TROCA-----------------------*/

/*SC6 PV TROCA*/LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2B.L2_FILIAL AND SC6A.C6_NUM = SL2B.L2_PEDRES AND SC6A.C6_ITEM = SL2B.L2_ITEM AND SC6A.C6_PRODUTO <> SL2B.L2_PRODUTO 
/*SC1 TROCA*/ 	LEFT JOIN SC1010 SC1A ON SC1A.D_E_L_E_T_ = '' AND SC1A.C1_ZFILPV = SC6A.C6_FILIAL AND SC1A.C1_ZNUMPV = SC6A.C6_NUM AND SC1A.C1_PRODUTO = SC6A.C6_PRODUTO AND SC1A.C1_ZITMPV = SC6A.C6_ITEM
/*SC7 PC TROCA*/LEFT JOIN SC7010 SC7A ON SC7A.D_E_L_E_T_ = '' AND SC7A.C7_FILIAL = SC1A.C1_FILIAL AND SC7A.C7_NUM = SC1A.C1_PEDIDO AND SC7A.C7_PRODUTO = SC1A.C1_PRODUTO AND SC7A.C7_NUMSC = SC1A.C1_NUM AND SC7A.C7_ITEMSC = SC1A.C1_ITEM
/*SC5 PV TROCA*/LEFT JOIN SC5010 SC5A ON SC5A.D_E_L_E_T_ = '' AND SC5A.C5_FILIAL = SC6A.C6_FILIAL AND SC5A.C5_NUM = SC6A.C6_NUM
/*SD1 DOC.ENTR*/LEFT JOIN SD1010 SD1A ON SD1A.D_E_L_E_T_ = '' AND SD1A.D1_FILIAL = SC7A.C7_FILENT AND SD1A.D1_PEDIDO = SC7A.C7_NUM AND SD1A.D1_COD = SC7A.C7_PRODUTO AND SD1A.D1_ITEMPC = SC7A.C7_ITEM
/*SC9 LIBERA T*/LEFT JOIN SC9010 SC9A ON SC9A.D_E_L_E_T_ = '' AND SC9A.C9_FILIAL = SC6A.C6_FILIAL AND SC9A.C9_PEDIDO = SC6A.C6_NUM AND SC9A.C9_ITEM = SC6A.C6_ITEM AND SC9A.C9_PRODUTO = SC6A.C6_PRODUTO
/*SD2DOC.SAI.T*/LEFT JOIN SD2010 SD2A ON SD2A.D_E_L_E_T_ = '' AND SD2A.D2_SERIE = SC9A.C9_SERIENF AND SD2A.D2_DOC = SC9A.C9_NFISCAL AND SD2A.D2_COD = SC9A.C9_PRODUTO AND SD2A.D2_ITEMPV = SC9A.C9_ITEM 

/*--------------------MANUAL-----------------------*/

/*SC1 MANUAL*/ 	LEFT JOIN SC1010 SC1X ON SC1X.D_E_L_E_T_ = '' AND SC1X.C1_ZFILPV = SC6.C6_FILIAL AND SC1X.C1_ZNUMPV = SC6.C6_NUM AND SC1X.C1_PRODUTO = SC6.C6_PRODUTO AND SC1X.C1_ZITMPV = SC6.C6_ITEM
/*SC7 PC TROCA*/LEFT JOIN SC7010 SC7X ON SC7X.D_E_L_E_T_ = '' AND SC7X.C7_FILIAL = SC1X.C1_FILIAL AND SC7X.C7_NUM = SC1X.C1_PEDIDO AND SC7X.C7_PRODUTO = SC1X.C1_PRODUTO AND SC7X.C7_NUMSC = SC1X.C1_NUM AND SC7X.C7_ITEMSC = SC1X.C1_ITEM
/*SD1 DOC.ENTR*/LEFT JOIN SD1010 SD1X ON SD1X.D_E_L_E_T_ = '' AND SD1X.D1_FILIAL = SC7X.C7_FILENT AND SD1X.D1_PEDIDO = SC7X.C7_NUM AND SD1X.D1_COD = SC7X.C7_PRODUTO AND SD1X.D1_ITEMPC = SC7X.C7_ITEM

/*--------------------CONDIÇÕES----------------------*/

WHERE 1=1

AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_OPER   <> '3' 
AND YEAR(SUA.UA_EMISSAO) IN (2019, 2020)
AND SA3.A3_ZSITVND IN ('1','2')
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
--AND SUA.UA_NUMSL1 <> ''
--AND SUA.UA_FILIAL = '0103'
--AND SUA.UA_NUM = '007495'
--AND SB1.B1_COD = 'EP198I'
--AND SC6.C6_NUM = '009877'

/*---------------ORDER BY------------------*/

ORDER BY SUA.UA_FILIAL, SUA.UA_NUM

/*---------------------------------------------TABELA PRINCIPAL--------------------------------------------------------*/


CREATE TABLE ZCUBO
    (
	Z_NUM_ATM			VARCHAR(6),
	Z_FILIAL_ATM		VARCHAR(4),
	Z_DT_EMI_ATM		VARCHAR(30),
	Z_CODPROD			VARCHAR(15),
	Z_PROD_TROCADO		VARCHAR(15),
	Z_PROD_REAL			VARCHAR(15),
	Z_PRODUTO			VARCHAR(70),
	Z_PROD_DESC_REDU	VARCHAR(40),
	Z_COD_APRE			VARCHAR(18),
	Z_QTD				FLOAT,
	Z_UND				VARCHAR(2),
	Z_SLD_FIS			FLOAT,
	Z_SLD_RES			FLOAT,
	Z_SLD_DISP			FLOAT,
	Z_COD_CLI			VARCHAR(6),
	Z_NOME_CLI			VARCHAR(70),
	Z_NOME_CLI_REDU		VARCHAR(20),
	Z_CNPJ_CPF			VARCHAR(18),
	Z_IE				VARCHAR(18),
	Z_CONTRIBU			VARCHAR(1),
	Z_CIDADE_UF			VARCHAR(63),
	Z_COD_CONTAT		VARCHAR(6),
	Z_CONTATO			VARCHAR(15),
	Z_DDD				VARCHAR(3),
	Z_FONE				VARCHAR(15),
	Z_CELULAR			VARCHAR(15),	
	Z_COD_VEND			VARCHAR(6),
	Z_VENDEDOR			VARCHAR(40),
	Z_COD_FOR			VARCHAR(6),
	Z_FORNECEDOR		VARCHAR(40),
	Z_NOME_FOR_REDU		VARCHAR(20),
	Z_PRZ_FOR_DIAS		INT,
	Z_VLR_TOTAL_ATM		FLOAT,	
	Z_CSTREP_L2			FLOAT,
	Z_CUSTD_B1			FLOAT,
	Z_VLR_UNI_UB		FLOAT,
	Z_VLR_UNI_PV		FLOAT,
	Z_TIPO_VENDA		VARCHAR(15),	
	Z_OPER_ATM			VARCHAR(1),   
	Z_NUMSL1_ATM		VARCHAR(6),
	Z_STATUS_ATM		VARCHAR(3),
	Z_CANCEL_ATM		VARCHAR(1),
	Z_DT_LIB_FAT		VARCHAR(30),
	Z_DATA_FAT			VARCHAR(30),
	Z_SER700			VARCHAR(3),
	Z_DOC700			VARCHAR(9),
	Z_NUM_RES_MANU		VARCHAR(6),
	Z_FILIAL_PAI		VARCHAR(4),
	Z_NUM_ORC_PAI		VARCHAR(6),
	Z_SERIE_PAI			VARCHAR(3),
	Z_NOTA_PAI			VARCHAR(9),
	Z_EMI_PAI			VARCHAR(30),
	Z_FILIAL_FILHO		VARCHAR(4),
	Z_NUM_ORC_FILHO 	VARCHAR(6),
	Z_SERIE_FILHO		VARCHAR(3),
	Z_NOTA_FILHO		VARCHAR(9),
	Z_EMI_FILHO			VARCHAR(30),
	Z_FILIAL_SC			VARCHAR(4),
	Z_NUM_SC			VARCHAR(6),
	Z_QTD_SC			FLOAT,
	Z_EMI_SC			VARCHAR(30),
	Z_FILIAL_PC			VARCHAR(4),		
	Z_NUM_PC			VARCHAR(6),
	Z_QTD_PC			FLOAT,
	Z_EMI_PC			VARCHAR(30),
	Z_FILIAL_PV			VARCHAR(4),
	Z_NUM_PV			VARCHAR(6),
	Z_ITEM_PV			VARCHAR(2),
	Z_QTD_PV			FLOAT,
	Z_QTD_LIB			FLOAT,
	Z_BLEST_C9			VARCHAR(2),
	Z_BLQ_C6			VARCHAR(2),
	Z_EMI_PV			VARCHAR(30),
	Z_SERIE_SAIDA		VARCHAR(3),
	Z_NOTA_SAIDA		VARCHAR(9),
	Z_DT_NOTA_SAIDA		VARCHAR(30),
	Z_SERIE_ENTRADA		VARCHAR(3),
	Z_NOTA_ENTRADA    	VARCHAR(9),
	Z_DT_NOTA_ENTRADA	VARCHAR(30),
	Z_PRZ_ENT_FOR		VARCHAR(30),
	Z_DT_ENT_CLI      	VARCHAR(30),
	Z_PRZ_ENT_CLI		INT,
	Z_DT_HJ				VARCHAR(30),
	Z_ATRASADO			VARCHAR(1),
    R_E_C_N_O_ 			INT,
    ESTAGIO 			VARCHAR(1),
	SITUACAO			VARCHAR(100)
	)
	
	
INSERT INTO ZCUBO(
	Z_NUM_ATM			,
	Z_FILIAL_ATM		,
	Z_DT_EMI_ATM		,
	Z_CODPROD			,
	Z_PROD_TROCADO		,
	Z_PROD_REAL			,
	Z_PRODUTO			,
	Z_PROD_DESC_REDU	,
	Z_COD_APRE			,
	Z_QTD				,
	Z_UND				,
	Z_SLD_FIS			,
	Z_SLD_RES			,
	Z_SLD_DISP			,
	Z_COD_CLI			,
	Z_NOME_CLI			,
	Z_NOME_CLI_REDU		,
	Z_CNPJ_CPF			,
	Z_IE				,
	Z_CONTRIBU			,
	Z_CIDADE_UF			,
	Z_COD_CONTAT		,
	Z_CONTATO			,
	Z_DDD				,
	Z_FONE				,
	Z_CELULAR			 ,	
	Z_COD_VEND			,
	Z_VENDEDOR			,
	Z_COD_FOR			,
	Z_FORNECEDOR		,
	Z_NOME_FOR_REDU		,
	Z_PRZ_FOR_DIAS		,
	Z_VLR_TOTAL_ATM		 ,	
	Z_CSTREP_L2			,
	Z_CUSTD_B1			,
	Z_VLR_UNI_UB		,
	Z_VLR_UNI_PV		,
	Z_TIPO_VENDA	   ,
	Z_OPER_ATM			,
	Z_NUMSL1_ATM		,
	Z_STATUS_ATM		,
	Z_CANCEL_ATM		,
	Z_DT_LIB_FAT		,
	Z_DATA_FAT			,
	Z_SER700			,
	Z_DOC700			,
	Z_NUM_RES_MANU		,
	Z_FILIAL_PAI		,
	Z_NUM_ORC_PAI		,
	Z_SERIE_PAI			,
	Z_NOTA_PAI			,
	Z_EMI_PAI			,
	Z_FILIAL_FILHO		,
	Z_NUM_ORC_FILHO 	,
	Z_SERIE_FILHO		,
	Z_NOTA_FILHO		,
	Z_EMI_FILHO			,
	Z_FILIAL_SC		    ,
	Z_NUM_SC		    ,
	Z_QTD_SC			,	
	Z_EMI_SC		    ,
	Z_FILIAL_PC		   	,
	Z_NUM_PC		    ,
	Z_QTD_PC			,
	Z_EMI_PC		    ,
	Z_FILIAL_PV			,
	Z_NUM_PV			,
	Z_ITEM_PV			,
	Z_QTD_PV			,
	Z_QTD_LIB			,
	Z_BLEST_C9			,
	Z_BLQ_C6			,
	Z_EMI_PV			,
	Z_SERIE_SAIDA		,
	Z_NOTA_SAIDA		,
	Z_DT_NOTA_SAIDA		,
	Z_SERIE_ENTRADA		,
	Z_NOTA_ENTRADA    	,
	Z_DT_NOTA_ENTRADA	,
	Z_PRZ_ENT_FOR	    ,
	Z_DT_ENT_CLI        ,
	Z_PRZ_ENT_CLI	    ,
	Z_DT_HJ			    ,
	Z_ATRASADO			,
	R_E_C_N_O_			,
	ESTAGIO				,
	SITUACAO			
)

SELECT
*,
CASE 
	WHEN
		Z_OPER_ATM = '4'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL 
	AND Z_DOC700 IS NULL 	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL
	AND Z_DOC700 IS NULL	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM <> ''
	AND Z_SER700 = ''
	AND Z_DOC700 = ''	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '1'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '2'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '2'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA  IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA  = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN '3'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '4'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN '4'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '4'
   	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
  	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA =''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '5'
		WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''
	AND Z_SERIE_PAI <> ''
	AND Z_NOTA_PAI <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN '6'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
    AND Z_PROD_TROCADO IS NULL
THEN '6'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN '6'
ELSE ''
END AS ESTAGIO,
CASE 
	WHEN
		Z_OPER_ATM = '4'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL 
	AND Z_DOC700 IS NULL 	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM = ''
	AND Z_SER700 IS NULL
	AND Z_DOC700 IS NULL	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
		Z_OPER_ATM = '2'
	AND Z_NUMSL1_ATM <> ''
	AND Z_SER700 = ''
	AND Z_DOC700 = ''	
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'AGUARDANDO FINANCEIRO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = '' 
	AND Z_NOTA_SAIDA = ''  
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_BLEST_C9 = '02'
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRA PENDENTE (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRA PENDENTE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA  IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA  = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'S'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
	AND  CONVERT(DATE, Z_PRZ_ENT_FOR,103) <  CONVERT(DATE, Z_DT_HJ,103)
THEN 'COMPRADO COM ATRASO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA IS NULL 
	AND Z_NOTA_SAIDA IS NULL 
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRADO NO PRAZO (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> '' 
THEN 'COMPRADO NO PRAZO (PROD. TROCADO)'
	WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV IS NULL
	AND Z_ATRASADO = 'N'
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'COMPRADO NO PRAZO'
   	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
  	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA =''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA IS NULL
	AND Z_NOTA_ENTRADA IS NULL
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC IS NULL
	AND Z_NUM_PC IS NULL
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA = ''
	AND Z_NOTA_ENTRADA = ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO EM ESTOQUE'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA IS NULL
	AND Z_NOTA_SAIDA IS NULL
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
	WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_NUM_ORC_FILHO <> ''	
	AND Z_NUM_SC <> ''
	AND Z_NUM_PC <> ''
	AND Z_NUM_PV <> ''
	AND Z_SERIE_ENTRADA <> ''
	AND Z_NOTA_ENTRADA <> ''
	AND Z_SERIE_SAIDA = ''
	AND Z_NOTA_SAIDA = ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO EM ESTOQUE (PROD. TROCADO)'
		WHEN
	    Z_SER700 = ''
	AND Z_DOC700 = ''
	AND Z_SERIE_PAI <> ''
	AND Z_NOTA_PAI <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO IS NULL 
THEN 'PRODUTO FATURADO'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
    AND Z_PROD_TROCADO IS NULL
THEN 'PRODUTO FATURADO'
		WHEN
	    Z_SER700 <> ''
	AND Z_DOC700 <> ''
	AND Z_SERIE_PAI = ''
	AND Z_NOTA_PAI = ''
	AND Z_SERIE_SAIDA <> ''
	AND Z_NOTA_SAIDA <> ''
    AND Z_NUM_RES_MANU IS NULL
	AND Z_PROD_TROCADO <> ''
THEN 'PRODUTO FATURADO (PROD. TROCADO)'
ELSE ''
END AS SITUACAO
FROM AUXZCUBO
WHERE 1=1
AND Z_OPER_ATM <> '3'
AND Z_BLQ_C6 IS NULL OR Z_BLQ_C6 <> 'R'
--AND Z_NUM_ATM = '027146'
--AND Z_PROD_REAL = 'IC137F'


/*--------------------------------------------------------FIM------------------------------------------------------------*/
GO

