
/*
SELECT A.UA_FILIAL,A.UA_NUM,MIN(B.ESTAGIO) AS SITATM
FROM SUA010 AS A
LEFT JOIN ZCUBO AS B ON B.Z_FILIAL_ATM = A.UA_FILIAL AND B.Z_NUM_ATM = A.UA_NUM
WHERE 1=1 
AND A.D_E_L_E_T_ = ''
AND A.UA_FILIAL = '0101'
AND A.UA_NUM = '027819'
AND A.UA_NUMSL1 <> ''
AND A.UA_EMISSAO >= '20200101' 
GROUP BY A.UA_FILIAL,A.UA_NUM
*/


SELECT 
CONCAT(A.Z_FILIAL_ATM, ' - ', A.Z_NUM_ATM) AS CHAVE,
A.Z_FILIAL_ATM,
A.Z_NUM_ATM,
A.Z_DT_EMI_ATM,
A.Z_VLR_TOTAL_ATM,
A.Z_COD_VEND,
A.Z_VENDEDOR,
A.Z_COD_CLI,
A.Z_NOME_CLI,
A.Z_CIDADE_UF,
MIN(A.ESTAGIO) AS SITU_ATM
FROM ZCUBO A
LEFT JOIN SUA010 B ON B.D_E_L_E_T_ = '' AND B.UA_FILIAL = A.Z_FILIAL_ATM AND B.UA_NUM = A.Z_NUM_ATM
WHERE 1=1 
--AND A.Z_CIDADE_UF = 'RIBEIRAO PRETO/SP'
AND A.ESTAGIO <> '' 
--AND A.ESTAGIO = '5'
AND A.Z_NUM_ATM NOT IN (SELECT C.Z_NUM_ATM FROM ZCUBO C WHERE YEAR(CONVERT(DATE, C.Z_DT_EMI_ATM, 103)) = 2019 AND C.ESTAGIO = '1')
GROUP BY
A.Z_FILIAL_ATM,
A.Z_NUM_ATM,
A.Z_DT_EMI_ATM,
A.Z_COD_VEND,
A.Z_VENDEDOR,
A.Z_COD_CLI,
A.Z_NOME_CLI,
A.Z_CIDADE_UF,
A.Z_VLR_TOTAL_ATM

