

SELECT 
E.HANDLE,
E.NOME,
A.HANDLE,
A.EMPRESA,
A.FILIAL,
A.NUMERO,
C1.VALORNOMINAL,
D.HANDLE,
D.VALOR,
D.VALORESBAIXADOS,
(D.VALOR - D.VALORESBAIXADOS) AS SALDO,
C1.STATUS,
D.DATAVENCIMENTO,
D.DATALIQUIDACAO,
A.TIPOCONTRATO,
F.NOME
FROM CN_CONTRATOS A
LEFT JOIN K_CN_CONTRATOFECHAMENTOCONTRAT B ON B.CONTRATO = A.HANDLE
LEFT JOIN FN_DOCUMENTOS C ON C.HANDLE = B.DOCUMENTOGERADO
LEFT JOIN FN_DOCUMENTOS C1 ON C1.HANDLE = C.DOCUMENTOORIGEM
LEFT JOIN FN_PARCELAS D ON D.DOCUMENTO = C1.HANDLE
LEFT JOIN GN_PESSOAS E ON E.HANDLE = A.PESSOA 
LEFT JOIN CN_TIPOSCONTRATOS F ON F.HANDLE = A.TIPOCONTRATO
WHERE 1=1
/* SOMENTE RECEBER */		AND C1.EHCONTASPAGAR = 'N'
/* VENCIMENTO < -30 DIAS */	AND D.DATAVENCIMENTO <= DATEADD(day, -30, getdate())
/* SOMENTE DOC ABERTOS */  	AND (D.VALOR - D.VALORESBAIXADOS) > 0
/* SOMENTE DOC ABERTOS */  	AND D.EMABERTO = 'S'
/* SOMENTE PUBLICOS	*/		AND F.PREFIXO NOT IN ('PU','PUBL')
/* FILTRAR EMPRESA */		AND C1.EMPRESA = 1
--AND E.HANDLE = 6443
--AND A.NUMERO IN ('CO-00002873-CT') 

