
SELECT 
	A.EMPRESA							 AS COD_EMPRESA,
	F.NOME								 AS EMPRESA,
	A.DATAEMISSAO						 AS DT_EMISSAO,
	A.DOCUMENTODIGITADO 				 AS DOCUMENTO,
	B.HISTORICO		   					 AS DESCRICAO,
	B.VALOR								 AS VALOR_TOTAL,
	CONCAT(D.CODIGOREDUZIDO, ' - ', D.NOME) 	 AS PROEJTO,
	CONCAT(E.CODIGO, ' - ', E.NOME) AS CENTRO_CUSTO,
	C.VALOR								 AS VALOR,
	C.PERCENTUAL						 AS PORCENTAGEM
FROM FN_DOCUMENTOS A
	LEFT JOIN FN_LANCAMENTOS B ON B.DOCUMENTO = A.HANDLE
	LEFT JOIN FN_LANCAMENTOCC C ON C.LANCAMENTO = B.HANDLE
	LEFT JOIN GN_PROJETOS D ON D.HANDLE = C.PROJETO
	LEFT JOIN CT_CC E ON E.HANDLE = C.CENTROCUSTO
	LEFT JOIN EMPRESAS F ON F.HANDLE = A.EMPRESA
WHERE 1=1
	AND B.TIPO = 1
	AND A.DATAEMISSAO = '20230202'
	AND A.DOCUMENTODIGITADO = 'FOL_3'
ORDER BY C.VALOR DESC
