

SELECT 
A.EMPRESA 					AS COD_EMPRESA,
B.NOME						AS EMPRESA,
A.BANCO 					AS COD_BANCO,
C.NOME 						AS BANCO,
A.NOMECARTEIRA 				AS CARTEIRA,
A.IDENTIFICACAOEMPRESABANCO AS CONVENIO,
A.TIPOCOBRANCABENNER		AS TIPO_CROB,
D.NOME						AS COBRANCA

FROM GN_BANCOHBCARTEIRAS A
JOIN EMPRESAS B ON B.HANDLE = A.EMPRESA
JOIN GN_BANCOS C ON C.HANDLE = A.BANCO
JOIN FN_TIPOSCOBRANCAS D ON D.HANDLE = A.TIPOCOBRANCABENNER
WHERE 1=1
AND A.BANCO = 104
ORDER BY 3