

SELECT 
    C.NOME,
    A.NOME,
    A.INATIVO
FROM GN_HBENTIDADESERVICO A
    LEFT JOIN GN_HBENTIDADES B ON B.HANDLE = A.ENTIDADE
    LEFT JOIN GN_BANCOS C ON C.HANDLE = B.ENTIDADE
WHERE 1=1
    AND A.INATIVO = 'N'

