

SELECT * FROM GN_HBARQUIVOESTRUTURAS WHERE HANDLE IN (113,764,846)
EXPRESSAO LIKE '%24%' 

SELECT * FROM GN_HBESTRUTURACAMPOS WHERE ARQUIVO IN (113,
764,
846) AND ORDEM = '012'

SELECT * FROM FN_FORMASPAGAMENTO

SELECT TOP 1000 * FROM FN_PARCELAS

/*

GN_HBARQUIVOESTRUTURAS = 24

GN_HBESTRUTURACAMPOS = 43

'IF(FORMALIQUIDACAO|FORMALANCAMENTO = ''34'',IF(BANCO|CODIGO<>''341'',''GERAR'',''NAOGERAR''),''NAOGERAR'')'

*/