
SELECT 
D.CONTA,
E.NOME,
A.EMPRESA			AS EMPRESA,
B.DOCUMENTODIGITADO	AS DOCUMENTO,
A.PARCELADIGITADA	AS PARCELA,
C.DATA				AS DATA_BAIXA,
C.VALOR				AS VALOR_BAIXADO,
A.VALOR				AS VALOR_PARCELA
FROM FN_PARCELAS A
LEFT JOIN FN_DOCUMENTOS B ON B.HANDLE = A.DOCUMENTO
LEFT JOIN FN_MOVIMENTACOES C ON C.PARCELA = A.HANDLE
LEFT JOIN FN_LANCAMENTOS D ON D.PARCELA = A.HANDLE
LEFT JOIN TS_LANCAMENTOS L ON L.HANDLE = D.LANCAMENTOTESOURARIA
LEFT JOIN FN_CONTAS E ON E.HANDLE = D.CONTA
WHERE 1=1
--AND A.EMPRESA = 2
AND C.DATA >= CONVERT(DATE, '2023-09-29')
AND C.DATA <= CONVERT(DATE,DATEADD(DAY,- 1,GETDATE()))
AND C.OPERACAO IS NOT NULL
AND D.LANCAMENTOTESOURARIA IS NOT NULL
AND L.CONCILIADO = 'S'
AND B.STATUS IN (1,2)
AND D.CONTA NOT IN (
225,
231,
122,
224,
124,
233,
40,
243
)

