/*---------------------SELECT------------------------*/

SELECT 
B.B1_COD AS COD_PROD, 
A.B5_COMPR AS COMPRIMENTO_TOTVS, 
A.B5_LARG AS LARGURA_TOTVS,
A.B5_ESPESS AS ESPESSURA_TOTVS,
B.B1_PESBRU AS PESO_BRUTO_TOTVS,
B.B1_ZCUBAGE AS CUBAGEM_TOTVS,
C.DM_ALTURA AS ALTURA_PLAN,
C.DM_LARGURA AS LARGURA_PLAN,
C.DM_PROFUNDIDADE AS PROFUNDIDADE_PLAN,
C.DM_PESO AS PESO_PLAN
FROM SB5010 A, SB1010 B , MKT_DIMENSOES C
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.B5_COD = B.B1_COD
AND A.B5_COD = C.DM_CODPROD

/*-------------------------SELECT SEPARADO---------------------------------*/

SELECT COUNT(*) AS COUNT_SB5 FROM SB5010 WHERE D_E_L_E_T_ = ''

SELECT COUNT(*) AS COUNT_SB1 FROM SB1010 WHERE D_E_L_E_T_ = '' 

SELECT COUNT(*) AS COUNT_MKT FROM MKT_DIMENSOES

/*---------------------------SB1 + SB5----------------------------------------------*/

SELECT COUNT(*) AS COUNT_SB1_SB5
FROM SB1010 A ,SB5010 B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.B1_COD = B.B5_COD


/*---------------------------SB1 + MKTDIMESSOES----------------------------------------------*/

SELECT COUNT(*) AS COUNT_SB1_MKT
FROM SB1010 A ,MKT_DIMENSOES B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND A.B1_COD = B.DM_CODPROD


/*---------------------------SB5 + MKTDIMESSOES----------------------------------------------*/


SELECT * 
FROM SB5010 A ,MKT_DIMENSOES B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND A.B5_COD = B.DM_CODPROD


/*---------------------------SB1 + SB5 + MKTDIMESSOES----------------------------------------------*/


SELECT COUNT(*) AS COUNT_SB1_SB5_MKT
FROM SB1010 A ,SB5010 B ,MKT_DIMENSOES C
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.B1_COD = B.B5_COD
AND A.B1_COD = C.DM_CODPROD

/*---------------------QUERRY PARA O EXCEL-------------------------*/


SELECT
RTRIM(DM_CODPROD) AS COD_PROD,
DM_PRODUTO AS PRODUTO,
DM_CODAPRE AS COD_APRE,
DM_CODFOR AS COD_FOR,
DM_FORNECEDOR AS FORNECEDOR,
DM_ALTURA AS ALTURA,
DM_LARGURA AS LARGURA,
DM_PROFUNDIDADE AS PROFUNDIDADE,
DM_PESO AS PESO
FROM MKT_DIMENSOES




SELECT * FROM SB5010 WHERE D_E_L_E_T_ = '' AND B5_COD = 'LB012F'


SELECT * FROM SB1010 WHERE D_E_L_E_T_ = ''


SELECT * FROM MKT_DIMENSOES


