/*---------------UPDATE SB5 - NKT (6 PRODUTOS)--------------------*/

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EP251I'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EP251I'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EP251I'),0)	 
WHERE B5_COD = 'EP251I';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EQ091V'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EQ091V'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'EQ091V'),0)	 
WHERE B5_COD = 'EQ091V';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC274F'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC274F'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC274F'),0)	 
WHERE B5_COD = 'IC274F';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC462P'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC462P'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'IC462P'),0)	 
WHERE B5_COD = 'IC462P';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB012F'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB012F'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB012F'),0)	 
WHERE B5_COD = 'LB012F';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB016F'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB016F'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'LB016F'),0)	 
WHERE B5_COD = 'LB016F';

UPDATE SB5010
SET B5_COMPR = ISNULL((SELECT DM_PROFUNDIDADE  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'UT001F'),0),
B5_LARG = ISNULL((SELECT DM_LARGURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'UT001F'),0),
B5_ESPESS = ISNULL((SELECT DM_ALTURA  FROM MKT_DIMENSOES WHERE DM_CODPROD = 'UT001F'),0)	 
WHERE B5_COD = 'UT001F';


/*------------------------------INSERT SB5----------------------------------*/

DECLARE @RECNO INT
DECLARE @N	   INT
DECLARE @COUNT INT 

SET @RECNO = ISNULL((SELECT MAX(R_E_C_N_O_) + 1 FROM SB5010),0)
SET @N = 	 ISNULL((SELECT COUNT(*) FROM MKT_DIMENSOES),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN


--INSERT INTO SB5010 (B5_FILIAL, B5_COD, B5_CEME, B5_COMPR, B5_LARG, B5_ESPESS , R_E_C_N_O_)

SELECT '0101', DM_CODPROD, DM_PRODUTO, DM_PROFUNDIDADE, DM_LARGURA, DM_ALTURA, @RECNO
FROM MKT_DIMENSOES A
WHERE 1=1
AND A.DM_CODPROD NOT IN ('EP251I','EQ091V','IC274F','IC462P','LB012F','LB016F','UT001F')
AND A.R_E_C_N_O_ = @COUNT

SET @RECNO = @RECNO + 1
SET @COUNT = @COUNT + 1

END;

SELECT * FROM MKT_DIMENSOES

/*------------------------------UPDATE SB1----------------------------------*/

DECLARE @N	   INT
DECLARE @COUNT INT 
DECLARE @PROD VARCHAR(15)


SET @N = 	 ISNULL((SELECT COUNT(*) FROM MKT_DIMENSOES),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD = ISNULL((SELECT DM_CODPROD FROM MKT_DIMENSOES WHERE R_E_C_N_O_ = @COUNT),0)

UPDATE SB1010
SET B1_PESBRU = ISNULL((SELECT DM_PESO FROM MKT_DIMENSOES WHERE DM_CODPROD = @PROD),0),
B1_ZCUBAGE = ISNULL((SELECT DM_CUBAGEM FROM MKT_DIMENSOES WHERE DM_CODPROD = @PROD),0) 	 
WHERE 
B1_COD = @PROD

SET @COUNT = @COUNT + 1

END;

/*------------------------------UPDATE SB5 (DESC PROD)----------------------------------*/


DECLARE @N	   INT
DECLARE @COUNT INT 
DECLARE @PROD VARCHAR(15)
DECLARE @DESC VARCHAR(70)


SET @N = 	 ISNULL((SELECT COUNT(*) FROM SB1010),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD = ISNULL((SELECT B1_COD FROM SB1010 WHERE R_E_C_N_O_ = @COUNT),0)

SET @DESC = ISNULL((SELECT B1_DESC FROM SB1010 WHERE R_E_C_N_O_ = @COUNT),0)


UPDATE SB5010
SET B5_CEME = @DESC
WHERE  
B5_COD = @PROD

SET @COUNT = @COUNT + 1

END;


/*------------------------------SELECT TESTE----------------------------------*/

SELECT * FROM #TMP

SELECT * FROM ARQMKT01

SELECT * FROM MKT_DIMENSOES

SELECT * FROM SB5010

SELECT * FROM SB1010


SELECT A.B5_COD, B.DM_CODPROD  FROM SB5010 A, MKT_DIMENSOES B
WHERE A.D_E_L_E_T_ = ''
AND A.B5_COD = B.DM_CODPROD


SELECT A.B1_COD, B.DM_CODPROD  FROM SB1010 A, MKT_DIMENSOES B
WHERE A.D_E_L_E_T_ = ''
AND A.B1_COD =  B.DM_CODPROD


SELECT  B5_COD, B5_CEME, B5_COMPR, B5_LARG, B5_ESPESS  FROM SB5010 WHERE B5_COD = 'EQ040E'

SELECT B1_COD, B1_PESBRU, B1_ZCUBAGE FROM SB1010 WHERE B1_COD = 'EQ040E'


SELECT * FROM MKT_DIMENSOES


SELECT B5_COD, B5_CEME,  B5_LARG, B5_COMPR, B5_ESPESS  FROM SB5010

SELECT * FROM SA5010


/*-------------------------------------------------------------------------------------*/

