
DECLARE @CEME VARCHAR(200)
DECLARE @DESC VARCHAR(75)
DECLARE @REC_SB5 INT
DECLARE @CONTADOR INT
DECLARE @CODPROD_SB5 VARCHAR(15)
DECLARE @CODPROD_SB1 VARCHAR(15)

SET @REC_SB5 = ISNULL((SELECT COUNT(R_E_C_N_O_) FROM SB5010),0)
SET @CONTADOR = 1

WHILE @CONTADOR <= @REC_SB5
BEGIN

SET @CEME = ISNULL((SELECT B5_CEME FROM SB5010 WHERE R_E_C_N_O_ = @CONTADOR),'')  

IF @CEME = ''
BEGIN

SET @CODPROD_SB5 = ISNULL((SELECT DISTINCT B5_COD FROM SB5010 WHERE R_E_C_N_O_ = @CONTADOR),0)
SET @DESC = ISNULL((SELECT DISTINCT B1_DESC FROM SB1010 WHERE B1_COD = @CODPROD_SB5),0)

--SELECT @CODPROD_SB5 AS COD_SB5, @CEME AS DESC_SB5, @CODPROD_SB1 AS COD_SB1, @DESC AS DESC_SB1


UPDATE SB5010
SET B5_CEME = @DESC
WHERE  
B5_COD = @CODPROD_SB1

END;

SET @CONTADOR = @CONTADOR + 1

END;



SELECT * FROM SB5010


SELECT DISTINCT B1_COD FROM SB1010







SELECT
A.B5_COD,
A.B5_CEME,
B.B1_COD,
B.B1_DESC,
B.R_E_C_N_O_
FROM SB5010 A, SB1010 B 
WHERE 
A.B5_CEME = ''
AND A.B5_COD = B.B1_COD







