/*------------------------------UPDATE SB1----------------------------------*/

DECLARE @N	   INT
DECLARE @COUNT INT 
DECLARE @PROD VARCHAR(15)


SET @N = 	 ISNULL((SELECT COUNT(*) FROM MKT_DIMENSOES),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD = ISNULL((SELECT DM_CODPROD FROM MKT_DIMENSOES WHERE R_E_C_N_O_ = @COUNT),0)

UPDATE SB1010
SET B1_PESBRU = ISNULL((SELECT DM_PESO FROM MKT_DIMENSOES WHERE DM_CODPROD = @PROD),0),
B1_ZCUBAGE = ISNULL((SELECT DM_CUBAGEM FROM MKT_DIMENSOES WHERE DM_CODPROD = @PROD),0) 	 
WHERE 
B1_COD = @PROD

SET @COUNT = @COUNT + 1

END;

/*------------------------------UPDATE SB5----------------------------------*/


DECLARE @N	   INT
DECLARE @COUNT INT 
DECLARE @PROD VARCHAR(15)
DECLARE @DESC VARCHAR(70)


SET @N = 	 ISNULL((SELECT COUNT(*) FROM SB1010),0)
SET @COUNT = 1

WHILE @COUNT <= @N
BEGIN

SET @PROD = ISNULL((SELECT B1_COD FROM SB1010 WHERE R_E_C_N_O_ = @COUNT),0)

SET @DESC = ISNULL((SELECT B1_DESC FROM SB1010 WHERE R_E_C_N_O_ = @COUNT),0)


UPDATE SB5010
SET B5_CEME = @DESC
WHERE  
B5_COD = @PROD

SET @COUNT = @COUNT + 1

END;


/*------------------------------SELECT TESTE----------------------------------*/


SELECT * FROM MKT_DIMENSOES



SELECT B1_COD, B1_DESC, B1_PESBRU, B1_ZCUBAGE FROM SB1010


SELECT B5_COD, B5_CEME, B5_COMPR, B5_LARG, B5_ESPESS FROM SB5010


/*-------------------------------------------------------------------------------------*/

