

SELECT 
*,

CASE
	WHEN
		Z1_DATA_FAT = ''
	AND Z1_NUM_RES_MANU IS NULL    
	AND Z1_PROD_TROCADO IS NULL	
THEN 'ESTAGIO 0'
	WHEN
		Z1_DOC700 <> ''
	AND Z1_SER700 <> ''
	AND Z1_NUM_RES_MANU IS NULL
	AND Z1_NUM_ORC_PAI <> ''
	AND Z1_NUM_ORC_FILHO <> ''
	AND Z1_NUM_SC IS NULL
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 1'

	WHEN
		Z1_DOC700 = ''
	AND Z1_SER700 = ''
	AND Z1_NUM_RES_MANU <> ''
	AND Z1_NUM_ORC_PAI <> ''
	AND Z1_NUM_ORC_FILHO IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 2'


	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 3'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 3'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR > Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 4'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL	
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR > Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 4'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR <= Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 5'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL	
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR <= Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 5'
	WHEN 
		Z1_NUM_SC IS NULL
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 6'
 	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA <> ''
	AND Z1_NOTA_ENTRADA <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 6'
 	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL
	AND Z1_SERIE_ENTRADA <> ''
	AND Z1_NOTA_ENTRADA <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 6'
	WHEN 
		Z1_SERIE_C6 <> ''
	AND Z1_NOTA_C6  <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 7'
	WHEN 
		Z1_DOC700 = ''
	AND Z1_SER700 = ''
	AND	Z1_SERIE_PAI  <> ''
	AND Z1_NOTA_PAI <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'ESTAGIO 7'
	WHEN 
	Z1_PROD_TROCADO IS NOT NULL
THEN 'ESTAGIO 8'
ELSE ''
END AS ESTAGIO,

CASE
	WHEN
		Z1_DATA_FAT = ''
	AND Z1_NUM_RES_MANU IS NULL 
	AND Z1_PROD_TROCADO IS NULL
THEN 'FATURAMENTO ABERTO'
	WHEN
		Z1_DOC700 <> ''
	AND Z1_SER700 <> ''
	AND Z1_NUM_RES_MANU IS NULL
	AND Z1_NUM_ORC_PAI <> ''
	AND Z1_NUM_ORC_FILHO <> ''
	AND Z1_NUM_SC IS NULL
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'PARADO NO V.D. S/ RESERVA'
	WHEN
		Z1_DOC700 = ''
	AND Z1_SER700 = ''
	AND Z1_NUM_RES_MANU <> ''
	AND Z1_NUM_ORC_PAI <> ''
	AND Z1_NUM_ORC_FILHO IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'RESERVA MANUAL'

	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA PENDENTE C/PV'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC IS NULL
	AND Z1_NUM_PV IS NULL
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA PENDENTE S/PV'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR > Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA COM ATRASO C/PV'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL	
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR > Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA COM ATRASO S/PV'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR <= Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA DENTRO DO PRAZO C/PV'
	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL	
	AND Z1_SERIE_ENTRADA IS NULL
	AND Z1_NOTA_ENTRADA IS NULL
	AND Z1_PRZ_ENT_FOR <= Z1_DT_ENT_CLI
	AND Z1_PROD_TROCADO IS NULL
THEN 'COMPRA DENTRO DO PRAZO S/PV'
	WHEN 
		Z1_NUM_SC IS NULL
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'NO ESTOQUE'
 	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV <> ''
	AND Z1_SERIE_C6 = ''
	AND Z1_NOTA_C6 = ''
	AND Z1_SERIE_ENTRADA <> ''
	AND Z1_NOTA_ENTRADA <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'NO ESTOQUE JÁ COMPRADO C/PV'
 	WHEN 
		Z1_NUM_SC <> ''
	AND Z1_NUM_PC <> ''
	AND Z1_NUM_PV IS NULL
	AND Z1_SERIE_ENTRADA <> ''
	AND Z1_NOTA_ENTRADA <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'NO ESTOQUE JÁ COMPRADO S/PV'
	WHEN 
		Z1_SERIE_C6 <> ''
	AND Z1_NOTA_C6  <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'FATURADO - NO PEDIDO DE VENDA'
	WHEN 
		Z1_DOC700 = ''
	AND Z1_SER700 = ''
	AND	Z1_SERIE_PAI  <> ''
	AND Z1_NOTA_PAI <> ''
	AND Z1_PROD_TROCADO IS NULL
THEN 'FATURADO - VENDA DIRETA'
	WHEN 
	Z1_PROD_TROCADO IS NOT NULL
THEN 'TROCA DE PRODUTO'
ELSE ''
END AS SITUACAO
FROM Z1CUBOFAT
WHERE 1=1
AND Z1_NUM_SC <> ''
AND Z1_NUM_PC IS NULL
AND Z1_NOTA_C6 = ''
