
DECLARE @CODARQ1 		VARCHAR(20)
DECLARE @CODARQ2 		VARCHAR(20)
DECLARE @CODPROD 		VARCHAR(20)
DECLARE @PRODUTO 		VARCHAR(70)
DECLARE @FORNECEDOR 	VARCHAR(40)
DECLARE @ALTURA 		FLOAT
DECLARE @LARGURA 		FLOAT
DECLARE @PROFUNDIDADE 	FLOAT
DECLARE @PESO 			FLOAT
DECLARE @INI     		INT
DECLARE @FIM     		INT
DECLARE @RECA    		INT
DECLARE @RECB    		INT

SET @INI = 1
SET @FIM = 6104
SET @RECA = ISNULL((SELECT TOP 1 R_E_C_N_O_ FROM ARQMKT01),0)
SET @RECB = ISNULL((SELECT TOP 1 R_E_C_N_O_ FROM ARQMKT02),0)


WHILE @INI <= @FIM
BEGIN

SET @CODPROD = 			ISNULL((SELECT SA5_PRODUTO FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @PRODUTO = 			ISNULL((SELECT SA5_NOMPROD FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @CODARQ1 = 			ISNULL((SELECT PEM_CODAPRE FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @CODARQ2 = 			ISNULL((SELECT SA5_CODPRF  FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @FORNECEDOR = 		ISNULL((SELECT PEM_FOENECEDOR FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @ALTURA = 			ISNULL((SELECT PEM_ALTURA FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @LARGURA = 			ISNULL((SELECT PEM_LARGURA FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @PROFUNDIDADE =     ISNULL((SELECT PEM_PROFUNDIDADE FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @PESO = 			ISNULL((SELECT PEM_PESO FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)

INSERT INTO #AUX (AUX_CODPROD, AUX_PRODUTO, AUX_APREPLAN, AUX_APRETOTV, AUX_FORNECEDOR, AUX_ALTURA, AUX_LARGURA, AUX_PROFUNDIDADE, AUX_PESO, AUX_RECNOPLAN, AUX_RECNOTOTV) 

SELECT 
@CODPROD 		AS COD_PROD,
@PRODUTO 		AS PRODUTO,
@CODARQ1 		AS COD_APRE_PLANILHA, 
@CODARQ1 		AS COD_APRE_TOTVS,
@FORNECEDOR 	AS FORNECEDOR, 
@ALTURA  		AS ALTURA, 
@LARGURA 		AS LARGURA,
@PROFUNDIDADE   AS PROFUNDIDADE,
@PESO			AS  PESO,
@RECA 			AS RECNO_PLANILHA,
@RECB 			AS RECNO_TOTVS


SET @RECA = @RECA + 1
SET @RECB = @RECB + 1
SET @INI = @INI + 1

END;






