
CREATE TABLE MKT_DIMENSOES
    (
     DM_CODPROD VARCHAR(15),
   	 DM_PRODUTO VARCHAR(70),
	 DM_CODAPRE VARCHAR(40),
	 DM_CODFOR VARCHAR(6),
	 DM_FORNECEDOR VARCHAR(40),
	 DM_ALTURA FLOAT,
	 DM_LARGURA FLOAT,
	 DM_PROFUNDIDADE FLOAT,
	 DM_CUBAGEM FLOAT,
	 DM_PESO FLOAT,
	)


INSERT INTO MKT_DIMENSOES (DM_CODPROD, DM_PRODUTO, DM_CODAPRE, DM_CODFOR, DM_FORNECEDOR, DM_ALTURA, DM_LARGURA, DM_PROFUNDIDADE, DM_PESO) 

SELECT 
RTRIM(C.B1_COD) AS CODPROD,
C.B1_DESC AS PRODUTO,
A.PEM_CODAPRE AS COD_APRE,
B.SA5_FORNECE AS COD_FOR,
B.SA5_NOMEFOR AS FORNECEDOR,
A.PEM_ALTURA AS ALTURA,
A.PEM_LARGURA AS LARGURA,
A.PEM_PROFUNDIDADE AS PROFUNDIDADE,
A.PEM_PESO AS PESO
FROM ARQMKT01 A, ARQMKT02 B, SB1010 AS C 
WHERE 1=1 
--AND A.PEM_CODAPRE LIKE '_' + B.SA5_CODPRF  + '%' 
AND A.PEM_CODAPRE = B.SA5_CODPRF
AND A.PEM_CODAPRE = C.B1_ZAPRES1
AND B.SA5_PRODUTO = C.B1_COD
AND C.B1_MSBLQL = '2'
AND SUBSTRING(C.B1_GRUPO,1,2) = 'MR'
AND C.D_E_L_E_T_ = ''



SELECT * FROM MKT_DIMENSOES



DELETE FROM MKT_DIMENSOES
