/*-----------------------CREAT TABLE----------------------------*/


CREATE TABLE ARQMKT01
    (
     PEM_CODAPRE VARCHAR(40),
     PEM_ALTURA FLOAT,
     PEM_LARGURA FLOAT,
     PEM_PROFUNDIDADE FLOAT,
     PEM_PESO FLOAT,     
     PEM_FOENECEDOR VARCHAR(40),
     R_E_C_N_O_ INT IDENTITY(1,1),
	)
	
	
CREATE TABLE ARQMKT02
    (
     SA5_PRODUTO VARCHAR(15),
     SA5_NOMPROD VARCHAR(70),
     SA5_FORNECE VARCHAR(6),
     SA5_LOJA 	 VARCHAR(2),
     SA5_NOMEFOR VARCHAR(40),
     SA5_CODPRF  VARCHAR(20) ,
     R_E_C_N_O_ INT IDENTITY(1,1),   
	)
	
	
CREATE TABLE #TMP
    (
     SA5_PRODUTO VARCHAR(15),
     SA5_ALTURA  FLOAT,
     SA5_LERGURA  FLOAT,
     SA5_PROFUNDIDADE  FLOAT,
     SA5_CUBAGEM FLOAT,
     SA5_PESO  FLOAT   
	)
	

	
		
	BULK 
INSERT #TMP
        FROM 'C:\TEMP\TESTE.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO
	
/*--------------------------INSERT-------------------------*/	
   
	
	BULK 
INSERT ARQMKT01
        FROM 'C:\TEMP\PesosMedidasFornecedores_SQL.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO


	BULK 
INSERT ARQMKT02
        FROM 'C:\TEMP\SA5.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO


/*------------------------DROP TABLE--------------------------*/

DROP TABLE ARQMKT01

DROP TABLE ARQMKT02

/*-----------------------SELECT TABLE-----------------------------*/


DECLARE @CODARQ1 		VARCHAR(20)
DECLARE @CODARQ2 		VARCHAR(20)
DECLARE @CODPROD 		VARCHAR(20)
DECLARE @PRODUTO 		VARCHAR(70)
DECLARE @FORNECEDOR 	VARCHAR(40)
DECLARE @ALTURA 		FLOAT
DECLARE @LARGURA 		FLOAT
DECLARE @PROFUNDIDADE 	FLOAT
DECLARE @PESO 			FLOAT
DECLARE @INI     		INT
DECLARE @FIM     		INT
DECLARE @RECA    		INT
DECLARE @RECB    		INT

SET @INI = 1
SET @FIM = 6104
SET @RECA = ISNULL((SELECT TOP 1 R_E_C_N_O_ FROM ARQMKT01),0)
SET @RECB = ISNULL((SELECT TOP 1 R_E_C_N_O_ FROM ARQMKT02),0)


WHILE @INI <= @FIM
BEGIN

SET @CODARQ1 = 			ISNULL((SELECT PEM_CODAPRE FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @CODARQ2 = 			ISNULL((SELECT SA5_CODPRF  FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @CODPROD = 			ISNULL((SELECT SA5_PRODUTO FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @PRODUTO = 			ISNULL((SELECT SA5_NOMPROD FROM ARQMKT02 WHERE R_E_C_N_O_ = @RECB  ),0)
SET @FORNECEDOR = 		ISNULL((SELECT PEM_FOENECEDOR FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @ALTURA = 			ISNULL((SELECT PEM_ALTURA FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @LARGURA = 			ISNULL((SELECT PEM_LARGURA FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @PROFUNDIDADE =     ISNULL((SELECT PEM_PROFUNDIDADE FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)
SET @PESO = 			ISNULL((SELECT PEM_PESO FROM ARQMKT01 WHERE R_E_C_N_O_ = @RECA  ),0)


INSERT INTO #AUX (AUX_CODPROD, AUX_PRODUTO, AUX_APREPLAN, AUX_APRETOTV, AUX_CODAPREPLAN, AUX_ALTURA, AUX_LARGURA, AUX_PROFUNDIDADE, AUX_PESO, AUX_RECNOPLAN, AUX_RECNOTOTV) 


SELECT 
@CODPROD 		AS COD_PROD,
@PRODUTO 		AS PRODUTO,
@CODARQ1 		AS COD_APRE_PLANILHA, 
@CODARQ1 		AS COD_APRE_TOTVS, 
@ALTURA  		AS ALTURA, 
@LARGURA 		AS LARGURA,
@PROFUNDIDADE   AS PROFUNDIDADE,
@PESO			AS  PESO,
@RECA 			AS RECNO_PLANILHA,
@RECB 			AS RECNO_TOTVS


SET @RECA = @RECA + 1
SET @RECB = @RECB + 1
SET @INI = @INI + 1

END;




SELECT TOP 1 
SQL.COD_APRE_PLANI, 
SQL.COD_APRE_SA5,
SQL.RECA,
SQL.RECB
FROM
(SELECT 
B.SA5_PRODUTO AS COD_PROD,
B.SA5_NOMPROD AS PRODUTO,
A.PEM_ALTURA AS ALTURA,
A.PEM_LARGURA AS LARGURA,
A.PEM_PROFUNDIDADE AS PROFUNDIDADE,
A.PEM_PESO AS PESO,
B.SA5_FORNECE AS COD_FOR,
A.PEM_FOENECEDOR AS NOME_FOR,
A.PEM_CODAPRE AS COD_APRE_PLANI,
B.SA5_CODPRF AS COD_APRE_SA5,
A.R_E_C_N_O_ AS RECA,
B.R_E_C_N_O_ AS RECB
FROM ARQMKT01 A, ARQMKT02 B 
WHERE A.R_E_C_N_O_ = @RECA
AND B.R_E_C_N_O_ = @RECB
) AS SQL



SELECT * FROM ARQMKT01

SELECT * FROM ARQMKT02















