
SELECT 
RTRIM(C.B1_COD) AS CODPROD,
C.B1_DESC AS PRODUTO,
A.PEM_CODAPRE AS COD_APRE,
B.SA5_FORNECE AS COD_FOR,
B.SA5_NOMEFOR AS FORNECEDOR,
A.PEM_ALTURA AS ALTURA,
A.PEM_LARGURA AS LARGURA,
A.PEM_PROFUNDIDADE AS PROFUNDIDADE,
A.PEM_PESO AS PESO
FROM ARQMKT01 A, ARQMKT02 B, SB1010 AS C 
WHERE 1=1 
--AND A.PEM_CODAPRE LIKE '_' + B.SA5_CODPRF  + '%' 
AND A.PEM_CODAPRE = B.SA5_CODPRF
AND A.PEM_CODAPRE = C.B1_ZAPRES1
AND B.SA5_PRODUTO = C.B1_COD
AND C.B1_MSBLQL = '2'
AND SUBSTRING(C.B1_GRUPO ,1,2) = 'MR'
AND C.D_E_L_E_T_ = ''




SELECT * FROM ARQMKT02



SELECT 
RTRIM(DM_CODPROD) AS CODPROD, 
DM_PRODUTO AS PRODUTO,
DM_CODAPRE AS COD_APRE,
DM_CODFOR AS COD_FOR,
DM_FORNECEDOR AS FORNECEDOR,
DM_ALTURA AS ALTURA,
DM_LARGURA AS LARGURA,
DM_PROFUNDIDADE AS PROFUNDIDADE,
DM_PESO AS PESO
FROM MKT_DIMENSOES