

DECLARE @ANOINI INT;
DECLARE @ANOFIM INT;
DECLARE @MESINI INT;
DECLARE @MESFIM INT;
DECLARE @SALDO VARCHAR(15);
DECLARE @CUSTO VARCHAR(15);
SET @ANOINI = 2018
SET @ANOFIM = 2018
SET @MESINI = 01
SET @MESFIM = 12

--SELECT CAST(@ANOINI as varchar(4)) as ANO 
--SELECT CAST(@MESINI as varchar(2)) as MES
--SELECT CONCAT( 'SALDO_', @ANOINI, '_0', @MESINI) AS SALDO 
--SELECT CONCAT( 'CUSTO_', @ANOINI, '_0', @MESINI) AS CUSTO
--SET @ANOINI = 	ISNULL(( SELECT CAST(@ANOINI as varchar(4)) as ANO   ),0)
--SET @MESINI =	ISNULL(( SELECT CAST(@MESINI as varchar(2)) as MES   ),0) 




	SET @SALDO =	ISNULL(( SELECT CONCAT( 'SALDO_', @ANOINI, '_0', @MESINI) AS SALDO  ),0) 
	SET @CUSTO = 	ISNULL(( SELECT CONCAT( 'CUSTO_', @ANOINI, '_0', @MESINI) AS CUSTO  ),0)
   
	--SELECT @ANOINI, @MESINI, @SALDO, @CUSTO
	
	INSERT INTO #DINAMICO (CODPROD, PRODUTO, SALDO_2018_02, CUSTO_2018_02) 
	SELECT A.CODPROD, A.PRODUTO, A.SALDO_FINAL, A.CUSTO_FINAL FROM #AUX A





WHILE @ANOINI <= @ANOFIM
BEGIN


   WHILE @MESINI <= @MESFIM
   BEGIN
     
   SET @MESINI = @MESINI + 1;
   END;
   
   SET @ANOINI = @ANOINI + 1;
   END;




CREATE TABLE #DINAMICO
    (
     CODPROD VARCHAR(15),
   	 PRODUTO VARCHAR(70),
     SALDO_2018_01 FLOAT,
     CUSTO_2018_01 FLOAT,
     SALDO_2018_02 FLOAT,
     CUSTO_2018_02 FLOAT,
     SALDO_2018_03 FLOAT,
     CUSTO_2018_03 FLOAT
	)


SELECT * FROM #DINAMICO


DROP TABLE #DINAMICO


SELECT * FROM #AUX

