
DEFINE @FILIAL_OLD  VARCHAR(4)
DEFINE @SC_OLD 		VARCHAR(6)
DEFINE @FILIAL_NEW  VARCHAR(4)
DEFINE @SC_NEW 		VARCHAR(6)
DEFINE @PROD   		VARCHAR(15)	

DECLARE @FILIAL_OLD VARCHAR(4)
DECLARE @SC_OLD 	VARCHAR(6)
DECLARE @FILIAL_NEW VARCHAR(4)
DECLARE @SC_NEW     VARCHAR(6)
DECLARE @PROD   	VARCHAR(15)	

SET @FILIAL_OLD  = $(@FILIAL_OLD)
SET @SC_OLD 	 = $(@SC_OLD)
SET @FILIAL_NEW  = $(@FILIAL_NEW)
SET @SC_NEW 	 = $(@SC_NEW)
SET @PROD 	  	 = $(@PROD)


/*-------------------DELETE DO NOVO (SC1)---------------------*/
/*
UPDATE SC1010
SET
D_E_L_E_T_ = '*'
WHERE 1=1
AND C1_FILIAL  = @FILIAL_NEW
AND C1_NUM     = @SC_NEW
AND C1_PRODUTO = @PROD
*/

/*-------------------UPDATE DO ANTIGO (SC1)---------------------*/

UPDATE SC1010
SET 
C1_FILIAL  = @FILIAL_NEW,
C1_NUM 	   = @SC_NEW,
C1_ORCAM   = ISNULL((SELECT C1_ORCAM   FROM SC1010 WHERE D_E_L_E_T_ = '*' AND C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0),
C1_PEDRES  = ISNULL((SELECT C1_PEDRES  FROM SC1010 WHERE D_E_L_E_T_ = '*' AND C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0),
C1_ZITNORC = ISNULL((SELECT C1_ZITNORC FROM SC1010 WHERE D_E_L_E_T_ = '*' AND C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0)
WHERE 1=1
AND C1_FILIAL  = @FILIAL_OLD
AND C1_NUM     = @SC_OLD
AND C1_PRODUTO = @PROD

/*-------------------UPDATE DO SC7---------------------*/

UPDATE SC7010
SET 
C7_NUMSC  = @SC_NEW,
C7_ITEMSC = ISNULL((SELECT C1_ITEM FROM SC1010 WHERE D_E_L_E_T_ = '*' AND C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0)
WHERE 1=1
AND C7_FILIAL  = @FILIAL_OLD
AND C7_NUMSC   = @SC_OLD 
AND C7_PRODUTO = @PROD

/*-----------------------------------------------*/

/*

SELECT
@FILIAL_OLD AS FILIAL_OLD,
@SC_OLD		AS SC_OLD,
@FILIAL_NEW	AS FILIAL_NEW,
@SC_NEW		AS SC_NEW,
@PROD		AS CODPROD,
ISNULL((SELECT C1_ORCAM   FROM SC1010 WHERE C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0) AS ORCAM,
ISNULL((SELECT C1_PEDRES  FROM SC1010 WHERE C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0) AS PEDRES,
ISNULL((SELECT C1_ZITNORC FROM SC1010 WHERE C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0) AS ITEML2,
ISNULL((SELECT C1_ITEM 	  FROM SC1010 WHERE C1_FILIAL = @FILIAL_NEW AND C1_NUM = @SC_NEW AND C1_PRODUTO = @PROD),0) AS ITEMC1

*/
