

SELECT  
SB1.B1_ZDESRDZ		AS DESC_REDU,
SB1.B1_ZAPRES1		AS COD_APRE,
SB5.B5_ALTURA		AS ALTURA,
SB5.B5_LARG			AS LARGURA,
SB5.B5_COMPR		AS COMPRIMENTO,
SC2.C2_QUANT		AS QTD,
SB5.B5_COMPR * SB5.B5_LARG	AS M2_PAINEL,
SC2.C2_QUANT * (SB5.B5_COMPR * SB5.B5_LARG)	AS TOTAL_M2,
SA1.A1_NOME			AS CLIENTE,
SA3.A3_NOME			AS VENDEDOR,
SA3.A3_NREDUZ		AS VEND_REDU,
SC2.*,
SD3.D3_EMISSAO		AS DT_FINALIZ,
CASE
	WHEN SC2.C2_QUANT = SC2.C2_QUJE
THEN 'S'
ELSE 'N'
END AS FINALIZADO
FROM SC2010 SC2
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SC2.C2_PRODUTO 
LEFT JOIN SB5010 SB5 ON SB5.D_E_L_E_T_ = '' AND SB5.B5_COD = SB1.B1_COD
LEFT JOIN SUA010 SUA ON SUA.D_E_L_E_T_ = '' AND SUA.UA_FILIAL = SC2.C2_FILIAL AND SUA.UA_NUM = SC2.C2_NUM
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SD3010 SD3 ON SD3.D_E_L_E_T_ = '' AND SD3.D3_OP = CONCAT(SC2.C2_NUM,SC2.C2_ITEM,SC2.C2_SEQUEN) AND SD3.D3_COD = SC2.C2_PRODUTO
WHERE 1=1
AND SC2.D_E_L_E_T_ = '' 
AND SB1.B1_ZDESRDZ  LIKE 'ISOPAINEL%'
AND SC2.C2_QUANT <> SC2.C2_QUJE



