


SELECT 
B.L2_FILIAL,
B.L2_NUM,
B.L2_PRODUTO,
A.C1_FILIAL,
A.C1_NUM,
A.C1_PRODUTO,
B.L2_ITEM,
A.C1_ZITNORC 
--UPDATE SC1010 SET C1_ZITNORC = L2_ITEM
FROM SC1010 A, SL2010 B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.C1_FILENT = B.L2_FILIAL
AND A.C1_NUM = B.L2_SOLCOM
AND A.C1_PRODUTO = B.L2_PRODUTO
--AND B.L2_ORCRES <> ''


