

SELECT
    A.CEP AS CEP,
    A.LOGRADOURO AS LOGRADOURO,
    A.BAIRRO AS BAIRRO,
    D.NOME AS CIDADE,
    B.SIGLA AS SIGLA_ESTADO,
    B.NOME AS ESTADO,
    C.SIGLA AS SIGLA_PAIS,
    C.NOME AS PAIS
FROM TA_LOGRADOUROS A
    LEFT JOIN TA_ESTADOS B ON B.HANDLE = A.ESTADO
    LEFT JOIN TA_PAISES C ON C.HANDLE = A.PAIS
    LEFT JOIN TA_MUNICIPIOS D ON D.HANDLE = A.MUNICIPIO
WHERE 1=1

