
/* PIVOT TRANSFORMA LINHAS EM COLUNAS SOMANDO OU CONTANTO ALGO */

SELECT * FROM 
(
	SELECT
		C.NOME 				AS TIPO_CONTRATO,
		MONTH(A.DATAINICIO) AS DATA,
		COUNT(B.CODIGO) 	AS QTD_BEN
		--SUM(B.VALOR)		AS VALOR
	FROM CN_CONTRATOS A
		/* BENEFICIARIO DOS CONTRATOS */ LEFT JOIN K_CN_CONTRATOBENEFICIARIOS AS B ON B.CONTRATO = A.HANDLE
		/* TIPO DOS CONTRATOS */ LEFT JOIN CN_TIPOSCONTRATOS AS C ON C.HANDLE = A.TIPOCONTRATO
	WHERE 1=1
		AND B.HANDLE IS NOT NULL
		AND C.HANDLE IS NOT NULL
		--AND C.NOME = 'FUNCIONARIO'
		AND YEAR(A.DATAINICIO) = 2022
	GROUP BY
		C.NOME,
		A.DATAINICIO
) AS Q1
PIVOT (SUM(QTD_BEN) FOR DATA IN ( [1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12] )) MES
--PIVOT (SUM(VALOR) FOR DATA IN ( [1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12] )) MES
ORDER BY 1

