
SELECT 'IMPORTACAO CONTRATOS' AS IMPORTACAO_CONTRATOS

SELECT * FROM K_CN_CONTRATOIMPORTACAO WHERE STATUS = 2

SELECT 'REQUICISOES' AS REQUISICOES

SELECT * FROM Z_BTLREQUISICOES WHERE  STATUS = 2

SELECT 'PROCESSOS AS PROCESSOS'

SELECT * FROM Z_PROCESSOS WHERE SITUACAO = 1

