


/* ----------- DETALHADO ----------- */

/*


SELECT 
   	F.NOMEFANTASIA AS EMPRESA,
   	D.NUMERO AS NUMERO,
	E.NOME AS CLIENTE,
	CASE
		WHEN E.TIPO = 1 THEN 'PF'
		WHEN E.TIPO = 2 THEN 'PJ'
	ELSE '' END AS TIPO,
	B.DATAVENCIMENTO AS DT_VENCIMENTO,
	B.VALOR,
	B.VALORESBAIXADOS,
	CASE 
		WHEN CONVERT(DATE, B.DATAVENCIMENTO) < CONVERT(DATE, GETDATE()) THEN (B.VALOR - B.VALORESBAIXADOS)
    ELSE 0 END AS SALDO,
	CASE 
		WHEN (B.VALOR - B.VALORESBAIXADOS) > 0 AND CONVERT(DATE, B.DATAVENCIMENTO) < CONVERT(DATE, GETDATE()) THEN 1
	ELSE 0
	END AS QTD_PARC
FROM FN_DOCUMENTOS A
LEFT JOIN FN_PARCELAS B ON B.DOCUMENTO = A.DOCUMENTOORIGEM
LEFT JOIN K_CN_CONTRATOFECHAMENTOCONTRAT C ON C.HANDLE = A.K_CONTRATOFECHAMENTOCONTRATO
LEFT JOIN CN_CONTRATOS D ON D.HANDLE = C.CONTRATO
LEFT JOIN GN_PESSOAS E ON E.HANDLE = A.PESSOA
LEFT JOIN EMPRESAS F ON F.HANDLE = A.EMPRESA
WHERE 1=1
AND A.STATUS <> 3
--AND D.NUMERO = 'CO-00021957-CT'
--AND D.NUMERO = 'EF-00009685-CT'
AND D.NUMERO = 'AP-00003980-CT'


 */
 
/* ------------- TOTAIS ------------ */


SELECT 
	Q1.EMPRESA AS EMPRESA,
	Q1.NUMERO AS NUMERO,
	Q1.COD_CLI AS COD_CLI,
	Q1.CLIENTE AS CLIENTE,
	Q1.TIPO AS TIPO,
	SUM(Q1.SALDO) AS SALDO,
	SUM(QTD_PARC) AS QTD_PARC
FROM 
(
SELECT 
   	F.NOMEFANTASIA AS EMPRESA,
   	D.NUMERO AS NUMERO,
   	E.CODIGO AS COD_CLI,
	E.NOME AS CLIENTE,
	CASE
		WHEN E.TIPO = 1 THEN 'PF'
		WHEN E.TIPO = 2 THEN 'PJ'
	ELSE '' END AS TIPO,
	B.DATAVENCIMENTO AS DT_VENCIMENTO,
	B.VALOR,
	B.VALORESBAIXADOS,
	CASE 
		WHEN CONVERT(DATE, B.DATAVENCIMENTO) < CONVERT(DATE, GETDATE()) THEN (B.VALOR - B.VALORESBAIXADOS)
    ELSE 0 END AS SALDO,	
	CASE 
		WHEN (B.VALOR - B.VALORESBAIXADOS) > 0 AND CONVERT(DATE, B.DATAVENCIMENTO) < CONVERT(DATE, GETDATE()) THEN 1
	ELSE 0
	END AS QTD_PARC
FROM FN_DOCUMENTOS A
LEFT JOIN FN_PARCELAS B ON B.DOCUMENTO = A.DOCUMENTOORIGEM
LEFT JOIN K_CN_CONTRATOFECHAMENTOCONTRAT C ON C.HANDLE = A.K_CONTRATOFECHAMENTOCONTRATO
LEFT JOIN CN_CONTRATOS D ON D.HANDLE = C.CONTRATO
LEFT JOIN GN_PESSOAS E ON E.HANDLE = A.PESSOA
LEFT JOIN EMPRESAS F ON F.HANDLE = A.EMPRESA
WHERE 1=1
AND A.STATUS <> 3
AND D.NUMERO = 'EF-00038557-CT'
) AS Q1
WHERE 1=1
AND Q1.NUMERO IS NOT NULL
GROUP BY
	Q1.EMPRESA,
	Q1.NUMERO,
	Q1.COD_CLI,
	Q1.CLIENTE,
	Q1.TIPO
	
	





