DECLARE @MATRICULA	INT
DECLARE @MATRICULA2	INT

SET @MATRICULA = $(@MATRICULA)
SET @MATRICULA2 = $(@MATRICULA2)

SELECT @MATRICULA, @MATRICULA2

SELECT MATRICULA, * FROM DO_FUNCIONARIOS WHERE 1=1 AND MATRICULA IN (@MATRICULA, @MATRICULA2)