

SELECT 
CASE
	WHEN ESTAGIO = '1' AND CONVERT(DATE, CONCAT(SUBSTRING(Z_DT_LIB_FAT,7,4),SUBSTRING(Z_DT_LIB_FAT,4,2),SUBSTRING(Z_DT_LIB_FAT,1,2)), 103) BETWEEN DATEADD(DAY, -15, GETDATE()) AND GETDATE()
THEN 'S'
ELSE 'N'
END AS ATE_QUINZE_DIAS,
CONVERT(DATE, CONCAT(SUBSTRING(Z_DT_LIB_FAT,7,4),SUBSTRING(Z_DT_LIB_FAT,4,2),SUBSTRING(Z_DT_LIB_FAT,1,2)), 103) AS DATA,
Z_DT_LIB_FAT,
*
FROM ZCUBOIND
WHERE 1=1
AND ESTAGIO = '1'
