
DEFINE @V 		 	VARCHAR(4)
DEFINE @PREFIXO  	VARCHAR(3)
DEFINE @NUM 	 	VARCHAR(9)
DEFINE @TIPO 	 	VARCHAR(3)
DEFINE @CV	 	 	VARCHAR(19)
DEFINE @DE_PARCELA	VARCHAR(19)
DEFINE @ATE_PARCELA	VARCHAR(19)

DECLARE @V 		 	 VARCHAR(4)
DECLARE @PREFIXO 	 VARCHAR(3)
DECLARE @NUM 	 	 VARCHAR(9)
DECLARE @TIPO 	 	 VARCHAR(3)
DECLARE @CV 	 	 VARCHAR(19)
DECLARE @DE_PARCELA	 VARCHAR(19)
DECLARE @ATE_PARCELA VARCHAR(19)


SET @V = $(@V)
SET @PREFIXO = $(@PREFIXO)
SET @NUM = $(@NUM)
SET @TIPO = $(@TIPO)
SET @CV = $(@CV)
SET @DE_PARCELA = $(@DE_PARCELA)
SET @ATE_PARCELA = $(@ATE_PARCELA)


UPDATE SE1010
SET E1_NUMCART = @CV
WHERE E1_FILIAL = @V
AND E1_PREFIXO = @PREFIXO
AND E1_NUM = @NUM
AND E1_TIPO = @TIPO
AND E1_PARCELA BETWEEN @DE_PARCELA AND @ATE_PARCELA

SELECT 
E1_FILIAL, 
E1_PREFIXO, 
E1_NUM,
E1_PARCELA,
E1_TIPO,
E1_NATUREZ,
E1_CLIENTE,
E1_NOMCLI,
E1_NUMCART,
R_E_C_N_O_
FROM SE1010 
WHERE 1=1
AND D_E_L_E_T_ = ''
AND E1_FILIAL = @V
AND E1_PREFIXO = @PREFIXO 
AND E1_NUM = @NUM
AND E1_TIPO = @TIPO
AND E1_PARCELA BETWEEN @DE_PARCELA AND @ATE_PARCELA



--SELECT E1_NUMCART, * FROM SE1010 WHERE E1_PREFIXO = '001' AND E1_NUM = '000029783' AND E1_TIPO = 'CC'



--SELECT @V AS FILIAL, @PREFIXO AS PREFIXO, @NUM AS TITULO, @TIPO AS TIPO, @CV AS CV
