

/*
-- Baixa Contas a Receber por Importação de Dados - Cartão de Crédito 053-SICREDI

-- DROP TABLE ARQTMP

CodFil;SerDoc;NumDoc;NumPar;Vencto;VlrReal;VlrTit;VlrJur;VlrLiq

*/

CREATE TABLE ARQTMP
( 
 cCodFil   	VARCHAR(04) NOT NULL,
 cSerDoc   	VARCHAR(03) NOT NULL,
 cNumDoc	VARCHAR(09) NOT NULL,
 cNumPar	VARCHAR(03) NOT NULL,
 cVencto    VARCHAR(08) NOT NULL,
 nVlrReal	DECIMAL(12,2),
 nVlrTit 	DECIMAL(12,2),
 nVlrJur    DECIMAL(12,2),
 nVlrLiq	DECIMAL(12,2)
 )
GO

SELECT * 
--UPDATE ARQTMP SET cNumDoc = '000001296'
FROM ARQTMP WHERE cCodFil = '0102' AND cSerDoc = '700' AND cNumDoc = '000001296'

-- Importa Registro do Arquivo .CSV para Tabela Temporária

BULK 
INSERT ARQTMP
        FROM 'C:\TEMP\ARQTMP.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO

SELECT A.cCodFil,A.cSerDoc,A.cNumDoc,A.cNumPar,A.cVencto,A.nVlrReal,A.nVlrTit,A.nVlrJur,A.nVlrLiq,B.E1_FILIAL,B.E1_PREFIXO,B.E1_NUM,B.E1_PARCELA,B.D_E_L_E_T_  
SELECT A.cCodFil,A.cSerDoc,A.cNumDoc,A.cNumPar,A.cVencto,A.nVlrReal,A.nVlrTit,A.nVlrJur,A.nVlrLiq,B.E1_FILIAL,B.E1_PREFIXO,B.E1_NUM,B.E1_PARCELA,B.D_E_L_E_T_,
B.E1_BAIXA,B.E1_MOVIMEN,B.E1_VALOR,B.E1_SALDO,E1_VALOR,E1_DECRESC,B.E1_VALLIQ,B.E1_VALJUR,B.E1_PORCJUR,B.E1_STATUS,B.E1_HIST 
--UPDATE ARQTMP SET cSerDoc = '700'
--UPDATE SE1010	SET E1_BAIXA = '20190528', E1_MOVIMEN = '20190528',E1_VALOR = A.nVlrTit,E1_SALDO = 0,E1_VALLIQ = A.nVlrLiq,E1_VALJUR = 0, E1_PORCJUR = 0,E1_STATUS = 'B',E1_HIST = 'BX.AUTOM.02/03/2020 ANTECIP 28/05/2019',E1_DECRESC = nVlrJur     
FROM ARQTMP AS A 
LEFT JOIN SE1010 AS B ON B.D_E_L_E_T_ = '' AND A.cCodFil = B.E1_FILIAL AND A.cSerDoc = B.E1_PREFIXO AND A.cNumDoc = B.E1_NUM AND A.cNumPar = B.E1_PARCELA
WHERE 1=1
AND B.D_E_L_E_T_ = ''
AND B.E1_TIPO = 'CC'
ORDER BY A.cCodFil,A.cSerDoc,A.cNumDoc,A.cNumPar


--AND A.cSerDoc = '100'


SELECT E1_DECRESC, * FROM SE1010 WHERE D_E_L_E_T_ = '' AND E1_FILIAL = '0103' AND E1_PREFIXO = 'RP' AND E1_NUM = '000000535' AND E1_PARCELA IN ('01','02')














SELECT A.E1_FILIAL,A.E1_PREFIXO,A.E1_NUM,A.E1_PARCELA,A.E1_TIPO,A.E1_CLIENTE,A.E1_LOJA,A.E1_NOMCLI,
CONVERT(VARCHAR,CAST(A.E1_EMISSAO AS DATETIME),103) AS EMISSAO,CONVERT(VARCHAR,CAST(A.E1_VENCREA AS DATETIME),103) AS VENCTO,
CONVERT(VARCHAR,CAST(A.E1_BAIXA AS DATETIME),103) AS BAIXA,A.E1_VALOR,A.E1_SALDO,A.E1_SITUACA,A.E1_STATUS,A.E1_VLCRUZ,A.E1_VLRREAL,
ISNULL((SELECT SUM(E1_VALOR) FROM SE1010 WHERE D_E_L_E_T_ = '' AND E1_FILIAL = A.E1_FILIAL AND E1_PREFIXO = A.E1_PREFIXO AND E1_NUM = A.E1_NUM),0) AS TOTTIT  
FROM SE1010 AS A
WHERE A.D_E_L_E_T_ = '' 
AND A.E1_TIPO = 'NCC' 
