/*
Acerto de Comissões de Vendas (SE3) X Contas a Receber (SE1)
*/
/*
https://docs.microsoft.com/pt-br/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017

////////////////////////////// Visualização / Acerto SE3  \\\\\\\\\\\\\\\\\\\\\\\\\
*/
-- CAST(9.5 AS DECIMAL(6, 4)) AS [decimal]


SELECT
A.E1_FILIAL,
A.E1_PREFIXO,
B.E3_EMISSAO,
A.E1_NUM,
A.E1_PARCELA,
A.E1_TIPO,
A.E1_VALOR,
B.E3_BASE,
B.E3_VEND,
C.A3_NOME,
A.E1_CLIENTE,
D.A1_NOME
--UPDATE SE3010 SET E3_BASE = A.E1_VALOR
FROM SE1010 AS A
LEFT JOIN SE3010 AS B ON B.D_E_L_E_T_ = '' AND B.E3_FILIAL = A.E1_FILIAL AND B.E3_SERIE = A.E1_PREFIXO AND B.E3_NUM = A.E1_NUM AND B.E3_PARCELA = A.E1_PARCELA AND B.E3_TIPO = A.E1_TIPO AND B.E3_CODCLI = A.E1_CLIENTE AND B.E3_LOJA = A.E1_LOJA 
LEFT JOIN SA3010 AS C ON C.D_E_L_E_T_ = '' AND C.A3_COD = B.E3_VEND
LEFT JOIN SA1010 AS D ON D.D_E_L_E_T_ = '' AND D.A1_COD = A.E1_CLIENTE
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND A.E1_EMISSAO BETWEEN CONCAT(SUBSTRING(CONVERT(VARCHAR, CAST(EOMONTH(GETDATE(), -1 ) AS DATETIME),112),1,6),'01') AND CONCAT(SUBSTRING(CONVERT(VARCHAR, CAST(EOMONTH( GETDATE()) AS DATETIME),112),1,6),'31') 
AND A.E1_VALOR <> B.E3_BASE
--AND B.E3_NUM = '000002319'


