  
SELECT
SB1.B1_COD		AS CODPROD,
SB1.B1_DESC		AS PRODUTO,
SB1.B1_UM		AS UM,
SA2.A2_COD		AS COD_FOR,
SA2.A2_NOME		AS FORNECEDOR,
SBM.BM_GRUPO	AS COD_GRUPO,
SBM.BM_DESC		AS GRUPO,
ZB1.ZB1_CODLIN	AS COD_LINHA,
ZB1.ZB1_DESLIN	AS LINHA,
ZB2.ZB2_CODFAM	AS COD_FAM,
ZB2.ZB2_DESFAM	AS FAMILIA,
SB5.B5_ALTURA	AS ALTURA,
SB5.B5_LARG		AS LARGURA,
SB5.B5_COMPR	AS COMPRIMENTO,
CASE
	WHEN SB1.B1_MSBLQL = '1'
THEN 'BLOQUEADO'
	WHEN SB1.B1_MSBLQL = '2'
THEN 'DESBLOQUEADO'
ELSE ''
END AS STATUS
FROM SB1010 SB1
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SB1.B1_PROC AND SA2.A2_LOJA = SB1.B1_LOJPROC
LEFT JOIN SBM010 SBM ON SBM.D_E_L_E_T_ = '' AND SBM.BM_GRUPO = SB1.B1_GRUPO
LEFT JOIN ZB1010 ZB1 ON ZB1.D_E_L_E_T_ = '' AND ZB1.ZB1_CODLIN = SB1.B1_ZCODLIN
LEFT JOIN ZB2010 ZB2 ON ZB2.D_E_L_E_T_ = '' AND ZB2.ZB2_CODFAM = SB1.B1_ZCODFAM
LEFT JOIN SB5010 SB5 ON SB5.D_E_L_E_T_ = '' AND SB5.B5_COD = SB1.B1_COD 
WHERE 1=1
AND SB1.D_E_L_E_T_ = ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) IN ('MR','CF', 'MP')
