
SELECT 
SE2.E2_FILIAL		AS FILIAL,
SE2.E2_PREFIXO		AS PREFIXO,
SE2.E2_NUM			AS TITULO,
SE2.E2_TIPO			AS TIPO,
SE2.E2_PARCELA		AS PARCELA,
SEV.EV_NATUREZ 		AS NATUREZA,
SED.ED_DESCRIC		AS DESC_NATUREZA,
SEV.EV_VALOR		AS VALOR,
SE2.E2_SALDO		AS SALDO,
SE2.E2_FORNECE		AS COD_FOR,
SA2.A2_NOME			AS FORNECEDOR,
SE2.E2_EMISSAO		AS EMISSAO,
SE2.E2_VENCREA		AS VENCIMENTO,
SE2.E2_ZMESBSE		AS MES_BASE,
SE2.E2_ZANOBSE		AS ANO_BASE,
CASE
	WHEN SE2.E2_SALDO = 0
THEN 'FECHADO'
ELSE 'ABERTO'
END AS STATUS
FROM SE2010 SE2
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SE2.E2_FORNECE AND SA2.A2_LOJA = SE2.E2_LOJA
LEFT JOIN SEV010 SEV ON SEV.D_E_L_E_T_ = '' AND SEV.EV_FILIAL = SE2.E2_FILIAL AND SEV.EV_PREFIXO = SE2.E2_PREFIXO AND SEV.EV_NUM = SE2.E2_NUM AND SEV.EV_PARCELA = SE2.E2_PARCELA AND SEV.EV_TIPO = SE2.E2_TIPO AND SE2.E2_FORNECE = SEV.EV_CLIFOR  
LEFT JOIN SED010 SED ON SED.D_E_L_E_T_ = '' AND SED.ED_CODIGO = SEV.EV_NATUREZ
WHERE 1=1
AND SE2.D_E_L_E_T_ = '' 
AND SE2.E2_EMISSAO BETWEEN '20200101' AND '20210131'
AND SE2.E2_MULTNAT = '1'
AND SE2.E2_NUM = '000013332'








/*
SELECT * FROM SEV010 WHERE D_E_L_E_T_ = '' AND EV_NUM = '000013332'

*/
