
SELECT 
A.PRODUTO,
A.ORDEMCOMPRA,
A.*
FROM CP_ORDENSCOMPRAITENS A
LEFT JOIN CP_ORDENSCOMPRA B ON B.HANDLE = A.ORDEMCOMPRA
WHERE 1=1
AND B.NUMERO = '28260'


SELECT RECEBIMENTOFISICOPAI, * FROM CP_RECEBIMENTOFISICO WHERE ORDEMCOMPRAITEM IN (75305,75306,75307)


SELECT * FROM CP_RECEBIMENTOFISICOPAI WHERE HANDLE = 60820


