
SELECT 
--(SELECT TOP 1 NOME		FROM FILIAIS		WHERE HANDLE 1=1 IN (@CAMPO(FILIAL))		) AS FILIAL	,
--(SELECT TOP 1 NOME		FROM CN_TIPOSCONTRATOS		WHERE HANDLE IN (@CAMPO(TIPOCONTRATO))) AS TIPOCONTRATO_FILTRO
	CONVERT(DATE, '2023-05-01')  AS INICIAL
	,CONVERT(DATE, '2023-05-31') AS FINAL
	,CASE 
		WHEN E.DATAVENCIMENTO IS NULL
			THEN E1.DATAVENCIMENTO
		ELSE E.DATAVENCIMENTO
		END DATAVENCIMENTO
	,CASE 
		WHEN E.HANDLE IS NULL
			THEN E1.HANDLE
		ELSE E.HANDLE
		END HANDLEPARCELA
	,CASE 
		WHEN A.K_NUMEROCONTRATO IS NOT NULL
			THEN A.K_NUMEROCONTRATO
		ELSE I.NUMERO
		END AS NUMEROCONTRATO
	,CASE 
		WHEN A.K_BENEFICIARIO IS NOT NULL
			THEN A.K_BENEFICIARIO
		ELSE H.NOME
		END AS BENEFICIARIO
	,CASE 
		WHEN A.K_FICHA IS NOT NULL
			THEN A.K_FICHA
		ELSE I.K_FICHA
		END AS FICHA
	,CASE 
		WHEN CONVERT(VARCHAR(10), A.K_DTBASE, 103) IS NOT NULL
			THEN CONVERT(VARCHAR(10), A.K_DTBASE, 103)
		ELSE CONVERT(VARCHAR(10), F.DATABASECOMISSAO, 103)
		END AS DATABASECOMISSAO
	,CASE 
		WHEN CONVERT(VARCHAR(10), A.K_DTINCLUSAOPROD, 103) IS NOT NULL
			THEN CONVERT(VARCHAR(10), A.K_DTINCLUSAOPROD, 103)
		ELSE CONVERT(VARCHAR(10), G.DATAINCLUIU, 103)
		END AS DATAINCLUIU
	,CASE 
		WHEN CONVERT(VARCHAR(10), A.K_DTVIGOR, 103) IS NOT NULL
			THEN CONVERT(VARCHAR(10), A.K_DTVIGOR, 103)
		ELSE CONVERT(VARCHAR(10), H.DATAVIGOR, 103)
		END AS DATAVIGOR
	,CASE 
		WHEN A.K_PARCELA IS NOT NULL
			THEN A.K_PARCELA
		ELSE F.PARCELA
		END AS PARCELA
	,CASE 
		WHEN J.NOME IS NOT NULL
			THEN CONCAT (J.CODIGO,'  ',J.NOME)
		ELSE CONCAT (A.K_PRODUTOID,'  ',A.K_PRODUTODESCRICAO)
		END AS PRODUTODESCRICAO
	,CASE 
		WHEN L.NOME IS NOT NULL
			THEN L.NOME
		ELSE A.K_TIPOCONTRATO
		END AS TIPOCONTRATO
	,C.LOGOTIPO
	,A.BASECALCULO
	,B.CODIGO
	,B.NOME AS AGENTEVENDAS
	,A.TIPOMOVIMENTO
	,A.DOCUMENTO
	,CONVERT(VARCHAR(10), A.DATA, 103) AS DATA
	,CASE 
		WHEN A.TIPOMOVIMENTO = 1
			THEN 'NÃO'
		WHEN A.TIPOMOVIMENTO = 3
			THEN 'SIM'
		WHEN(
SELECT MAX(A.TIPOMOVIMENTO)
	FROM FN_DOCUMENTOCOMISSOES A
				WHERE A.DOCUMENTO = A.DOCUMENTO
					AND A.PARCELA = E.HANDLE
					AND A.AGENTEVENDAS = B.HANDLE
			) = 1 THEN 'NÃO'
		WHEN(
SELECT MAX(A.TIPOMOVIMENTO)
	FROM FN_DOCUMENTOCOMISSOES A
				WHERE A.DOCUMENTO = A.DOCUMENTO
					AND A.PARCELA = E.HANDLE
					AND A.AGENTEVENDAS = B.HANDLE
			) = 3 THEN 'SIM'
		END AS SITUACAO
	,A.PERCENTUAL
	,A.VALOR
	,F.HANDLE HANDLECMS
FROM FN_DOCUMENTOCOMISSOES A
INNER JOIN GN_PESSOAS B ON B.HANDLE = A.AGENTEVENDAS
INNER JOIN EMPRESAS C ON C.HANDLE = A.EMPRESA
LEFT JOIN FN_DOCUMENTOS D ON D.HANDLE = A.DOCUMENTO
LEFT JOIN FN_DOCUMENTOS D1 ON D1.HANDLE = D.DOCUMENTOORIGEM
LEFT JOIN FN_PARCELAS E ON E.DOCUMENTO = D1.HANDLE
LEFT JOIN FN_PARCELAS E1 ON E1.DOCUMENTO = D.HANDLE
INNER JOIN K_CN_CONTRATOBENPRODUTOCMS F ON F.DOCUMENTOCOMISSAO = A.HANDLE
LEFT JOIN K_CN_CONTRATOBENPRODUTOS G ON G.HANDLE = F.CONTRATOBENPRODUTO
LEFT JOIN K_CN_CONTRATOBENEFICIARIOS H ON H.HANDLE = G.CONTRATOBENEFICIARIO
LEFT JOIN CN_CONTRATOS I ON I.HANDLE = H.CONTRATO
LEFT JOIN PD_PRODUTOS J ON J.HANDLE = G.PRODUTO
LEFT JOIN CN_TIPOSCONTRATOS L ON L.HANDLE = I.TIPOCONTRATO
WHERE 1 = 1
	--AND (A.FILIAL IN (@CAMPO(FILIAL))OR - 1 IN (@CAMPO(FILIAL)))
	--AND (I.TIPOCONTRATO IN (@CAMPO(TIPOCONTRATO)) OR - 1 IN (@CAMPO(TIPOCONTRATO)))
	AND (A.AGENTEVENDAS IN (39305) OR - 1 IN (39305))
	--------------
	AND (
			(
				CASE 
					WHEN E.DATAVENCIMENTO IS NULL
						THEN E1.DATAVENCIMENTO
					ELSE E.DATAVENCIMENTO
					END BETWEEN CONVERT(DATE, '2023-05-01') 
					AND CONVERT(DATE, '2023-05-31')
				AND (
					CASE 
						WHEN E.HANDLE IS NULL
							THEN E1.HANDLE
						ELSE E.HANDLE
						END NOT IN (
SELECT PARCELA
	FROM FN_MOVIMENTACOES
	WHERE TIPOMOVIMENTO IN (1, 2, 3, 5, 6, 14, 8)
							AND LANCAMENTOTESOURARIA IS NULL
							AND DATA BETWEEN CONVERT(DATE, '2023-05-01')  AND CONVERT(DATE, '2023-05-31')
						)
					)
			)
		OR (
				
					CASE 
						WHEN E.HANDLE IS NULL
							THEN E1.HANDLE
						ELSE E.HANDLE
						END IN (
SELECT PARCELA
	FROM FN_MOVIMENTACOES
	WHERE TIPOMOVIMENTO IN (1, 2, 3, 5, 6, 14, 8)
							AND LANCAMENTOTESOURARIA IS NOT NULL
							AND DATA BETWEEN CONVERT(DATE, '2023-05-01') 
								AND CONVERT(DATE, '2023-05-31')
						)
					
			)
	)
	-------------------------------------------------
	AND TIPOMOVIMENTO = 1
	AND (A.PARCELA IS NULL OR (A.PARCELA IS NOT NULL AND A.K_NUMEROCONTRATO IS NOT NULL))
	-- AQUI ABAIXO FOI O CÓDIGO INSERIDO NA SMS - 2058008
	AND (
		(
			(
SELECT COUNT(*) REG
				FROM CN_CONTRATOS A1
				INNER JOIN K_CN_CONTRATOBENEFICIARIOS A2 ON A2.CONTRATO = A1.HANDLE
				INNER JOIN K_CN_CONTRATOBENPRODUTOS A3 ON A3.CONTRATOBENEFICIARIO = A2.HANDLE
				INNER JOIN CP_CONDICOESPAGAMENTO A4 ON A4.HANDLE = A1.CONDICAOPAGAMENTODEFAULT
				INNER JOIN FN_FORMASPAGAMENTO A5 ON A5.HANDLE = A4.FORMAPAGAMENTO
					AND A5.K9_EHCARNE = 'S'
				WHERE A3.HANDLE = F.CONTRATOBENPRODUTO
				) > 0
			AND CASE 
				WHEN E.HANDLE IS NULL
					THEN E1.HANDLE
				ELSE E.HANDLE
				END = A.PARCELA
			)
		OR (
			(
SELECT COUNT(*) REG
				FROM CN_CONTRATOS A1
				INNER JOIN K_CN_CONTRATOBENEFICIARIOS A2 ON A2.CONTRATO = A1.HANDLE
				INNER JOIN K_CN_CONTRATOBENPRODUTOS A3 ON A3.CONTRATOBENEFICIARIO = A2.HANDLE
				INNER JOIN CP_CONDICOESPAGAMENTO A4 ON A4.HANDLE = A1.CONDICAOPAGAMENTODEFAULT
				INNER JOIN FN_FORMASPAGAMENTO A5 ON A5.HANDLE = A4.FORMAPAGAMENTO
					AND A5.K9_EHCARNE = 'N'
				WHERE A3.HANDLE = F.CONTRATOBENPRODUTO
				) > 0
			)
		)
-- AQUI ACIMA FOI O CÓDIGO INSERIDO NA SMS - 2058008
ORDER BY B.NOME ASC
	,CASE 
		WHEN A.K_PARCELA IS NOT NULL
			THEN A.K_PARCELA
		ELSE F.PARCELA
		END ASC
	,CASE 
		WHEN A.K_NUMEROCONTRATO IS NOT NULL
			THEN A.K_NUMEROCONTRATO
		ELSE I.NUMERO
		END
