
/*
BA3 - FAMILIA
BA1 - BENEFICIARIOS
BDK - VALORES
*/

SELECT
BA3.BA3_FILIAL      AS FILAIL,
BA3.BA3_CODINT      AS OPERADORA,
BA3.BA3_CODEMP      AS GRUPO_EMPRESA,
BA3.BA3_CONEMP      AS CONTRATO,
BA3.BA3_SUBCON      AS SUB_CONTRATO,
BA3.BA3_MATEMP      AS MATRICULA,
BA3.BA3_XCARTE      AS NUMERO_BENNER,
BA3.BA3_IDBENN      AS ID_BENNER_CONTRATO,
BA1.BA1_CPFUSR      AS CPF,
BA1.BA1_NOMUSR      AS NOME,
BA1.BA1_TIPUSU      AS TIPO,
BA1.BA1_XCARTE      AS CARTEIRINHA,
BA1.BA1_IDBENN      AS ID_BENNER_BENEFICIARIO,
BDK.BDK_VALOR       AS VALOR
FROM BA3010 BA3
LEFT JOIN BA1010 BA1 ON BA1.BA1_CODINT = BA3.BA3_CODINT AND BA1.BA1_CODEMP = BA3.BA3_CODEMP AND BA1.BA1_CONEMP = BA3.BA3_CONEMP AND BA1.BA1_SUBCON = BA3.BA3_SUBCON AND BA1.BA1_MATEMP = BA3.BA3_MATEMP
LEFT JOIN BDK010 BDK ON BDK.BDK_CODINT = BA1.BA1_CODINT AND BDK.BDK_CODEMP = BA1.BA1_CODEMP AND BDK.BDK_MATRIC = BA1.BA1_MATRIC
WHERE 1=1
/* REMOVE DELETADOS */ AND BA3.D_E_L_E_T_ = ''
/* REMOVE DELETADOS */ AND BA1.D_E_L_E_T_ = ''
/* REMOVE DELETADOS */ AND BDK.D_E_L_E_T_ = ''
--/* MATRICULA TOTVS */  AND BA1.MATRIC = ''
--/* ID BENEFICIARIOS */ AND BA3.BA3_MATEMP = '2786439'
/* ID DO CONTRATO */   AND BA3.BA3_IDBENN = '1015470'


