

/* ----------------- EXCLUSAO CLICKLIFE (CONTRATOS PF) ----------------- */


SELECT 
UPPER(A.NOME) AS NOME_CLIENTE,
REPLACE(REPLACE(REPLACE(A.CPF, '.',''),'-',''),'/','') AS CPF_CLIENTE,
B.CNPJ AS CNPJ_CONTRATO,
D.NOME AS EMPRESA,
C.NOME AS TIPOCONTRATO
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
AND
(
    B.STATUS = 5
    OR B.STATUS = 2
    AND A.STATUS = 2
)
AND A.TEMATENDIMENTO = 'S'
AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
AND LEN(B.CNPJ) <= 14
AND B.DATASUSPENSAO BETWEEN CONVERT(DATE,DATEADD(DAY,-4,GETDATE())) AND CONVERT(DATE,GETDATE())
       

/* ----------------- EXCLUSAO CLICKLIFE (CONTRATOS PJ) ----------------- */


SELECT 
UPPER(A.NOME) AS NOME_CLIENTE,
REPLACE(REPLACE(REPLACE(A.CPF, '.',''),'-',''),'/','') AS CPF_CLIENTE,
B.CNPJ AS CNPJ_CONTRATO,
D.NOME AS EMPRESA,
C.NOME AS TIPOCONTRATO
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
AND
(
    B.STATUS = 5
    OR B.STATUS = 2
    AND A.STATUS = 2
)
AND A.TEMATENDIMENTO = 'S'
AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
AND LEN(B.CNPJ) > 14
AND B.DATASUSPENSAO BETWEEN CONVERT(DATE,DATEADD(DAY,-4,GETDATE())) AND CONVERT(DATE,GETDATE())