
/* ----------------- MASSA TOTAL CLICKLIFE (ENVIAR TODO MÊS) ----------------- */

SELECT 
D.NOME EMPRESA,
B.K_APELIDO CONTRATO,
B.CNPJ,
C.NOME TIPOCONTRATO,
A.NOME ASSOCIADO,
A.CPF,
B.STATUS STATUSCONTRATO,
A.STATUS STATUSBEN,
A.TEMATENDIMENTO
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
AND B.STATUS = 2
AND A.STATUS = 1
AND A.TEMATENDIMENTO = 'S'
AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
UNION ALL
SELECT 
D.NOME EMPRESA,
B.K_APELIDO CONTRATO,
B.CNPJ,
C.NOME TIPOCONTRATO,
A.NOME ASSOCIADO,
A.CPF,
B.STATUS STATUSCONTRATO,
A.STATUS STATUSBEN,
A.TEMATENDIMENTO
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE C.HANDLE = 12
AND B.STATUS = 2
AND A.STATUS = 1
AND A.TEMATENDIMENTO = 'S'
AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
AND B.HANDLE IN (SELECT A.HANDLE FROM CN_CONTRATOS A INNER JOIN K_CN_CONTRATOBENEFICIARIOS B ON B.CONTRATO = A.HANDLE WHERE A.TIPOCONTRATO = 12 AND A.STATUS = 2 AND B.STATUS = 1 GROUP BY A.HANDLE HAVING COUNT(B.HANDLE) <= 10)

