INCLUSÕES:
SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF,
       B.STATUS STATUSCONTRATO,
       A.STATUS STATUSBEN,
       A.TEMATENDIMENTO
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
 WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
       AND B.STATUS = 2
       AND A.STATUS = 1
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
       AND DATAVIGOR BETWEEN CONVERT(DATE, '2022-09-19') AND CONVERT(DATE, '2022-09-25')
	   
	   
	   
	   
	   
SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       B.CNPJ,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
 WHERE C.HANDLE IN (12)
       AND B.STATUS = 2
       AND A.STATUS = 1
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
       AND DATAVIGOR < CONVERT(DATE, '2022-11-28')
       AND B.HANDLE IN (SELECT B.HANDLE
                          FROM K_CN_CONTRATOBENEFICIARIOS A
                               INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
                         WHERE
                               C.HANDLE IN (12)
                               AND B.STATUS = 2
                               AND A.STATUS = 1
                               AND A.TEMATENDIMENTO = 'S'
                               AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
                               AND DATAVIGOR < CONVERT(DATE, '2022-11-28')
                         GROUP BY B.HANDLE
                        HAVING COUNT(A.HANDLE) < 11
                       ) 
---------------------//----------------------------//--------------------------------//--------------------------------------------//-------------------------------

CANCELAMENTOS:
SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF,
       B.STATUS STATUSCONTRATO,
       A.STATUS STATUSBEN,
       A.TEMATENDIMENTO
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
 WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
       AND
       (
           B.STATUS = 5
           OR B.STATUS = 2
           AND A.STATUS = 2
       )
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
       AND B.DATASUSPENSAO BETWEEN CONVERT(DATE, '2022-09-19') AND CONVERT(DATE, '2022-09-25') 



SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF,
       B.STATUS STATUSCONTRATO,
       A.STATUS STATUSBEN,
       A.TEMATENDIMENTO,
       C2.DATAINCLUSAO
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
       INNER JOIN PD_STATUS C2 ON C2.HANDLEREGISTROORIGEM = A.HANDLE AND HANDLETABELAORIGEM = 6687 AND C2.STATUS = 2
AND C2.HANDLE IN (

SELECT MAX(C1.HANDLE) FROM PD_STATUS C1
INNER JOIN K_CN_CONTRATOBENEFICIARIOS L1 ON L1.HANDLE = C1.HANDLEREGISTROORIGEM
WHERE C1.HANDLETABELAORIGEM = 6687 AND C1.STATUS = 2 AND C1.DATAINCLUSAO BETWEEN CONVERT(DATE, '2022-07-25') AND CONVERT(DATE, '2022-07-31')
GROUP BY C1.HANDLEREGISTROORIGEM

)
 WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
       AND (B.STATUS = 5 OR B.STATUS = 2 AND A.STATUS = 2)
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)



-----------------------------------------------------------------------------BASE GERAL TODO FINAL DE MES--------------------------------------------------------------------------------------

SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       B.CNPJ,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF,
       B.STATUS STATUSCONTRATO,
       A.STATUS STATUSBEN,
       A.TEMATENDIMENTO
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
 WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
       AND B.STATUS = 2
       AND A.STATUS = 1
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
UNION ALL
SELECT D.NOME EMPRESA,
       B.K_APELIDO CONTRATO,
       B.CNPJ,
       C.NOME TIPOCONTRATO,
       A.NOME ASSOCIADO,
       A.CPF,
       B.STATUS STATUSCONTRATO,
       A.STATUS STATUSBEN,
       A.TEMATENDIMENTO
  FROM K_CN_CONTRATOBENEFICIARIOS A
       INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
       INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
       INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
 WHERE C.HANDLE = 12
       AND B.STATUS = 2
       AND A.STATUS = 1
       AND A.TEMATENDIMENTO = 'S'
       AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
       AND B.HANDLE IN (SELECT A.HANDLE
                          FROM CN_CONTRATOS A
                               INNER JOIN K_CN_CONTRATOBENEFICIARIOS B ON B.CONTRATO = A.HANDLE
                         WHERE A.TIPOCONTRATO = 12
                               AND A.STATUS = 2
                               AND B.STATUS = 1
                         GROUP BY A.HANDLE
                        HAVING COUNT(B.HANDLE) <= 10
                       )