
SELECT A.NUMERO, B.NOME NOMEPESSOA, B.CGCCPF CPF,A.HANDLE HANDLECONTRATO, D.NOME TIPOCONTRATO, C.DATAINCLUSAO DTCANCELAMENTO,
E.DDD, E.TELEFONE, F.DESCRICAO CONDICAOPAGAMENTO, H.NOME FORMAPAGAMENTO, A.K_DTBASE DTBASE, I.NOME MOTIVO, C.TEXTOSTATUS OBSERVAÇÃO, J.LOGOTIPO,
B.HANDLE PESSOA, L.QTDE, L.VALOR, J.NOME NOMEFILIAL
FROM CN_CONTRATOS A
INNER JOIN GN_PESSOAS B ON B.HANDLE = A.PESSOA
INNER JOIN PD_STATUS C ON C.HANDLEREGISTROORIGEM = A.HANDLE AND HANDLETABELAORIGEM = 1907 AND C.STATUS = 5
AND C.HANDLE IN (
SELECT MAX(C1.HANDLE) FROM PD_STATUS C1
INNER JOIN CN_CONTRATOS L1 ON L1.HANDLE = C1.HANDLEREGISTROORIGEM
WHERE C1.HANDLETABELAORIGEM = 1907 AND C1.STATUS = 5 AND CONVERT (DATE,C1.DATAINCLUSAO) BETWEEN CONVERT(DATE,'2023-01-01') AND CONVERT(DATE,'2023-06-30')
GROUP BY C1.HANDLEREGISTROORIGEM
)
INNER JOIN CN_TIPOSCONTRATOS D ON D.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOATELEFONES E ON E.PESSOA = B.HANDLE AND E.HANDLE IN (SELECT MIN(HANDLE) FROM GN_PESSOATELEFONES GROUP BY PESSOA)
LEFT JOIN CP_CONDICOESPAGAMENTO F ON F.HANDLE = A.CONDICAOPAGAMENTODEFAULT
LEFT JOIN CP_MAPACONDICAOPAGAMENTO G ON G.CONDICOESPAGAMENTO = F.HANDLE
LEFT JOIN FN_FORMASPAGAMENTO H ON H.HANDLE = G.FORMAPAGAMENTO
LEFT JOIN CN_MOTIVOS I ON I.HANDLE = A.MOTIVO
INNER JOIN FILIAIS J ON J.HANDLE = A.FILIAL
INNER JOIN EMPRESAS K ON K.HANDLE = A.EMPRESA
LEFT JOIN (SELECT A1.CONTRATO, COUNT(*) QTDE, SUM(A1.VALOR) VALOR FROM K_CN_CONTRATOBENEFICIARIOS A1 WHERE A1.STATUS = 1 GROUP BY A1.CONTRATO) L ON L.CONTRATO = A.HANDLE
--WHERE A.NUMERO = 'FA-00007546-CT'
WHERE A.STATUS = 5
AND CONVERT(DATE,C.DATAINCLUSAO) BETWEEN CONVERT(DATE,'2023-01-01') AND CONVERT(DATE,'2023-06-30')
--AND ( I.HANDLE IN (@CAMPO(MOTIVO))OR -1 IN (@CAMPO(MOTIVO)) )
--AND ( J.HANDLE IN (@CAMPO(FILIAL))OR -1 IN (@CAMPO(FILIAL)) )
AND ( K.HANDLE IN (1, 2, 3, 5, 17, 18) )
AND ( D.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55) )
ORDER BY A.FILIAL, DTCANCELAMENTO
