
DEFINE @FILIAL VARCHAR(4)
DEFINE @LOCAL VARCHAR(2)
DEFINE @PROD VARCHAR(15)
DEFINE @DTINI VARCHAR(8)
DEFINE @DTFIN VARCHAR(8)

DECLARE @FILIAL VARCHAR(4)
DECLARE @LOCAL VARCHAR(2)
DECLARE @PROD VARCHAR(15)
DECLARE @CHAVE VARCHAR(100)
DECLARE @CONT INT
DECLARE @CONT_MAX INT
DECLARE @DTINI DATE
DECLARE @DTFIN DATE
DECLARE @SALDO FLOAT

SET @FILIAL = $(@FILIAL)
SET @LOCAL = $(@LOCAL)
SET @PROD = $(@PROD)
SET @CONT = 1
SET @CONT_MAX = ISNULL((SELECT COUNT(*) FROM ZKARDEX WHERE ZK_FILIAL = @FILIAL AND ZK_COD_ARMZ = @LOCAL AND ZK_CODPROD = @PROD AND ZK_ESTOQUE = 'S'),0)
SET @DTINI = $(@DTINI)
SET @DTFIN =  $(@DTFIN)
SET @SALDO = 0

EXEC Z_KARDEX
DROP TABLE AUXKARDEX
DROP TABLE KARDEX


CREATE TABLE AUXKARDEX
(
		ID 			INT IDENTITY(1,1),
 		FILIAL		VARCHAR(4),
 		LOCAL		VARCHAR(2),
 		CODPROD		VARCHAR(15),
 		QTD			FLOAT,
 		SERIE		VARCHAR(3),
 		DOC			VARCHAR(9),
 		DATA		VARCHAR(9),
 		TES			VARCHAR(3),
 		USUARIO		VARCHAR(30),
 		IDENT		VARCHAR(30)
)

CREATE TABLE KARDEX
(
		ID 			INT,
 		FILIAL		VARCHAR(4),
 		LOCAL		VARCHAR(2),
 		CODPROD		VARCHAR(15),
 		QTD			FLOAT,
 		SERIE		VARCHAR(3),
 		DOC			VARCHAR(9),
 		DATA		VARCHAR(9),
 		TES			VARCHAR(3),
 		USUARIO		VARCHAR(30),
 		IDENT		VARCHAR(30),
 		SALDO		FLOAT
)

INSERT INTO AUXKARDEX
(
 		FILIAL		,
 		LOCAL		,
 		CODPROD		,
 		QTD			,
 		SERIE		,
 		DOC			,
 		DATA		,
 		TES			,	
 		USUARIO	    ,
 		IDENT		 	 
)

SELECT 
ZK_FILIAL,
ZK_COD_ARMZ,
ZK_CODPROD,
ZK_QTD,
ZK_SERIE,
ZK_DOC,
ZK_DT_MOV,
ZK_TES,
ZK_USUARIO,
ZK_IDENT
FROM ZKARDEX 
WHERE 1=1
AND ZK_FILIAL = @FILIAL 
AND ZK_COD_ARMZ = @LOCAL 
AND ZK_CODPROD = @PROD
AND ZK_ESTOQUE = 'S' 
AND ZK_DT_CANCEL = '' 
ORDER BY ZK_DT_MOV

/*---------------------INSERT TABLE KARDEX--------------------*/

WHILE @CONT <= @CONT_MAX
BEGIN 

IF ISNULL((SELECT IDENT FROM AUXKARDEX WHERE ID = @CONT), '') = 'ENTRADA' 
BEGIN
SET @SALDO = @SALDO +  ISNULL((SELECT QTD FROM AUXKARDEX WHERE ID = @CONT), 0)
END
IF ISNULL((SELECT IDENT FROM AUXKARDEX WHERE ID = @CONT), '') = 'SAIDA'
BEGIN
SET @SALDO = @SALDO -  ISNULL((SELECT QTD FROM AUXKARDEX WHERE ID = @CONT), 0)
END
IF ISNULL((SELECT IDENT FROM AUXKARDEX WHERE ID = @CONT), '') = 'MOV. INTERNA' AND ISNULL((SELECT TES FROM AUXKARDEX WHERE ID = @CONT), '') <= 499
BEGIN
SET @SALDO = @SALDO +  ISNULL((SELECT QTD FROM AUXKARDEX WHERE ID = @CONT), 0)
END
IF ISNULL((SELECT IDENT FROM AUXKARDEX WHERE ID = @CONT), '') = 'MOV. INTERNA' AND ISNULL((SELECT TES FROM AUXKARDEX WHERE ID = @CONT), '') >= 500
BEGIN
SET @SALDO = @SALDO -  ISNULL((SELECT QTD FROM AUXKARDEX WHERE ID = @CONT), 0)
END

INSERT INTO KARDEX
(
		ID			,
 		FILIAL		,
 		LOCAL		,
 		CODPROD		,
 		QTD			,
 		SERIE		,
 		DOC			,
 		DATA		,
 		TES			,
 		USUARIO		,
 		IDENT  		,
 		SALDO		
)

SELECT 
*,
@SALDO AS SALDO 
FROM AUXKARDEX WHERE ID = @CONT 
AND DATA BETWEEN @DTINI AND @DTFIN 
ORDER BY DATA

SET @CONT = @CONT + 1

END

SELECT '---- KARDEX ----' AS MOVIMENTAÇÃO

SELECT 
FILIAL,
LOCAL,
CODPROD,
QTD,
SERIE,
DOC,
CONVERT(VARCHAR,CAST(DATA AS DATETIME),103) AS DATA,
TES,
USUARIO,
IDENT,
SALDO  
FROM KARDEX 

SELECT '---- INVENTARIO ----' AS MOVIMENTAÇÃO

SELECT 
B7_FILIAL	AS FILIAL,
B7_LOCAL	AS ARMAZEM,
B7_COD		AS PRODUTO,
B7_QUANT	AS QTD,
B7_DOC		AS DOC,
CONVERT(VARCHAR,CAST(B7_DATA AS DATETIME),103) AS DATA 
FROM SB7010 
WHERE 1=1
AND B7_FILIAL = @FILIAL 
AND B7_LOCAL = @LOCAL 
AND B7_COD = @PROD
AND B7_DATA BETWEEN @DTINI AND @DTFIN
ORDER BY B7_DATA



