

SELECT 
D.NOME				AS EMPRESA,
E.FILIALCONTABIL	AS FILIAL,
C.HANDLE			AS COD_USUARIO,
C.NOME				AS USUARIO,
B.HANDLE            AS COD_ALCADA,
B.NOMEDOGRUPO		AS GRUPO_ALCADA,
A.ATIVO             AS ATIVO
--UPDATE CP_GRUPOALCADASINTEGRANTES SET ATIVO = 'N'
FROM CP_GRUPOALCADASINTEGRANTES A
LEFT JOIN CP_GRUPOALCADAS B ON B.HANDLE = A.GRUPO
LEFT JOIN Z_GRUPOUSUARIOS C ON C.HANDLE = A.USUARIO
LEFT JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
LEFT JOIN FILIAIS E ON E.HANDLE = B.FILIAL
WHERE 1=1
AND B.NOMEDOGRUPO LIKE '%MANUT%'
--AND B.NOMEDOGRUPO LIKE '%COMPRAS FR%'
/* DIEGO, FERNANDO, HELBER */ AND C.HANDLE NOT IN (61,690,688)


