
/*--------------------------------------- DE ACORDO COM A PLANILHA -------------------------------------------*/

SELECT 
A.PLACANUMERO	AS PLACA,
B.NOME AS MODELO,
A.ANO	AS ANO,
A.NOME AS TRANSFORMACAO,
CONCAT(C.ESTRUTURA, ' - ', C.NOME) AS PROJETO,
'ALIENACAO' AS ALIENACAO,
A.CHASSI	AS CHASSI,
A.RENAVAM	AS RENAVAM,
D.CGCCPF	AS CNPJ_PROPIETARIO,
D.NOME		AS PROPIETARIO
FROM MA_RECURSOS A
LEFT JOIN MF_VEICULOMODELOS B ON B.HANDLE = A.MODELOVEICULO
LEFT JOIN GN_PROJETOS C ON C.HANDLE = A.PROJETO
LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PROPRIETARIO
WHERE 1=1
--AND HANDLE = 584


/*----------------------------------------------------------------------------------*/


SELECT 
A.CODIGO,       
A.NOME,       
A.ANO,       
A.PLACANUMERO,       
B.NOME PROJETO,
E.NOME PROPRIETARIO,       
B.NOME AS 'CENTRO DE CUSTO',
C1.NOME AS 'LOCAL PROJETO',
D.NOME AS 'LOCAL FILIAL'
/*
F.SIGLA ESTADO,  
G.NOME MUNICIPIO,       
CASE A.K_STATUS      
    WHEN '1' THEN 'VZ - Veículo Zero em estoque, aguardando ativação de contratos.'      
    WHEN '2' THEN 'FA - FROTA ATIVA - VEíCULO INSERIDO NO CONTRATO PúBLICO OU PRIVADO,FAZ NECESSáRIO A IMPUTAçãO DOS DADOS DO VEíCULO NO SISTEMA E SE POSSíVEL ATRELAR O NúMERO DO CONTRATO NA PLACA;'       
    WHEN '3' THEN 'VR - VEíCULO DISPONíVEL RELOCAçãO: VEíCULO ENCERROU O CONTRATO E FICARá EM STAD BY PARA UMA NOVA RELOCAçãO;'       
    WHEN '4' THEN 'VO - FORA DE OPERAçãO: VEíCULO COM ALGUM PROBLEMA DE DOC OU ETC... NO QUAL ESTARá AGUARDANDO REGULARIZAçãO PARA TRAMITES FUTURO.'       
    WHEN '5' THEN 'VD - VEíCULO DISPONíVEL PARA VENDA.'
    WHEN '6' THEN 'VE - VEíCULO VENDIDO E ENCERRADO DA FROTA. APóS A VENDA DO ATIVO, NECESSÁRIO DAR BAIXA DO CARRO NO SISTEMA E BLOQUEAR A PLACA SISTEMICAMENTE, PARA NãO CORRER O RISCO DE PAGAR' 
END AS STATUS
*/
FROM MA_RECURSOS A
LEFT JOIN CT_CC B ON B.HANDLE = A.LOCALCENTRODECUSTO
INNER JOIN GN_PROJETOS C ON C.HANDLE = A.PROJETO
--LEFT JOIN GN_PROJETOS C ON C.HANDLE = A.PROJETO
LEFT JOIN GN_PROJETOS C1 ON C1.HANDLE = A.LOCALPROJETO
LEFT JOIN FILIAIS D ON D.HANDLE = A.LOCALFILIAL
LEFT JOIN GN_PESSOAS E ON E.HANDLE = A.PROPRIETARIO
--LEFT JOIN ESTADOS F ON F.HANDLE = A.K_LOCALUF
--LEFT JOIN MUNICIPIOS G ON G.HANDLE = A.K_LOCALMUNICIPIO
WHERE 1=1


/*

CRIAR CAMPOS EM MA_RECURSOS

1 - K_LOCALUF
2 - K_LOCALMUNICIPIO
3 - K_STATUS

*/

/*----------------------------------------------------------------------------------*/

SELECT
    CONCAT(A.PLACANUMERO, ' - ', G.NOME, '/', B.NOME, ' - ', YEAR(A.ANO), '/', YEAR(A.ANODOMODELO)) AS CHAVE,
    E.NOME AS FILIAL,
    F.NOME AS LOCALFILIAL,
    E.NOME,
    A.PLACANUMERO AS PLACA,
    G.NOME as MARCA,
    B.NOME AS MODELO,
    CONCAT(G.NOME, '/', B.NOME) AS MARCAMODELO,
    CONCAT(YEAR(A.ANO), '/', YEAR(A.ANODOMODELO)) AS ANOMODELO,
    A.NOME AS TRANSFORMACAO,
    CONCAT(C.ESTRUTURA, ' - ', C.NOME) AS PROJETO,
    C.NOME AS PROJETO_DESC,
    'ALIENACAO' AS ALIENACAO,
    A.CHASSI AS CHASSI,
    A.RENAVAM AS RENAVAM,
    D.CGCCPF AS CNPJ_PROPIETARIO,
    D.NOME AS PROPIETARIO
FROM MA_RECURSOS A
    LEFT JOIN MF_VEICULOMODELOS B ON B.HANDLE = A.MODELOVEICULO
    LEFT JOIN GN_PROJETOS C ON C.HANDLE = A.PROJETO
    LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PROPRIETARIO
    LEFT JOIN FILIAIS E ON E.HANDLE = A.FILIAL
    LEFT JOIN FILIAIS F ON F.HANDLE = A.LOCALFILIAL
    LEFT JOIN MF_FABRICANTES G ON G.HANDLE = A.FABRICANTE
WHERE 1=1