
/* ---------- CAPA ORDEM SERVIÇO ---------- */

SELECT 
D.HANDLE			AS COD_EMPRESA,
D.NOME 				AS EMPRESA,
G.HANDLE			AS COD_FILIAL,
G.NOME				AS FILIAL,
A.CODIGO			AS NUMERO_OS,
CASE
	WHEN A.STATUS = 1 THEN 'CADASTRADA'
	WHEN A.STATUS = 2 THEN 'EM EXECUCAO'
	WHEN A.STATUS = 3 THEN 'CANCELADA'
	WHEN A.STATUS = 4 THEN 'ENCERRADA'
	WHEN A.STATUS = 5 THEN 'AGUARDADO APROVACAO'
	WHEN A.STATUS = 6 THEN 'AGUARDANDO ORDEM DE COMPRA'
	WHEN A.STATUS = 7 THEN 'AGUARDANDO REQUISICAO DE COMPRA'
	WHEN A.STATUS = 8 THEN 'AGUARDANDO REQUISICAO DE CONSUMO'
	WHEN A.STATUS = 9 THEN 'AGUARDANDO GERAR FINANCEIRO'
	WHEN A.STATUS = 10 THEN 'AGUARDANDO MODIFICACOES'
	WHEN A.STATUS = 11 THEN 'AGUARDANDO GERAR ORDEM DE COMPRA'
	WHEN A.STATUS = 12 THEN 'AGUARDANDO ENVIAR PARA RH'
	WHEN A.STATUS = 13 THEN 'AGUARDANDO GERAR ROMANEIO'
	WHEN A.STATUS = 14 THEN 'AGUARDANDO RETORNO RECAPAGEM'
	WHEN A.STATUS = 15 THEN 'AGUARDANDO GERAR ADIATAMENTO'
	WHEN A.STATUS = 16 THEN 'AGUARDANDO GERAR SALDO FINANCEIRO'
	WHEN A.STATUS = 17 THEN 'AGUARDANDO SERVIDOR'
	WHEN A.STATUS = 19 THEN 'AGUARDANDO MATERIAIS'
	WHEN A.STATUS = 20 THEN 'PROGRAMADA'
	WHEN A.STATUS = 21 THEN 'EXECUTADA'
ELSE ''
END 				AS STATUS,

A.DESCRICAO			AS DESCRICAO_OS,
E.NOME				AS TIPO_SERVICO,
CONCAT(F.PLACANUMERO, ' - ', F.NOME) AS VEICULO,
A.OBSERVACOES		AS OBSERVACAO,
A.DATASOLICITACAO	AS DT_SOLICITACAO,
A.DATAINICIAL		AS DT_INICIO,
A.PREVISAOTERMINO	AS DT_PREVISAOTERMINO,
A.DATAFINAL			AS DT_FIM,
B.PRODUTO			AS COD_PROD,
C.NOME				AS PRODUTO,
B.QUANTIDADE		AS QTD
FROM MF_ORDEMSERVICOS A
LEFT JOIN MF_ORDEMSERVICOPRODUTOS B ON B.ORDEMSERVICO = A.HANDLE
LEFT JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
LEFT JOIN EMPRESAS D ON D.HANDLE = A.EMPRESA 
LEFT JOIN MF_TIPOORDEMSERVICOS E ON E.HANDLE = A.TIPOORDEMSERVICO
LEFT JOIN MA_RECURSOS F ON F.HANDLE = A.VEICULO
LEFT JOIN FILIAIS G ON G.HANDLE = A.FILIAL
WHERE 1=1
AND A.CODIGO = 'OSCE.0003894/23'


/*

--PRODUTOS

SELECT 
D.HANDLE			AS COD_EMPRESA,
G.HANDLE			AS COD_FILIAL,
A.CODIGO			AS NUMERO_OS,
B.PRODUTO			AS COD_PROD,
C.NOME				AS PRODUTO,
B.QUANTIDADE		AS QTD
FROM MF_ORDEMSERVICOS A
LEFT JOIN MF_ORDEMSERVICOPRODUTOS B ON B.ORDEMSERVICO = A.HANDLE
LEFT JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
LEFT JOIN EMPRESAS D ON D.HANDLE = A.EMPRESA 
LEFT JOIN MF_TIPOORDEMSERVICOS E ON E.HANDLE = A.TIPOORDEMSERVICO
LEFT JOIN MA_RECURSOS F ON F.HANDLE = A.VEICULO
LEFT JOIN FILIAIS G ON G.HANDLE = A.FILIAL
WHERE 1=1
--AND A.CODIGO = 'OSCE.0003894/23'
AND A.CODIGO = 'OSCE.0001166/20'
--AND A.CODIGO = 'OSCE.0002101/23'




SELECT 
F.PLACANUMERO		AS PLACA,
MAX(A.DATAFINAL)	AS QTD
FROM MF_ORDEMSERVICOS A
LEFT JOIN MF_ORDEMSERVICOPRODUTOS B ON B.ORDEMSERVICO = A.HANDLE
LEFT JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
LEFT JOIN EMPRESAS D ON D.HANDLE = A.EMPRESA 
LEFT JOIN MF_TIPOORDEMSERVICOS E ON E.HANDLE = A.TIPOORDEMSERVICO
LEFT JOIN MA_RECURSOS F ON F.HANDLE = A.VEICULO
LEFT JOIN FILIAIS G ON G.HANDLE = A.FILIAL
WHERE 1=1
AND F.PLACANUMERO IS NOT NULL
AND A.DATAFINAL IS NOT NULL
GROUP BY 			   
F.PLACANUMERO



*/