
/*

SELECT 
FN_DOCUMENTOS.PESSOA, 
FN_DOCUMENTOS.DOCUMENTODIGITADO, 
FN_DOCUMENTOS.HANDLE, 
FN_DOCUMENTOS.TIPODOCUMENTO, 
FN_DOCUMENTOS.ENTRADASAIDA, 
FN_DOCUMENTOS.ABRANGENCIA, 
FN_DOCUMENTOS.DOCUMENTOORIGEM, 
SUM(CM_ITENS.VALORLIQUIDO) VALORLIQUIDO 
FROM CM_ITENS , FN_DOCUMENTOS 
WHERE 1=1
AND CM_ITENS.DOCUMENTO = FN_DOCUMENTOS.HANDLE 
GROUP BY 
FN_DOCUMENTOS.PESSOA, 
FN_DOCUMENTOS.DOCUMENTODIGITADO,
FN_DOCUMENTOS.HANDLE, 
FN_DOCUMENTOS.TIPODOCUMENTO, 
FN_DOCUMENTOS.ENTRADASAIDA, 
FN_DOCUMENTOS.ABRANGENCIA, 
FN_DOCUMENTOS.DOCUMENTOORIGEM


*/




SELECT 
	D.HANDLE			AS COD_LANC, 
	E.DOCUMENTO			AS COD_DOC, 
	I.ESTRUTURA 		AS ESTR_PROJ, 
	I.NOME 				AS PROJETO , 
	L.ESTRUTURA 		AS ESTR_CONTA, 
	L.NOME 				AS CONTA , 
	J.ESTRUTURA 		AS ESTR_CC, 
	J.NOME 				AS CENTROCUSTO,
	F.DOCUMENTODIGITADO	AS DOCUMENTO, 
	M.NOME 				AS FORNECEDOR, 
	C.DOCUMENTOCONTABIL	AS DOC_CONTAB, 
	H.CODIGOREFERENCIA	AS COD_REF,  
	H.NOME 				AS PRODUTO ,    
	C.FAVORECIDO 		AS FAVORECIDO_LANC_TES,
	SUM( 
		CASE 
			WHEN B.NATUREZA = 'C' THEN  ROUND( (CASE WHEN G.HANDLE IS NULL THEN (IIF(B.PERCENTUAL > 100.00,((A.VALOR*100)/B.PERCENTUAL),A.VALOR) - (ISNULL(D.DESCONTO*(A.VALOR / D.VALOR),0) + ISNULL(D.ABATIMENTO*(A.VALOR / D.VALOR),0)))  
			ELSE ((IIF(B.PERCENTUAL > 100.00,((A.VALOR*100)/B.PERCENTUAL),A.VALOR) - (ISNULL(D.DESCONTO*(A.VALOR / D.VALOR),0) + ISNULL(D.ABATIMENTO*(A.VALOR / D.VALOR),0)))) * (G.VALORLIQUIDO / F.VALORLIQUIDO) END ) , 4) 
			ELSE 0 END
		) 				AS VALORCREDITO,	
	SUM( 
		CASE 
			WHEN B.NATUREZA = 'D' THEN  ROUND( (CASE WHEN G.HANDLE IS NULL THEN (IIF(B.PERCENTUAL > 100.00,((A.VALOR*1000)/B.PERCENTUAL),A.VALOR) - (ISNULL(D.DESCONTO*(A.VALOR / D.VALOR),0) + ISNULL(D.ABATIMENTO*(A.VALOR / D.VALOR),0)))  
			ELSE ((IIF(B.PERCENTUAL > 100.00,((A.VALOR*100)/B.PERCENTUAL),A.VALOR) - (ISNULL(D.DESCONTO*(A.VALOR / D.VALOR),0) + ISNULL(D.ABATIMENTO*(A.VALOR / D.VALOR),0)))) * (G.VALORLIQUIDO / F.VALORLIQUIDO) END ) , 4) 
			ELSE 0 END
		) 				AS VALORDEBITO,
	SUM(G.QUANTIDADE) 	AS QTDE, 
	SUM(G.TOTALGERAL) 	AS TOTALGERAL, 
	R.PLACANUMERO 		AS PLACA, 
	E.PARCELADIGITADA	AS PARCELA, 
	C.DATAEMISSAO 		AS DT_EMISSAO,
	EMP.NOME 			AS EMPRESA, 
	FIL.NOME 			AS FILIAL
FROM FN_LANCAMENTOCC A
	INNER  JOIN FN_LANCAMENTOS B ON (A.LANCAMENTO = B.HANDLE)
	INNER JOIN TS_LANCAMENTOS C ON (B.LANCAMENTOTESOURARIA = C.HANDLE)
	LEFT OUTER JOIN CT_CC J ON (J.HANDLE = A.CENTROCUSTO  )
	LEFT OUTER JOIN FN_CONTAS L ON (L.HANDLE = B.CONTA )
	LEFT OUTER JOIN FN_MOVIMENTACOES D ON (D.HANDLE = B.MOVIMENTACAO AND D.LANCAMENTOTESOURARIA = C.HANDLE )
	LEFT OUTER JOIN FN_PARCELAS E ON (E.HANDLE = D.PARCELA  )
	LEFT OUTER JOIN (SELECT FN_DOCUMENTOS.PESSOA, FN_DOCUMENTOS.DOCUMENTODIGITADO, FN_DOCUMENTOS.HANDLE, FN_DOCUMENTOS.TIPODOCUMENTO, FN_DOCUMENTOS.ENTRADASAIDA, FN_DOCUMENTOS.ABRANGENCIA, FN_DOCUMENTOS.DOCUMENTOORIGEM, SUM(CM_ITENS.VALORLIQUIDO) VALORLIQUIDO FROM CM_ITENS , FN_DOCUMENTOS WHERE  CM_ITENS.DOCUMENTO = FN_DOCUMENTOS.HANDLE GROUP BY FN_DOCUMENTOS.PESSOA, FN_DOCUMENTOS.DOCUMENTODIGITADO,FN_DOCUMENTOS.HANDLE, FN_DOCUMENTOS.TIPODOCUMENTO, FN_DOCUMENTOS.ENTRADASAIDA, FN_DOCUMENTOS.ABRANGENCIA, FN_DOCUMENTOS.DOCUMENTOORIGEM ) F ON (F.DOCUMENTOORIGEM = E.DOCUMENTO  AND F.ABRANGENCIA IN ('A','R') )
	LEFT OUTER JOIN CM_ITENS G ON ( G.DOCUMENTO = F.HANDLE   )
	LEFT OUTER JOIN PD_PRODUTOS H ON (G.PRODUTO = H.HANDLE  )
	LEFT OUTER JOIN GN_PROJETOS I ON (I.HANDLE = A.PROJETO  )
	LEFT OUTER JOIN GN_PESSOAS M ON (F.PESSOA = M.HANDLE )
	LEFT JOIN CP_ORDENSCOMPRAITENS N ON G.ORDEMCOMPRAITEM = N.HANDLE
	LEFT JOIN CP_ORDENSCOMPRA O ON O.HANDLE = N.ORDEMCOMPRA
	LEFT JOIN MF_ORDEMCOMPRAS P ON P.ORDEMCOMPRA = O.HANDLE
	LEFT JOIN MF_ORDEMSERVICOS Q ON Q.FROTASORDEMCOMPRA = P.HANDLE
	LEFT JOIN MA_RECURSOS R ON Q.VEICULO = R.HANDLE
	LEFT JOIN EMPRESAS EMP ON C.EMPRESA = EMP.HANDLE
	LEFT JOIN FILIAIS FIL ON C.FILIAL = FIL.HANDLE
WHERE 1=1
	AND C.DATAEMISSAO >= '2023-04-01' 
	AND C.DATAEMISSAO <= '2023-04-30'
	AND ( ( F.ENTRADASAIDA IN ('E','I') 
	AND F.TIPODOCUMENTO NOT IN (56,67) )  OR F.HANDLE IS NULL)
	AND C.ATUALIZASALDO = 'S' 
	AND C.NATUREZALANCAMENTO = 'D' 
	AND C.HANDLE IS NOT NULL
	AND (C.CANCELADO <> 'S' OR C.CANCELADO IS NULL)
	AND C.CONCILIADO = 'S' 
	AND A.VALOR > 0
	AND L.HANDLE NOT IN (38)
	AND L.ESTRUTURA = '4.2.02.01.030'
	AND NOT EXISTS (SELECT * FROM FN_DOCUMENTOS WHERE FN_DOCUMENTOS.HANDLE = ISNULL(D.DOCUMENTO,0) AND FN_DOCUMENTOS.TIPODOCUMENTO  IN (56,67))
GROUP BY 
	D.HANDLE,
	E.DOCUMENTO, 
	C.FAVORECIDO , 
	I.ESTRUTURA, 
	I.NOME ,
	L.ESTRUTURA, 
	L.NOME, 
	J.ESTRUTURA, 
	J.NOME , 
	F.DOCUMENTODIGITADO , 
	M.NOME,  
	C.DOCUMENTOCONTABIL, 
	H.CODIGOREFERENCIA, 
	H.NOME, R.PLACANUMERO, 
	E.PARCELADIGITADA, 
	C.DATAEMISSAO,
	EMP.NOME, 
	FIL.NOME 
--ORDER BY I.ESTRUTURA

