
/*PRÉ REQUISITO PARA INSERÇÃO*/

RECNO+1 = SELECT MAX(R_E_C_N_O_)+1 FROM SUB010

ITEM+1 = SELECT MAX(UB_ITEM)+1 FROM SUB010 WHERE UB_FILIAL = 'FILIAL DESEJADA' AND UB_NUM = 'ATENDIMENTO DESEJADO'

UB_OPER = '01' /*PADRAO 01*/

UB_DTENTRE = 'DATA ATUAL' /*(AAAAMMDD)*/

ATENDIMENTO, PRODUTO E QUANTIDADE = CONFORME O USUARIO


/*INSERT NA TABELA DOS ITENS DO ATENDIMENTO*/

INSERT INTO SUB010 (UB_FILIAL, UB_NUM, UB_ITEM, UB_PRODUTO, UB_QUANT, R_E_C_N_O_)
VALUES (filial, atendimento, item+1, produto, qtde, oper(01), dtentre(AAAAMMDD), recno+1)


OBS: SEGUIR ESTA ORDEM DO INSERT.


SELECT R_E_C_N_O_, * FROM SUB010 WHERE D_E_L_E_T_ = '' AND UB_NUM = '034613'




