
SELECT 
SUA.UA_FILIAL	AS FILIAL_ATM,
SUA.UA_NUM		AS ATENDIMENTO,
SUA.UA_VEND		AS VENDEDOR,
SL1.L1_EMISNF	AS DT_FIN,
SUM(SL2.L2_QUANT)	AS QTD,
SUM(SL2.L2_VLRITEM) AS VLR_ITEM,
SUM(SL2.L2_DESCPRO) AS DESC_ITEM,
SUM(SL2.L2_VLRITEM + SL2.L2_DESCPRO) AS VLR_TAB_ITEM,
CASE
	WHEN ISNULL((
SELECT
ZZ3.ZZ3_CUSTD
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_HORA =ISNULL((
SELECT
MAX(ZZ2.ZZ2_HORA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA = ISNULL((
SELECT
MAX(ZZ2.ZZ2_DATA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA >= SL1.L1_EMISNF
),0)
),0)
AND ZZ2.ZZ2_DATA = ISNULL((
SELECT
MAX(ZZ2.ZZ2_DATA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA >= SL1.L1_EMISNF
),0)
),0) <> 0 
THEN
ISNULL((
SELECT
ZZ3.ZZ3_CUSTD
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_HORA =ISNULL((
SELECT
MAX(ZZ2.ZZ2_HORA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA = ISNULL((
SELECT
MAX(ZZ2.ZZ2_DATA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA >= SL1.L1_EMISNF
),0)
),0)
AND ZZ2.ZZ2_DATA = ISNULL((
SELECT
MAX(ZZ2.ZZ2_DATA)
FROM ZZ2010 ZZ2
LEFT JOIN ZZ3010 ZZ3 ON ZZ3.D_E_L_E_T_ = '' AND ZZ3.ZZ3_FILIAL = ZZ2.ZZ2_FILIAL AND ZZ3.ZZ3_COD = ZZ2.ZZ2_CODIGO
WHERE 1=1
AND ZZ2.D_E_L_E_T_ = ''
AND ZZ3.ZZ3_CODPRD = SB1.B1_COD
AND ZZ2.ZZ2_DATA >= SL1.L1_EMISNF
),0)
),0)
ELSE SB1.B1_CUSTD
END AS CUSTO_STD,
SB1.B1_CUSTD AS CUSTO_ATUAL,
CASE
	WHEN SL1.L1_SERIE <> ''
THEN SL1.L1_SERIE
	WHEN SL1.L1_SERPED <> ''
THEN SL1.L1_SERPED
ELSE ''
END AS SERIE,

CASE
	WHEN SL1.L1_DOC <> ''
THEN SL1.L1_DOC
	WHEN SL1.L1_DOCPED <> ''
THEN SL1.L1_DOCPED
ELSE ''
END AS DOC,


CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E1_VALOR) FROM SE1010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E1_FILIAL = SUA.UA_FILIAL  AND A.E1_PREFIXO = SL1.L1_SERIE  AND A.E1_NUM = SL1.L1_DOC AND A.E1_VEND1 = SUA.UA_VEND),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E1_VALOR) FROM SE1010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E1_FILIAL = SUA.UA_FILIAL  AND A.E1_PREFIXO = SL1.L1_SERPED  AND A.E1_NUM = SL1.L1_DOCPED AND A.E1_VEND1 = SUA.UA_VEND),0)
ELSE ''
END AS SE1,



CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = ''),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = ''),0)
ELSE ''
END AS BASE,
CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '1'),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '1'),0)
ELSE ''
END AS INDICADORES,
CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '2'),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '2'),0)
ELSE ''
END AS MECANICO,
CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '3'),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '3'),0)
ELSE ''
END AS FRETE,
CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '5'),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '5'),0)
ELSE ''
END AS DEVOLUCAO,
CASE
	WHEN SL1.L1_DOC <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERIE  AND A.E3_NUM = SL1.L1_DOC AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '8'),0)
	WHEN SL1.L1_DOCPED <> ''
THEN ISNULL((SELECT SUM(A.E3_BASE) FROM SE3010 A WHERE 1=1 AND A.D_E_L_E_T_ = '' AND A.E3_FILIAL = SUA.UA_FILIAL  AND A.E3_SERIE = SL1.L1_SERPED  AND A.E3_NUM = SL1.L1_DOCPED AND A.E3_VEND = SUA.UA_VEND AND A.E3_ZCODRT = '8'),0)
ELSE ''
END AS OUTROS,
CASE
	WHEN SL1.L1_DOC <> ''
THEN 
ISNULL((
SELECT 
SUM(DATEDIFF(day, B.L1_EMISNF ,C.E1_VENCREA))
FROM SE3010 A
LEFT JOIN SL1010 B ON B.D_E_L_E_T_ = '' AND B.L1_FILIAL = A.E3_FILIAL AND B.L1_SERIE = A.E3_SERIE AND B.L1_DOC = A.E3_NUM AND B.L1_VEND = A.E3_VEND
LEFT JOIN SE1010 C ON C.D_E_L_E_T_ = '' AND C.E1_FILIAL = A.E3_FILIAL AND C.E1_PREFIXO = A.E3_SERIE AND C.E1_NUM = A.E3_NUM AND C.E1_PARCELA = A.E3_PARCELA AND C.E1_VEND1 = A.E3_VEND AND C.E1_TIPO = A.E3_TIPO AND C.E1_CLIENTE = A.E3_CODCLI
WHERE 1=1 
AND A.D_E_L_E_T_ = '' 
AND A.E3_FILIAL = SL1.L1_FILIAL
AND A.E3_SERIE = SL1.L1_SERIE
AND A.E3_NUM = SL1.L1_DOC
AND A.E3_VEND = SL1.L1_VEND
),0) 
	WHEN SL1.L1_DOCPED <> ''
THEN 
ISNULL((
SELECT 
SUM(DATEDIFF(day, B.L1_EMISNF ,C.E1_VENCREA))
FROM SE3010 A
LEFT JOIN SL1010 B ON B.D_E_L_E_T_ = '' AND B.L1_FILIAL = A.E3_FILIAL AND B.L1_SERPED = A.E3_SERIE AND B.L1_DOCPED = A.E3_NUM AND B.L1_VEND = A.E3_VEND
LEFT JOIN SE1010 C ON C.D_E_L_E_T_ = '' AND C.E1_FILIAL = A.E3_FILIAL AND C.E1_PREFIXO = A.E3_SERIE AND C.E1_NUM = A.E3_NUM AND C.E1_PARCELA = A.E3_PARCELA AND C.E1_VEND1 = A.E3_VEND AND C.E1_TIPO = A.E3_TIPO AND C.E1_CLIENTE = A.E3_CODCLI
WHERE 1=1 
AND A.D_E_L_E_T_ = '' 
AND A.E3_FILIAL = SL1.L1_FILIAL
AND A.E3_SERIE = SL1.L1_SERPED
AND A.E3_NUM = SL1.L1_DOCPED
AND A.E3_VEND = SL1.L1_VEND
),0)
ELSE ''
END AS DIAS

FROM SUA010 SUA
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
LEFT JOIN SL2010 SL2 ON SL2.D_E_L_E_T_ = '' AND SL2.L2_FILIAL = SL1.L1_FILIAL AND SL2.L2_NUM = SL1.L1_NUM 
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SL2.L2_PRODUTO
WHERE 1=1
AND SUA.D_E_L_E_T_ = '' 
AND SL1.L1_EMISNF <> ''
AND YEAR(SL1.L1_EMISNF) = 2021
AND month(SL1.L1_EMISNF) = 06
--AND SUA.UA_NUM = '035862'
--AND SUA.UA_NUM = '032407'
--AND SUA.UA_NUM = '036336'
--AND SUA.UA_NUM = '008808'
--AND SUA.UA_NUM = '036183'
AND SUA.UA_VEND = '000099'
GROUP BY
SUA.UA_FILIAL,
SUA.UA_NUM,	
SUA.UA_VEND,
SL1.L1_VEND,
SL1.L1_FILIAL,
SL1.L1_NUM,
SL1.L1_EMISNF,
SL1.L1_SERIE,
SL1.L1_SERPED,
SL1.L1_DOC,
SL1.L1_DOCPED,
SB1.B1_COD,
SB1.B1_CUSTD