
SELECT 
H.EMPRESA			AS COD_EMPRESA,
J.NOME				AS EMPRESA,
H.DOCUMENTODIGITADO	AS DOCUMENTO,
D.CODIGO			AS CODIGO_CC,
D.NOME				AS CENTRO_CUSTO,
I.CODIGOREDUZIDO	AS CODIGO_PROJETO,
I.NOME				AS PROJETO,
H.DATACONFIRMACAO	AS DT_EMISSAO,
G.DATAVENCIMENTO	AS DT_VENCIMENTO,
G.DATALIQUIDACAO	AS DT_LIQUIDACAO,
A.VALOR				AS VALOR_NOMINAL,
G.VALOR				AS VALOR,
G.VALORESBAIXADOS	AS BAIXADO,
G.VALOR	- G.VALORESBAIXADOS	AS SALDO,
K.NOME				AS CLIENTE,
K.CGCCPF			AS CGC_CLIENTE,
CASE
	WHEN H.STATUS = 1 THEN 'CADASTRADA'
	WHEN H.STATUS = 1 THEN 'EMITIDA'
ELSE ''
END AS STATUS,
'---------------'
FROM FN_LANCAMENTOCC A
INNER  JOIN FN_LANCAMENTOS B ON B.HANDLE = A.LANCAMENTO
INNER JOIN TS_LANCAMENTOS C ON C.HANDLE = B.LANCAMENTOTESOURARIA
LEFT OUTER JOIN CT_CC D ON D.HANDLE = A.CENTROCUSTO
LEFT OUTER JOIN FN_CONTAS E ON E.HANDLE = B.CONTA
LEFT OUTER JOIN FN_MOVIMENTACOES F ON F.HANDLE = B.MOVIMENTACAO AND F.LANCAMENTOTESOURARIA = C.HANDLE
LEFT OUTER JOIN FN_PARCELAS G ON G.HANDLE = F.PARCELA
LEFT OUTER JOIN FN_DOCUMENTOS H ON H.HANDLE = G.DOCUMENTO
LEFT OUTER JOIN GN_PROJETOS I ON I.HANDLE = A.PROJETO
LEFT OUTER JOIN EMPRESAS J ON J.HANDLE = H.EMPRESA
LEFT OUTER JOIN GN_PESSOAS K ON K.HANDLE = H.PESSOA
WHERE 1=1
AND H.DATACONFIRMACAO >= '2023-05-15' AND H.DATACONFIRMACAO <= '2023-06-05'
AND A.CENTROCUSTO = 14
AND E.NIVELSUPERIOR = 25
AND H.EHCONTASPAGAR = 'N'
AND H.STATUS IN (1,2)
--AND H.DOCUMENTODIGITADO IN ('2023/10','2023/11','2023/12')



--SELECT * FROM GN_PESSOAS WHERE NOME LIKE '%MUNICIPIO DE PARIQUERA-ACU%'	


