

SELECT 
E.HANDLE			AS COD_USUARIO,
E.NOME				AS NOME,
E.NASCIMENTO		AS NASCIMENTO,
E.CGCCPF			AS CPF,
E.NOME				AS RESPFINAN,
E.CGCCPF			AS CPF_RESPFINAN,
E.LOGRADOURO		AS ENDERECO,
E.NUMERO			AS NUMERO,
E.COMPLEMENTO		AS COMPLEMENTO,
E.BAIRRO			AS BAIRRO,
G.NOME				AS CIDADE,
H.SIGLA				AS ESTADO,
E.CEP				AS CEP,
ISNULL((SELECT TOP 1CONCAT('(',F1.DDD,') ', F1.TELEFONE) FROM GN_PESSOATELEFONES F1 WHERE F1.PESSOA = E.HANDLE), '') AS FONE,
''					AS FONE1,
''					AS FONE2,
''					AS CELULAR,
D.HANDLE			AS DUPLICATA,
D.DATAVENCIMENTO 	AS DT_VENCIMENTO,
(D.VALOR - D.VALORESBAIXADOS) AS VALOR,
E.EMAIL				 AS EMAIL,
C1.DOCUMENTODIGITADO AS DOCUMENTO
--UPDATE FN_PARCELAS SET FORMALIQUIDACAO = 49
FROM CN_CONTRATOS A
LEFT JOIN K_CN_CONTRATOFECHAMENTOCONTRAT B ON B.CONTRATO = A.HANDLE
LEFT JOIN FN_DOCUMENTOS C ON C.HANDLE = B.DOCUMENTOGERADO
LEFT JOIN FN_DOCUMENTOS C1 ON C1.HANDLE = C.DOCUMENTOORIGEM
LEFT JOIN FN_PARCELAS D ON D.DOCUMENTO = C1.HANDLE
LEFT JOIN GN_PESSOAS E ON E.HANDLE = A.PESSOA 
LEFT JOIN CN_TIPOSCONTRATOS F ON F.HANDLE = A.TIPOCONTRATO
LEFT JOIN MUNICIPIOS G ON G.HANDLE = E.MUNICIPIO
LEFT JOIN ESTADOS H ON H.HANDLE = E.ESTADO
WHERE 1=1
/* SOMENTE RECEBER */		AND C1.EHCONTASPAGAR = 'N'
/* VENCIMENTO < -30 DIAS */	AND D.DATAVENCIMENTO <= DATEADD(day, -30, getdate())
/* SOMENTE DOC ABERTOS */  	AND (D.VALOR - D.VALORESBAIXADOS) > 0
/* SOMENTE DOC ABERTOS */  	AND D.EMABERTO = 'S'
/* SOMENTE PUBLICOS	*/		AND F.PREFIXO NOT IN ('PU','PUBL')
/* REMOVER DUPL ENVIADOS */ AND D.FORMALIQUIDACAO <> 49
/* FILTRAR EMPRESA */		AND C1.EMPRESA = 1
/* 1,3 - PF | 2,4 - PJ */	AND E.TIPO IN (1,3)
--AND E.HANDLE = 6443





