
SELECT 
	C.HANDLE 		AS COD_USUARIO,
	C.NOME 			AS NOME,
	C.NASCIMENTO 	AS NASCIMENTO,
	C.CGCCPF		AS CPF,
	C.NOME			AS RESPFINAN,
	C.CGCCPF		AS CPF_RESPFINAN,
	C.LOGRADOURO	AS ENDERECO,
	C.NUMERO		AS NUMERO,
	C.COMPLEMENTO	AS COMPLEMENTO,
	C.BAIRRO		AS BAIRRO,
	F.NOME			AS CIDADE,
	G.NOME			AS ESTADO,
	C.CEP			AS CEP,
	ISNULL((SELECT TOP 1CONCAT('(',F1.DDD,') ', F1.TELEFONE) FROM GN_PESSOATELEFONES F1 WHERE F1.PESSOA = C.HANDLE), '') AS FONE,
	''				AS FONE1,
	''				AS FONE2,
	''				AS CELULAR,
	A.HANDLE		AS DUPLICATA,
	A.VCTOPRORROGADO			AS DT_VENCIMENTO,
	(A.VALOR - A.VALORESBAIXADOS) AS VALOR,
	C.EMAIL						AS EMAIL,
	B.DOCUMENTODIGITADO			AS DOCUMENTO
--UPDATE FN_PARCELAS SET FORMALIQUIDACAO = 49
FROM FN_PARCELAS A
LEFT JOIN FN_DOCUMENTOS B ON B.HANDLE = A.DOCUMENTO
LEFT JOIN GN_PESSOAS C ON C.HANDLE = B.PESSOA
LEFT JOIN FN_LANCAMENTOS D ON D.PARCELA = A.HANDLE
LEFT JOIN FN_LANCAMENTOCC E ON E.LANCAMENTO = D.HANDLE
LEFT JOIN MUNICIPIOS F ON F.HANDLE = C.MUNICIPIO
LEFT JOIN ESTADOS G ON G.HANDLE = C.ESTADO
WHERE 1=1
/* VENCIMENTO < -30 DIAS */	AND A.VCTOPRORROGADO <= DATEADD(day, -30, getdate())
/* VENCTO APARTIR DE 2020*/	AND YEAR(A.VCTOPRORROGADO) >= 2020
--/* CLIENTES COM CONTRATO */ AND ISNULL((SELECT TOP 1 HANDLE FROM CN_CONTRATOS C1 WHERE C1.PESSOA = C.HANDLE), 0) > 0
/* SALDO > 0*/				AND (A.VALOR -  A.VALORESBAIXADOS) > 0
/* SOMENTE ABERTOS */		AND A.EMABERTO = 'S'
--/* SOMENTE CRE */			AND B.EHCONTASPAGAR = 'N'
/* SOMENTE CRE 2.0*/		AND B.ENTRADASAIDA = 'S'
/* REMOVE PUBLICOS */		AND E.CENTROCUSTO <> 14
/* REMOVER TMK */			AND A.FORMALIQUIDACAO NOT IN (49,51)
/* REMOVER BERNANDO */		AND C.HANDLE <> 55
/* EMPRESA */				AND B.EMPRESA = 1
/* PF - 1,3 | PJ - 2,4 */  	AND C.TIPO IN (1,3)
GROUP BY 
	C.HANDLE 		,
	C.NOME 			,
	C.NASCIMENTO 	,
	C.CGCCPF		,
	C.NOME			,
	C.CGCCPF		,
	C.LOGRADOURO	,
	C.NUMERO		,
	C.COMPLEMENTO	,
	C.BAIRRO		,
	F.NOME			,
	G.NOME			,
	C.CEP			,
	A.HANDLE		,
	A.VCTOPRORROGADO,			
	A.VALOR         ,
	A.VALORESBAIXADOS,
	C.EMAIL			,		
	B.DOCUMENTODIGITADO		
