
SELECT 
SD1.D1_FILIAL		AS FILIAL,
SD1.D1_SERIE		AS SERIE,
SD1.D1_DOC			AS DOC,
SD1.D1_COD			AS CODPROD,
SB1.B1_ZDESRDZ		AS PRODUTO,
SB1.B1_ZAPRES1		AS COD_APRE,
SB1.B1_UM			AS UM,
SB1.B1_GRUPO		AS GRUOPO_PROD,
SB1.B1_ZLIBREG		AS REGI_PROD,
SD1.D1_ITEM			AS ITEM,
SD1.D1_QUANT		AS QTD,
SD1.D1_VUNIT		AS VLR_UNI,
SD1.D1_TOTAL		AS VLR_ITEM,
SB1.B1_CUSTD		AS CUSTO_B1,
0					AS CUSTO_D3,
SD1.D1_LOCAL		AS COD_ARMZ,
NNR.NNR_DESCRI		AS ARMAZEM,
SD1.D1_DTDIGIT		AS DT_MOV,
SD1.D1_TES			AS TES,
SF4.F4_TEXTO		AS DESC_TES,	
SD1.D1_CF			AS CFOP,
SF4.F4_DUPLIC		AS FIN_CUSTO,
SF4.F4_ESTOQUE		AS ESTOQUE,
SD1.D1_TIPO			AS TIPO_DOC,
CASE
	WHEN SD1.D1_TIPO = 'N'
THEN 'NORMAL'
	WHEN SD1.D1_TIPO = 'B'
THEN 'BENEFICIAMENTO'
	WHEN SD1.D1_TIPO = 'D'
THEN 'DEVOLUÇÃO'
ELSE ''
END AS DESC_TIPO,
SFT.FT_DTCANC		AS DT_CANCEL,
SFT.FT_OBSERV		AS OBS,
CASE
	WHEN SA1.A1_COD <> ''
THEN SA1.A1_COD
	WHEN SA2.A2_COD <> ''
THEN SA2.A2_COD
ELSE ''
END AS COD_CLIFOR,
CASE
	WHEN SA1.A1_NOME <> ''
THEN SA1.A1_NOME
	WHEN SA2.A2_NOME <> ''
THEN SA2.A2_NOME
ELSE ''
END AS CLIFOR,
MAX(SF1.F1_DTDIGIT)	AS MAXDT,
MAX(SF1.F1_HORA)	AS MAXHR,
'ENTRADA'			AS IDENT
FROM SD1010 SD1
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD1.D1_COD
LEFT JOIN SF1010 SF1 ON SF1.D_E_L_E_T_ = '' AND SF1.F1_FILIAL = SD1.D1_FILIAL AND SF1.F1_SERIE = SD1.D1_SERIE AND SF1.F1_DOC = SD1.D1_DOC AND SF1.F1_FORNECE = SD1.D1_FORNECE AND SF1.F1_LOJA = SD1.D1_LOJA
LEFT JOIN SFT010 SFT ON SFT.FT_FILIAL = SD1.D1_FILIAL AND SFT.FT_SERIE = SD1.D1_SERIE AND SFT.FT_NFISCAL = SD1.D1_DOC AND SFT.FT_CLIEFOR = SD1.D1_FORNECE AND SFT.FT_LOJA = SD1.D1_LOJA AND SD1.D1_COD = SFT.FT_PRODUTO AND SD1.D1_ITEM = SFT.FT_ITEM  
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SD1.D1_FORNECE AND SA1.A1_LOJA = SD1.D1_LOJA AND SD1.D1_TIPO = 'D'
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SD1.D1_FORNECE AND SA2.A2_LOJA = SD1.D1_LOJA AND SD1.D1_TIPO <> 'D'
LEFT JOIN SF4010 SF4 ON SF4.D_E_L_E_T_ = '' AND SF4.F4_CODIGO = SD1.D1_TES
LEFT JOIN NNR010 NNR ON NNR.D_E_L_E_T_ = '' AND NNR.NNR_CODIGO = SD1.D1_LOCAL
WHERE 1=1
AND SD1.D_E_L_E_T_ = ''
AND SD1.D1_TIPO IN ('D', 'N', 'B')
GROUP BY
SD1.D1_FILIAL,
SD1.D1_SERIE,
SD1.D1_DOC,
SD1.D1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SB1.B1_UM,
SB1.B1_GRUPO,
SB1.B1_ZLIBREG,
SD1.D1_ITEM,
SD1.D1_QUANT,
SD1.D1_VUNIT,
SD1.D1_TOTAL,
SB1.B1_CUSTD,
SD1.D1_LOCAL,
NNR.NNR_DESCRI,
SD1.D1_DTDIGIT,
SD1.D1_TES,	
SF4.F4_TEXTO,	 
SD1.D1_CF,		   
SF4.F4_DUPLIC,		
SF4.F4_ESTOQUE,	   
SD1.D1_TIPO,			
SFT.FT_DTCANC,	   
SFT.FT_OBSERV,
SA1.A1_COD,
SA2.A2_COD,
SA1.A1_NOME,
SA2.A2_NOME



