
SELECT 
SD3.D3_FILIAL	AS FILIAL,
''				AS SERIE,		
SD3.D3_DOC		AS DOC,
SD3.D3_COD		AS CODPROD,
SB1.B1_ZDESRDZ	AS PRODUTO,
SB1.B1_ZAPRES1	AS COD_APRE,
SB1.B1_UM		AS UM,
SB1.B1_GRUPO	AS GRUPO_PROD,
SB1.B1_ZLIBREG	AS REGI_PROD,
SD3.D3_ITEM		AS ITEM,
SD3.D3_QUANT	AS QTD,
 ''				AS VLR_UNI,	
 ''				AS VLR_ITEM,
SB1.B1_CUSTD	AS CUSTO_B1,
SD3.D3_CUSTO1 	AS CUSTO_D3,
SD3.D3_LOCAL	AS COD_ARMZ,
NNR.NNR_DESCRI	AS ARMAZEM,
SD3.D3_EMISSAO	AS DT_MOV,
SD3.D3_TM		AS TES,
CASE
	WHEN SD3.D3_TM = '499'
THEN 'ENTRADA MERC. ARMZ'
	WHEN SD3.D3_TM = '999'
THEN 'SAIDA MERC. ARMZ'
ELSE SF5.F5_TEXTO
END AS DESC_TES,
''			AS CFOP,
CASE
	WHEN SD3.D3_TM = '501'
THEN 'S'
ELSE 'N'
END AS FIN_CUSTO,
'S'			AS ESTOQUE,
'N'			AS TIPO_DOC,
'NORMAL'	AS DESC_TIPO,
''			AS DT_CANCEL,
''			AS OBS,
''			AS COD_CLIFOR,
''			AS CLIFOR,
''			AS MAXDT,
''			AS MAXHR,
'MOV. INTERNA' AS IDENT
FROM SD3010 SD3
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD3.D3_COD
LEFT JOIN NNR010 NNR ON NNR.NNR_CODIGO = SD3.D3_LOCAL
LEFT JOIN SF5010 SF5 ON SF5.D_E_L_E_T_ = '' AND SF5.F5_CODIGO = SD3.D3_TM
WHERE 1=1
AND SD3.D_E_L_E_T_ = ''

