SELECT 
A.BA3_IDBENN, 
A.BA3_XCARTE, 
A.BA3_EQUIPE,
B.BA1_NOMSOC
FROM BA3010 A
INNER JOIN BA1BKP B ON B.D_E_L_E_T_ = '' AND B.BA1_CONEMP = A.BA3_IDBENN
WHERE 1=1
AND A.D_E_L_E_T_ = '' 
AND A.BA3_EQUIPE = '' 
AND A.BA3_CODEMP IN ('0003','0006')


SELECT 
COUNT(*) 
FROM BA3010 WHERE BA3010.D_E_L_E_T_ = '' 
AND BA3010.BA3_EQUIPE <> '' 
AND BA3010.BA3_CODEMP IN ('0003','0006')


SELECT
E.BDF_FILIAL        AS FILIAL,
A.BQC_SUBCON        AS ID_CONTRATO,
A.BQC_DESCRI        AS EMPRESA,
SUM(D.BDK_VALOR)    AS VALOR_CONTRATO,
SUM(E.BDF_VALOR)    AS VALOR_LOTE,
SUM(D.BDK_VALOR) -  SUM(E.BDF_VALOR)  AS DIFERENCA
FROM BQC010 A
LEFT JOIN BA3010 B ON B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON AND B.D_E_L_E_T_ = ''
LEFT JOIN BA1010 C ON C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP AND C.D_E_L_E_T_ = ''
LEFT JOIN BDK010 D ON D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG AND D.D_E_L_E_T_ = ''
LEFT JOIN BDF010 E ON E.D_E_L_E_T_ = '' AND E.BDF_SUBCON = A.BQC_SUBCON AND E.BDF_VERSUB = A.BQC_VERCON
LEFT JOIN BDC010 F ON F.D_E_L_E_T_ = '' AND F.BDC_FILIAL = E.BDF_FILIAL AND F.BDC_NUMERO = E.BDF_NUMERO
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND E.BDF_ANOTIT = '2024'
AND E.BDF_MESTIT = '02'
--AND E.BDF_NUMERO = '00000326'
AND F.BDF_NUMERO = CONVERT(DATE, '2024-02-')
GROUP BY 
E.BDF_FILIAL,
A.BQC_SUBCON,   
A.BQC_DESCRI
HAVING  SUM(D.BDK_VALOR) -  SUM(E.BDF_VALOR) > 0



