SELECT 
'23361' 	AS PLANO,
A.HANDLE 	AS IDENTIFICACAO,
A.NOME		AS NOME,
LEFT(REPLACE(REPLACE(A.CPF, '.',''),'-',''),11) AS CPF,
0			AS LIMITE
FROM K_CN_CONTRATOBENEFICIARIOS A
LEFT JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
WHERE 1=1
AND A.STATUS = 1
AND B.STATUS = 2
AND B.EMPRESA = 5