
/*      TOTAL       */
SELECT
A.BQC_SUBCON                        AS ID_CONTRATO,
C.BA1_NOMUSR AS QTD_VIDAS,
D.BDK_MATRIC AS MATRICULA,
D.BDK_VALOR                    AS VALOR
FROM BQC010 A
LEFT JOIN BA3010 B ON B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON AND B.D_E_L_E_T_ = ''
LEFT JOIN BA1010 C ON C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP AND C.D_E_L_E_T_ = ''
LEFT JOIN BDK010 D ON D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG AND D.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND A.BQC_SUBCON = '001025439'
AND A.BQC_CODINT = ''
AND A.BQC_CODEMP = ''
AND A.BQC_CONEMP = ''
GROUP BY A.BQC_SUBCON


/*      TITULAR       */
SELECT
A.BQC_SUBCON                        AS ID_CONTRATO,
COUNT(CONCAT(C.BA1_MATRIC, C.BA1_TIPREG))  AS QTD_VIDAS,
SUM(D.BDK_VALOR)                    AS VALOR
FROM BQC010 A
LEFT JOIN BA3010 B ON B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON AND B.D_E_L_E_T_ = ''
LEFT JOIN BA1010 C ON C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP AND C.D_E_L_E_T_ = ''
LEFT JOIN BDK010 D ON D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG AND D.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND C.BA1_TIPUSU = 'T'
AND A.BQC_SUBCON = '001024569'
AND A.BQC_CODINT = ''
AND A.BQC_CODEMP = ''
AND A.BQC_CONEMP = ''
GROUP BY A.BQC_SUBCON


/*      DEPEDENTE       */
SELECT
A.BQC_SUBCON                        AS ID_CONTRATO,
COUNT(CONCAT(C.BA1_MATRIC, C.BA1_TIPREG))  AS QTD_VIDAS,
SUM(D.BDK_VALOR)                    AS VALOR
FROM BQC010 A
LEFT JOIN BA3010 B ON B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON AND B.D_E_L_E_T_ = ''
LEFT JOIN BA1010 C ON C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP AND C.D_E_L_E_T_ = ''
LEFT JOIN BDK010 D ON D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG AND D.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND C.BA1_TIPUSU = 'D'
AND A.BQC_SUBCON = '001024569'
AND A.BQC_CODINT = ''
AND A.BQC_CODEMP = ''
AND A.BQC_CONEMP = ''
GROUP BY A.BQC_SUBCON
