
DEFINE @1_FILIAL 	VARCHAR(4)
DEFINE @2_PV 		VARCHAR(4)
DEFINE @3_OPC 		VARCHAR(4)

DECLARE @1_FILIAL 	VARCHAR(4)
DECLARE @2_PV	    VARCHAR(6)
DECLARE @3_OPC		VARCHAR(4)

SET @1_FILIAL = $(@1_FILIAL)
SET @2_PV = $(@2_PV)
SET @3_OPC = $(@3_OPC)

/*---------------------UPDATE---------------------*/

IF @3_OPC = 'A'
BEGIN

SELECT 'ABERTURA DE PV'

UPDATE SC5010
SET C5_ORCRES = ''
WHERE C5_FILIAL = @1_FILIAL AND C5_NUM = @2_PV

SELECT 
C5_ORCRES, 
C5_ZORCRES, 
* 
FROM SC5010
WHERE 1=1
AND D_E_L_E_T_ = ''
AND C5_FILIAL = @1_FILIAL
AND C5_NUM = @2_PV

END

IF @3_OPC = 'F'
BEGIN

SELECT 'FECHAMENTO DE PV'

UPDATE SC5010
SET C5_ORCRES = C5_ZORCRES
WHERE C5_FILIAL = @1_FILIAL AND C5_NUM = @2_PV

SELECT 
C5_ORCRES, 
C5_ZORCRES, 
* 
FROM SC5010
WHERE 1=1
AND D_E_L_E_T_ = ''
AND C5_FILIAL = @1_FILIAL
AND C5_NUM = @2_PV

END

/*----------------------------------SELECT DE TESTE---------------------------------------*/

/*
SELECT 
C5_ORCRES, 
C5_ZORCRES, 
*
FROM SC5010
WHERE 1=1
AND D_E_L_E_T_ = ''
AND C5_FILIAL = '0101'
AND C5_NUM = '011619'
*/


