
DEFINE @filial  VARCHAR(4)
DEFINE @num_atm VARCHAR(6)
DEFINE @DT_ENT  VARCHAR(8)  

DECLARE @filial 	VARCHAR(4)
DECLARE @num_atm 	VARCHAR(6)	
DECLARE @DT_ENT 	VARCHAR(8)
DECLARE @DT_ENT_ANT VARCHAR(8) 

SET @filial 	=	$(@filial)	
SET @num_atm 	=	$(@num_atm)	   
SET @DT_ENT 	=	$(@DT_ENT)	
SET @DT_ENT_ANT =   ISNULL((SELECT UA_ZDTAENT FROM SUA010 WHERE D_E_L_E_T_ = '' AND UA_FILIAL = @filial AND UA_NUM = @num_atm),0)							   

UPDATE SUA010
SET UA_ZDTAENT = @DT_ENT
WHERE UA_FILIAL = @filial AND UA_NUM = @num_atm 

SELECT 
UA_FILIAL AS FILIAL,
UA_NUM AS ATENDIMENTO,
CONVERT(VARCHAR,CAST(UA_ZDTAENT AS DATETIME),103)  AS NOVA_DT,
CONVERT(VARCHAR,CAST(@DT_ENT_ANT AS DATETIME),103) AS ANTIGA_DT
FROM SUA010 WHERE
D_E_L_E_T_ = '' 
AND UA_FILIAL = @filial 
AND UA_NUM = @num_atm 
