

DEFINE @1_FILIAL VARCHAR(4)
DEFINE @2_ATM VARCHAR(6)

DECLARE @1_FILIAL VARCHAR(4)
DECLARE @2_ATM VARCHAR(6)
DECLARE @3_DT VARCHAR(8)
DECLARE @4_HR VARCHAR(5)

SET @1_FILIAL = $(@1_FILIAL)
SET @2_ATM = $(@2_ATM) 
SET @3_DT = CONVERT(VARCHAR, CAST(GETDATE() AS DATETIME),112)
SET @4_HR = SUBSTRING(CONVERT(VARCHAR, CAST(GETDATE() AS TIME)),1,5)


/*--------------LIBERAR DE 3 PARA 4--------------*/


UPDATE SUA010 SET
UA_OPER = '4',
UA_ZDTLBFT = @3_DT,
UA_ZHRLBFT = @4_HR
FROM SUA010 WHERE UA_FILIAL = @1_FILIAL AND UA_NUM = @2_ATM 


SELECT UA_OPER, UA_ZDTLBFT, UA_ZHRLBFT, UA_ZDTAENT, * FROM SUA010 WHERE UA_FILIAL = @1_FILIAL AND UA_NUM = @2_ATM 


/*--------------FECHAR DE 4 PARA 3--------------*/

/*
UPDATE SUA010 SET
UA_OPER = '3',
UA_ZDTLBFT = '',
UA_ZHRLBFT = ''
FROM SUA010 WHERE UA_FILIAL = @1_FILIAL AND UA_NUM = @2_ATM 
*/



/*-------------- TESTE ----------------*/

/*

SELECT UA_ZDTAENT, UA_ZIDPIPE, * FROM SUA010 WHERE UA_NUM = '034763'

SELECT @1_FILIAL, @2_ATM, @3_DT, @4_HR

*/
