

SELECT 
SUA.UA_FILIAL,
SUA.UA_NUM,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS EMISSAO,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT AS DATETIME),103) AS ENTREGA,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTALOG AS DATETIME),103) AS DTENTLOG,
SL2A.L2_SERIE,
SL2A.L2_DOC,
CONVERT(VARCHAR,CAST(SC6A.C6_ENTREG AS DATETIME),103) AS DT_DOC_C6_A,
SC6A.C6_SERIE,
SC6A.C6_NOTA,
CONVERT(VARCHAR,CAST(SC6B.C6_ENTREG AS DATETIME),103) AS DT_DOC_C6_B,
SC6B.C6_SERIE,
SC6B.C6_NOTA
FROM SUA010 SUA
/*ATENDIMENTO CABEÇARIO*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ =  '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM 		
/*ATENDIMENTO ITEMS*/  	 LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ =  '' AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/			 LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*FORNECEDOR*/			 LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/	   	     LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*ORC SL1 (PAI)*/		 LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ =  '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM
/*ORC SL2 PAI*/	         LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SUA.UA_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO
/*ORC SL2 FILHO*/		 LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO
/*PV SC6 (PAI)*/   		 LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2A.L2_FILIAL AND SC6A.C6_NUM = SL2A.L2_PEDRES AND SC6A.C6_ITEM = SL2A.L2_ITEM AND SC6A.C6_PRODUTO = SL2A.L2_PRODUTO
/*PV SC6 (FILHO)*/  	 LEFT JOIN SC6010 SC6B ON SC6B.D_E_L_E_T_ = '' AND SC6B.C6_FILIAL = SL2B.L2_FILIAL AND SC6B.C6_NUM = SL2B.L2_PEDRES AND SC6B.C6_ITEM = SL2B.L2_ITEM AND SC6B.C6_PRODUTO = SL2B.L2_PRODUTO
WHERE 1=1
/*----------------SUA - ATENDIMENTO----------------*/

AND SUA.D_E_L_E_T_ = ''	 -- SUA ATENDIMENTO
--AND SUA.UA_OPER   <> '3' -- SUA ATENDIMENTO
AND SUA.UA_NUMSL1 <> ''	 -- SUA ATENDIMENTO
--AND SUA.UA_OPER   <> '4' -- SUA ATENDIMENTO


/*----------FILTROS ATIVOS-------------*/

 
--  AND SL2A.L2_DOC <> ''	-- VENDA DIRETA
--  AND SC6A.C6_NOTA <> ''	-- NOTA NO C6 PAI
--.  AND SC6B.C6_NOTA <> ''	-- NOTA NO C6 PAI
  AND YEAR(SUA.UA_EMISSAO) IN(2020)
  AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
