
CREATE TABLE ZANOTTI_FRETE
(
	CIDADE		VARCHAR(50),
	CEP			VARCHAR(30),
	PESO		FLOAT,
	VLR_FRETE 	FLOAT,
	CODPROD		VARCHAR(30)	
)


DROP TABLE ZANOTTI_FRETE



	BULK 
INSERT ZANOTTI_FRETE
        FROM 'C:\TEMP\frete.csv'
            WITH
    (
                FIELDTERMINATOR = ';',
                ROWTERMINATOR = '\n'
    )
GO



SELECT * FROM ZANOTTI_FRETE WHERE CODPROD = 'LB016F' AND CIDADE = 'Alto Alegre'


SELECT B1_PESBRU, * FROM SB1010 WHERE D_E_L_E_T_ = '' AND B1_COD = 'EQ800A'