CREATE
PROCEDURE CREAT_TABLE_SALDO_ESTOQUE AS


DECLARE @SQL VARCHAR(MAX)


SET @SQL = '

CREATE TABLE #AUX
    (
     AUX_CODPROD VARCHAR(15),
   	 AUX_PRODUTO VARCHAR(70),
	 AUX_UND	 VARCHAR(2),
	 AUX_CUSTPROD FLOAT,
	 AUX_CODFOR VARCHAR(6),
	 AUX_LOJFOR VARCHAR(2),
	 AUX_GRUPPROD VARCHAR(4),
     AUX_CODLIN VARCHAR(2),
     AUX_CODFAM VARCHAR(6),
   	 AUX_DATSLD VARCHAR(6),
	 AUX_SALDO FLOAT,
	 AUX_CUSTO FLOAT,
	)
'

EXEC(@SQL)

GO