   
DECLARE @TESTE FLOAT

 SET @TESTE = 
 
ISNULL(( 
SELECT SQL.CUSTO  FROM (
SELECT TOP 1 MAX(TAB1.ZZ2_DATA)AS  DATA, TAB2.ZZ3_CODPRD AS PRODUTO, TAB2.ZZ3_CUSTD AS CUSTO
FROM ZZ2010 TAB1, ZZ3010 TAB2
WHERE TAB1.D_E_L_E_T_ = ''
AND TAB2.D_E_L_E_T_ = ''
AND TAB2.ZZ3_COD = TAB1.ZZ2_CODIGO
AND TAB2.ZZ3_CUSTD <> 0
--AND YEAR(TAB1.ZZ2_DATA) = 2029
--AND MONTH(TAB1.ZZ2_DATA) = 01
AND TAB2.ZZ3_CODPRD = 'CFTC001F'
GROUP BY TAB1.ZZ2_DATA, TAB2.ZZ3_CODPRD, TAB2.ZZ3_CUSTD 
ORDER BY TAB1.ZZ2_DATA DESC)AS SQL
),0)    
 
SELECT @TESTE AS ULTIMO_CUSTO 
    
    
    

 
 
 
 
 
 
 
   
    
    
    