

SELECT * FROM #AUX WHERE AUX_CODPROD = 'LB012F'
ORDER BY AUX_DATSLD



SELECT A.ZZ3_CODPRD,A.ZZ3_DESCPR,A.ZZ3_COD,B.ZZ2_DATA AS DATMAX,A.ZZ3_CUSTD
FROM ZZ3010 AS A, ZZ2010 AS B
WHERE A.D_E_L_E_T_ = '' AND B.D_E_L_E_T_ = ''
AND A.ZZ3_COD = B.ZZ2_CODIGO
AND A.ZZ3_CUSTD <> 0
AND YEAR(B.ZZ2_DATA) = 2019
AND MONTH(B.ZZ2_DATA) = 01
--AND A.ZZ3_CODPRD = 'CFTC001F'
GROUP BY A.ZZ3_CODPRD,A.ZZ3_DESCPR,A.ZZ3_COD,A.ZZ3_CUSTD,B.ZZ2_DATA
ORDER BY 1,4

