

DECLARE @cDatIni VARCHAR(8)
DECLARE @cDatFim VARCHAR(8)
DECLARE @ANOINI INT;
DECLARE @ANOFIM INT;
DECLARE @MESINI INT;
DECLARE @MESFIM INT;
SET @ANOINI = 2020
SET @ANOFIM = 2020
SET @MESINI = 01
SET @MESFIM = 01

 --SET @DTSLD = 		ISNULL(( SELECT CONCAT(@ANOINI,@MESINI) AS SALDO  ),0)
 SET @cDatIni = 	ISNULL(( SELECT CONCAT(@ANOINI, '0', @MESINI ,'01') AS SALDO  ),0) 
 SET @cDatFim = 	ISNULL(( SELECT CONCAT(@ANOINI, '0', @MESFIM, '31') AS SALDO  ),0) 



SELECT *,
(SELECT_PRINCIPAL.SALDO_FINAL * SELECT_PRINCIPAL.CUSTO_PROD) AS CUSTO_FINAL
FROM(
SELECT 
SALDO.COD_PROD,
SALDO.PRODUTO,
SALDO.UND,
SALDO.CUSTO_PROD,
SALDO.COD_FOR,
SALDO.LOJA_FOR,
SALDO.GRUPO_PROD,
SALDO.COD_LINHA,
SALDO.COD_FAM,
--SALDO.SLD_INI_SB9,
--SALDO.QTD_ENT_SD1,
--SALDO.QTD_SAI_SD2,
--SALDO.QTD_ENT_SD3,
--SALDO.QTD_SAI_SD3,
SALDO.SLD_INI_SB9 + ( SALDO.QTD_ENT_SD1 + SALDO.QTD_ENT_SD3 ) - ( SALDO.QTD_SAI_SD2 + SALDO.QTD_SAI_SD3 ) AS SALDO_FINAL
FROM (
SELECT 	A.B1_COD   	  AS COD_PROD,
		A.B1_DESC  	  AS PRODUTO,
		A.B1_UM    	  AS UND,
		A.B1_CUSTD 	  AS CUSTO_PROD,
		A.B1_PROC  	  AS COD_FOR,
		A.B1_LOJPROC  AS LOJA_FOR,
		A.B1_GRUPO    AS GRUPO_PROD,
		A.B1_ZCODLIN  AS COD_LINHA,
		A.B1_ZCODFAM  AS COD_FAM,
		
		ISNULL(( SELECT SUM(B9_QINI)  FROM SB9010 WHERE D_E_L_E_T_ = '' AND B9_COD = A.B1_COD AND YEAR(B9_DATA) = 2017),0) AS SLD_INI_SB9,
		ISNULL(( SELECT SUM(D1_QUANT) FROM SD1010 AS SD1, SF4010 AS SF4 WHERE SD1.D_E_L_E_T_ = '' AND SF4.D_E_L_E_T_ = '' AND SD1.D1_COD = A.B1_COD AND SD1.D1_DTDIGIT BETWEEN @cDatIni AND @cDatFim AND SD1.D1_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_ENT_SD1,
		ISNULL(( SELECT SUM(D2_QUANT) FROM SD2010 AS SD2, SF4010 AS SF4 WHERE SD2.D_E_L_E_T_ = '' AND SF4.D_E_L_E_T_ = '' AND SD2.D2_COD = A.B1_COD AND SD2.D2_EMISSAO BETWEEN @cDatIni AND @cDatFim AND SD2.D2_TES = SF4.F4_CODIGO AND SF4.F4_ESTOQUE = 'S'),0) AS QTD_SAI_SD2,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010  WHERE D_E_L_E_T_ = '' AND D3_COD = A.B1_COD AND D3_TM <= '499' AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_ENT_SD3,
		ISNULL(( SELECT SUM(D3_QUANT) FROM SD3010  WHERE D_E_L_E_T_ = '' AND D3_COD = A.B1_COD AND D3_TM >= '500' AND D3_EMISSAO BETWEEN @cDatIni AND @cDatFim),0) AS QTD_SAI_SD3	
FROM SB1010 A
LEFT JOIN SD1010 B ON A.B1_COD = B.D1_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD2010 C ON A.B1_COD = C.D2_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SD3010 D ON A.B1_COD = D.D3_COD AND D.D_E_L_E_T_ = ''
LEFT JOIN SB9010 E ON A.B1_COD = E.B9_COD AND E.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
--AND A.B1_GRUPO = 'MPCH'
AND A.B1_COD = 'LB012F'
GROUP BY A.B1_COD, A.B1_DESC, A.B1_UM, A.B1_CUSTD, A.B1_PROC, A.B1_LOJPROC, A.B1_GRUPO, A.B1_ZCODLIN, A.B1_ZCODFAM 
) AS SALDO
) AS SELECT_PRINCIPAL





SELECT 
A.B1_COD,
A.B1_DESC,
A.B1_UM,
A.B1_CUSTD,
A.B1_PROC ,
A.B1_LOJPROC ,
A.B1_GRUPO ,
A.B1_ZCODLIN ,
A.B1_ZCODFAM 
FROM SB1010 A
	







