

SELECT 
SUA.UA_FILIAL	AS FILIAL,
SUA.UA_NUM		AS NUM,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS EMISSAO,
SA1.A1_COD		AS COD_CLI,
SA1.A1_NOME 	AS CLIENTE,
SA1.A1_NREDUZ	AS CLIENTE_REDU,		
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SUBSTRING(SU5.U5_CONTAT,1,15) AS CONTATO,
SU5.U5_CODCONT, 
SU5.U5_DDD, 
SU5.U5_FONE, 
SU5.U5_CELULAR,
SUA.UA_ZPRZENT,
CASE
	WHEN SUA.UA_ZDTAENT = 1900
THEN ''
	WHEN SUA.UA_ZDTAENT <> ''
THEN CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT  AS DATETIME),103) 
ELSE ''
END AS DT_ENTREGA,
SUA.UA_VLRLIQ 	AS VLR_TOTAL_ATM,
SUA.UA_OPER		AS OPER_ATM,
SUA.UA_NUMSL1	AS NUMSL1_ATM,
SUA.UA_STATUS	AS STATUS,
SUA.UA_CANC		AS CANCEL,
SA3.A3_COD		AS COD_VEND,
SA3.A3_NOME		AS VENDEDOR,
SA3.A3_NREDUZ	AS VEND_REDU,
CASE 
	WHEN YEAR(SL1.L1_EMISNF) = 1900
THEN ''
	WHEN SL1.L1_EMISNF <> ''
THEN CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103)
ELSE ''
END AS EMISSAO_NF_L1,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CASE
	WHEN 
		SUA.UA_OPER = '3'
	AND	SUA.UA_STATUS <> 'CAN'
	AND SUA.UA_CANC = ''
THEN 'ATENDIMENTO ABERTO'
	WHEN 
		SUA.UA_OPER = '4'
	AND	SUA.UA_STATUS <> 'CAN'
	AND SUA.UA_CANC = ''
THEN 'ATENDIMENTO LIB. P/ FAT.'
	WHEN
	   	SUA.UA_OPER = '2'
	AND SUA.UA_NUMSL1 <> ''
	AND SL1.L1_EMISNF = ''
	AND	SUA.UA_STATUS <> 'CAN'
	AND SUA.UA_CANC = ''
THEN 'ATENDIMENTO AGUARDANDO FAT.'
	WHEN 
		SUA.UA_OPER IN ('1','2')
	AND SUA.UA_NUMSL1 <> ''
	AND SL1.L1_EMISNF <> ''
	AND	SUA.UA_STATUS <> 'CAN'
	AND SUA.UA_CANC = ''
THEN 'ATENDIMENTO FATURADO'
	WHEN 
		SUA.UA_STATUS = 'CAN'
	AND SUA.UA_CANC = 'S'
THEN 'ATENDIMENTO CANCELADO' 
ELSE ''
END AS SITUACAO
FROM SUA010 SUA
LEFT JOIN SUB010 SUB ON SUB.D_E_L_E_T_ = '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SUB.UB_PRODUTO
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA 
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SU5010 SU5 ON SU5.D_E_L_E_T_ = '' AND SU5.U5_CODCONT = SUA.UA_CODCONT 
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND YEAR(SUA.UA_EMISSAO) = 2020
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
AND SA3.A3_ZSITVND IN ('1','2')
--AND SUA.UA_FILIAL = '0101' AND SUA.UA_NUM = '023633'
GROUP BY 
SUA.UA_FILIAL,
SUA.UA_NUM,
SUA.UA_EMISSAO,
SA1.A1_COD,		
SA1.A1_NOME, 	
SA1.A1_NREDUZ,			
SA1.A1_MUN,
SA1.A1_EST,
SU5.U5_CONTAT,
SU5.U5_CODCONT, 
SU5.U5_DDD, 
SU5.U5_FONE, 
SU5.U5_CELULAR,
SUA.UA_ZPRZENT,
SUA.UA_ZDTAENT,
SUA.UA_VLRLIQ, 	
SUA.UA_OPER,	   
SUA.UA_NUMSL1,	
SUA.UA_STATUS,	
SUA.UA_CANC,		
SA3.A3_COD,		
SA3.A3_NOME,		
SA3.A3_NREDUZ,	
SL1.L1_EMISNF

