
CREATE PROCEDURE CUBOVEND AS


/*------------------------------DROP DA TABELA------------------------------------*/ 


DROP TABLE Z2CUBOVEND


/*------------------------------CREATE TABLE------------------------------------*/ 

CREATE TABLE Z2CUBOVEND
    (
	Z2_NUM_ATM			VARCHAR(6),
	Z2_FILIAL_ATM		VARCHAR(4),
	Z2_DT_EMI_ATM		VARCHAR(30),
	Z2_CODPROD			VARCHAR(15),
	Z2_PROD_TROCADO		VARCHAR(15),
	Z2_PRODUTO			VARCHAR(70),
	Z2_PROD_DESC_REDU	VARCHAR(40),
	Z2_COD_APRE			VARCHAR(18),
	Z2_QTD				FLOAT,
	Z2_UND				VARCHAR(2),
	Z2_COD_CLI			VARCHAR(6),
	Z2_NOME_CLI			VARCHAR(70),
	Z2_NOME_CLI_REDU	VARCHAR(20),
	Z2_CIDADE_UF		VARCHAR(63),
	Z2_COD_VEND			VARCHAR(6),
	Z2_VENDEDOR			VARCHAR(40),
	Z2_COD_FOR			VARCHAR(6),
	Z2_FORNECEDOR		VARCHAR(40),
	Z2_NOME_FOR_REDU	VARCHAR(20),
	Z2_PRZ_FOR_DIAS		FLOAT,
	Z2_VLR_TOTAL_ATM	FLOAT,	
	Z2_CSTREP_L2		FLOAT,					
	Z2_CUSTD_B1			FLOAT,	
	Z2_OPER_ATM			VARCHAR(1),   
	Z2_NUMSL1_ATM		VARCHAR(6),
	Z2_STATUS_ATM		VARCHAR(3),
	Z2_CANCEL_ATM		VARCHAR(1),
	Z2_DATA_FAT			VARCHAR(30),
	Z2_DOC700			VARCHAR(9),
	Z2_SER700			VARCHAR(3),
	Z2_NUM_RES_MANU		VARCHAR(6),
	Z2_FILIAL_PAI		VARCHAR(4),
	Z2_NUM_ORC_PAI		VARCHAR(6),
	Z2_SERIE_PAI		VARCHAR(3),
	Z2_NOTA_PAI			VARCHAR(9),
	Z2_FILIAL_FILHO		VARCHAR(4),
	Z2_NUM_ORC_FILHO 	VARCHAR(6),
	Z2_SERIE_FILHO		VARCHAR(3),
	Z2_NOTA_FILHO		VARCHAR(9),
	Z2_ORCRES_DO_FILHO	VARCHAR(6),
	Z2_FILIAL_SC		VARCHAR(4),
	Z2_NUM_SC			VARCHAR(6),
	Z2_DT_EMI_SC		VARCHAR(30),
	Z2_FILIAL_PC		VARCHAR(4),		
	Z2_NUM_PC			VARCHAR(6),
	Z2_DT_EMI_PC		VARCHAR(30),
	Z2_FILIAL_PV		VARCHAR(4),
	Z2_NUM_PV			VARCHAR(6),
	Z2_DT_DOCSAI		VARCHAR(30),
	Z2_SERIE_C6			VARCHAR(3),
	Z2_NOTA_C6			VARCHAR(9),
	Z2_FILIAL_C6_TROCA	VARCHAR(4),
	Z2_NUM_C6_TROCA		VARCHAR(6),	
	Z2_DT_DOCSAI_TROCA	VARCHAR(30),
	Z2_SERIE_C6_TROCA  	VARCHAR(3),
	Z2_NOTA_C6_TROCA	VARCHAR(9),
	Z2_DT_NOTA_ENTRADA	VARCHAR(30),
	Z2_SERIE_ENTRADA	VARCHAR(3),
	Z2_NOTA_ENTRADA    	VARCHAR(9),
	Z2_PRZ_ENT_FOR		VARCHAR(30),
	Z2_DT_HJ			VARCHAR(30),
	Z2_DT_ENT_CLI      	VARCHAR(30),
	--ESTAGIO				VARCHAR(300),
	--SITUACAO			VARCHAR(300),
	--SITUACAO_ATM        VARCHAR(300),
    D_E_L_E_T_ 			VARCHAR(1),
    R_E_C_N_O_ 			INT IDENTITY(1,1),
	)
 
/*------------------------------INSERT TABLE------------------------------------*/ 
	
INSERT INTO Z2CUBOVEND(
	Z2_NUM_ATM,			
	Z2_FILIAL_ATM,		
	Z2_DT_EMI_ATM,		
	Z2_CODPROD,			
	Z2_PROD_TROCADO,		
	Z2_PRODUTO,	
	Z2_PROD_DESC_REDU,	
	Z2_COD_APRE,
	Z2_QTD,	   
	Z2_UND,			
	Z2_COD_CLI,			
	Z2_NOME_CLI,			
	Z2_NOME_CLI_REDU,   
	Z2_CIDADE_UF,		
	Z2_COD_VEND,	   
	Z2_VENDEDOR,		
	Z2_COD_FOR,		
	Z2_FORNECEDOR,		
	Z2_NOME_FOR_REDU,	
	Z2_PRZ_FOR_DIAS,
	Z2_VLR_TOTAL_ATM, 
	Z2_CSTREP_L2,	   					
	Z2_CUSTD_B1,			
	Z2_OPER_ATM,			
	Z2_NUMSL1_ATM,
	Z2_STATUS_ATM,	   
	Z2_CANCEL_ATM,
	Z2_DATA_FAT,			
	Z2_DOC700,		   
	Z2_SER700,	 
	Z2_NUM_RES_MANU,		
	Z2_FILIAL_PAI,		
	Z2_NUM_ORC_PAI,		
	Z2_SERIE_PAI,		
	Z2_NOTA_PAI,		
	Z2_FILIAL_FILHO,	
	Z2_NUM_ORC_FILHO,   
	Z2_SERIE_FILHO,		
	Z2_NOTA_FILHO,		
	Z2_ORCRES_DO_FILHO,	
	Z2_FILIAL_SC,		
	Z2_NUM_SC,	 
	Z2_DT_EMI_SC,		
	Z2_FILIAL_PC,			
	Z2_NUM_PC,
	Z2_DT_EMI_PC,		
	Z2_FILIAL_PV,		
	Z2_NUM_PV,			
	Z2_DT_DOCSAI,	   
	Z2_SERIE_C6,		   
	Z2_NOTA_C6,			
	Z2_FILIAL_C6_TROCA,	
	Z2_NUM_C6_TROCA,		
	Z2_DT_DOCSAI_TROCA,	
	Z2_SERIE_C6_TROCA,  	
	Z2_NOTA_C6_TROCA,	
	Z2_DT_NOTA_ENTRADA,	
	Z2_SERIE_ENTRADA,	
	Z2_NOTA_ENTRADA,    	
	Z2_PRZ_ENT_FOR,		
	Z2_DT_HJ,			
	Z2_DT_ENT_CLI     
	--ESTAGIO,			   
	--SITUACAO,			
	--SITUACAO_ATM
) 


SELECT
SUA.UA_NUM 			  			AS NUM_ATM,
SUA.UA_FILIAL 		  			AS FILIAL_ATM,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS DT_EMI_ATM,
SUB.UB_PRODUTO 		  			AS CODPROD,
CASE
	WHEN SC6C.C6_PRODUTO = SC6D.C6_PRODUTO
THEN SC6C.C6_PRODUTO
	WHEN SC6C.C6_PRODUTO IS NULL
THEN SC6D.C6_PRODUTO
	WHEN SC6D.C6_PRODUTO IS NULL
THEN SC6C.C6_PRODUTO
ELSE ''
END AS PROD_TROCADO,
SB1.B1_DESC 			  	   	AS PRODUTO,
SB1.B1_ZDESRDZ					AS PROD_DESC_REDU,
SB1.B1_ZAPRES1					AS COD_APRE, 
SUB.UB_QUANT 			  	   	AS QTD,
SB1.B1_UM					   	AS UND,
SUA.UA_CLIENTE		  			AS COD_CLI,
SA1.A1_NOME 			  	   	AS NOME_CLI,
SA1.A1_NREDUZ					AS NOME_CLI_REDU,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SA3.A3_COD 		      			AS COD_VEND,
SA3.A3_NOME 			  		AS VENDEDOR,
SA2.A2_COD						AS COD_FOR,
SA2.A2_NOME						AS FORNECEDOR,
SA2.A2_NREDUZ					AS NOME_FOR_REDU,
SB1.B1_PE						AS PRZ_FOR_DIAS,
SUA.UA_VLRLIQ					AS VLR_TOTAL_ATM,
SL2A.L2_ZCSTREP					AS CSTREP,
SB1.B1_CUSTD					AS CSTSTD,
SUA.UA_OPER						AS OPER_ATM,
SUA.UA_NUMSL1					AS NUMSL1_ATM, 
SUA.UA_STATUS					AS STATUS_ATM,
SUA.UA_CANC						AS CANCEL_ATM,
CASE
	WHEN YEAR(SL1.L1_EMISNF) = 1900
THEN ''
	WHEN SL1.L1_EMISNF <> ''
THEN CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103)
ELSE ''
END AS DATA_FAT,

SL1.L1_DOCPED				   	AS DOC700,
SL1.L1_SERPED				   	AS SER700,
SC0.C0_NUM						AS NUM_RESERV_MANU,
SL2A.L2_FILIAL					AS FILIAL_PAI,
SL2A.L2_NUM			  			AS NUM_ORC_PAI,
SL2A.L2_SERIE					AS SERIE_PAI,
SL2A.L2_DOC						AS NOTA_PAI	,
SL2B.L2_FILIAL					AS FILIAL_FILHO,
SL2B.L2_NUM			  			AS NUM_ORC_FILHO,
SL2B.L2_SERIE					AS SERIE_FILHO,
SL2B.L2_DOC						AS NOTA_FILHO,
SL2B.L2_ORCRES					AS ORCRES_DO_FILHO,
CASE
	WHEN SC1A.C1_FILIAL = SC1B.C1_FILIAL
THEN SC1A.C1_FILIAL
	WHEN SC1A.C1_FILIAL IS NULL
THEN SC1B.C1_FILIAL
	WHEN SC1B.C1_FILIAL IS NULL
THEN SC1A.C1_FILIAL
	ELSE ''
END AS FILIAL_SC,
CASE
	WHEN SC1A.C1_NUM = SC1B.C1_NUM
THEN SC1A.C1_NUM
	WHEN SC1A.C1_NUM IS NULL
THEN SC1B.C1_NUM
	WHEN SC1B.C1_NUM IS NULL
THEN SC1A.C1_NUM
ELSE ''
END AS NUM_SC,
CASE
	WHEN SC1A.C1_EMISSAO = SC1B.C1_EMISSAO
THEN CONVERT(VARCHAR,CAST(SC1A.C1_EMISSAO AS DATETIME),103)
	WHEN SC1A.C1_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC1B.C1_EMISSAO AS DATETIME),103)
	WHEN SC1B.C1_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC1A.C1_EMISSAO AS DATETIME),103)
ELSE ''
END AS DT_EMI_SC,
CASE
	WHEN SC7A.C7_FILIAL	= SC7B.C7_FILIAL  
THEN SC7A.C7_FILIAL
	WHEN SC7A.C7_FILIAL IS NULL
THEN SC7B.C7_FILIAL
	WHEN SC7B.C7_FILIAL IS NULL
THEN SC7A.C7_FILIAL
ELSE ''
END AS FILIAL_PC,	
CASE
	WHEN SC7A.C7_NUM = SC7B.C7_NUM
THEN SC7B.C7_NUM
	WHEN SC7A.C7_NUM IS NULL
THEN SC7B.C7_NUM
	WHEN SC7B.C7_NUM IS NULL
THEN SC7A.C7_NUM	   
ELSE '' 
END AS NUM_PC,
CASE
	WHEN SC7A.C7_EMISSAO = SC7B.C7_EMISSAO
THEN CONVERT(VARCHAR,CAST(SC7A.C7_EMISSAO AS DATETIME),103)
	WHEN SC7A.C7_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC7B.C7_EMISSAO AS DATETIME),103)
	WHEN SC7B.C7_EMISSAO IS NULL
THEN CONVERT(VARCHAR,CAST(SC7A.C7_EMISSAO AS DATETIME),103)
ELSE ''
END AS DT_EMI_PC,
CASE
	WHEN SC6A.C6_FILIAL	= SC6B.C6_FILIAL  
THEN SC6A.C6_FILIAL
	WHEN SC6A.C6_FILIAL IS NULL
THEN SC6B.C6_FILIAL
	WHEN SC6B.C6_FILIAL IS NULL
THEN SC6A.C6_FILIAL
ELSE ''
END AS FILIAL_PV,
CASE
	WHEN SC6A.C6_NUM = SC6B.C6_NUM
THEN SC6A.C6_NUM
	WHEN SC6A.C6_NUM IS NULL
THEN SC6B.C6_NUM
	WHEN SC6B.C6_NUM IS NULL
THEN SC6A.C6_NUM
ELSE ''
END AS NUM_PV,
CASE
	WHEN SC6A.C6_ENTREG = SC6B.C6_ENTREG
THEN CONVERT(VARCHAR,CAST(SC6A.C6_ENTREG AS DATETIME),103)
	WHEN SC6A.C6_ENTREG IS NULL
THEN CONVERT(VARCHAR,CAST(SC6B.C6_ENTREG AS DATETIME),103)
	WHEN SC6B.C6_ENTREG IS NULL
THEN CONVERT(VARCHAR,CAST(SC6A.C6_ENTREG AS DATETIME),103)
ELSE ''
END AS DT_DOCSAI,
CASE 
	WHEN SC6A.C6_SERIE = SC6B.C6_SERIE
THEN SC6A.C6_SERIE
	WHEN SC6A.C6_SERIE IS NULL
THEN SC6B.C6_SERIE
	WHEN SC6B.C6_SERIE IS NULL
THEN SC6A.C6_SERIE
ELSE ''
END AS SERIE_C6,
CASE 
	WHEN SC6A.C6_NOTA = SC6B.C6_NOTA
THEN SC6A.C6_NOTA
	WHEN SC6A.C6_NOTA IS NULL
THEN SC6B.C6_NOTA
	WHEN SC6B.C6_NOTA IS NULL
THEN SC6A.C6_NOTA
ELSE ''
END AS NOTA_C6,
CASE
	WHEN SC6C.C6_FILIAL = SC6D.C6_FILIAL
THEN SC6C.C6_FILIAL
	WHEN SC6C.C6_FILIAL IS NULL
THEN SC6D.C6_FILIAL
	WHEN SC6D.C6_FILIAL IS NULL
THEN SC6C.C6_FILIAL
ELSE ''
END AS FILIAL_C6_TROCA,
CASE
	WHEN SC6C.C6_NUM = SC6D.C6_NUM
THEN SC6C.C6_NUM
	WHEN SC6C.C6_NUM IS NULL
THEN SC6D.C6_NUM
	WHEN SC6D.C6_NUM IS NULL
THEN SC6C.C6_NUM
ELSE ''
END AS NUM_C6_TROCA,
CASE
	WHEN SC6C.C6_ENTREG = SC6D.C6_ENTREG
THEN CONVERT(VARCHAR,CAST(SC6C.C6_ENTREG AS DATETIME),103)
	WHEN SC6C.C6_ENTREG IS NULL
THEN CONVERT(VARCHAR,CAST(SC6D.C6_ENTREG AS DATETIME),103)
	WHEN SC6D.C6_ENTREG IS NULL
THEN CONVERT(VARCHAR,CAST(SC6C.C6_ENTREG AS DATETIME),103)
ELSE ''
END AS DT_DOCSAI_TROCA,
CASE
	WHEN SC6C.C6_SERIE = SC6D.C6_SERIE
THEN SC6C.C6_SERIE
	WHEN SC6C.C6_SERIE IS NULL
THEN SC6D.C6_SERIE
	WHEN SC6D.C6_SERIE IS NULL
THEN SC6C.C6_SERIE
ELSE ''
END AS SERIE_C6_TROCA,
CASE
	WHEN SC6C.C6_NOTA = SC6D.C6_NOTA
THEN SC6C.C6_NOTA
	WHEN SC6C.C6_NOTA IS NULL 
THEN SC6D.C6_NOTA
	WHEN SC6D.C6_NOTA IS NULL
THEN SC6C.C6_NOTA
ELSE ''
END AS NOTA_C6_TROCA,
CASE 
	WHEN SD1A.D1_DTDIGIT = SD1B.D1_DTDIGIT 
THEN CONVERT(VARCHAR,CAST(SD1A.D1_DTDIGIT AS DATETIME),103)
	WHEN SD1A.D1_DTDIGIT IS NULL
THEN CONVERT(VARCHAR,CAST(SD1B.D1_DTDIGIT AS DATETIME),103)
	WHEN SD1B.D1_DTDIGIT IS NULL
THEN CONVERT(VARCHAR,CAST(SD1A.D1_DTDIGIT AS DATETIME),103)
ELSE ''
END AS DT_NOTA_ENTRADA,
CASE
	WHEN SD1A.D1_SERIE = SD1B.D1_SERIE
THEN SD1A.D1_SERIE
	WHEN SD1A.D1_SERIE IS NULL
THEN SD1B.D1_SERIE
	WHEN SD1B.D1_SERIE IS NULL
THEN SD1A.D1_SERIE
ELSE ''
END AS SERIE_ENTRADA,
CASE
	WHEN SD1A.D1_DOC = SD1B.D1_DOC
THEN SD1A.D1_DOC
	WHEN SD1A.D1_DOC IS NULL
THEN SD1B.D1_DOC
	WHEN SD1B.D1_DOC IS NULL
THEN SD1A.D1_DOC
ELSE ''
END AS NOTA_ENTRADA,
CASE 
	WHEN SC7A.C7_DATPRF = SC7B.C7_DATPRF
THEN CONVERT(VARCHAR,CAST(SC7A.C7_DATPRF AS DATETIME),103)
	WHEN SC7A.C7_DATPRF IS NULL
THEN CONVERT(VARCHAR,CAST(SC7B.C7_DATPRF AS DATETIME),103)
	WHEN SC7B.C7_DATPRF IS NULL
THEN CONVERT(VARCHAR,CAST(SC7A.C7_DATPRF AS DATETIME),103)
ELSE ''
END AS PRZ_ENT_FOR,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT AS DATETIME),103) AS DT_ENT_CLI
FROM SUA010 SUA
/*ATENDIMENTO CABEÇARIO*/LEFT JOIN SUB010 SUB  ON SUB.D_E_L_E_T_ =  '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM 		
/*ATENDIMENTO ITEMS*/  	 LEFT JOIN SB1010 SB1  ON SB1.D_E_L_E_T_ =  '' AND SB1.B1_COD = SUB.UB_PRODUTO
/*CLIENTRE*/			 LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ =  '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
/*FORNECEDOR*/			 LEFT JOIN SA2010 SA2  ON SA2.D_E_L_E_T_ = ''  AND SA2.A2_COD = SB1.B1_PROC
/*VENDEDOR*/	   	     LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ =  '' AND SA3.A3_COD = SUA.UA_VEND
/*ORC SL1 (PAI)*/		 LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ =  '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
/*ORC SL2 PAI*/	         LEFT JOIN SL2010 SL2A ON SL2A.D_E_L_E_T_ = '' AND SL2A.L2_FILIAL = SUA.UA_FILIAL AND SL2A.L2_NUM = SL1.L1_NUM AND SL2A.L2_PRODUTO = SUB.UB_PRODUTO
/*ORC SL2 FILHO*/		 LEFT JOIN SL2010 SL2B ON SL2B.D_E_L_E_T_ = '' AND SL2B.L2_FILIAL = SL2A.L2_FILRES AND SL2B.L2_NUM = SL2A.L2_ORCRES AND SL2B.L2_PRODUTO = SL2A.L2_PRODUTO AND SL2B.L2_ITEM = SL2A.L2_ITEM
/*RESERVA SC0 (PAI)*/	 LEFT JOIN SC0010 SC0  ON SC0.D_E_L_E_T_ = ''  AND SC0.C0_FILRES = SL2A.L2_FILIAL AND SUBSTRING(SC0.C0_OBS,8,6) = SL2A.L2_NUM AND SC0.C0_PRODUTO = SL2A.L2_PRODUTO 
/*PV SC6 (PAI)*/   		 LEFT JOIN SC6010 SC6A ON SC6A.D_E_L_E_T_ = '' AND SC6A.C6_FILIAL = SL2A.L2_FILIAL AND SC6A.C6_NUM = SL2A.L2_PEDRES AND SC6A.C6_ITEM = SL2A.L2_ITEM AND SC6A.C6_PRODUTO = SL2A.L2_PRODUTO
/*PV SC6 (FILHO)*/  	 LEFT JOIN SC6010 SC6B ON SC6B.D_E_L_E_T_ = '' AND SC6B.C6_FILIAL = SL2B.L2_FILIAL AND SC6B.C6_NUM = SL2B.L2_PEDRES AND SC6B.C6_ITEM = SL2B.L2_ITEM AND SC6B.C6_PRODUTO = SL2B.L2_PRODUTO
/*SC SC1 (PAI)*/ 		 LEFT JOIN SC1010 SC1A ON SC1A.D_E_L_E_T_ = '' AND SC1A.C1_FILENT = SL2A.L2_FILIAL AND SC1A.C1_NUM = SL2A.L2_SOLCOM AND SC1A.C1_PRODUTO = SL2A.L2_PRODUTO AND SC1A.C1_ZITNORC = SL2A.L2_ITEM   
/*SC SC1 (FILHO)*/ 		 LEFT JOIN SC1010 SC1B ON SC1B.D_E_L_E_T_ = '' AND SC1B.C1_FILIAL = SL2B.L2_FILIAL AND SC1B.C1_NUM = SL2B.L2_SOLCOM AND SC1B.C1_PRODUTO = SL2B.L2_PRODUTO AND SC1B.C1_ZITNORC = SL2B.L2_ITEM  
/*PC SC7 (PAI)*/		 LEFT JOIN SC7010 SC7A ON SC7A.D_E_L_E_T_ = '' AND SC7A.C7_FILIAL = SC1A.C1_FILIAL AND SC7A.C7_NUMSC = SC1A.C1_NUM AND SC7A.C7_ITEMSC = SC1A.C1_ITEM AND SC7A.C7_PRODUTO = SC1A.C1_PRODUTO
/*PC SC7 (FILHO)*/ 		 LEFT JOIN SC7010 SC7B ON SC7B.D_E_L_E_T_ = '' AND SC7B.C7_FILIAL = SC1B.C1_FILIAL AND SC7B.C7_NUMSC = SC1B.C1_NUM AND SC7B.C7_ITEMSC = SC1B.C1_ITEM AND SC7B.C7_PRODUTO = SC1B.C1_PRODUTO
/*DOC.ENTR SD1(PAI)*/    LEFT JOIN SD1010 SD1A ON SD1A.D_E_L_E_T_ = '' AND SD1A.D1_FILIAL = SC7A.C7_FILENT AND SD1A.D1_PEDIDO = SC7A.C7_NUM AND SD1A.D1_COD = SC7A.C7_PRODUTO AND SD1A.D1_ITEMPC = SC7A.C7_ITEM
/*DOC.ENTR SD1(FILHO)*/  LEFT JOIN SD1010 SD1B ON SD1B.D_E_L_E_T_ = '' AND SD1B.D1_FILIAL = SC7B.C7_FILENT AND SD1B.D1_PEDIDO = SC7B.C7_NUM AND SD1B.D1_COD = SC7B.C7_PRODUTO AND SD1B.D1_ITEMPC = SC7B.C7_ITEM
/*TROOC.PROD (PAI)*/	 LEFT JOIN SC6010 SC6C ON SC6C.D_E_L_E_T_ = '' AND SC6C.C6_FILIAL = SL2A.L2_FILIAL AND SC6C.C6_NUM = SL2A.L2_PEDRES AND SC6C.C6_ITEM = SL2A.L2_ITEM AND SC6C.C6_PRODUTO <> SL2A.L2_PRODUTO
/*TROOC.PROD (FILHO)*/	 LEFT JOIN SC6010 SC6D ON SC6D.D_E_L_E_T_ = '' AND SC6D.C6_FILIAL = SL2B.L2_FILIAL AND SC6D.C6_NUM = SL2B.L2_PEDRES AND SC6D.C6_ITEM = SL2B.L2_ITEM AND SC6D.C6_PRODUTO <> SL2B.L2_PRODUTO
WHERE 1=1
/*----------------SUA - ATENDIMENTO----------------*/

AND SUA.D_E_L_E_T_ = ''	   -- SUA ATENDIMENTO
--AND SUA.UA_OPER   <> '3' -- SUA ATENDIMENTO
--AND SUA.UA_OPER   = '3' -- SUA ATENDIMENTO
--AND SUA.UA_NUMSL1 <> ''  -- SUA ATENDIMENTO

/*---------------SL1 - (700 OU NAO)----------------*/

--AND SL1.L1_SERPED <> '' 	  -- FINANCEIRO (700)
--AND SL1.L1_DOCPED <> ''     -- FINANCEIRO (700) 
--  AND SL1.L1_PEDRES = ''
--  AND SL1.L1_ORCRES = ''

/*----------------SL2 - (ORC PAI)------------------*/  

--AND SL2A.L2_FILRES = ''   -- SL2 PAI
--AND SL2A.L2_PEDRES = ''   -- SL2 PAI
--AND SL2A.L2_ORCRES <> ''  -- SL2 PAI
--AND SL2A.L2_SERPED = ''   -- SL2 PAI
--AND SL2A.L2_DOCPED = ''   -- SL2 PAI
--AND SL2A.L2_SOLCOM = ''	-- SL2 PAI
--AND SL2A.L2_SERIE  = ''   -- SL2 PAI
--AND SL2A.L2_DOC    = ''   -- SL2 PAI
--AND SL2A.L2_NUM IS NOT NULL

/*----------------SL2 - (ORC FILHO)----------------*/ 

--AND SL2B.L2_FILRES  = ''   	-- SL2 FILHO
--AND SL2B.L2_PEDRES <> ''   	-- SL2 FILHO
--AND SL2B.L2_ORCRES  = ''   	-- SL2 FILHO
--AND SL2B.L2_SERPED  = ''   	-- SL2 FILHO
--AND SL2B.L2_DOCPED  = ''	  	-- SL2 FILHO
--AND SL2B.L2_SOLCOM <> ''		-- SL2 FILHO	
--AND SL2B.L2_SERIE  = ''   	-- SL2 FILHO
--AND SL2B.L2_DOC    = ''   	-- SL2 FILHO
--AND SL2B.L2_NUM IS NOT NULL  -- UTILIZAR ESSE FILTRO PARA ATENDIMENTOS QUE ESTAJAM COM SERIE_PAI E NOTA_PAI EM BRANCO		

/*--------SC6 - (PEDIDO DE VENDA/RESERVA)----------*/ 

--AND SC6A.C6_SERIE = ''	 	-- SC6 PV (PAI)
--AND SC6A.C6_NOTA  = '' 	 	-- SC6 PV (PAI)
--AND SC6B.C6_SERIE = ''	 	-- SC6 PV (FILHO)
--AND SC6B.C6_NOTA  = '' 	 	-- SC6 PV (FILHO)

/*--------SC1 - (SOLICITAÇÃO DE COMPRA)-----------*/
 
--AND SC1A.C1_PEDIDO	<> ''	-- SC1 SC (PAI)
--AND SC1B.C1_PEDIDO	<> ''	-- SC1 SC (FILHO)

/*----------SC7 - (PEDIDO DE COMPRA)-------------*/
 
--AND SC7A.C7_NUMSC = ''		-- SC7 PC (PAI)
--AND SC7A.C7_NUM   = ''		-- SC7 PC (PAI)
--AND SC7B.C7_NUMSC = ''		-- SC7 PC (FILHO)
--AND SC7B.C7_NUM   = ''		-- SC7 PC (FILHO)

/*----------FILTROS GERAIS-------------*/

--AND SC7A.C7_DATPRF > SUA.UA_ZDTAENT		-- ATRASADO (PAI)
--AND SC7A.C7_DATPRF < SUA.UA_ZDTAENT		-- NO PRAZO (PAI)
--AND SC7B.C7_DATPRF > SUA.UA_ZDTAENT		-- ATRASADO (FILHO)
--AND SC7B.C7_DATPRF < SUA.UA_ZDTAENT		-- NO PRAZO (FILHO)
--AND SL2A.L2_NUM IS NOT NULL
--AND MONTH(SUA.UA_EMISSAO) IN(6,7)
--AND MONTH(SUA.UA_EMISSAO) = 12   
--AND SA3.A3_COD = '000064'		
--AND SUA.UA_NUM = '025840'
--  AND SUA.UA_FILIAL = '0101'
--  AND SUA.UA_NUM = '024039'	  
 
/*----------FILTROS ATIVOS-------------*/

  AND SA3.A3_ZSITVND IN ('1','2')
  AND YEAR(SUA.UA_EMISSAO) IN(2020)
  AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
--  AND SUA.UA_FILIAL = '0103'
--  AND SUA.UA_NUM = '007745' 
--    AND SUA.UA_FILIAL = @V
--    AND SUA.UA_NUM = @ATM

GO