
SELECT 
*,
CASE
	WHEN
		Z2_DATA_FAT = ''
	AND Z2_NUM_RES_MANU IS NULL 
	AND Z2_PROD_TROCADO IS NULL
THEN 'NÃO FATURADO'


	WHEN
		Z2_DOC700 = ''
	AND Z2_SER700 = ''
	AND Z2_NUM_ORC_PAI <> ''
	AND Z2_NUM_ORC_FILHO IS NULL
	AND Z2_NUM_RES_MANU IS NULL
	AND Z2_PROD_TROCADO IS NULL
THEN 'PRODUTO RESERVADO'


	WHEN
		Z2_DOC700 = ''
	AND Z2_SER700 = ''
	AND Z2_NUM_RES_MANU <> ''
	AND Z2_NUM_ORC_PAI <> ''
	AND Z2_NUM_ORC_FILHO IS NULL
	AND Z2_PROD_TROCADO IS NULL
THEN 'PRODUTO RESERVADO'
	WHEN
		Z2_DOC700 <> ''
	AND Z2_SER700 <> ''
	AND Z2_NUM_ORC_PAI <> ''
	AND Z2_NUM_ORC_FILHO <> ''
	AND Z2_NUM_SC IS NULL
	AND Z2_NUM_PC IS NULL
	AND Z2_NUM_PV IS NULL
	AND Z2_NUM_RES_MANU IS NULL
	AND Z2_PROD_TROCADO IS NULL
THEN 'PRODUTO RESERVADO'

	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC IS NULL
	AND Z2_NUM_PV <> ''
	AND Z2_SERIE_C6 = ''
	AND Z2_NOTA_C6 = ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRA PENDENTE'
	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC IS NULL
	AND Z2_NUM_PV IS NULL
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRA PENDENTE'
	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV <> ''
	AND Z2_SERIE_C6 = ''
	AND Z2_NOTA_C6 = ''
	AND Z2_SERIE_ENTRADA IS NULL
	AND Z2_NOTA_ENTRADA IS NULL
	AND Z2_PRZ_ENT_FOR > Z2_DT_ENT_CLI
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRADO COM ATRASO'
	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV IS NULL	
	AND Z2_SERIE_ENTRADA IS NULL
	AND Z2_NOTA_ENTRADA IS NULL
	AND Z2_PRZ_ENT_FOR > Z2_DT_ENT_CLI
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRADO COM ATRASO'
	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV <> ''
	AND Z2_SERIE_C6 = ''
	AND Z2_NOTA_C6 = ''
	AND Z2_SERIE_ENTRADA IS NULL
	AND Z2_NOTA_ENTRADA IS NULL
	AND Z2_PRZ_ENT_FOR <= Z2_DT_ENT_CLI
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRADO DENTRO DO PRAZO'
	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV IS NULL	
	AND Z2_SERIE_ENTRADA IS NULL
	AND Z2_NOTA_ENTRADA IS NULL
	AND Z2_PRZ_ENT_FOR <= Z2_DT_ENT_CLI
	AND Z2_PROD_TROCADO IS NULL
THEN 'COMPRADO DENTRO DO PRAZO'
	WHEN 
		Z2_NUM_SC IS NULL
	AND Z2_NUM_PV <> ''
	AND Z2_SERIE_C6 = ''
	AND Z2_NOTA_C6 = ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'PRODUTO RSERVADO NO ESTOQUE'
 	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV <> ''
	AND Z2_SERIE_C6 = ''
	AND Z2_NOTA_C6 = ''
	AND Z2_SERIE_ENTRADA <> ''
	AND Z2_NOTA_ENTRADA <> ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'NO ESTOQUE JÁ COMPRADO C/PV'
 	WHEN 
		Z2_NUM_SC <> ''
	AND Z2_NUM_PC <> ''
	AND Z2_NUM_PV IS NULL
	AND Z2_SERIE_ENTRADA <> ''
	AND Z2_NOTA_ENTRADA <> ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'NO ESTOQUE JÁ COMPRADO S/PV'
	WHEN 
		Z2_SERIE_C6 <> ''
	AND Z2_NOTA_C6  <> ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'FATURADO - NO PEDIDO DE VENDA'
	WHEN 
		Z2_DOC700 = ''
	AND Z2_SER700 = ''
	AND	Z2_SERIE_PAI  <> ''
	AND Z2_NOTA_PAI <> ''
	AND Z2_PROD_TROCADO IS NULL
THEN 'FATURADO - VENDA DIRETA'
	WHEN 
	Z2_PROD_TROCADO IS NOT NULL
THEN 'TROCA DE PRODUTO'
ELSE ''
END AS SITUACAO
FROM Z2CUBOVEND

