
SELECT 
SUA.UA_FILIAL 	AS FILIAL,
SUA.UA_NUM	  	AS NUM,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS EMISSAO,
SUB.UB_PRODUTO	AS CODPROD,
SB1.B1_DESC		AS PRODUTO,
SB1.B1_ZDESRDZ	AS PRODUTO_REDU, 
SUB.UB_QUANT 	AS QTD,
SB1.B1_UM		AS UND,
SA1.A1_COD		AS COD_CLI,
SA1.A1_NOME 	AS CLIENTE,
SA1.A1_NREDUZ	AS CLIENTE_REDU,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF,
SUA.UA_ZPRZENT,
CONVERT(VARCHAR,CAST(SUA.UA_ZDTAENT  AS DATETIME),103) AS DT_ENTREGA,
SUA.UA_VLRLIQ	AS VLR_TOTAL_ATM,
SUA.UA_OPER		AS OPER_ATM,
SUA.UA_NUMSL1	AS NUMSL1_ATM,
SUA.UA_STATUS	AS STATUS,
SUA.UA_CANC		AS CANCEL,
SA3.A3_COD		AS COD_VEND,
SA3.A3_NOME		AS VENDEDOR,
SA3.A3_NREDUZ	AS VEND_REDU,
CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103) AS EMISSAO_NF_L1,
SL1.L1_FILIAL,
SL1.L1_NUM,
CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS DT_HJ,
CASE
WHEN SUA.UA_OPER = '3'
	AND UA_STATUS <> 'CAN'
	AND UA_CANC <> 'S'
THEN 'PRODUTO EM ATENDIMENTO ABERTO'
	WHEN SUA.UA_OPER = '4'
	AND UA_STATUS <> 'CAN'
	AND UA_CANC <> 'S'
THEN 'PRODUTO EM ATENDIMENTO LIB. P/ FAT.'
	WHEN UA_STATUS = 'CAN'
	AND UA_CANC = 'S'
THEN 'PRODUTO EM ATENDIMENTO CANCELADO'
ELSE ''
END AS SITUACAO

FROM SUA010 SUA
LEFT JOIN SUB010 SUB ON SUB.D_E_L_E_T_ = '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SUB.UB_PRODUTO
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SUA.UA_LOJA = SA1.A1_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
--AND SL1.L1_ORCRES = ''
AND YEAR(SUA.UA_EMISSAO) = 2020
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'
AND SA3.A3_ZSITVND IN ('1','2')
AND SUA.UA_OPER IN ('3','4')

  
