--BQC - CONTRATOS PJ

60765823000130

63089205000105

SELECT CASE WHEN C.BA1_FILIAL = '001' THEN 'Medicar Ribeirao Preto' WHEN C.BA1_FILIAL = '002' THEN 'Medicar Campinas' WHEN C.BA1_FILIAL = '003' THEN 'Medicar Sao Paulo' WHEN C.BA1_FILIAL = '006' THEN 'Medicar Tech' WHEN C.BA1_FILIAL = '008' THEN 'Medicar Litoral' WHEN C.BA1_FILIAL = '016' THEN 'N1 Card' WHEN C.BA1_FILIAL = '021' THEN 'Medicar Rio de Janeiro' ELSE '' END AS FILIAL, A.BQC_SUBCON AS ID_CONTRATO, A.BQC_ANTCON AS NUMERO_CONTRATO, E.BT5_NOME AS PERFIL, BQL_DESCRI AS FORMAPAGAMENTO, COUNT(CONCAT(C.BA1_FILIAL,C.BA1_CODINT,C.BA1_CODEMP,C.BA1_MATRIC,C.BA1_TIPUSU,C.BA1_TIPREG,C.BA1_DIGITO,C.BA1_NOMUSR)) AS QTD_VIDAS, SUM(D.BDK_VALOR) AS VALOR
CASE WHEN A.BQC_TIPBLO = '0' AND A.BQC_DATBLO <> '' THEN 'BLOQUEADO' ELSE 'ATIVO' END AS STATUSC
FROM BQC010 A
LEFT JOIN BA3010 B ON B.D_E_L_E_T_ = '' AND B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON 
LEFT JOIN BA1010 C ON C.D_E_L_E_T_ = '' AND C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP
LEFT JOIN BDK010 D ON D.D_E_L_E_T_ = '' AND D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG 
LEFT JOIN BT5010 E ON E.D_E_L_E_T_ = '' AND E.BT5_FILIAL = A.BQC_FILIAL AND E.BT5_CODINT = A.BQC_CODINT AND E.BT5_CODIGO = A.BQC_CODEMP AND E.BT5_NUMCON = A.BQC_NUMCON AND E.BT5_VERSAO = A.BQC_VERCON
LEFT JOIN BQL010 F ON F.D_E_L_E_T_ = '' AND F.BQL_CODIGO = A.BQC_TIPPAG
LEFT JOIN ZI0010 G ON G.D_E_L_E_T_ = '' AND G.Z10_CODIGO = A.BQC_XCONDI
WHERE 1=1 
AND A.D_E_L_E_T_ = ''
AND A.BQC_COBNIV = '1'
AND A.BQC_CODCLI = '070194'
AND A.BQC_LOJA = '01'
GROUP BY C.BA1_FILIAL,A.BQC_SUBCON,E.BT5_NOME,A.BQC_DESCRI,A.BQC_ZNFANT,A.BQC_ANTCON

--BA3 - CONTRATOS PF

SELECT CASE WHEN C.BA1_FILIAL = '001' THEN 'Medicar Ribeirao Preto' WHEN C.BA1_FILIAL = '002' THEN 'Medicar Campinas' WHEN C.BA1_FILIAL = '003' THEN 'Medicar Sao Paulo' WHEN C.BA1_FILIAL = '006' THEN 'Medicar Tech' WHEN C.BA1_FILIAL = '008' THEN 'Medicar Litoral' WHEN C.BA1_FILIAL = '016' THEN 'N1 Card' WHEN C.BA1_FILIAL = '021' THEN 'Medicar Rio de Janeiro' ELSE '' END AS FILIAL, CASE WHEN B.BA3_IDBENN <> '' THEN B.BA3_IDBENN ELSE B.BA3_MATEMP END AS ID_CONTRATO, B.BA3_XCARTE AS NUMERO_CONTRATO, E.BT5_NOME AS PERFIL,COUNT(CONCAT(C.BA1_FILIAL,C.BA1_CODINT,C.BA1_CODEMP,C.BA1_MATRIC,C.BA1_TIPUSU,C.BA1_TIPREG,C.BA1_DIGITO,C.BA1_NOMUSR)) AS QTD_VIDAS,SUM(D.BDK_VALOR) AS VALOR
CASE WHEN B.BA3_MOTBLO <> '' AND B.BA3_DATBLO <> '' THEN 'BLOQUEADO' ELSE 'ATIVO' END AS STATUSC
FROM BQC010 A
LEFT JOIN BA3010 B ON B.D_E_L_E_T_ = '' AND B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON 
LEFT JOIN BA1010 C ON C.D_E_L_E_T_ = '' AND C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP
LEFT JOIN BDK010 D ON D.D_E_L_E_T_ = '' AND D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG 
LEFT JOIN BT5010 E ON E.D_E_L_E_T_ = '' AND E.BT5_FILIAL = A.BQC_FILIAL AND E.BT5_CODINT = A.BQC_CODINT AND E.BT5_CODIGO = A.BQC_CODEMP AND E.BT5_NUMCON = A.BQC_NUMCON AND E.BT5_VERSAO = A.BQC_VERCON
LEFT JOIN SA1010 F ON F.D_E_L_E_T_ = '' AND F.A1_COD = B.BA3_CODCLI AND F.A1_LOJA = B.BA3_LOJA
LEFT JOIN BQL010 F ON F.D_E_L_E_T_ = '' AND F.BQL_CODIGO = 
LEFT JOIN ZI0010 G ON G.D_E_L_E_T_ = '' AND G.Z10_CODIGO = 
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.BA3_COBNIV = '1'
AND B.BA3_CODCLI = '059279'
AND B.BA3_LOJA = '01'
GROUP BY C.BA1_FILIAL,B.BA3_IDBENN,B.BA3_MATEMP,B.BA3_XCARTE,E.BT5_NOME,F.A1_NOME,F.A1_NREDUZ


-- BA1 BENEFICIARIOS
SELECT TOP 10
C.BA1_XCARTE AS CARTEIRINHA, 
C.BA1_NOMUSR AS BENEFICIARIO,

CASE
    WHEN LEN(C.BA1_CPFUSR) > 11 THEN CONCAT(SUBSTRING(C.BA1_CPFUSR,1,2),'.',SUBSTRING(C.BA1_CPFUSR,3,3),'.',SUBSTRING(C.BA1_CPFUSR,6,3),'/',SUBSTRING(C.BA1_CPFUSR,9,4),'-',SUBSTRING(C.BA1_CPFUSR,13,2))
    ELSE CONCAT(SUBSTRING(C.BA1_CPFUSR,1,3),'.',SUBSTRING(C.BA1_CPFUSR,4,3),'.',SUBSTRING(C.BA1_CPFUSR,7,3),'-',SUBSTRING(C.BA1_CPFUSR,10,2))
END AS CPF,
CASE
    WHEN C.BA1_ZATEND = '1' THEN 'Sim'
    WHEN C.BA1_ZATEND = '0' THEN 'Não'
    ELSE ''
END         AS TEMATENDIMENTO,
CASE
    WHEN BA1_DATBLO <> '' AND BA1_MOTBLO <> '' THEN 'Inativo'
    ELSE 'ATIVO'
END         AS STATUSBENE,
D.BDK_VALOR AS VALOR,
C.BA1_TIPUSU AS TIPO
FROM BQC010 A
LEFT JOIN BA3010 B ON B.D_E_L_E_T_ = '' AND B.BA3_CODINT = A.BQC_CODINT AND B.BA3_CODEMP = A.BQC_CODEMP AND B.BA3_CONEMP = A.BQC_NUMCON AND B.BA3_SUBCON = A.BQC_SUBCON 
LEFT JOIN BA1010 C ON C.D_E_L_E_T_ = '' AND C.BA1_FILIAL = B.BA3_FILIAL AND C.BA1_CODINT = B.BA3_CODINT AND C.BA1_CODEMP = B.BA3_CODEMP AND C.BA1_CONEMP = B.BA3_CONEMP AND C.BA1_SUBCON = B.BA3_SUBCON AND C.BA1_MATEMP = B.BA3_MATEMP
LEFT JOIN BDK010 D ON D.D_E_L_E_T_ = '' AND D.BDK_FILIAL = C.BA1_FILIAL AND D.BDK_CODINT = C.BA1_CODINT AND D.BDK_CODEMP = C.BA1_CODEMP AND D.BDK_MATRIC = C.BA1_MATRIC AND D.BDK_TIPREG = C.BA1_TIPREG 
LEFT JOIN BT5010 E ON E.D_E_L_E_T_ = '' AND E.BT5_FILIAL = A.BQC_FILIAL AND E.BT5_CODINT = A.BQC_CODINT AND E.BT5_CODIGO = A.BQC_CODEMP AND E.BT5_NUMCON = A.BQC_NUMCON AND E.BT5_VERSAO = A.BQC_VERCON
WHERE 1=1 
AND A.D_E_L_E_T_ = ''
AND A.BQC_COBNIV = '1'
AND A.BQC_CODCLI = '070194'
AND A.BQC_LOJA = '01'




    