
SELECT 
FILIAL,
ATENDIMENTO,
CONCAT(SUBSTRING(DT_ENTREGA_ATM,7,2), '/',SUBSTRING(DT_ENTREGA_ATM,5,2), '/', SUBSTRING(DT_ENTREGA_ATM,1,4)) AS DT_ENTREGA,
COD_CLI,
CLIENTE,
END_CLIENTE,
BAIRRO_CLIENTE,
CIDADE_CLIENTE,
ESTADO_CLIENTE,
MSG_NF,
CASE
	WHEN COD_FRETE = '000001'
THEN 'Entrega (Zanotti)'
	WHEN COD_FRETE = '000002'
THEN 'Coleta Cliente'
	WHEN COD_FRETE <> '' AND COD_FRETE NOT IN ('000001', '000002')
THEN 'Tranportadora'
ELSE ''
END AS TIPO_DE_TRANSPORTE,
CASE
	WHEN TRANSPORTADOR NOT IN ('000001', '000002')
THEN ''
ELSE TRANSPORTADOR
END AS TRANSPORTADOR_NOME,
CASE
	WHEN TIPO_VENDA = '1'
THEN 'Varejo'
	WHEN TIPO_VENDA = '2'
THEN 'Projeto'
	WHEN TIPO_VENDA = '3'
THEN 'Indústria (Adega)'
	WHEN TIPO_VENDA = '4'
THEN 'Indústria (Painel)'
	WHEN TIPO_VENDA = '5'
THEN 'Indústria (Câmara Fria)'
	WHEN TIPO_VENDA = '6'
THEN 'Indústria (Walk-in Cooler)'
ELSE ''
END AS TIPO_DE_VENDA,
CASE
	WHEN MONTAGEM = 'S'
THEN 'Sim'
	WHEN MONTAGEM = 'N'
THEN 'Não'
ELSE ''
END AS MONTAGEM_DE_PRODUTOS,
CASE
	WHEN CORTE_PAINEL = 'S'
THEN 'Sim'
	WHEN CORTE_PAINEL = 'N'
THEN 'Não'
ELSE ''
END AS CORTE_DE_PAINEL,
CASE
	WHEN PLOTAGEM = 'S'
THEN 'Sim'
	WHEN PLOTAGEM = 'N'
THEN 'Não'
ELSE ''
END AS PLOTAGEM_PRODUTO,
CASE
	WHEN MONTADOR_PAINEL = 'Z'
THEN 'Instalação Vendida pela Zanotti'
	WHEN MONTADOR_PAINEL = 'P'
THEN 'Instalação por Montador Parceiro'
	WHEN MONTADOR_PAINEL = 'R'
THEN 'Instalação Responsabilidade do Cliente'
ELSE ''
END MONTADOR_DE_PAINEL,
VENDEDOR,
CONCAT(SUBSTRING(EMISSAO_ATM,7,2), '/',SUBSTRING(EMISSAO_ATM,5,2), '/', SUBSTRING(EMISSAO_ATM,1,4)) AS DT_EMISSAO,
CASE
	WHEN PROD_MULT = 'S'
THEN 'Sim'
	WHEN PROD_MULT = 'N'
THEN 'Não'
ELSE ''
END AS PROD_MULTIFRIO,
CASE
	WHEN PROD_RIB = 'S'
THEN 'Sim'
	WHEN PROD_RIB = 'N'
THEN 'Não'
ELSE ''
END AS PROD_METALRIB,
MIN(ESTAGIO) AS ESTAGIO
FROM
(
SELECT 
SUA.UA_FILIAL		AS FILIAL,
SUA.UA_NUM			AS ATENDIMENTO,
SUA.UA_CLIENTE		AS COD_CLI,
SA1.A1_NOME			AS CLIENTE,
SUA.UA_VEND			AS COD_VEND,
SA3.A3_NOME			AS VENDEDOR,
SUA.UA_EMISSAO		AS EMISSAO_ATM,
SUA.UA_ZDTAENT		AS DT_ENTREGA_ATM,
SUA.UA_OPER			AS OPER_SUA,
SUB.UB_PRODUTO  	AS PRODUTO,
SUB.UB_ITEM			AS ITEM,
SUA.UA_ZTIPVND		AS TIPO_VENDA,
SUA.UA_ZMONTAG		AS MONTAGEM,
SUA.UA_ZPLOTAG		AS PLOTAGEM,
SUA.UA_ZCRTPNL		AS CORTE_PAINEL,
SUA.UA_ZMONTPN		AS MONTADOR_PAINEL,
SUA.UA_ZFINPEN		AS FIN_PENDENTE,
SUA.UA_ZPRDMLT		AS PROD_MULT,
SUA.UA_ZPRDRIB		AS PROD_RIB,
SUA.UA_TPFRETE		AS TIPO_FRETE,
SUA.UA_ZZMSGNF		AS MSG_NF,
SA1.A1_END			AS END_CLIENTE,
SA1.A1_BAIRRO		AS BAIRRO_CLIENTE,
SA1.A1_MUN			AS CIDADE_CLIENTE,
SA1.A1_EST			AS ESTADO_CLIENTE,
SUA.UA_ZCODFRT		AS COD_FRETE,
SA4.A4_NOME			AS TRANSPORTADOR,
CASE
	WHEN SUB.UB_OPER = '01'
THEN '1 - 501'
	WHEN SUB.UB_OPER = '02'
THEN '2 - 700'
	WHEN SUB.UB_OPER = '04'
THEN '3 - 720'
ELSE ''
END AS ESTAGIO,
SUA.UA_ZCTRLIB		AS CTR_LIB,
SUA.UA_ZPIPEFY		AS FLAG_PIPE
FROM SUA010 SUA
LEFT JOIN SUB010 SUB ON SUB.D_E_L_E_T_ = '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SA4010 SA4 ON SA4.D_E_L_E_T_ = '' AND SA4.A4_COD = SUA.UA_ZCODFRT
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_EMISSAO >= '20210211'
AND SUA.UA_OPER = '2'
AND SUA.UA_ZPIPEFY = ''
AND SUA.UA_NUM = '008940'
) AS ATENDIMENTO
WHERE 1=1
AND ESTAGIO = '1 - 501'
GROUP BY 
FILIAL,
ATENDIMENTO,
DT_ENTREGA_ATM,
COD_CLI,
CLIENTE,
END_CLIENTE,
BAIRRO_CLIENTE,
CIDADE_CLIENTE,
ESTADO_CLIENTE,
MSG_NF,
COD_FRETE, 
TRANSPORTADOR,
TIPO_VENDA,
MONTAGEM, 
CORTE_PAINEL,
PLOTAGEM,
MONTADOR_PAINEL,
FIN_PENDENTE,
VENDEDOR,
EMISSAO_ATM,
PROD_MULT, 
PROD_RIB 