
SELECT 

FILIAL,
ATENDIMENTO,
CONCAT(SUBSTRING(DT_ENTREGA_ATM,7,2), '/',SUBSTRING(DT_ENTREGA_ATM,5,2), '/', SUBSTRING(DT_ENTREGA_ATM,1,4)) AS DT_ENTREGA,
COD_CLI,
CLIENTE,
END_CLIENTE,
BAIRRO_CLIENTE,
CIDADE_CLIENTE,
ESTADO_CLIENTE,
MSG_NF,
CASE
	WHEN COD_FRETE = '000001'
THEN 'Entrega (Zanotti)'
	WHEN COD_FRETE = '000002'
THEN 'Cliente Retira'
	WHEN COD_FRETE <> '' AND COD_FRETE NOT IN ('000001', '000002')
THEN 'Tranportadora'
ELSE ''
END AS TIPO_DE_TRANSPORTE,
CASE
	WHEN TRANSPORTADOR NOT IN ('000001', '000002')
THEN ''
ELSE TRANSPORTADOR
END AS TRANSPORTADOR_NOME,
CASE
	WHEN TIPO_VENDA = '1'
THEN 'Varejo'
	WHEN TIPO_VENDA = '2'
THEN 'Projeto'
	WHEN TIPO_VENDA = '3'
THEN 'Indústria (Adega)'
	WHEN TIPO_VENDA = '4'
THEN 'Indústria (Painel)'
	WHEN TIPO_VENDA = '5'
THEN 'Indústria (Câmara Fria)'
	WHEN TIPO_VENDA = '6'
THEN 'Indústria (Walk-in Cooler)'
ELSE ''
END AS TIPO_DE_VENDA,
CASE
	WHEN MONTAGEM = 'S'
THEN 'Sim'
	WHEN MONTAGEM = 'N'
THEN 'Não'
ELSE ''
END AS MONTAGEM_DE_PRODUTOS,
CASE
	WHEN CORTE_PAINEL = 'S'
THEN 'Sim'
	WHEN CORTE_PAINEL = 'N'
THEN 'Não'
ELSE ''
END AS CORTE_DE_PAINEL,
CASE
	WHEN PLOTAGEM = 'S'
THEN 'Sim'
	WHEN PLOTAGEM = 'N'
THEN 'Não'
ELSE ''
END AS PLOTAGEM_PRODUTO,
CASE
	WHEN MONTADOR_PAINEL = 'Z'
THEN 'Instalação Vendida pela Zanotti'
	WHEN MONTADOR_PAINEL = 'P'
THEN 'Instalação por Montador Parceiro'
	WHEN MONTADOR_PAINEL = 'R'
THEN 'Instalação Responsabilidade do Cliente'
ELSE ''
END MONTADOR_DE_PAINEL,
VENDEDOR,
CONCAT(SUBSTRING(EMISSAO_ATM,7,2), '/',SUBSTRING(EMISSAO_ATM,5,2), '/', SUBSTRING(EMISSAO_ATM,1,4)) AS DT_EMISSAO,
CASE
	WHEN PROD_MULT = 'S'
THEN 'Sim'
	WHEN PROD_MULT = 'N'
THEN 'Não'
ELSE ''
END AS PROD_MULTIFRIO,
CASE
	WHEN PROD_RIB = 'S'
THEN 'Sim'
	WHEN PROD_RIB = 'N'
THEN 'Não'
ELSE ''
END AS PROD_METALRIB,
PV,
MIN(ESTAGIO) AS ESTAGIO
 FROM
(
SELECT 
SUA.UA_FILIAL		AS FILIAL,
SUA.UA_NUM			AS ATENDIMENTO,
SUA.UA_CLIENTE		AS COD_CLI,
SA1.A1_NOME			AS CLIENTE,
SUA.UA_VEND			AS COD_VEND,
SA3.A3_NOME			AS VENDEDOR,
SUA.UA_EMISSAO		AS EMISSAO_ATM,
SUA.UA_ZDTAENT		AS DT_ENTREGA_ATM,
SUA.UA_OPER			AS OPER_SUA,
SUA.UA_ZTIPVND		AS TIPO_VENDA,
SUA.UA_ZMONTAG		AS MONTAGEM,
SUA.UA_ZPLOTAG		AS PLOTAGEM,
SUA.UA_ZCRTPNL		AS CORTE_PAINEL,
SUA.UA_ZMONTPN		AS MONTADOR_PAINEL,
SUA.UA_ZFINPEN		AS FIN_PENDENTE,
SUA.UA_ZPRDMLT		AS PROD_MULT,
SUA.UA_ZPRDRIB		AS PROD_RIB,
SUA.UA_TPFRETE		AS TIPO_FRETE,
SUA.UA_ZZMSGNF		AS MSG_NF,
SA1.A1_END			AS END_CLIENTE,
SA1.A1_BAIRRO		AS BAIRRO_CLIENTE,
SA1.A1_MUN			AS CIDADE_CLIENTE,
SA1.A1_EST			AS ESTADO_CLIENTE,
SUA.UA_ZCODFRT		AS COD_FRETE,
SA4.A4_NOME			AS TRANSPORTADOR,
SC5.C5_NUM			AS PV,
SC6.C6_PRODUTO		AS PRODUTO,
SC6.C6_QTDVEN		AS QTD,
SC9.C9_QTDLIB		AS QTDLIB,	
SC9.C9_SERIENF		AS SERIE,
SC9.C9_NFISCAL		AS NOTA,
SC9.C9_BLEST		AS BLEST,
CASE
	WHEN SC9.C9_BLEST = '02'
THEN '1 - BLOQ. ESTOQUE'
	WHEN SC9.C9_BLEST = ''
THEN '2 - RESERVADO'
	WHEN SC9.C9_BLEST = '10'
THEN '3 - FATURADO'
ELSE ''
END AS ESTAGIO,
SUA.UA_ZCTRLIB		AS CTR_LIB,
SC5.C5_ZPIPEFY		AS FLAG_PIPE
FROM SUA010 SUA
LEFT JOIN SL1010 SL1  ON SL1.D_E_L_E_T_ = ''  AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
LEFT JOIN SL1010 SL1F ON SL1F.D_E_L_E_T_ = '' AND SL1F.L1_FILRES = SL1.L1_FILIAL AND SL1F.L1_ORCRES = SL1.L1_NUM    
LEFT JOIN SC5010 SC5  ON SC5.D_E_L_E_T_ = ''  AND SC5.C5_FILIAL = SL1F.L1_FILIAL AND SC5.C5_NUM = SL1F.L1_PEDRES
LEFT JOIN SC6010 SC6  ON SC6.D_E_L_E_T_ = ''  AND SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SL1F.L1_PEDRES
LEFT JOIN SC9010 SC9  ON SC9.D_E_L_E_T_ = ''  AND SC9.C9_FILIAL = SC6.C6_FILIAL AND SC9.C9_PEDIDO = SC6.C6_NUM AND SC9.C9_PRODUTO = SC6.C6_PRODUTO AND SC9.C9_ITEM = SC6.C6_ITEM
LEFT JOIN SA1010 SA1  ON SA1.D_E_L_E_T_ = ''  AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3  ON SA3.D_E_L_E_T_ = ''  AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SA4010 SA4  ON SA4.D_E_L_E_T_ = ''  AND SA4.A4_COD = SUA.UA_ZCODFRT
WHERE 1=1
AND SUA.D_E_L_E_T_ = '' 
AND SUA.UA_EMISSAO >= '20210211'
AND SC5.C5_ZPIPEFY = ''
AND SUA.UA_NUM = '008940'
) AS PEDIDO
WHERE 1=1
AND ESTAGIO = '2 - RESERVADO'
GROUP BY
FILIAL,
ATENDIMENTO,
DT_ENTREGA_ATM,
COD_CLI,
CLIENTE,
END_CLIENTE,
BAIRRO_CLIENTE,
CIDADE_CLIENTE,
ESTADO_CLIENTE,
MSG_NF,
COD_FRETE, 
TRANSPORTADOR,
TIPO_VENDA,
MONTAGEM, 
CORTE_PAINEL,
PLOTAGEM,
MONTADOR_PAINEL,
FIN_PENDENTE,
VENDEDOR,
EMISSAO_ATM,
PROD_MULT, 
PROD_RIB,
PV