SELECT 
SUA.UA_FILIAL		AS FILIAL,
SUA.UA_NUM			AS ATENDIMENTO,
SUA.UA_CLIENTE		AS COD_CLI,
SA1.A1_NOME			AS CLIENTE,
SUA.UA_VEND			AS COD_VEND,
SA3.A3_NOME			AS VENDEDOR,
Trim(SA3.A3_EMAIL)  AS EMAIL_VENDEDOR, 
SUA.UA_EMISSAO		AS DT_EMISSAO,
SUA.UA_ZDTAENT		AS DT_ENTREGA,
SUA.UA_OPER			AS OPER_SUA,
CASE
	WHEN SUA.UA_ZTIPVND = '1'
THEN 'Varejo'
	WHEN SUA.UA_ZTIPVND = '2'
THEN 'Projeto'
	WHEN SUA.UA_ZTIPVND = '3'
THEN 'Indústria (Adega)'
	WHEN SUA.UA_ZTIPVND = '4'
THEN 'Indústria (Painel)'
	WHEN SUA.UA_ZTIPVND = '5'
THEN 'Indústria (Câmara Fria)'
	WHEN SUA.UA_ZTIPVND = '6'
THEN 'Indústria (Walk-in Cooler)'
ELSE ''
END AS TIPO_DE_VENDA,
CASE
	WHEN SUA.UA_ZMONTAG = 'S'
THEN 'Sim'
	WHEN SUA.UA_ZMONTAG = 'N'
THEN 'Não'
ELSE ''
END AS MONTAGEM_DE_PRODUTOS,
CASE
	WHEN SUA.UA_ZPLOTAG = 'S'
THEN 'Sim'
	WHEN SUA.UA_ZPLOTAG = 'N'
THEN 'Não'
ELSE ''
END AS PLOTAGEM_PRODUTO,
CASE
	WHEN SUA.UA_ZCRTPNL = 'S'
THEN 'Sim'
	WHEN SUA.UA_ZCRTPNL = 'N'
THEN 'Não'
ELSE ''
END AS CORTE_DE_PAINEL,
CASE
	WHEN SUA.UA_ZMONTPN = 'Z'
THEN 'Instalação Vendida pela Zanotti'
	WHEN SUA.UA_ZMONTPN = 'P'
THEN 'Instalação por Montador Parceiro'
	WHEN SUA.UA_ZMONTPN = 'R'
THEN 'Instalação Responsabilidade do Cliente'
ELSE ''
END MONTADOR_DE_PAINEL,
SUA.UA_ZFINPEN		AS FIN_PENDENTE,
CASE
	WHEN SUA.UA_ZPRDMLT = 'S'
THEN 'Sim'
	WHEN SUA.UA_ZPRDMLT = 'N'
THEN 'Não'
ELSE ''
END AS PROD_MULTIFRIO,
CASE
	WHEN SUA.UA_ZPRDRIB = 'S'
THEN 'Sim'
	WHEN SUA.UA_ZPRDRIB = 'N'
THEN 'Não'
ELSE ''
END AS PROD_METALRIB,
CASE
	WHEN SUA.UA_ZCODFRT = '000001'
THEN 'Zanotti Refrigeração'
	WHEN SUA.UA_ZCODFRT = '000002'
THEN 'Cliente Retira'
	WHEN SUA.UA_ZCODFRT <> '' AND SUA.UA_ZCODFRT NOT IN ('000001', '000002')
THEN 'Transportadora'
ELSE ''
END AS TIPO_DE_TRANSPORTE,
SUA.UA_TPFRETE		AS TIPO_FRETE,
SUA.UA_ZZMSGNF		AS MSG_NF,
SA1.A1_END			AS END_CLIENTE,
SA1.A1_BAIRRO		AS BAIRRO_CLIENTE,
SA1.A1_MUN			AS CIDADE_CLIENTE,
SA1.A1_EST			AS ESTADO_CLIENTE,
SUA.UA_ZCODFRT		AS COD_FRETE,
SA4.A4_NOME			AS TRANSPORTADOR,
SUA.UA_ZIDPIPE		AS IDPIPE,
SUA.UA_ZPIPEFY		AS PIPEFY,
CASE
	WHEN SL2.L2_DOC <> ''
THEN '1 - 501'
	WHEN SL1.L1_DOCPED <> ''
THEN '2 - 700'
ELSE ''
END AS TIPOFIN
FROM SUA010 SUA
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SA4010 SA4 ON SA4.D_E_L_E_T_ = '' AND SA4.A4_COD = SUA.UA_ZCODFRT
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM AND SL1.L1_ORCRES = ''
LEFT JOIN SL2010 SL2 ON SL2.D_E_L_E_T_ = '' AND SL2.L2_FILIAL = SL1.L1_FILIAL AND SL2.L2_NUM = SL1.L1_NUM 
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_EMISSAO >= '20210329'
AND SUA.UA_OPER <> 3
AND SUA.UA_ZPIPEFY = ''
AND SUA.UA_ZCODFRT <> '000003'
AND CONCAT(SL2.L2_DOC,SL1.L1_DOCPED) <> ''
GROUP BY
SUA.UA_FILIAL,
SUA.UA_NUM,
SUA.UA_CLIENTE,
SA1.A1_NOME,
SUA.UA_VEND,
SA3.A3_NOME,
SA3.A3_EMAIL,
SUA.UA_EMISSAO,
SUA.UA_ZDTAENT,
SUA.UA_OPER,
SUA.UA_ZTIPVND,
SUA.UA_ZMONTAG,
SUA.UA_ZPLOTAG,
SUA.UA_ZCRTPNL,
SUA.UA_ZMONTPN,
SUA.UA_ZFINPEN,
SUA.UA_ZPRDMLT,
SUA.UA_ZPRDRIB,
SUA.UA_TPFRETE,
SUA.UA_ZZMSGNF,
SA1.A1_END,
SA1.A1_BAIRRO,
SA1.A1_MUN,
SA1.A1_EST,
SUA.UA_ZCODFRT,
SA4.A4_NOME,
SUA.UA_ZIDPIPE,
SUA.UA_ZPIPEFY,
SL2.L2_DOC,
SL1.L1_DOCPED

/*
'008943', 
'008942', 
'008940', 
'008921', 
'008908'
*/

/*
'034633', 
'033683', 
'033288', 
'033288', 
'034887',
'034602', 
'033683', 
'034757'
*/