
/* ----------------- ANALISE CONTABILIZAÇÃO (ARQUIVO INTEGRADO) ----------------- */

SELECT
A.DOCUMENTOCONTABIL,
A.DATAINCLUSAO,
B.HISTORICO,
B.COMPLEMENTO,
CAST(SUBSTRING(B.COMPLEMENTO,CHARINDEX('CLC', B.COMPLEMENTO)+4,99) AS INT) AS CLC,
--B.VALOR,
B.NATUREZA,
CASE 
	WHEN B.NATUREZA = 'D' THEN D.CODIGOREDUZIDO
ELSE 0
END AS CONTA_DEBITO,
CASE 
	WHEN B.NATUREZA = 'C' THEN D.CODIGOREDUZIDO
ELSE 0
END AS CONTA_CREDITO,
D.NOME,
CASE 
	WHEN B.NATUREZA = 'D' THEN B.VALOR
ELSE 0
END AS VAL_DEBITO,
CASE 
	WHEN B.NATUREZA = 'C' THEN B.VALOR
ELSE 0
END AS VAL_CREDITO
FROM CT_DOCUMENTOS A
LEFT JOIN CT_LANCAMENTOS B ON B.DOCUMENTO = A.HANDLE
LEFT JOIN CT_CONTAS D ON D.HANDLE = B.CONTA
WHERE 1=1
AND A.DOCUMENTOCONTABIL = 'CONTABIL-RP-JAN23'
AND CAST(SUBSTRING(B.COMPLEMENTO,CHARINDEX('CLC', B.COMPLEMENTO)+4,99) AS INT) IN (1250,1251,1252,1253)
--AND B.COMPLEMENTO LIKE '%HORAS%'
--AND B.NATUREZA = 'C'
--AND D.CODIGOREDUZIDO = 4171


