SELECT 
RESULTADO.DATA, 
RESULTADO.NATUREZA, 
RESULTADO.COMPLEMENTO,
--CAST(SUBSTRING(RESULTADO.COMPLEMENTO,CHARINDEX('CLC', RESULTADO.COMPLEMENTO)+4,99) AS INT) AS CLC,
CASE RESULTADO.NATUREZA WHEN 'C' THEN SUM(RESULTADO.VALOR) ELSE 0.00 END AS VALORCREDITO,
CASE RESULTADO.NATUREZA WHEN 'D' THEN SUM(RESULTADO.VALOR) ELSE 0.00 END AS VALORDEBITO
FROM 
(
	SELECT 
	LAN.HANDLE,
	LAN.CONTA,
	LAN.DATA,
	LAN.NATUREZA,
	LAN.VALOR,
	LAN.EMPRESA,
	LAN.HISTORICO CODHIS,
	CON.NOME NOMCONTA,
	CON.ESTRUTURA,
	CON.CODIGOREDUZIDO,
	LAN.COMPLEMENTO,
	CON.APELIDO,
	HIS.NOME HISTORICO
	FROM CT_LANCAMENTOS LAN
	JOIN CT_CONTAS CON ON LAN.CONTA = CON.HANDLE
	LEFT JOIN CT_HISTORICOSPADROES HIS ON LAN.HISTORICO = HIS.HANDLE
	WHERE 1=1
	AND LAN.DATA >= CONVERT(DATE,'2023-01-01')
	AND LAN.DATA <= CONVERT(DATE,'2023-01-31')
	--AND (CON.VERSAO  IN (1) OR -1 IN  (1))
	AND (LAN.CONTA IN (245) OR -1 IN  (245))
	AND (LAN.FILIAL IN (1,13,16,18,19,20,22,24,25) OR -1 IN  (1,13,16,18,19,20,22,24,25))
	AND LAN.LANCAMENTOGERADO IN ('N', 'F')
	AND LAN.LANCAMENTOGERADO <> 'B'  
	AND LAN.BLOQUEADO = 'N'
	AND LAN.EMPRESA = 1 
) AS RESULTADO
WHERE 1=1
--AND CAST(SUBSTRING(RESULTADO.COMPLEMENTO,CHARINDEX('CLC', RESULTADO.COMPLEMENTO)+4,99) AS INT) IN (1228)
GROUP BY 
RESULTADO.
COMPLEMENTO,
RESULTADO.DATA, 
RESULTADO.NATUREZA
ORDER BY 
RESULTADO.DATA

/*

AND LAN.DATA >= @CAMPO(EMISSAOINICIAL)
AND LAN.DATA <= @CAMPO(EMISSAOFINAL)
AND (CON.VERSAO  IN (@CAMPO(PLANOVERSAO)) OR -1 IN  (@CAMPO(PLANOVERSAO)) )
AND (LAN.CONTA IN (@CAMPO(CONTA)) OR -1 IN  (@CAMPO(CONTA)) )
AND (LAN.FILIAL IN (@CAMPO(FILIAL)) OR -1 IN  (@CAMPO(FILIAL)) )
AND LAN.LANCAMENTOGERADO IN ('N', 'F'   )
AND (LAN.LANCAMENTOGERADO <> 'B')  
AND (LAN.BLOQUEADO = 'N')
AND LAN.EMPRESA = @EMPRESA 

*/
