/* ----------------------------  SINTETICO ---------------------------- */

SELECT 
A.DOCUMENTOCONTABIL,
A.DATAINCLUSAO,
B.HISTORICO,
B.COMPLEMENTO,
CAST(SUBSTRING(B.COMPLEMENTO,CHARINDEX('CLC', B.COMPLEMENTO)+4,99) AS INT) AS CLC,
SUM(B.VALOR) AS VALOR
/*
'--------------------',
C.CENTROCUSTO,
C.PROJETO,
C.VALOR
*/
FROM CT_DOCUMENTOS A
LEFT JOIN CT_LANCAMENTOS B ON B.DOCUMENTO = A.HANDLE
--LEFT JOIN CT_LANCAMENTOCC C ON C.DOCUMENTO = A.HANDLE
WHERE 1=1
AND A.DOCUMENTOCONTABIL = 'FOL2_CONTABIL-JAN23'
--AND B.COMPLEMENTO LIKE '%HORAS%'
AND B.NATUREZA = 'C'
GROUP BY 
A.DOCUMENTOCONTABIL,
A.DATAINCLUSAO,
B.HISTORICO,
B.COMPLEMENTO,
CAST(SUBSTRING(B.COMPLEMENTO,CHARINDEX('CLC', B.COMPLEMENTO)+4,99) AS INT)


/* ----------------------------  ANALITICO ---------------------------- */


SELECT
A.DOCUMENTOCONTABIL,
A.DATAINCLUSAO,
B.HISTORICO,
B.COMPLEMENTO,
CAST(SUBSTRING(B.COMPLEMENTO,CHARINDEX('CLC', B.COMPLEMENTO)+4,99) AS INT) AS CLC,
B.VALOR,
B.NATUREZA,
D.CODIGOREDUZIDO,
D.NOME
/*
'--------------------',
C.CENTROCUSTO,
C.PROJETO,
C.VALOR
*/
FROM CT_DOCUMENTOS A
LEFT JOIN CT_LANCAMENTOS B ON B.DOCUMENTO = A.HANDLE
--LEFT JOIN CT_LANCAMENTOCC C ON C.DOCUMENTO = A.HANDLE
LEFT JOIN CT_CONTAS D ON D.HANDLE = B.CONTA
WHERE 1=1
AND A.DOCUMENTOCONTABIL = 'FOL2_CONTABIL-JAN23'
--AND B.COMPLEMENTO LIKE '%HORAS%'
--AND B.NATUREZA = 'C'



