

SELECT
B.EMPRESA AS EMPRESA,
B.MATRICULA AS MATRICULA,
B.NOME AS FUNCIONARIO,
A.AFASTAMENTO AS DT_AFASTAMENTO,
A.RETORNO AS DT_RETORNO,
D.CODIGO AS COD_MOTIVO,
D.NOME AS MOTIVO,
C.CODIGO AS CID,
C.DESCRICAO AS DESCRICAO_CID
FROM DO_FUNCIONARIOAFASTAMENTOS A
LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO
LEFT JOIN MS_CIDS C ON C.HANDLE = A.CID
LEFT JOIN FP_MOTIVOSAFASTAMENTOS D ON D.HANDLE = A.MOTIVO
WHERE 1=1
AND A.RETORNO IS NULL
--AND B.MATRICULA = 1487
--AND B.MATRICULA = 1089
