
SELECT 
C.EMPRESA AS EMPRESA,
C.MATRICULA AS MATRICULA,
C.NOME AS FUNCIONARIO,
D.NOME AS DEPEDENTE,
E.NOME AS BENEFICIO,
A.INICIO AS DT_INICIO,
A.FIM AS DT_FIM
FROM BS_FUNCIONARIODEPENDENTES A
LEFT JOIN BS_FUNCIONARIOBENEFICIOS B ON B.HANDLE = A.BENEFICIO
LEFT JOIN DO_FUNCIONARIOS C ON C.HANDLE = A.FUNCIONARIO
LEFT JOIN DO_FUNCIONARIODEPENDENTES D ON D.HANDLE = A.DEPENDENTE
LEFT JOIN BS_BENEFICIOS E ON E.HANDLE = B.BENEFICIO
WHERE 1=1
AND C.EMPRESA = 1
AND C.MATRICULA = 1954



