
SELECT
    A.CODIGO AS COD_EVENTO, 
    A.NOME AS EVENTO,
    B.ESOCIAL,
    B.NOME,
    B.DESCRICAO
FROM FP_VERBAS A
    LEFT JOIN TA_RUBRICAS B ON B.HANDLE = A.ESOCIALRUBRICA
WHERE 1=1
    AND A.CODIGO = 2002

