/* -------------------------------------------------- CONSULTA BASICA DE FUNCIONARIO -------------------------------------------------- */

SELECT
	A.EMPRESA 	 	 AS COD_EMPRESA,
	B.NOME 		 	 AS EMPRESA,
	A.MATRICULA 	 AS MATRICULA,
	A.NOME 			 AS FUNCIONARIO,
	E.TITULO 		 AS CARGO,
	CONVERT(VARCHAR, A.DATANASCIMENTO, 103) AS DT_NASCIMENTO,
CASE
	WHEN A.TIPOCOLABORADOR = 1 THEN 'Funcionario'
	WHEN A.TIPOCOLABORADOR = 2 THEN 'Terceiro'
	WHEN A.TIPOCOLABORADOR = 3 THEN 'Estagiario/Bolsista'
	WHEN A.TIPOCOLABORADOR = 4 THEN 'Requisitado'
	WHEN A.TIPOCOLABORADOR = 5 THEN 'Externo'
ELSE '' END AS TIPO_FUNCIONARIO,
	C.NOME 		AS SITUACAO,
	D.FOLHAS 		 AS FOLHAS
FROM DO_FUNCIONARIOS A 
LEFT JOIN ADM_EMPRESAS B ON B.HANDLE = A.EMPRESA
LEFT JOIN TA_SITUACOES C ON C.HANDLE = A.SITUACAO
LEFT JOIN FP_FUNCIONARIOPAGAMENTO D ON D.FUNCIONARIO = A.HANDLE
LEFT JOIN CS_CARGOS E ON E.HANDLE = A.CARGO
WHERE 1=1
AND A.SITUACAO = 2
AND A.MATRICULA = 2172

/* -------------------------------------------------- PAI E MAE (FUNCIONARIOS) -------------------------------------------------- */

SELECT
	A.EMPRESA 	AS COD_EMPRESA,
	B.NOME 		AS EMPRESA,
	A.MATRICULA AS MATRICULA,
CASE
	WHEN A.TIPOCOLABORADOR = 1 THEN 'Funcionario'
	WHEN A.TIPOCOLABORADOR = 2 THEN 'Terceiro'
	WHEN A.TIPOCOLABORADOR = 3 THEN 'Estagiario/Bolsista'
	WHEN A.TIPOCOLABORADOR = 4 THEN 'Requisitado'
	WHEN A.TIPOCOLABORADOR = 5 THEN 'Externo'
ELSE '' END AS TIPO_FUNCIONARIO,
	A.NOME 		AS FUNCIONARIO,
	A.MAE 		AS MAE,
	A.PAI 		AS PAI
FROM DO_FUNCIONARIOS A 
LEFT JOIN ADM_EMPRESAS B ON B.HANDLE = A.EMPRESA
WHERE 1=1
AND A.SITUACAO = 2
--AND A.MATRICULA = 2172

/* -------------------------------------------------- DEPENDENTES (FUNCIONARIOS) -------------------------------------------------- */

SELECT
	B.EMPRESA 	AS COD_EMPRESA,
	D.NOME 		AS EMPRESA,
	B.MATRICULA AS MATRICULA,
	B.NOME 		AS FUNCIONARIO,
	A.NOME 		AS DEPENDENTE,
	A.CPFNUMERO AS CPF_DEPENDENTE,
	A.TIPO 		AS COD_TIPO_DEPENDENTE,
	C.NOME 		AS TIPO_DEPENDENTE,
	B.SITUACAO 	AS COD_SITUACAO,
	E.NOME 		AS SITUACAO
FROM DO_FUNCIONARIODEPENDENTES A
LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO
LEFT JOIN TA_TIPOSDEPENDENTES C ON C.HANDLE = A.TIPO
LEFT JOIN ADM_EMPRESAS D ON D.HANDLE = B.EMPRESA
LEFT JOIN TA_SITUACOES E ON E.HANDLE = B.SITUACAO
WHERE 1=1
--AND B.SITUACAO = 2
--AND B.MATRICULA = 78

/* -------------------------------------------------- DEPENDENCIAS DOS DEPENDENTES -------------------------------------------------- */

SELECT
	B.EMPRESA 		 AS COD_EMPRESA,
	D.NOME 			 AS EMPRESA,
	B.MATRICULA 	 AS MATRICULA,
	B.NOME 			 AS FUNCIONARIO,
	A.NOME 			 AS DEPENDENTE,
	A.CPFNUMERO 	 AS CPF_DEPENDENTE,
	A.TIPO 			 AS COD_TIPO_DEPENDENTE,
	a.DATANASCIMENTO AS DATA_NASCIMENTO,
	C.NOME 			 AS TIPO_DEPENDENTE,
	B.SITUACAO 		 AS COD_SITUACAO,
	E.NOME 			 AS SITUACAO,
	A.DEPENDENCIAS 	 AS COD_DEPENDENCIA,
CASE
	WHEN A.DEPENDENCIAS = 1 THEN 'IRRF'
	WHEN A.DEPENDENCIAS = 2 THEN 'Salario familia'
	WHEN A.DEPENDENCIAS = 3 THEN 'Salario familia, IRRF'
	WHEN A.DEPENDENCIAS = 2147483647 THEN 'Todas, Salário Família, IRRF'
ELSE '' END 		 AS DEPENDENCIA
FROM DO_FUNCIONARIODEPENDENTES A
LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO
LEFT JOIN TA_TIPOSDEPENDENTES C ON C.HANDLE = A.TIPO
LEFT JOIN ADM_EMPRESAS D ON D.HANDLE = B.EMPRESA
LEFT JOIN TA_SITUACOES E ON E.HANDLE = B.SITUACAO
WHERE 1=1
--AND B.SITUACAO = 2
AND B.MATRICULA IN (2045)

