

SELECT
	B.EMPRESA 	AS COD_EMPRESA,
	D.NOME 		AS EMPRESA,
	B.MATRICULA AS MATRICULA,
	B.NOME 		AS FUNCIONARIO,
	A.INICIO 	AS INICIO,
	A.FIM 		AS FIM,
	A.MOTIVO 	AS COD_MOTIVO,
	C.NOME 		AS MOTIVO,
	A.SALARIO 	AS SALARIO
FROM DO_FUNCIONARIOSALARIOS A
	LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO
	LEFT JOIN CS_MOTIVOSREAJUSTE C ON C.HANDLE = A.MOTIVO
	LEFT JOIN ADM_EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE 1=1
--AND B.MATRICULA = 2172

