

SELECT
CONCAT(A.LOGRADOURO, ', ', A.BAIRRO, ', ', B.NOME, '/', C.SIGLA, ' - ', A.CEP) AS CHAVE,
A.CEP AS CEP,
A.LOGRADOURO AS RUA,
A.BAIRRO AS BAIRRO,
B.NOME AS MUNICIPIO,
C.SIGLA AS ESTADO
FROM TA_LOGRADOUROS A
LEFT JOIN TA_MUNICIPIOS B ON B.HANDLE = A.MUNICIPIO
LEFT JOIN TA_ESTADOS C ON C.HANDLE = B.ESTADO
WHERE 1=1
AND C.SIGLA = 'PE'
AND A.BAIRRO LIKE '%IPUTINGA%'
--AND LOGRADOURO LIKE '%MOACYR%'

