

SELECT 
Q1.EMPRESA,
Q1.MATRICULA,
Q1.FUNCIONARIO,
Q1.INICIO_PERIODO,
Q1.FIM_PERIODO,
AVG(Q1.DIAS_CREDITO) AS DIAS_FERIAS,
SUM(Q1.DIAS_ABONO) AS DIAS_ABONO, 
SUM(Q1.DIAS_GOZADOS) AS DIAS_GOZADOS,
AVG(Q1.DIAS_CREDITO) - (SUM(Q1.DIAS_ABONO) + SUM(Q1.DIAS_GOZADOS)) AS SALDO
 FROM
(
SELECT
B.EMPRESA 	AS EMPRESA,
B.MATRICULA AS MATRICULA,
B.NOME 		AS FUNCIONARIO,
A.INICIO 	AS INICIO_PERIODO,
A.FIM 		AS FIM_PERIODO,
(A.DIASCREDITO + A.DIASPROPORCIONAIS) AS DIAS_CREDITO,
CASE
	WHEN C.HANDLE IS NOT NULL THEN (C.DIASABONO1 + C.DIASABONO2)
	ELSE 0
END AS DIAS_ABONO,

CASE
	WHEN C.HANDLE IS NOT NULL THEN (C.DIASGOZOMES1 + C.DIASGOZOMES2 + C.DIASGOZOMES3)
	ELSE 0
END AS DIAS_GOZADOS
FROM FP_FUNCIONARIOFERIASADQUIRIDAS A
LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO 
LEFT JOIN FP_FUNCIONARIOFERIASGOZADAS C ON C.PERIODOADQUIRIDO = A.HANDLE
WHERE 1=1
AND B.SITUACAO = 2
--AND B.MATRICULA = 1254
--AND B.MATRICULA = 1048
--AND B.MATRICULA = 1961
--AND B.MATRICULA = 1442
--AND B.MATRICULA = 623
--AND A.DIASCREDITO > 0
) AS Q1
WHERE 1=1
GROUP BY
Q1.EMPRESA,
Q1.MATRICULA,
Q1.FUNCIONARIO,
Q1.INICIO_PERIODO,
Q1.FIM_PERIODO



