
/*------------------------------ VALORES FICOS FUNCIONARIOS -------------------------------*/

SELECT
B.EMPRESA		AS EMPRESA,
B.MATRICULA 	AS MATRICULA,
B.NOME			AS FUNCIONARIO,
A.INICIO		AS INICIO,
C.CODIGO		AS COD_VERBA,
C.NOME			AS VERBA,
A.PARCELAS		AS PARCELAS,
A.VALORMES		AS VALOR_MES,
A.VALORTOTAL 	AS VALOR_TOTAL,
CASE 
	WHEN A.CALCULO = 1 THEN 'INFINITO'
	WHEN A.CALCULO = 2 THEN 'N MESES'
ELSE '' END AS CALCULO,
A.CANCELADO		AS CANCELADO,
A.DATACANCELAMENTO AS DATA_CANCELAMENTO,
CASE
	WHEN B.TIPOCOLABORADOR = 1 THEN 'Funcionario'
	WHEN B.TIPOCOLABORADOR = 2 THEN 'Terceiro'
	WHEN B.TIPOCOLABORADOR = 3 THEN 'Estagiario/Bolsista'
	WHEN B.TIPOCOLABORADOR = 4 THEN 'Requisitado'
	WHEN B.TIPOCOLABORADOR = 5 THEN 'Externo'
ELSE '' END AS TIPO_FUNCIONARIO,
D.NOME 			AS SITUACAO
FROM FP_FUNCIONARIOVALORESFIXOS A
LEFT JOIN DO_FUNCIONARIOS B ON B.HANDLE = A.FUNCIONARIO
LEFT JOIN FP_VERBAS C ON C.HANDLE = A.VERBA
LEFT JOIN TA_SITUACOES D ON D.HANDLE = B.SITUACAO
WHERE 1=1

/*------------------------------ VALORES FICOS LOCAMEDI -------------------------------*/

SELECT 
	A.EMPRESA	AS COD_EMPRESA,
	E.NOME		AS EMPRESA,
	A.HANDLE	AS COD_BENEFICIO,
	A.NOME		AS BENEFICIO,
	C.MATRICULA	AS MATRICULA,
	C.NOME		AS FUNCIONARIO,
	D.VALOR		AS VALOR,
	C.SITUACAO	AS COD_SIT,
	F.NOME		AS SITUACAO
FROM BS_BENEFICIOS A
	LEFT JOIN BS_FUNCIONARIOBENEFICIOS B ON B.BENEFICIO = A.HANDLE
	LEFT JOIN DO_FUNCIONARIOS C ON C.HANDLE = B.FUNCIONARIO
	LEFT JOIN BS_CLASSES D ON D.BENEFICIO = A.HANDLE
	LEFT JOIN ADM_EMPRESAS E ON E.HANDLE = A.EMPRESA 
	LEFT JOIN TA_SITUACOES F ON F.HANDLE = C.SITUACAO
WHERE 1=1
	AND A.EMPRESA = 4
	AND A.TIPOBENEFICIO = 4
	AND A.HANDLE IN (25,26)
	AND C.SITUACAO <> 5

