

SELECT 
    A.RECIBOENTREGA,
    A.LEIAUTE,
    B.ESOCIAL,
    B.DESCRICAO,
    A.DESCRICAO,
    A.DATASITUACAO,
    A.PROTOCOLOENVIO,
    A.RECIBOENTREGA,
    A.XML,
    A.XMLRETORNO
FROM ES_AUDITORIAS A
    LEFT JOIN TA_TIPOARQUIVOS B ON B.HANDLE = A.LEIAUTE
WHERE 1=1
    --AND A.XMLRETORNO IS NOT NULL
    --AND A.RECIBOENTREGA  LIKE '%1.1.0000000016490311429%'
    --AND A.PROTOCOLOENVIO LIKE '%1.1.0000000016490311429%'
    --AND A.LEIAUTE = 27
    --AND A.DESCRICAO LIKE '%MILENE CRIS%'



