
CREATE PROCEDURE ATUALIZAZAC AS

/*PASSO 1 - DROPAR A TABELA PARA INICARMOS DO ZERO*/

DROP TABLE ZANALISECOMPRAS

/*PASSO 2 - CRIAR A TABERLA NOVAMENTE COM TODOS OS CAMPOS*/

CREATE TABLE ZANALISECOMPRAS
(
	ZAC_CODPROD			VARCHAR(15),
	ZAC_PRODUTO			VARCHAR(40),
	ZAC_CODAPRE			VARCHAR(18),
	ZAC_GRUPO			VARCHAR(4),
	ZAC_CODFORN			VARCHAR(6),
	ZAC_FORNECEDOR		VARCHAR(40),
	ZAC_FORNREDU		VARCHAR(20),
	ZAC_CODFAM			VARCHAR(6),
	ZAC_FAMILIA			VARCHAR(30),
	ZAC_DATA	  		VARCHAR(8),
	ZAC_QTD				FLOAT,
	ZAC_FINCUSTO		FLOAT,
	ZAC_FINVENDA		FLOAT,
	ZAC_FATCUSTO		FLOAT,
	ZAC_FATVENDA		FLOAT,
	ZAC_ENTRADA			FLOAT,
	ZAC_PEDIDOCOMPRA	FLOAT,
	ZAC_ATT				DATETIME
	
)


/*PASSO 3 - INSERIR FINANCEIRO NA TABELA ZAC*/

INSERT INTO ZANALISECOMPRAS 
(
	ZAC_CODPROD,
	ZAC_PRODUTO,
	ZAC_CODAPRE,
	ZAC_GRUPO,
	ZAC_CODFORN,
	ZAC_FORNECEDOR,
	ZAC_FORNREDU,
	ZAC_CODFAM,
	ZAC_FAMILIA,
	ZAC_DATA,
	ZAC_QTD,
	ZAC_FINCUSTO,
	ZAC_FINVENDA,
	ZAC_ATT
)

SELECT 
SB1.B1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SB1.B1_GRUPO,
SA2.A2_COD,
SA2.A2_NOME,
SA2.A2_NREDUZ,
ZB2.ZB2_CODFAM,
ZB2.ZB2_DESFAM,
SL1.L1_EMISNF,
SL2.L2_QUANT,
ISNULL((SELECT ZZ4_CSTUNI FROM ZZ4010 WHERE D_E_L_E_T_ = '' AND ZZ4_CODPRD = SB1.B1_COD AND ZZ4_ANOMES = CONCAT(SUBSTRING(SL1.L1_EMISNF,1,4), SUBSTRING(SL1.L1_EMISNF,5,2))),0) AS CUSTO, 
SL2.L2_VRUNIT,
GETDATE()
FROM SL1010 SL1
LEFT JOIN SL2010 SL2 ON SL2.D_E_L_E_T_ = '' AND SL2.L2_FILIAL = SL1.L1_FILIAL AND SL2.L2_NUM = SL1.L1_NUM
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SL2.L2_PRODUTO
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SB1.B1_PROC AND SA2.A2_LOJA = SB1.B1_LOJPROC
LEFT JOIN ZB2010 ZB2 ON ZB2.D_E_L_E_T_ = '' AND ZB2.ZB2_CODFAM = SB1.B1_ZCODFAM
WHERE 1=1
AND SL1.D_E_L_E_T_ = ''
AND SL1.L1_ORCRES = ''
AND SL1.L1_EMISNF <> ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'


/*PASSO 4 - INSERIR FATURADO NA TABELA ZAC*/

INSERT INTO ZANALISECOMPRAS 
(
	ZAC_CODPROD,
	ZAC_PRODUTO,
	ZAC_CODAPRE,
	ZAC_GRUPO,
	ZAC_CODFORN,
	ZAC_FORNECEDOR,
	ZAC_FORNREDU,
	ZAC_CODFAM,
	ZAC_FAMILIA,
	ZAC_DATA,
	ZAC_QTD,
	ZAC_FATCUSTO,
	ZAC_FATVENDA,
	ZAC_ATT
)

SELECT 
SB1.B1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SB1.B1_GRUPO,
SA2.A2_COD,
SA2.A2_NOME,
SA2.A2_NREDUZ,
ZB2.ZB2_CODFAM,
ZB2.ZB2_DESFAM,
SF2.F2_EMISSAO,
SD2.D2_QUANT,
ISNULL((SELECT ZZ4_CSTUNI FROM ZZ4010 WHERE D_E_L_E_T_ = '' AND ZZ4_CODPRD = SB1.B1_COD AND ZZ4_ANOMES = CONCAT(SUBSTRING(SF2.F2_EMISSAO,1,4), SUBSTRING(SF2.F2_EMISSAO,5,2))),0) AS CUSTO, 
SD2.D2_PRCVEN,
GETDATE()
FROM SF2010 SF2  
LEFT JOIN SD2010 SD2 ON SD2.D2_FILIAL = SF2.F2_FILIAL AND SD2.D2_SERIE = SF2.F2_SERIE AND SD2.D2_DOC = SF2.F2_DOC AND SD2.D2_CLIENTE = SF2.F2_CLIENTE AND SD2.D2_LOJA = SF2.F2_LOJA
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD2.D2_COD
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SB1.B1_PROC AND SA2.A2_LOJA = SB1.B1_LOJPROC
LEFT JOIN ZB2010 ZB2 ON ZB2.D_E_L_E_T_ = '' AND ZB2.ZB2_CODFAM = SB1.B1_ZCODFAM
WHERE 1=1 
AND SF2.D_E_L_E_T_ = ''
AND SD2.D2_TIPO = 'N'
AND SF2.F2_CLIENTE NOT IN ('022105','025201','003669','006104','024752','021950','001798')
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'


/*PASSO 5 - INSERIR ENTRADA NA TABELA ZAC*/

INSERT INTO ZANALISECOMPRAS 
(
	ZAC_CODPROD,
	ZAC_PRODUTO,
	ZAC_CODAPRE,
	ZAC_GRUPO,
	ZAC_CODFORN,
	ZAC_FORNECEDOR,
	ZAC_FORNREDU,
	ZAC_CODFAM,
	ZAC_FAMILIA,
	ZAC_DATA,
	ZAC_QTD,
	ZAC_ENTRADA,
	ZAC_ATT
)

SELECT 
SB1.B1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SB1.B1_GRUPO,
SA2.A2_COD,
SA2.A2_NOME,
SA2.A2_NREDUZ,
ZB2.ZB2_CODFAM,
ZB2.ZB2_DESFAM,
SD1.D1_DTDIGIT,
SD1.D1_QUANT,
ISNULL((SELECT ZZ4_CSTUNI FROM ZZ4010 WHERE D_E_L_E_T_ = '' AND ZZ4_CODPRD = SB1.B1_COD AND ZZ4_ANOMES = CONCAT(SUBSTRING(SD1.D1_DTDIGIT,1,4), SUBSTRING(SD1.D1_DTDIGIT,5,2))),0) AS CUSTO, 
GETDATE()
FROM SD1010 SD1
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD1.D1_COD
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SB1.B1_PROC AND SA2.A2_LOJA = SB1.B1_LOJPROC
LEFT JOIN ZB2010 ZB2 ON ZB2.D_E_L_E_T_ = '' AND ZB2.ZB2_CODFAM = SB1.B1_ZCODFAM
WHERE 1=1
AND SD1.D_E_L_E_T_ = ''
AND SD1.D1_PEDIDO <> ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'



/*PASSO 6 - INSERIR PEDIDO DE COMPRAS NA TABELA ZAC*/


INSERT INTO ZANALISECOMPRAS 
(
	ZAC_CODPROD,
	ZAC_PRODUTO,
	ZAC_CODAPRE,
	ZAC_GRUPO,
	ZAC_CODFORN,
	ZAC_FORNECEDOR,
	ZAC_FORNREDU,
	ZAC_CODFAM,
	ZAC_FAMILIA,
	ZAC_DATA,
	ZAC_QTD,
	ZAC_PEDIDOCOMPRA,
	ZAC_ATT
)

SELECT 
SB1.B1_COD,
SB1.B1_ZDESRDZ,
SB1.B1_ZAPRES1,
SB1.B1_GRUPO,
SA2.A2_COD,
SA2.A2_NOME,
SA2.A2_NREDUZ,
ZB2.ZB2_CODFAM,
ZB2.ZB2_DESFAM,
SC7.C7_EMISSAO,
SC7.C7_QUANT,
ISNULL((SELECT ZZ4_CSTUNI FROM ZZ4010 WHERE D_E_L_E_T_ = '' AND ZZ4_CODPRD = SB1.B1_COD AND ZZ4_ANOMES = CONCAT(SUBSTRING(SC7.C7_EMISSAO,1,4), SUBSTRING(SC7.C7_EMISSAO,5,2))),0) AS CUSTO, 
GETDATE() 
FROM SC7010 SC7
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SC7.C7_PRODUTO
LEFT JOIN SA2010 SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SB1.B1_PROC AND SA2.A2_LOJA = SB1.B1_LOJPROC
LEFT JOIN ZB2010 ZB2 ON ZB2.D_E_L_E_T_ = '' AND ZB2.ZB2_CODFAM = SB1.B1_ZCODFAM
WHERE 1=1
AND SC7.D_E_L_E_T_ = ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MR'

