

DEFINE @VENDEDOR 000096 	VARCHAR(6)

/*------------------- 1 - VARIAVEIS -------------------*/

DECLARE @VENDEDOR 			VARCHAR(6)
DECLARE @SP		 			VARCHAR(2)
DECLARE @MG					VARCHAR(2)
DECLARE @COD_CLI_SP_1		VARCHAR(6)
DECLARE @COD_CLI_SP_2		VARCHAR(6)
DECLARE @COD_CLI_MG_1		VARCHAR(6)
DECLARE @COD_CLI_MG_2		VARCHAR(6)
DECLARE @NOME_N_CONTRI_SP	VARCHAR(70)
DECLARE @NOME_CONTRI_SP  	VARCHAR(70)
DECLARE @NOME_N_CONTRI_MG	VARCHAR(70)
DECLARE @NOME_CONTRI_MG  	VARCHAR(70)
DECLARE @NOME_VENDEDOR		VARCHAR(40)
DECLARE @RECNO				INT

/*------------------- 2 - SETANDO VARIAVEIS -------------------*/

SET @VENDEDOR = $(@VENDEDOR)
SET @SP = 'SP'
SET @MG = 'MG'
SET @COD_CLI_SP_1 = CONCAT(@SP,SUBSTRING(@VENDEDOR,4,3),1)
SET @COD_CLI_SP_2 = CONCAT(@SP,SUBSTRING(@VENDEDOR,4,3),2)
SET @COD_CLI_MG_1 = CONCAT(@MG,SUBSTRING(@VENDEDOR,4,3),1)
SET @COD_CLI_MG_2 = CONCAT(@MG,SUBSTRING(@VENDEDOR,4,3),2)
SET @NOME_VENDEDOR = ISNULL((SELECT A3_NREDUZ FROM SA3010 WHERE D_E_L_E_T_ = '' AND A3_COD = @VENDEDOR),'')
SET @NOME_N_CONTRI_SP = CONCAT('CONSUMIDOR NAO CONTRIBUINTE', ' ', @SP, ' ', @NOME_VENDEDOR)
SET @NOME_CONTRI_SP = CONCAT('CONSUMIDOR CONTRIBUINTE', ' ', @SP, ' ', @NOME_VENDEDOR)
SET @NOME_N_CONTRI_MG = CONCAT('CONSUMIDOR NAO CONTRIBUINTE', ' ', @MG, ' ', @NOME_VENDEDOR)
SET @NOME_CONTRI_MG = CONCAT('CONSUMIDOR CONTRIBUINTE', ' ', @MG, ' ', @NOME_VENDEDOR)
SET @RECNO = ISNULL((SELECT MAX(R_E_C_N_O_) FROM SA1010),0) + 1

/*------------------- 3 - UPDATE NA TABELA AUXILIAR -------------------*/

UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_SP_1, ZCP_A1_NOME = @NOME_CONTRI_SP, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO
WHERE 1=1 AND ZCP_A1_PESSOA = 'F' AND ZCP_A1_CONTRIB = '1' AND ZCP_A1_EST = 'SP'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_SP_2, ZCP_A1_NOME = @NOME_N_CONTRI_SP, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 1
WHERE 1=1 AND ZCP_A1_PESSOA = 'F' AND ZCP_A1_CONTRIB = '2' AND ZCP_A1_EST = 'SP'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_SP_1, ZCP_A1_NOME = @NOME_CONTRI_SP, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 2
WHERE 1=1 AND ZCP_A1_PESSOA = 'J' AND ZCP_A1_CONTRIB = '1' AND ZCP_A1_EST = 'SP'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_SP_2, ZCP_A1_NOME = @NOME_N_CONTRI_SP, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 3
WHERE 1=1 AND ZCP_A1_PESSOA = 'J' AND ZCP_A1_CONTRIB = '2' AND ZCP_A1_EST = 'SP'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_MG_1, ZCP_A1_NOME = @NOME_CONTRI_MG, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 4
WHERE 1=1 AND ZCP_A1_PESSOA = 'F' AND ZCP_A1_CONTRIB = '1' AND ZCP_A1_EST = 'MG'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_MG_2, ZCP_A1_NOME = @NOME_N_CONTRI_MG, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 5
WHERE 1=1 AND ZCP_A1_PESSOA = 'F' AND ZCP_A1_CONTRIB = '2' AND ZCP_A1_EST = 'MG'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_MG_1, ZCP_A1_NOME = @NOME_CONTRI_MG, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 6
WHERE 1=1 AND ZCP_A1_PESSOA = 'J' AND ZCP_A1_CONTRIB = '1' AND ZCP_A1_EST = 'MG'
UPDATE ZCP SET ZCP_A1_COD = @COD_CLI_MG_2, ZCP_A1_NOME = @NOME_N_CONTRI_MG, ZCP_A1_VEND = @VENDEDOR, ZCP_A1_ZVEND = @VENDEDOR, ZCP_R_E_C_N_O_ = @RECNO + 7
WHERE 1=1 AND ZCP_A1_PESSOA = 'J' AND ZCP_A1_CONTRIB = '2' AND ZCP_A1_EST = 'MG'


SELECT * FROM ZCP

/*------------------- 4 - INSERT NA TABELA SA1 (FAZER ISSO MANUALMENTE) -------------------*/

/*
INSERT INTO SA1010
SELECT * FROM ZCP
*/

/*------------------- 5 - SELECT DE TESTE -------------------*/

/*
SELECT TOP 1 ZCP_A1_COD,ZCP_A1_LOJA,ZCP_A1_PESSOA,ZCP_A1_NOME,ZCP_A1_VEND,ZCP_A1_ZVEND,ZCP_R_E_C_N_O_ FROM ZCP

SELECT TOP 1 A1_COD,A1_LOJA,A1_PESSOA,A1_NOME,A1_VEND,A1_ZVEND,R_E_C_N_O_ FROM SA1010 
*/













