
/*------------------------ALTERAÇÃO DATA VENCIMENTO------------------------------*/
/*----------------------------CONSULTA APENAS------------------------------------*/
/*------------------------ALTERAR A DATA PELO APSDU------------------------------*/


SELECT 
A.E1_FILIAL AS FILIAL,
A.E1_LOJA AS LOJA,
A.E1_NUM AS NUMERO,
A.E1_CLIENTE AS CLIENTE,
A.E1_VALOR AS VALOR,
CONVERT(VARCHAR,CAST(A.E1_VENCTO AS DATETIME),103) AS DATA_VENC,
CONVERT(VARCHAR,CAST(A.E1_VENCREA AS DATETIME),103) AS DATA_VENC_REAL,
CONVERT(VARCHAR,CAST(A.E1_EMIS1 AS DATETIME),103) AS DATA_EMISSAO,
CONVERT(VARCHAR,CAST(A.E1_VENCORI AS DATETIME),103) AS DATA_VENC_ORIGINAL
FROM SE1010 A




