

SELECT 
DISTINCT(
SB2.B2_LOCAL
),
NNR.NNR_DESCRI,
SUM(SB2.B2_QATU)	AS SLD_FIS,
SUM(SB2.B2_RESERVA)	AS SLD_RES,
SUM(SB2.B2_QATU - SB2.B2_RESERVA)	AS SLD_DISP
FROM SB2010 SB2
LEFT JOIN NNR010 NNR ON NNR.D_E_L_E_T_ = '' AND NNR.NNR_CODIGO = SB2.B2_LOCAL
WHERE 1=1
AND SB2.D_E_L_E_T_ = ''
AND SB2.B2_LOCAL <> '00'
GROUP BY 
SB2.B2_LOCAL,
NNR.NNR_DESCRI


