
DEFINE @variavel1 VARCHAR(4)
DEFINE @variavel2 VARCHAR(60)
DECLARE @variavel1 VARCHAR(4)
DECLARE @variavel2 VARCHAR(60)
SET @variavel1 = $(@variavel1)
SET @variavel2 = $(@variavel2)
SELECT
A.UA_FILIAL,
A.UA_NUM,
A.UA_CLIENTE,
A.UA_LOJA,
B.A1_COD,
B.A1_PESSOA,
B.A1_NOME,
B.A1_END,
B.A1_EST,
B.A1_MUN,
B.A1_BAIRRO
FROM SUA010 AS A, SA1010 AS B
WHERE
A.UA_CLIENTE = B.A1_COD AND 
A.UA_FILIAL = @variavel1 AND
B.A1_MUN LIKE @variavel2

