
/*-----------------------COM ISNULL-------------------------*/

SELECT  
ISNULL(CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX),UA_ZINFCOM)),'') AS OBSVND,
CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX),UA_ZINFCOM))
FROM SUA010 
WHERE D_E_L_E_T_ = '' 
AND UA_FILIAL = '0101' 
AND UA_NUM = '031378'


/*-----------------------SEM ISNULL-------------------------*/


SELECT  
UA_ZINFCOM,
CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX),UA_ZINFCOM)) AS OBSVND
FROM SUA010 
WHERE D_E_L_E_T_ = '' 
AND UA_FILIAL = '0101' 
AND UA_NUM = '031378'





