

DEFINE @filial VARCHAR(4)
DEFINE @num_atm VARCHAR(6)
DECLARE @filial VARCHAR(4)
DECLARE @num_atm VARCHAR(6)
SET @filial = $(@filial)
SET @num_atm = $(@num_atm)
SELECT A.UB_ITEM,A.UB_PRODUTO,B.B1_DESC,A.UB_QUANT,A.UB_UM,A.UB_VRUNIT,A.UB_VLRITEM,C.UA_VEND,
D.A2_NOME
FROM SUB010 AS A, SB1010 AS B, SUA010 AS C, SA2010 AS D
WHERE A.D_E_L_E_T_ = '' AND B.D_E_L_E_T_ = '' AND C.D_E_L_E_T_ = ''
AND A.UB_PRODUTO = B.B1_COD
AND A.UB_FILIAL = @filial
AND A.UB_NUM = @num_atm  
AND A.UB_FILIAL = C.UA_FILIAL
AND A.UB_NUM = C.UA_NUM
AND D.A2_COD = B.B1_PROC
AND D.A2_LOJA = B.B1_LOJPROC
ORDER BY A.UB_ITEM


