
/*
INSERT INTO SA1010
(
A1_FILIAL
A1_COD,
A1_LOJA,
A1_PESSOA,
A1_NOME,
A1_NREDUZ,
A1_END,
A1_TIPO,
A1_COD_MUN,
A1_MUN,
A1_BAIRRO,
A1_CEP,
A1_DDI,
A1_DDD,
A1_TEL,
A1_INSCR,
A1_ZVEND,
A1_ATIVIDA,
A1_EMAIL,
A1_ZAGREC
)
VALUES
(
'01 (FIXO)',
SELECT ISNULL((SELECT MAX(A1_COD) + 1 FROM SA1010  WHERE 1=1 AND LEN(A1_COD) = 6 AND A1_COD NOT LIKE '%TO%' AND A1_COD NOT LIKE '%SP%' AND A1_COD NOT LIKE '%SE%' AND A1_COD NOT LIKE '%SC%' AND A1_COD NOT LIKE '%RJ%' AND A1_COD NOT LIKE '%MG%' AND A1_COD NOT LIKE '%RS%' AND A1_COD NOT LIKE '%DF%' AND A1_COD NOT LIKE '%PR%' AND A1_COD NOT LIKE '%PI%' AND A1_COD NOT LIKE '%RN%' AND A1_COD NOT LIKE '%RO%' AND A1_COD NOT LIKE '%RR%' AND A1_COD NOT LIKE '%PE%' AND A1_COD NOT LIKE '%PB%' AND A1_COD NOT LIKE '%PA%' AND A1_COD NOT LIKE '%MT%' AND A1_COD NOT LIKE '%MS%' AND A1_COD NOT LIKE '%MA%' AND A1_COD NOT LIKE '%GO%' AND A1_COD NOT LIKE '%ES%' AND A1_COD NOT LIKE '%CE%' AND A1_COD NOT LIKE '%BA%' AND A1_COD NOT LIKE '%AP%' AND A1_COD NOT LIKE '%AM%' AND A1_COD NOT LIKE '%AL%' AND A1_COD NOT LIKE '%AC%'),0) AS MAX_COD_CLI, 
'01 (FIXO)',
'PESSOA FISICA OU JURIDICA (J ou F)',
'NOME DO CLIENTE',
'NOME REDUZIDO DO CLIENTE',
'ENDEREÇO DO CLIENTE',
'F (FIXO)',
'ESTADO DO CLIENTE (2 CARACTERES)',
'COD. MUNICIPIO',
'MUNICIPIO DO CLIENTE',
'BAIRRO DO CLIENTE',
'CEP DO CLIENTE',
'55 (FIXO)',
'DDD DO CLIENTE',
'TELEFONE DO CLIENTE',
'INSCRIÇÃO ESTADUAL',
'COD VENDEDOR',
'COD ATIVIDADE CLIENTE',
'EMAIL CLIENTE',
'L (FISICO)'
)
*/



SELECT 
MAX(A1_COD) + 1
FROM SA1010 
WHERE 1=1
AND LEN(A1_COD) = 6
AND A1_COD NOT LIKE '%TO%'
AND A1_COD NOT LIKE '%SP%'
AND A1_COD NOT LIKE '%SE%'
AND A1_COD NOT LIKE '%SC%'
AND A1_COD NOT LIKE '%RJ%'
AND A1_COD NOT LIKE '%MG%'
AND A1_COD NOT LIKE '%RS%'
AND A1_COD NOT LIKE '%DF%'
AND A1_COD NOT LIKE '%PR%'
AND A1_COD NOT LIKE '%PI%'
AND A1_COD NOT LIKE '%RN%'
AND A1_COD NOT LIKE '%RO%'
AND A1_COD NOT LIKE '%RR%'
AND A1_COD NOT LIKE '%PE%'
AND A1_COD NOT LIKE '%PB%'
AND A1_COD NOT LIKE '%PA%'
AND A1_COD NOT LIKE '%MT%'
AND A1_COD NOT LIKE '%MS%'
AND A1_COD NOT LIKE '%MA%'
AND A1_COD NOT LIKE '%GO%'
AND A1_COD NOT LIKE '%ES%'
AND A1_COD NOT LIKE '%CE%'
AND A1_COD NOT LIKE '%BA%'
AND A1_COD NOT LIKE '%AP%'
AND A1_COD NOT LIKE '%AM%'
AND A1_COD NOT LIKE '%AL%'
AND A1_COD NOT LIKE '%AC%'

