
SELECT 
SUA.UA_FILIAL		AS FILIAL,
SUA.UA_NUM			AS ATENDIMENTO,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS EMISSAO,
SUB.UB_PRODUTO		AS CODPROD,
SB1.B1_ZDESRDZ		AS PRODUTO,
SUB.UB_ITEM			AS ITEM,
SUB.UB_QUANT		AS QTD,
SB5.B5_ALTURA		AS ALTURA,
SB5.B5_LARG			AS LARGURA,
SB5.B5_COMPR		AS PROFUNDIDADE,
SB1.B1_PESBRU		AS PESO,
SB5.B5_LARG * SB5.B5_COMPR AS M2_UNIT,
SB5.B5_LARG * SB5.B5_COMPR * SB5.B5_ALTURA AS M3_UNIT,
(SB5.B5_LARG * SB5.B5_COMPR) * SUB.UB_QUANT AS M2_TOTAL,
(SB5.B5_LARG * SB5.B5_COMPR * SB5.B5_ALTURA) * SUB.UB_QUANT AS M3_TOTAL,
SUA.UA_CLIENTE		AS COD_CLI,
SA1.A1_NOME			AS CLIENTE,
SUA.UA_VEND			AS COD_VEND,
SA3.A3_NOME			AS VENDEDOR,
SUA.UA_ZMONTAG		AS MONTAGEM,
SUA.UA_ZPLOTAG		AS PLOTAGEM,
SUA.UA_ZPRDMLT		AS PROD_MLT,
SUA.UA_ZPRDRIB		AS PROD_RIB,
SUA.UA_ZCRTPNL		AS CORTE_PAINEL,
CASE
	WHEN SUA.UA_ZMONTPN = 'Z'
THEN 'ZANOTTI'
	WHEN SUA.UA_ZMONTPN = 'P'
THEN 'PARCEIRO'
	WHEN SUA.UA_ZMONTPN = 'R'
THEN 'RESPONSAVEL CLIENTE'
ELSE ''
END AS MONTAGEM_PAINEL,
CASE
	WHEN SUA.UA_ZPROJET = '1'
THEN 'FELIPE PARENTE'
	WHEN SUA.UA_ZPROJET = '2'
THEN 'RHUAN ZATTONI'
	WHEN SUA.UA_ZPROJET = '3'
THEN 'EVELIN BARROS'
	WHEN SUA.UA_ZPROJET = '4'
THEN 'GABRIEL MENDES'
ELSE ''
END AS PROJETISTA,
CASE
	WHEN SUA.UA_ZCODFRT = '000001'
THEN 'ZANOTTI REFRIGERACAO'	
	WHEN SUA.UA_ZCODFRT = '000002'
THEN 'CLIENTE RETIRA MATRIZ'
	WHEN SUA.UA_ZCODFRT = '000003'
THEN 'CLIENTE RETIRA DOM PEDRO'
ELSE 'TRANSPORTADORA'
END AS TIPO_TRANSPORTE,
SUA.UA_ZIDPIPE		AS PIPEDRIVE,
SUA.UA_ZPIPEFY		AS PIPEFY,
CASE
	WHEN SUA.UA_OPER = '1'
THEN 'NF EMITIDA'
	WHEN SUA.UA_OPER = '2'
THEN 'VENDA CONFIRMADA'
	WHEN SUA.UA_OPER = '3'
THEN 'EM ATENDIMENTO'
	WHEN SUA.UA_OPER = '4'
THEN 'LIB P/ FATURAR'
ELSE ''
END AS OPERACAO
FROM SUA010 SUA
LEFT JOIN SUB010 SUB ON SUB.D_E_L_E_T_ = '' AND SUB.UB_FILIAL = SUA.UA_FILIAL AND SUB.UB_NUM = SUA.UA_NUM
LEFT JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SUB.UB_PRODUTO
LEFT JOIN SB5010 SB5 ON SB5.D_E_L_E_T_ = '' AND SB5.B5_COD = SUB.UB_PRODUTO
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND SUA.UA_ZPIPEFY = 'S'
AND SUBSTRING(SB1.B1_GRUPO,1,2) = 'MP'
--AND SUA.UA_EMISSAO BETWEEN @3_DTINI AND @4_DTFIN
AND SUA.UA_NUM = '034556'
