/////////////////////////////////////////////////////////////////////////////////////
//                                                                                 //   
//                   Pedido de Compra Dentro do Prazo de Entregua                  //
//                                                                                 // 
//  3- Prazo de Entrega do Fornecedor Menor que a Data do Atendimento ao Cliente   //
//                                                                                 //   
/////////////////////////////////////////////////////////////////////////////////////

SELECT 	A.C7_FILIAL,A.C7_NUM,A.C7_ITEM,A.C7_PRODUTO,I.B1_DESC,A.C7_LOCAL,
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0101' AND B2_LOCAL = A.C7_LOCAL AND B2_COD = A.C7_PRODUTO ),0) AS SLDFIL01ARZ01,
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0102' AND B2_LOCAL = A.C7_LOCAL AND B2_COD = A.C7_PRODUTO ),0) AS SLDFIL02ARZ01,
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0103' AND B2_LOCAL = A.C7_LOCAL AND B2_COD = A.C7_PRODUTO ),0) AS SLDFIL03ARZ01,
		ISNULL((SELECT  SUM(B2_RESERVA)  FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_LOCAL  = A.C7_LOCAL AND B2_COD = A.C7_PRODUTO),0) AS QTDRES,
		ISNULL((SELECT (SUM(B2_QATU)-(SUM(B2_RESERVA)+SUM(B2_QEMPPRE)))  FROM SB2010 
		WHERE D_E_L_E_T_ = '' AND  B2_LOCAL = A.C7_LOCAL AND B2_COD = A.C7_PRODUTO ),0) AS SLDDIS,
		A.C7_UM,A.C7_QUANT,C7_QUJE,C7_QTDSOL,A.C7_CC,CONVERT(VARCHAR,CAST(A.C7_EMISSAO AS DATETIME),103) AS EMISSAO,
     	B.C1_SOLICIT,D.L1_CLIENTE,D.L1_LOJA,G.A1_NREDUZ,D.L1_VEND,H.A3_NREDUZ,B.C1_FILENT,D.L1_NUMATEN,B.C1_ORCAM,B.C1_PEDRES,
     	A.C7_NUMSC,A.C7_DATPRF,F.UA_ZDTAENT
FROM SC7010 A
LEFT JOIN SC1010 AS B ON B.D_E_L_E_T_ = '' AND B.C1_FILIAL = A.C7_FILIAL AND B.C1_NUM  = A.C7_NUMSC  AND B.C1_ITEM = A.C7_ITEMSC AND B.C1_PRODUTO = A.C7_PRODUTO
LEFT JOIN SL2010 AS C ON C.D_E_L_E_T_ = '' AND C.L2_FILIAL = B.C1_FILENT AND C.L2_NUM  = B.C1_ORCAM  AND C.L2_ITEM = B.C1_ITEM AND C.L2_PRODUTO = B.C1_PRODUTO AND L2_ENTREGA = '3'
LEFT JOIN SL1010 AS D ON D.D_E_L_E_T_ = '' AND D.L1_FILIAL = B.C1_FILENT AND D.L1_NUM  = B.C1_ORCAM
LEFT JOIN SC6010 AS E ON E.D_E_L_E_T_ = '' AND E.C6_FILIAL = B.C1_FILIAL AND E.C6_NUM  = B.C1_PEDRES AND E.C6_ITEM = B.C1_ITEM AND E.C6_PRODUTO = B.C1_PRODUTO
LEFT JOIN SUA010 AS F ON F.D_E_L_E_T_ = '' AND F.UA_FILIAL = D.L1_FILIAL AND F.UA_NUM  = D.L1_NUMATEN
LEFT JOIN SA1010 AS G ON G.D_E_L_E_T_ = '' AND G.A1_COD = D.L1_CLIENTE   AND G.A1_LOJA = D.L1_LOJA
LEFT JOIN SA3010 AS H ON H.D_E_L_E_T_ = '' AND H.A3_COD = D.L1_VEND 
LEFT JOIN SB1010 AS I ON I.D_E_L_E_T_ = '' AND I.B1_COD = A.C7_PRODUTO
WHERE A.D_E_L_E_T_ 	= '' 
AND B.C1_COTACAO 	<> ''
AND B.C1_FORNECE 	<> ''
AND B.C1_LOJA 		<> ''
AND A.C7_ENCER  	= 'E'
AND A.C7_DATPRF < F.UA_ZDTAENT OR A.C7_QUJE >= A.C7_QTDSOL  
AND B.C1_PEDIDO		<> ''
AND SUBSTRING(B.C1_CC,1,2) = 'MR'