//////////////////////////////////////////////////////////////////////////////
//                                                                          //   
//  		        Solicita��es de Compras N�o Entregue                    //
//                                                                          // 
//  1- Solicita��es de Compras Sem Pedido de Compra e com Data de Entrega   //
//                                                                          //   
//////////////////////////////////////////////////////////////////////////////

SELECT 	A.C1_FILIAL,A.C1_NUM,A.C1_ITEM,A.C1_PRODUTO,B.B1_DESC,B.B1_ZAPRES1, A.C1_LOCAL,
		-- Saldo Produto  --
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0101' AND B2_LOCAL = A.C1_LOCAL AND B2_COD = A.C1_PRODUTO ),0) AS SLDFIL01ARZ01,
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0102' AND B2_LOCAL = A.C1_LOCAL AND B2_COD = A.C1_PRODUTO ),0) AS SLDFIL02ARZ01,
		ISNULL((SELECT  SUM(B2_QATU)     FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_FILIAL = '0103' AND B2_LOCAL = A.C1_LOCAL AND B2_COD = A.C1_PRODUTO ),0) AS SLDFIL03ARZ01,
		ISNULL((SELECT  SUM(B2_RESERVA)  FROM SB2010 WHERE D_E_L_E_T_ = '' AND  B2_LOCAL  = A.C1_LOCAL AND B2_COD = A.C1_PRODUTO),0) AS QTDRES,
		ISNULL((SELECT (SUM(B2_QATU)-(SUM(B2_RESERVA)+SUM(B2_QEMPPRE)))  FROM SB2010 
		WHERE D_E_L_E_T_ = '' AND  B2_LOCAL = A.C1_LOCAL AND B2_COD = A.C1_PRODUTO ),0) AS SLDDIS,B.B1_PROC,B.B1_LOJPROC,I.A2_NREDUZ,
		A.C1_UM,A.C1_QUANT,C1_QUJE,A.C1_CC,CONVERT(VARCHAR,CAST(A.C1_EMISSAO AS DATETIME),103) AS EMISC,
       	A.C1_SOLICIT,D.L1_CLIENTE,D.L1_LOJA,G.A1_NOME,G.A1_NREDUZ,D.L1_VEND,H.A3_NREDUZ,A.C1_FILENT,D.L1_NUMATEN,A.C1_ORCAM,A.C1_PEDRES,
       	A.C1_PEDIDO,
       	       	
--     	CONVERT(VARCHAR,CAST(F.UA_ZDTAENT AS DATETIME),103) AS DATATM,J.B1_PE,       	
--     	CONVERT(VARCHAR,CAST(A.C1_DATPRF AS DATETIME),103) AS PRVENT,
--     	DIFDIAS=(CASE WHEN A.C1_DATPRF = '' OR F.UA_ZDTAENT = '' THEN 0 ELSE DATEDIFF(day,A.C1_DATPRF,F.UA_ZDTAENT) END),
--      CONVERT(VARCHAR,CAST(GETDATE() AS DATETIME),103) AS HOJE

		A.C1_PEDIDO,CONVERT(VARCHAR,CAST(F.UA_ZDTAENT AS DATETIME),103) AS DATATM,J.B1_PE,CONVERT(VARCHAR,CAST(A.C1_DATPRF AS DATETIME),103) AS PRVENT,
     	DIFDIAS=(CASE WHEN A.C1_DATPRF = '' OR F.UA_ZDTAENT = '' THEN 0 ELSE DATEDIFF(day,A.C1_DATPRF,F.UA_ZDTAENT) END)

FROM SC1010 AS A
LEFT JOIN SB1010 AS B ON B.D_E_L_E_T_ = '' AND B.B1_COD = A.C1_PRODUTO
LEFT JOIN SL2010 AS C ON C.D_E_L_E_T_ = '' AND C.L2_FILIAL = A.C1_FILENT AND C.L2_NUM  = A.C1_ORCAM  AND C.L2_PRODUTO = A.C1_PRODUTO AND C.L2_LOCAL = A.C1_LOCAL AND L2_ENTREGA = '3'
LEFT JOIN SL1010 AS D ON D.D_E_L_E_T_ = '' AND D.L1_FILIAL = A.C1_FILENT AND D.L1_NUM  = A.C1_ORCAM
LEFT JOIN SC6010 AS E ON E.D_E_L_E_T_ = '' AND E.C6_FILIAL = A.C1_FILIAL AND E.C6_NUM  = A.C1_PEDRES AND E.C6_PRODUTO = A.C1_PRODUTO AND E.C6_LOCAL = A.C1_LOCAL
LEFT JOIN SUA010 AS F ON F.D_E_L_E_T_ = '' AND F.UA_FILIAL  = D.L1_FILIAL AND F.UA_NUM  = D.L1_NUMATEN
LEFT JOIN SA1010 AS G ON G.D_E_L_E_T_ = '' AND G.A1_COD = D.L1_CLIENTE   AND G.A1_LOJA = D.L1_LOJA
LEFT JOIN SA3010 AS H ON H.D_E_L_E_T_ = '' AND H.A3_COD = D.L1_VEND 
LEFT JOIN SA2010 AS I ON I.D_E_L_E_T_ = '' AND I.A2_COD = B.B1_PROC AND I.A2_LOJA = B.B1_LOJPROC
LEFT JOIN SB1010 AS J ON J.D_E_L_E_T_ = '' AND A.C1_PRODUTO = J.B1_COD
WHERE A.D_E_L_E_T_ 	= '' 
AND SUBSTRING(A.C1_CC,1,2) = 'MR'
AND A.C1_COTACAO 	= ''
AND A.C1_FORNECE 	= ''
AND A.C1_LOJA 	    = ''
AND A.C1_QUJE		= 0
AND A.C1_QTDREEM	= 0
AND A.C1_PEDIDO		= ''
--AND A.C1_PRODUTO = 'EQ120C'
