/*---------ANALISE DA RESERVA----------*/
	
	SELECT 
	A.C9_FILIAL,
	A.C9_PEDIDO,
	C.A1_COD,
	C.A1_NOME,
	B.B1_GRUPO,
	A.C9_ITEM,
	B.B1_COD,
	B.B1_DESC,
	A.C9_QTDLIB,
	A.C9_LOCAL,
	B.B1_MSBLQL
	FROM SC9010 A, SB1010 B, SA1010 C
	WHERE A.D_E_L_E_T_ = ''
	AND B.D_E_L_E_T_ = ''
	AND C.D_E_L_E_T_ = ''
	AND A.C9_PRODUTO = B.B1_COD
	AND A.C9_CLIENTE = C.A1_COD
	AND A.C9_NFISCAL = ''
	AND A.C9_SERIENF = ''
	AND A.C9_LOCAL = '01'
	GROUP BY A.C9_FILIAL, A.C9_PEDIDO, C.A1_COD, C.A1_NOME, B.B1_GRUPO, A.C9_ITEM, B.B1_COD, B.B1_DESC, A.C9_QTDLIB,A.C9_LOCAL,B.B1_MSBLQL


/*-------CONTROLE DA RESERVA---------*/


SELECT
A.C0_FILIAL AS FILIAL,
A.C0_NUM AS NUM_RES,
A.C0_LOCAL AS ARMZ,
A.C0_SOLICIT AS USUARIO,
A.C0_DOCRES AS COD_CLI,
C.A1_NOME AS CLIENTE,
CONVERT(VARCHAR,CAST(A.C0_EMISSAO AS DATETIME),103) AS DT_EMISSAO,
A.C0_OBS AS OBSERVAÇÃO,
A.C0_PRODUTO AS COD_PROD,
B.B1_DESC AS PRODUTO,
A.C0_QTDPED AS QTD_PED,
CONVERT(VARCHAR,CAST(A.C0_VALIDA AS DATETIME),103) AS DT_VALIDADE
FROM SC0010 A , SB1010 B, SA1010 C
WHERE A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND A.C0_PRODUTO = B.B1_COD
AND A.C0_DOCRES = C.A1_COD


/*-------------DIVERGENCIA RESERVA----------------*/


SELECT
A.B1_COD,
CASE
WHEN A.B1_MSBLQL = '1' THEN 'BLQ'
WHEN A.B1_MSBLQL = '2' THEN 'LIB'
END AS STS, 
ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE B2_COD = A.B1_COD AND B2_LOCAL = '01' AND D_E_L_E_T_ = ''),0) AS RESERVADO,
ISNULL((SELECT SUM(C9_QTDLIB) FROM SC9010 WHERE C9_PRODUTO = A.B1_COD AND C9_LOCAL = '01' AND C9_NFISCAL = '' AND D_E_L_E_T_ ='' AND C9_BLEST = ''),0) AS LIBERADO,
ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE B2_COD = A.B1_COD AND B2_LOCAL = '01' AND D_E_L_E_T_ = ''),0) - ISNULL((SELECT SUM(C9_QTDLIB) FROM SC9010 WHERE C9_PRODUTO = A.B1_COD AND C9_LOCAL = '01' AND C9_NFISCAL = '' AND D_E_L_E_T_ ='' AND C9_BLEST = ''),0) AS DIV_RESERVA
FROM SB1010 A, SB2010 B, SC9010 C
WHERE A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND C.D_E_L_E_T_ = ''
AND A.B1_COD = B.B2_COD
AND A.B1_COD = C.C9_PRODUTO
AND B.B2_COD = C.C9_PRODUTO
AND B.B2_LOCAL = C.C9_LOCAL
AND C.C9_NFISCAL = ''
AND C.C9_SERIENF = ''
AND B.B2_LOCAL = '01'
AND A.B1_COD = '40408'
AND ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE B2_COD = A.B1_COD AND B2_LOCAL = '01' AND D_E_L_E_T_ =''),0) - ISNULL((SELECT SUM(C9_QTDLIB) FROM SC9010 WHERE C9_PRODUTO = A.B1_COD AND C9_LOCAL = '01' AND C9_NFISCAL = '' AND D_E_L_E_T_ ='' AND C9_BLEST = ''),0) <> 0
GROUP BY A.B1_COD, A.B1_MSBLQL


/*------------------------------SALDOS ESTOQUE------------------------------*/


SELECT
A.B2_COD AS COD_PROD,
C.C9_FILIAL,
SUM(A.B2_QATU) AS SALDO_FISICO,
SUM(A.B2_RESERVA) AS RESERVADO,
SUM(A.B2_QATU - A.B2_RESERVA)AS SALDO_DISPONIVEL
FROM
SB2010 A, SA1010 B, SC9010 C
WHERE A.D_E_L_E_T_ = ''
AND A.B2_COD = C.C9_PRODUTO
AND C.C9_CLIENTE = B.A1_COD
--AND A.B2_LOCAL = '01'
AND A.B2_COD = '40408'
GROUP BY A.B2_COD, C.C9_FILIAL


/*-----------------------------------------------------------------------------------------------------------------*/


ISNULL((SELECT SUM(C9_QTDLIB) FROM SC9010 WHERE C9_PRODUTO = A.B1_COD AND C9_LOCAL = '01'),0)

ISNULL((SELECT SUM(B2_RESERVA) FROM SB2010 WHERE B2_COD = A.B1_COD AND B2_LOCAL = '01'),0) 


