/*

Mapa de Vendas com Apresentação Reservas Técnicas ( Oficial )

*/

DECLARE @cDatVndIni VARCHAR(08)
DECLARE @cDatVndFim VARCHAR(08)
DECLARE @cCodVndIni VARCHAR(06)
DECLARE @cCodVndFim VARCHAR(06)
DECLARE @cCodCliIni VARCHAR(06)
DECLARE @cCodCliFim VARCHAR(06)

SET @cDatVndIni = '20200901'
SET @cDatVndFim = '20200930'

SET @cCodVndIni = ''
SET @cCodVndFim = 'ZZZZZZ'

SET @cCodCliIni = ''
SET @cCodCliFim = 'ZZZZZZ'


SELECT A.E3_FILIAL,A.E3_VEND,B.A3_NREDUZ,CONVERT(VARCHAR,CAST(A.E3_EMISSAO AS DATETIME),103) AS EMISS,
A.E3_CODCLI,A.E3_LOJA,C.A1_NREDUZ,RTRIM(C.A1_MUN)+'/'+C.A1_EST AS NUMEST, A.E3_SERIE,A.E3_NUM,A.E3_PARCELA,A.E3_TIPO,
BASCOM  = CASE WHEN A.E3_BASE >= 0 AND  A.E3_ZCODRT <> '9' THEN A.E3_BASE ELSE 0 END,
VLRCOM  = CASE WHEN                     A.E3_ZCODRT <> '9' THEN A.E3_BASE ELSE 0 END,A.E3_PORC,A.E3_COMIS, 
RETIND  = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '1' THEN A.E3_BASE ELSE 0 END,
RETMO   = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '2' THEN A.E3_BASE ELSE 0 END,
RETFRT  = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '3' THEN A.E3_BASE ELSE 0 END,
CCBNDS  = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '4' THEN A.E3_BASE ELSE 0 END,
DEVMERC = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '5' THEN A.E3_BASE ELSE 0 END,
INDREC  = CASE WHEN A.E3_BASE >  0 AND  A.E3_ZCODRT =  '6' THEN A.E3_BASE ELSE 0 END,
INDPAG  = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '6' THEN A.E3_BASE ELSE 0 END,
COMANT  = CASE WHEN A.E3_BASE >  0 AND  A.E3_ZCODRT =  '7' THEN A.E3_BASE ELSE 0 END,
OUTROS  = CASE WHEN A.E3_BASE >  0 AND  A.E3_ZCODRT =  '8' THEN A.E3_BASE ELSE 0 END,
RETCOP  = CASE WHEN A.E3_BASE <  0 AND  A.E3_ZCODRT =  '9' THEN A.E3_BASE ELSE 0 END
FROM SE3010 AS A
LEFT JOIN SA3010 AS B ON B.D_E_L_E_T_ = '' AND B.A3_COD = A.E3_VEND
LEFT JOIN SA1010 AS C ON C.D_E_L_E_T_ = '' AND C.A1_COD = A.E3_CODCLI AND C.A1_LOJA = A.E3_LOJA
WHERE A.D_E_L_E_T_ = '' 
--AND A.E3_FILIAL IN ('0101')
--AND A.E3_FILIAL IN ('0103')
AND A.E3_FILIAL IN ('0101','0102','0103')
--AND B.A3_ZLOCVND  IN ('L')
--AND B.A3_ZLOCVND  IN ('Z','M')
--AND B.A3_ZLOCVND  IN ('Z','M','L')
AND A.E3_EMISSAO 	BETWEEN @cDatVndIni AND @cDatVndFim 
AND A.E3_VEND 		BETWEEN @cCodVndIni AND @cCodVndFim
AND C.A1_COD  		BETWEEN @cCodCliIni AND @cCodCliFim	
--AND A.E3_BASE = 970
ORDER BY A.E3_FILIAL,A.E3_SERIE,A.E3_NUM,A.E3_PARCELA,A.E3_TIPO

-- //////////////////////// \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

/*
SELECT E3_VEND,E3_EMISSAO,E3_NUM,E3_SERIE,E3_BASE,E3_ZCODRT,E3_ZCODFOR,E3_ZOBS
FROM SE3010 
WHERE D_E_L_E_T_ = '' 
AND E3_EMISSAO BETWEEN '20200501' AND '20200531'
AND E3_VEND = '000003'
AND E3_BASE < 0
--AND E3_ZCODRT = '5'
--AND E3_ZCODRT <> '6'
ORDER BY E3_VEND

-- SELECT * FROM SE3010 WHERE D_E_L_E_T_ = '' 
*/


