
SELECT * FROM SD1010 -- Entrada de estoque
SELECT * FROM SD2010 -- Saida de estoque
SELECT * FROM SD3010 -- Entrada / Saida (Movimentação de estoque) 
SELECT * FROM SB9010 -- Fechamento 2017 (Saldo inicial)
SELECT * FROM SF4010 -- TES F4_ESTOQUE = S

/*---------------------------SALDO INICIAL (2017)-------------------------------*/

SELECT 
A.B9_FILIAL,
A.B9_COD,
A.B9_LOCAL,
A.B9_DATA,
SUM(A.B9_QINI)  AS QTD_INI ,
A.B9_CUSTD
FROM SB9010 A
WHERE D_E_L_E_T_ = '' 
AND YEAR(B9_DATA) = 2017
AND A.B9_COD = 'LB012F'
GROUP BY A.B9_FILIAL, A.B9_COD, A.B9_LOCAL, A.B9_DATA, A.B9_CUSTD

/*--------------------ENTRADA----------------------------*/


SELECT 
A.B1_COD AS COD_PROD,
--CONVERT(VARCHAR,CAST(B.B9_DATA AS DATETIME),103) AS DATA_B9,
--CONVERT(VARCHAR,CAST(C.D1_DTDIGIT AS DATETIME),103) AS DATA_D1,
SUM(B.B9_QINI) AS QTD_INI_B9,
SUM(C.D1_QUANT) AS QTD_ENTRADA_D1
FROM SB1010 A 
LEFT JOIN SB9010 B ON A.B1_COD = B.B9_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD1010 C ON A.B1_COD = C.D1_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SF4010 D ON D.F4_CODIGO = C.D1_TES AND D.D_E_L_E_T_ = '' 
WHERE 1=1 
AND A.D_E_L_E_T_ = '' 
AND YEAR(B.B9_DATA) = 2017
AND YEAR(C.D1_DTDIGIT) = 2018
AND MONTH(C.D1_DTDIGIT) = 01
AND D.F4_ESTOQUE = 'S'
GROUP BY A.B1_COD


/*-------------------SAIDA---------------------*/


SELECT 
A.B1_COD AS COD_PROD,
--CONVERT(VARCHAR,CAST(B.B9_DATA AS DATETIME),103) AS DATA_B9,
--CONVERT(VARCHAR,CAST(C.D2_EMISSAO AS DATETIME),103) AS DATA_D2,
SUM(B.B9_QINI) AS QTD_INI_B9,
SUM(C.D2_QUANT) AS QTD_SAIDA_D2
FROM SB1010 A 
LEFT JOIN SB9010 B ON A.B1_COD = B.B9_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD2010 C ON A.B1_COD = C.D2_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SF4010 D ON D.F4_CODIGO = C.D2_TES AND D.D_E_L_E_T_ = '' 
WHERE 1=1 
AND A.D_E_L_E_T_ = '' 
AND YEAR(B.B9_DATA) = 2017
AND YEAR(C.D2_EMISSAO) = 2018
AND MONTH(C.D2_EMISSAO) = 01
AND D.F4_ESTOQUE = 'S'
GROUP BY A.B1_COD



/*----------------------TUDO JUNTO SB2 SB9 SD1 SD2 SD3 SF4 (ENTRADA E SAIDA)--------------------------------*/

SELECT 
A.B1_COD AS COD_PROD,
SUM(B.B9_QINI) AS QTD_INI_B9,
SUM(C.D1_QUANT) AS QTD_ENTRADA_D1,
SUM(D.D2_QUANT) AS QTD_SAIDA_D2,
CASE WHEN E.D3_TM<='499' THEN SUM(E.D3_QUANT) ELSE '' END AS QTD_ENTRADA_D3,
CASE WHEN E.D3_TM>='499' THEN SUM(E.D3_QUANT) ELSE '' END AS QTD_SAIDA_D3,
(CASE WHEN E.D3_TM<='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(C.D1_QUANT)) AS TOTAL_ENTRADA_D1_D3,
(CASE WHEN E.D3_TM>='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(D.D2_QUANT)) AS TOTAL_SAIDA_D2_D3
FROM SB1010 A
LEFT JOIN SB9010 B ON A.B1_COD = B.B9_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD1010 C ON A.B1_COD = C.D1_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SD2010 D ON A.B1_COD = D.D2_COD AND D.D_E_L_E_T_ = '' 
LEFT JOIN SD3010 E ON A.B1_COD = E.D3_COD AND E.D_E_L_E_T_ = '' 
LEFT JOIN SF4010 F ON F.F4_CODIGO = C.D1_TES AND F.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND YEAR(B.B9_DATA) = 2017
AND YEAR(C.D1_DTDIGIT) = 2018
AND MONTH(C.D1_DTDIGIT) = 01
AND YEAR(D.D2_EMISSAO) = 2018
AND MONTH(D.D2_EMISSAO) = 01
AND F.F4_ESTOQUE = 'S'
GROUP BY A.B1_COD, E.D3_TM

/*-----------------------------SUB SELECT--------------------------------------*/


SELECT 
JAN2018.COD_PROD,
SUM(JAN2018.QTD_INI_B9) + SUM(JAN2018.TOTAL_ENTRADA_D1_D3) - SUM(JAN2018.TOTAL_SAIDA_D2_D3) AS JAN2018
FROM(
SELECT 
A.B1_COD AS COD_PROD,
SUM(B.B9_QINI) AS QTD_INI_B9,
(CASE WHEN E.D3_TM<='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(C.D1_QUANT)) AS TOTAL_ENTRADA_D1_D3,
(CASE WHEN E.D3_TM>='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(D.D2_QUANT)) AS TOTAL_SAIDA_D2_D3
FROM SB1010 A
LEFT JOIN SB9010 B ON A.B1_COD = B.B9_COD AND B.D_E_L_E_T_ = ''
LEFT JOIN SD1010 C ON A.B1_COD = C.D1_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SD2010 D ON A.B1_COD = D.D2_COD AND D.D_E_L_E_T_ = '' 
LEFT JOIN SD3010 E ON A.B1_COD = E.D3_COD AND E.D_E_L_E_T_ = '' 
LEFT JOIN SF4010 F ON F.F4_CODIGO = C.D1_TES AND F.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND YEAR(B.B9_DATA) = 2017
AND YEAR(C.D1_DTDIGIT) = 2018
AND MONTH(C.D1_DTDIGIT) = 02
AND YEAR(D.D2_EMISSAO) = 2018
AND MONTH(D.D2_EMISSAO) = 02
AND F.F4_ESTOQUE = 'S'
AND A.B1_COD = 'LB012F'
GROUP BY A.B1_COD, E.D3_TM
) AS JAN2018
GROUP BY JAN2018.COD_PROD


/*--------------------------------------TESTE---------------------------------------------------*/


SELECT 
(CASE WHEN E.D3_TM<='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(C.D1_QUANT)) AS TOTAL_ENTRADA_D1_D3,
(CASE WHEN E.D3_TM>='499' THEN SUM(E.D3_QUANT) ELSE '' END) + (SUM(D.D2_QUANT)) AS TOTAL_SAIDA_D2_D3
FROM SB1010 A
LEFT JOIN SD1010 C ON A.B1_COD = C.D1_COD AND C.D_E_L_E_T_ = ''
LEFT JOIN SD2010 D ON A.B1_COD = D.D2_COD AND D.D_E_L_E_T_ = '' 
LEFT JOIN SD3010 E ON A.B1_COD = E.D3_COD AND E.D_E_L_E_T_ = '' 
LEFT JOIN SF4010 F ON F.F4_CODIGO = C.D1_TES AND F.D_E_L_E_T_ = ''
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND YEAR(C.D1_DTDIGIT) = 2018
AND MONTH(C.D1_DTDIGIT) = 01
AND YEAR(D.D2_EMISSAO) = 2018
AND MONTH(D.D2_EMISSAO) = 01
AND F.F4_ESTOQUE = 'S'
GROUP BY A.B1_COD, E.D3_TM