/*

Kardex Customizado - AN�LISE DAS MOVIMENTA��ES / AUDITORIA

Por : Alexandre Lacerda
Data: 26/12/2019

*/

DECLARE @cFilIni 	VARCHAR(04)		-- Codigo da Filial Inicial
DECLARE @cFilFin 	VARCHAR(04)		-- Codigo da Filial Final
DECLARE @cPrdIni    VARCHAR(15)     -- Codigo do Produto Inicial
DECLARE @cPrdFin    VARCHAR(15)     -- Codigo do Produto Inicial
DECLARE @dDatIni	VARCHAR(10)		-- Data Inicial
DECLARE @dDatFin	VARCHAR(10) 	-- Data Final
DECLARE @cAmzIni    VARCHAR(02)     -- Codigo Armazem Inicial 
DECLARE @cAmzFin    VARCHAR(02)     -- Codigo Armazem Final 
DECLARE @cClFrIn	VARCHAR(06)		-- Codigo Cliente/Fornecedor Inicial
DECLARE	@cClFrFn	VARCHAR(06)		-- Codigo Cliente/Fornecedor Final
DECLARE	@cFiltro	VARCHAR(02)		-- MR Mercadoria de Revenda | CF - Industria | MP - Materia Prima 

SET @cFilIni 	= '0101'
SET @cFilFin 	= '0103'
SET @cPrdIni    = ''
SET @cPrdFin    = 'ZZZZZZ'
SET @dDatIni	= '20200309'
SET @dDatFin	= '20200309'
SET @cAmzIni	= ''
SET @cAmzFin	= 'ZZ'
SET @cClFrIn	= ''
SET @cClFrFn	= 'ZZZZZZ'
SET @cFiltro	= 'MR'                

/*
SD1 - Movimenta��es de Entradas
*/

SELECT('SD1 - ENTRADA') AS MOVIMENTACAO

SELECT SD1.D1_FILIAL CodFil,CONVERT(VARCHAR,CAST(SD1.D1_DTDIGIT AS DATETIME),103) DatEnt,SD1.D1_COD CodPrd,SB1.B1_DESC DesPrd,SD1.D1_FORNECE CodFor,
CASE 
	WHEN SD1.D1_TIPO <> 'D' THEN SA2.A2_NOME
	WHEN SD1.D1_TIPO =  'D' THEN SA1.A1_NOME
END ForCli,SD1.D1_TIPO TipMov,SD1.D1_SERIE SerDoc,SD1.D1_DOC NumDoc,SD1.D1_TES TES,SF4.F4_ESTOQUE MovEstq,SF4.F4_DUPLIC MovFin,SD1.D1_CF CFOP,
SX5.X5_DESCRI DesCFOP,SD1.D1_LOCAL Armz,NNR.NNR_DESCRI DesArmz,
QtdEnt =  CASE WHEN SD1.D1_TES <= '499' THEN SD1.D1_QUANT ELSE '' END, 
QtdSai =  CASE WHEN SD1.D1_TES >= '500' THEN SD1.D1_QUANT ELSE '' END,
SD1.D1_UM UndPrd,SD1.D1_VUNIT VlrUni,SD1.D1_TOTAL TotDoc,SFT.FT_OBSERV ObsDoc,SD1.D1_DESC Descto,(SD1.D1_QUANT*SB1.B1_CUSTD) CstRep 
FROM SD1010 AS SD1
LEFT JOIN SB1010 AS SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD1.D1_COD 
LEFT JOIN NNR010 AS NNR ON NNR.D_E_L_E_T_ = '' AND NNR.NNR_CODIGO = SD1.D1_LOCAL
LEFT JOIN SFT010 AS SFT ON SFT.D_E_L_E_T_ = '' AND SFT.FT_FILIAL = SD1.D1_FILIAL AND SFT.FT_NFISCAL = SD1.D1_DOC AND SFT.FT_SERIE = SD1.D1_SERIE AND SFT.FT_ITEM = SD1.D1_ITEM AND SFT.FT_PRODUTO = SD1.D1_COD
LEFT JOIN SF4010 AS SF4 ON SF4.D_E_L_E_T_ = '' AND SF4.F4_CODIGO = SD1.D1_TES
LEFT JOIN SA2010 AS SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SD1.D1_FORNECE AND SA2.A2_LOJA = SD1.D1_LOJA AND SD1.D1_TIPO <> 'D'
LEFT JOIN SA1010 AS SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SD1.D1_FORNECE AND SA1.A1_LOJA = SD1.D1_LOJA AND SD1.D1_TIPO =  'D'
LEFT JOIN SX5010 AS SX5 ON SX5.D_E_L_E_T_ = '' AND SX5.X5_CHAVE = SD1.D1_CF AND SX5.X5_TABELA = '13'
WHERE SD1.D_E_L_E_T_ = ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) = @cFiltro
AND SD1.D1_FILIAL 	BETWEEN @cFilIni AND @cFilFin
AND SD1.D1_DTDIGIT 	BETWEEN @dDatIni AND @dDatFin 
AND SD1.D1_COD 		BETWEEN @cPrdIni AND @cPrdFin 
AND SD1.D1_LOCAL 	BETWEEN @cAmzIni AND @cAmzFin
AND SD1.D1_FORNECE 	BETWEEN @cClFrIn AND @cClFrFn
ORDER BY SD1.D1_FILIAL,SD1.D1_EMISSAO,SD1.D1_COD,SD1.D1_DOC  


/*
SD2 - Movimenta��es de Sa�das
*/

SELECT('SD2 - SAIDA') AS MOVIMENTACAO

SELECT SD2.D2_FILIAL CodFil,CONVERT(VARCHAR,CAST(SD2.D2_EMISSAO AS DATETIME),103) Emissao,SD2.D2_COD CodPrd,SB1.B1_DESC DesPrd,SD2.D2_CLIENTE CliFor,
CASE 
	WHEN SD2.D2_TIPO <> 'D' THEN SA1.A1_NOME
	WHEN SD2.D2_TIPO =  'D' THEN SA2.A2_NOME
END CliFor,SD2.D2_TIPO TipMov,SD2.D2_SERIE SerDoc,SD2.D2_DOC NumDoc,SD2.D2_TES TES,SF4.F4_ESTOQUE MovEstq,SF4.F4_DUPLIC MovFin,SD2.D2_CF CFOP,
SX5.X5_DESCRI DesCFOP,SD2.D2_LOCAL Armz,NNR.NNR_DESCRI DesArmz,
QtdEnt =  CASE WHEN SD2.D2_TES <= '499' THEN SD2.D2_QUANT ELSE '' END, 
QtdSai =  CASE WHEN SD2.D2_TES >= '500' THEN SD2.D2_QUANT ELSE '' END,
SD2.D2_UM UndPrd,SD2.D2_PRCVEN VlrUni,SD2.D2_TOTAL TotDoc,SFT.FT_OBSERV ObsDoc,SD2.D2_DESC Descto,(SD2.D2_QUANT*SB1.B1_CUSTD) CstRep 
FROM SD2010 AS SD2
LEFT JOIN SB1010 AS SB1 ON SB1.D_E_L_E_T_ = '' AND SB1.B1_COD = SD2.D2_COD 
LEFT JOIN NNR010 AS NNR ON NNR.D_E_L_E_T_ = '' AND NNR.NNR_CODIGO = SD2.D2_LOCAL
LEFT JOIN SFT010 AS SFT ON SFT.D_E_L_E_T_ = '' AND SFT.FT_FILIAL = SD2.D2_FILIAL AND SFT.FT_NFISCAL = SD2.D2_DOC AND SFT.FT_SERIE = SD2.D2_SERIE AND SFT.FT_ITEM = SD2.D2_ITEM AND SFT.FT_PRODUTO = SD2.D2_COD
LEFT JOIN SF4010 AS SF4 ON SF4.D_E_L_E_T_ = '' AND SF4.F4_CODIGO = SD2.D2_TES
LEFT JOIN SA1010 AS SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SD2.D2_CLIENTE AND SA1.A1_LOJA = SD2.D2_LOJA AND SD2.D2_TIPO <> 'D'
LEFT JOIN SA2010 AS SA2 ON SA2.D_E_L_E_T_ = '' AND SA2.A2_COD = SD2.D2_CLIENTE AND SA2.A2_LOJA = SD2.D2_LOJA AND SD2.D2_TIPO =  'D'
LEFT JOIN SX5010 AS SX5 ON SX5.D_E_L_E_T_ = '' AND SX5.X5_CHAVE = SD2.D2_CF AND SX5.X5_TABELA = '13'
WHERE SD2.D_E_L_E_T_ = ''
AND SUBSTRING(SB1.B1_GRUPO,1,2) = @cFiltro
AND SD2.D2_FILIAL 	BETWEEN @cFilIni AND @cFilFin
AND SD2.D2_EMISSAO 	BETWEEN @dDatIni AND @dDatFin 
AND SD2.D2_COD 		BETWEEN @cPrdIni AND @cPrdFin 
AND SD2.D2_LOCAL 	BETWEEN @cAmzIni AND @cAmzFin
AND SD2.D2_CLIENTE 	BETWEEN @cClFrIn AND @cClFrFn
ORDER BY SD2.D2_FILIAL,SD2.D2_EMISSAO,SD2.D2_COD,SD2.D2_DOC  

/*
SD3 - Movimenta��es Interna de Produtos ( Controle de Qualidade, Transfer�ncias  e Invent�rios )
*/

SELECT('SD3 - MOV.INTERNA') AS MOVIMENTACAO

SELECT SD3.D3_FILIAL CodFil,CONVERT(VARCHAR,CAST(SD3.D3_EMISSAO AS DATETIME),103) AS Emissao,SD3.D3_COD CodPrd,SB1.B1_DESC DesPrd,
SD3.D3_LOCAL Armz,NNR.NNR_DESCRI DesArmz,SD3.D3_DOC NumDoc,SD3.D3_TM TES,SD3.D3_CF CodMov,
QtdEnt =  CASE WHEN SD3.D3_TM <= '499' THEN  SD3.D3_QUANT ELSE '' END, 
QtdSai =  CASE WHEN SD3.D3_TM >= '500' THEN  SD3.D3_QUANT ELSE '' END, 
SD3.D3_QUANT*(SB1.B1_CUSTD+(SB1.B1_CUSTD*(SB1.B1_IPI/100))) CstRep,  
SD3.D3_OP NumOP,SD3.D3_OBS ObsDoc,SD3.D3_USUARIO NomUsr 
FROM SD3010 AS SD3, SB1010 AS SB1, NNR010 AS NNR  
WHERE SD3.D_E_L_E_T_ = '' AND SB1.D_E_L_E_T_ = '' AND NNR.Ds_E_L_E_T_ = '' 
AND SB1.B1_COD = D3_COD 
AND NNR.NNR_CODIGO = SD3.D3_LOCAL
AND SUBSTRING(SB1.B1_GRUPO,1,2) = @cFiltro
AND SD3.D3_FILIAL 	BETWEEN @cFilIni AND @cFilFin
AND SD3.D3_EMISSAO 	BETWEEN @dDatIni AND @dDatFin 
AND SD3.D3_COD 		BETWEEN @cPrdIni AND @cPrdFin 
AND SD3.D3_ESTORNO <> 'S' 
AND SD3.D3_LOCAL 	BETWEEN @cAmzIni AND @cAmzFin
ORDER BY SD3.D3_FILIAL,SD3.D3_EMISSAO,SD3.D3_DOC,SD3.D3_COD