
SELECT
SE1.E1_FILIAL	AS FILIAL,
SE1.E1_PREFIXO	AS PREFIXO,
SE1.E1_NUM		AS TITULO,
SE1.E1_PARCELA	AS PARCELA,
SE1.E1_TIPO		AS TIPO,
SE1.E1_EMISSAO	AS EMI_NCC,
SE1.E1_VENCREA	AS VENC_NCC,
SE1.E1_VALOR	AS VALOR_NCC,
SL1.L1_NUMATEN  AS ULT_ATEND,
SUA.UA_EMISSAO  AS EMI_ATEND, 
SL1.L1_SERPED	AS SER_FIN,
SL1.L1_DOCPED	AS DOC_FIN,
SL1.L1_EMISNF   AS DT_FIN,
SL1.L1_CLIENTE  AS COD_CLI,
SA1.A1_NOME		AS CLIENTE,
SL1.L1_VEND		AS COD_VEND,
SA3.A3_NOME		AS VENDEDOR
FROM SE1010 SE1
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_NUMATEN = (SELECT MAX(L1_NUMATEN) FROM SL1010 WHERE D_E_L_E_T_ = '' AND L1_CLIENTE = SE1.E1_CLIENTE AND L1_LOJA = SE1.E1_LOJA AND L1_ORCRES = '' AND L1_DOCPED <> '')
LEFT JOIN SUA010 SUA ON SUA.D_E_L_E_T_ = '' AND SUA.UA_FILIAL = SL1.L1_FILIAL AND SUA.UA_NUM = SL1.L1_NUMATEN
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SL1.L1_CLIENTE AND SA1.A1_LOJA = SL1.L1_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SL1.L1_VEND
WHERE 1=1
AND SE1.D_E_L_E_T_ = '' 
AND SE1.E1_TIPO = 'NCC' 
AND YEAR(SE1.E1_EMISSAO) = 2020
AND SL1.L1_SERPED	<> ''
AND SL1.L1_DOCPED	<> ''
AND SL1.L1_EMISNF   <> ''


