
CREATE TABLE AUXSOL
(
AUX_L2_NUM		VARCHAR(6),
AUX_L2_EMISSAO	VARCHAR(8),
AUX_L2_PRODUTO  VARCHAR(15),
AUX_L2_DESCRI	VARCHAR(30),
AUX_L2_ITEM		VARCHAR(2),
AUX_L2_SOLCOM	VARCHAR(6),
AUX_C1_FILIAL	VARCHAR(4),
AUX_C1_NUM		VARCHAR(6),
AUX_C1_PEDIDO	VARCHAR(6)	 
)


INSERT INTO AUXSOL (
AUX_L2_NUM,	   
AUX_L2_EMISSAO, 
AUX_L2_PRODUTO,  
AUX_L2_DESCRI,	
AUX_L2_ITEM,		
AUX_L2_SOLCOM,  
AUX_C1_FILIAL,	
AUX_C1_NUM,		
AUX_C1_PEDIDO	
)


SELECT 
A.L2_NUM,
A.L2_EMISSAO,
A.L2_PRODUTO,
A.L2_DESCRI,
A.L2_ITEM,
A.L2_SOLCOM,
B.C1_FILIAL,
B.C1_NUM,
B.C1_PEDIDO 
FROM SL2010 A, SC1010 B
WHERE 1=1
AND A.D_E_L_E_T_ = ''
AND B.D_E_L_E_T_ = ''
AND A.L2_FILIAL = B.C1_FILIAL
AND A.L2_SOLCOM = B.C1_NUM
AND A.L2_PRODUTO = B.C1_PRODUTO
AND A.L2_ORCRES = ''
AND B.C1_PEDIDO <> ''



SELECT 
SC1.C1_NUM,
SC1.C1_PRODUTO,
SC1.C1_PEDIDO,
AUX.AUX_C1_NUM,
AUX.AUX_C1_PEDIDO
FROM SC1010 SC1, AUXSOL AUX
WHERE 1=1
AND SC1.D_E_L_E_T_ = ''
AND SC1.C1_NUM <> AUX.AUX_C1_NUM  
AND SC1.C1_PRODUTO <> AUX.AUX_L2_PRODUTO



SELECT * FROM AUXSOL