
SELECT 	A.C1_PRODUTO,B.B1_DESC,B.B1_ZAPRES1,A.C1_QUANT,
		DATEDIFF(day,GETDATE(),F.UA_ZDTAENT) AS PRZ_CLI,J.B1_PE,A.C1_NUM,CONVERT(VARCHAR,CAST(F.UA_ZDTAENT AS DATETIME),103) AS ENTREGA,
		D.L1_NUMATEN,A.C1_ORCAM,I.A2_COD,I.A2_NREDUZ,H.A3_NREDUZ,CONVERT(VARCHAR,CAST(A.C1_EMISSAO AS DATETIME),103) AS EMISC
FROM SC1010 AS A
LEFT JOIN SB1010 AS B ON B.D_E_L_E_T_ = '' AND B.B1_COD = A.C1_PRODUTO
LEFT JOIN SL2010 AS C ON C.D_E_L_E_T_ = '' AND C.L2_FILIAL = A.C1_FILENT AND C.L2_NUM  = A.C1_ORCAM  AND C.L2_PRODUTO = A.C1_PRODUTO AND C.L2_LOCAL = A.C1_LOCAL AND L2_ENTREGA = '3'
LEFT JOIN SL1010 AS D ON D.D_E_L_E_T_ = '' AND D.L1_FILIAL = A.C1_FILENT AND D.L1_NUM  = A.C1_ORCAM
LEFT JOIN SUA010 AS F ON F.D_E_L_E_T_ = '' AND F.UA_FILIAL = D.L1_FILIAL AND F.UA_NUM  = D.L1_NUMATEN
LEFT JOIN SA1010 AS G ON G.D_E_L_E_T_ = '' AND G.A1_COD = D.L1_CLIENTE   AND G.A1_LOJA = D.L1_LOJA
LEFT JOIN SA3010 AS H ON H.D_E_L_E_T_ = '' AND H.A3_COD = D.L1_VEND 
LEFT JOIN SA2010 AS I ON I.D_E_L_E_T_ = '' AND I.A2_COD = B.B1_PROC AND I.A2_LOJA = B.B1_LOJPROC
LEFT JOIN SB1010 AS J ON J.D_E_L_E_T_ = '' AND A.C1_PRODUTO = J.B1_COD
WHERE 	A.D_E_L_E_T_ = '' AND B.D_E_L_E_T_ = ''  AND C.D_E_L_E_T_ = '' AND D.D_E_L_E_T_ = '' AND
		F.D_E_L_E_T_ = '' AND G.D_E_L_E_T_ = ''  AND H.D_E_L_E_T_ = '' AND I.D_E_L_E_T_ = '' AND J.D_E_L_E_T_ = '' 
AND SUBSTRING(A.C1_CC,1,2) = 'MR'
AND A.C1_COTACAO 	= ''
AND A.C1_FORNECE 	= ''
AND A.C1_LOJA 	    = ''
AND A.C1_QUJE		= 0
AND A.C1_QTDREEM	= 0
AND A.C1_PEDIDO		= ''
--AND A.C1_PRODUTO    = 'UT251M'
ORDER BY A.C1_PRODUTO
--ORDER BY I.A2_NREDUZ
