/*
DECLARE @VALOR1 FLOAT
DECLARE @VALOR2 FLOAT
DECLARE @VALORTOTAL FLOAT

SET @VALOR1 = (SELECT B3_Q01 FROM SB3010 WHERE B3_COD = 'LB012F' AND B3_FILIAL = '0101')
SET @VALOR2 = (SELECT B3_Q02 FROM SB3010 WHERE B3_COD = 'LB012F' AND B3_FILIAL = '0101')
SET @VALORTOTAL = @VALOR1 + @VALOR2
SELECT @VALOR1,@VALOR2, @VALORTOTAL
*/

ISNULL((SELECT  SUM(B3_Q12) FROM SB3010 WHERE D_E_L_E_T_ = '' AND B3_COD = A.B1_COD ),0) AS DEZ2018,



/*----------------------------DEMANDA TODOS OS PRODUTOS------------------------------*/
DECLARE @JANEIRO FLOAT
DECLARE @FEVEREIRO FLOAT
DECLARE @TOTBIM FLOAT
SET @JANEIRO = ISNULL((SELECT SUM(B3_Q01) FROM SB3010 A, SB1010 B WHERE A.D_E_L_E_T_ = '' AND A.B3_COD = B.B1_COD ),0)
SET @FEVEREIRO = ISNULL((SELECT SUM(B3_Q02) FROM SB3010 A, SB1010 B WHERE A.D_E_L_E_T_ = '' AND A.B3_COD = B.B1_COD ),0) 
SET @TOTBIM = (@JANEIRO + @FEVEREIRO)
SELECT @JANEIRO AS JANEIRO, @FEVEREIRO AS FEVEREIRO, @TOTBIM AS TOTAL




/*-------------------------------DEMANDAS POR PRODUTO--------------------------------*/
SELECT B.B1_COD AS PRODUTO, A.B3_Q01 AS JANEIRO, A.B3_Q02 AS FEVEREIRO, A.B3_Q01 + A.B3_Q02 AS TOTBIM, (A.B3_Q01 + A.B3_Q02) / 2 AS DM_BIMESTRAL  FROM SB3010 A, SB1010 B
WHERE 
A.D_E_L_E_T_ = ''
AND A.B3_COD = B.B1_COD

/*-----------------------------------------------------------------------------------*/

DECLARE @JAN FLOAT
DECLARE @FEV FLOAT
DECLARE @TOTAL FLOAT
DECLARE @DM FLOAT
SET @JAN = 0
SET @FEV = 0
SET @TOTAL = 0
SET @DM = 0
SELECT A.B3_COD, A.B3_Q01, A.B3_Q01, A.B3_Q02, @JAN AS JANEIRO, @FEV AS FEVEREIRO, @TOTAL AS TOTAL, @DM AS DEMANDA_BIMESTRAL FROM SB3010 A, SB1010 B
WHERE 
A.D_E_L_E_T_ = ''
AND A.B3_COD = B.B1_COD



SELECT * FROM SB3010


DECLARE @PRODUTO VARCHAR(15)
DECLARE @JAN FLOAT
DECLARE @FEV FLOAT
DECLARE @TOTAL FLOAT
DECLARE @DEMANDA FLOAT
DECLARE @ID INT
SELECT @PRODUTO = A.B3_COD, @JAN = A.B3_Q01, @FEV = A.B3_Q02, @TOTAL = (@JAN + @FEV), @DEMANDA = (@JAN + @FEV)/2, @ID = A.R_E_C_N_O_ FROM SB3010 A, SB1010 B
WHERE
A.D_E_L_E_T_ = ''
AND A.B3_COD = B.B1_COD
AND A.R_E_C_N_O_ = 6612
SELECT @PRODUTO AS PRODUTO, @JAN AS JANEIRO, @FEV AS FEVEREIRO, @TOTAL AS TOTAL, @DEMANDA AS DEMANDA_BIMESTRAL, @ID AS ID FROM SB3010


SELECT * FROM SB3010  6612




DECLARE @PROD VARCHAR(15)
DECLARE @JAN FLOAT
DECLARE @FEV FLOAT
DECLARE @TOTAL FLOAT
DECLARE @DEMANDA FLOAT
DECLARE @R INT
SELECT @PROD = A.B3_COD, @JAN = A.B3_Q01, @FEV = A.B3_Q02, @TOTAL = (@JAN + @FEV), @DEMANDA = (@JAN + @FEV)/2, @R = A.R_E_C_N_O_ FROM SB3010 A, SB1010 B
WHERE
A.D_E_L_E_T_ = ''
AND A.R_E_C_N_O_ = 6612
AND A.B3_COD = B.B1_COD
SELECT @PROD AS PRODUTO, @JAN AS JANEIRO, @FEV AS FEVEREIRO, @TOTAL AS TOTAL, @DEMANDA AS DEMANDA_BIMESTRAL, @R AS CODIGO FROM SB3010 A
WHERE 
A.R_E_C_N_O_ = @R





