/*--------------------------------------*/
CREATE TABLE #TESTE_DEMANDA
    (
     TD_CODPROD varchar(15),
     TD_JAN FLOAT,
     TD_FEV FLOAT,
     TD_TOTAL FLOAT,
     TD_DM FLOAT,
     TD_ID INT
    )

/*---------------------------------------*/


SELECT TD_ID AS ID, TD_CODPROD AS PRODUTO, TD_JAN AS JANEIRO, TD_FEV AS FEVEREIRO, TD_TOTAL AS TOTAL, TD_DM AS DEMANDA FROM #TESTE_DEMANDA
WHERE TD_CODPROD != '0'
AND TD_DM <> 0


/*----------------------------------------*/


DECLARE @PROD VARCHAR(15)
DECLARE @JAN FLOAT
DECLARE @FEV FLOAT
DECLARE @TOTAL FLOAT
DECLARE @DEMANDA FLOAT
DECLARE @R INT
SET @R = 16
WHILE @R <= 9468 
BEGIN
SET @PROD    = ISNULL((SELECT DISTINCT A.B3_COD FROM SB3010 A, SB1010 B WHERE A.D_E_L_E_T_ = '' AND A.B3_COD = B.B1_COD AND A.R_E_C_N_O_ = @R),0)
SET @JAN     = ISNULL((SELECT DISTINCT A.B3_Q01 FROM SB3010 A, SB1010 B WHERE A.D_E_L_E_T_ = '' AND A.B3_COD = B.B1_COD AND A.R_E_C_N_O_ = @R),0)
SET @FEV     = ISNULL((SELECT DISTINCT A.B3_Q02 FROM SB3010 A, SB1010 B WHERE A.D_E_L_E_T_ = '' AND A.B3_COD = B.B1_COD AND A.R_E_C_N_O_ = @R),0)
SET @TOTAL   = (@JAN + @FEV)
SET @DEMANDA = (@JAN + @FEV)/2
INSERT INTO #TESTE_DEMANDA (TD_CODPROD, TD_JAN, TD_FEV, TD_TOTAL, TD_DM, TD_ID)
VALUES (@PROD, @JAN, @FEV, @TOTAL, @DEMANDA, @R)
SET @R = @R + 1
END


/*------------------------------------------*/

DROP TABLE #TESTE_DEMANDA 



