
/* ----------------- UPDATE BENEFICIARIOS ----------------- */

-- A.BENEFICIARIOTITULAR IS NULL		= TITULAR
-- A.BENEFICIARIOTITULAR IS NOT NULL 	= DEPENDENTE

SELECT 
A.CONTRATO,
A.NOME,
A.CPF,
CASE
 WHEN A.BENEFICIARIOTITULAR IS NULL THEN 'TITULAR'
ELSE 'DEPENDENTE'
END AS TIPO_BENEFICIARIO,
A.VALOR AS VALOR
--UPDATE K_CN_CONTRATOBENEFICIARIOS SET VALOR = 11.05
FROM K_CN_CONTRATOBENEFICIARIOS A
WHERE 1=1
AND A.STATUS = 1
AND A.CONTRATO IN (14241)
--AND A.BENEFICIARIOTITULAR IS NOT NULL
--AND A.BENEFICIARIOTITULAR IS NULL


/* ----------------- UPDATE PRODUTOS BENEFICIARIOS ----------------- */

-- A.BENEFICIARIOTITULAR IS NULL		= TITULAR
-- A.BENEFICIARIOTITULAR IS NOT NULL 	= DEPENDENTE

SELECT 
A.NOME 	AS BENEFICIARIO,
A.CPF 	AS CPF,
CASE
 WHEN A.BENEFICIARIOTITULAR IS NULL THEN 'TITULAR'
ELSE 'DEPENDENTE'
END AS TIPO_BENEFICIARIO,
C.HANDLE AS COD_PROD,
C.NOME 	AS PRODUTO,
B.VALOR AS VALOR,
'--------------',
B.*
--UPDATE K_CN_CONTRATOBENPRODUTOS SET VALOR = 11.05
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN K_CN_CONTRATOBENPRODUTOS B ON B.CONTRATOBENEFICIARIO = A.HANDLE
INNER JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
WHERE 1=1
--AND A.STATUS = 1
AND A.CONTRATO IN (14241)
--AND C.HANDLE = 30
--AND A.BENEFICIARIOTITULAR IS NOT NULL
--AND A.BENEFICIARIOTITULAR IS NULL

