

SELECT 
A.EMPRESA AS EMPRESA,
A.NUMERO AS CONTRATO,
CASE
	WHEN A.STATUS = 3 THEN 'ENCERRADO'
	WHEN A.STATUS = 5 THEN 'SUSPENSO'
ELSE ''
END AS STATUS,
CONCAT(A.USUARIOINCLUIU, ' - ', C.NOME) AS USUARIO_ICLUIU,
CONCAT(A.USUARIOALTEROU, ' - ', B.NOME) AS USUARIO_ALTEROU,
A.DATAALTERACAO AS DT_ALTERAÇÃO,
D.NOME AS MOTIVO,
A.TEXTOASSINATURAS AS HISTORICO
FROM CN_CONTRATOS A
LEFT JOIN Z_GRUPOUSUARIOS B ON B.HANDLE = A.USUARIOALTEROU
LEFT JOIN Z_GRUPOUSUARIOS C ON C.HANDLE = A.USUARIOINCLUIU
LEFT JOIN CN_MOTIVOS D ON D.HANDLE = A.MOTIVO
WHERE 1=1
AND A.STATUS IN (3,5)
AND A.DATAALTERACAO >= CONVERT(DATE,'2022-09-01')

