SELECT 
Q1.CONTRATO,
Q1.COD,
Q1.BENEFICIARIO,
MIN(Q1.CPF) AS CPF,
SUM(Q1.VALOR) AS VALOR
FROM
(
	SELECT 
	B.NUMERO AS CONTRATO,
	CASE 
		WHEN C.HANDLE IS NOT NULL THEN C.HANDLE
	ELSE A.HANDLE
	END AS COD,
	CASE 
		WHEN C.HANDLE IS NOT NULL THEN C.NOME
	ELSE A.NOME
	END AS BENEFICIARIO,
	A.VALOR AS VALOR,
	A.CPF,
	CASE 
		WHEN C.HANDLE IS NOT NULL THEN 'DEPEDENTE'
	ELSE 'TITULAR'
	END AS TIPO_BENEFICIARIO	
	FROM K_CN_CONTRATOBENEFICIARIOS A
	LEFT JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
	LEFT JOIN K_CN_CONTRATOBENEFICIARIOS C ON C.HANDLE = A.BENEFICIARIOTITULAR
	WHERE 1=1
	AND B.NUMERO = 'CO-00002364-CT'
	AND A.STATUS = 1
	--AND A.BENEFICIARIOTITULAR IS NULL
	--AND A.NOME LIKE '%ADAIR%'
	--AND A.BENEFICIARIOTITULAR = 909970
) AS Q1
WHERE 1=1
--AND Q1.COD = 909970
GROUP BY 
Q1.CONTRATO,
Q1.COD,
Q1.BENEFICIARIO