

SELECT 
D.HANDLE,
B.NOME 			  	 AS EMPRESA,
A.NUMERO 		  	 AS CONTRATO,
C.NOME 			  	 AS TIPO_CONTRATO,
D.CODIGO		  	 AS CODIGO_CLIENTE,
D.NOME			  	 AS CLIENTE,
D.EMAIL			  	 AS EMAIL,
CONCAT(CONCAT('(',E.DDD),')') + E.TELEFONE AS TELEFONE,
A.DATAINICIOVIGENCIA AS DT_INICIO_VIGENCIA

FROM CN_CONTRATOS A
LEFT JOIN EMPRESAS B ON B.HANDLE = A.EMPRESA
LEFT JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PESSOA
LEFT JOIN GN_PESSOATELEFONES E ON E.PESSOA = D.HANDLE
WHERE 1=1
--AND D.EMAIL IS NULL OR D.TELEFONEEMPRESA IS NULL
--AND D.HANDLE = 47026
--AND D.CODIGO = 44142
AND A.STATUS = 2


