
SELECT	
B.NOME 				AS EMPRESA,
A.NUMERO 			AS CONTRATO,
C.NOME 				AS TIPO_CONTRATO,
A.DATAINICIO		AS DATA,
D.NOME				AS CLIENTE,
CONCAT('(',E.DDD, ')', E.TELEFONE) AS FONE1,
D.TELEFONEEMPRESA	AS FONE2
FROM CN_CONTRATOS A
LEFT JOIN EMPRESAS B ON B.HANDLE = A.EMPRESA
LEFT JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PESSOA
LEFT JOIN GN_PESSOATELEFONES E ON E.PESSOA = D.HANDLE
WHERE 1=1
AND A.EMPRESA = 2
AND C.HANDLE IN (49, 55, 50, 54)
AND D.TIPO IN (1,3)
AND YEAR(A.DATAINICIO) IN (2021, 2022, 2023)


/*

SELECT	
B.NOME 				AS EMPRESA,
A.NUMERO 			AS CONTRATO,
C.NOME 				AS TIPO_CONTRATO,
A.DATAINICIO		AS DATA,
D.NOME				AS CLIENTE,
CASE
	WHEN D.TIPO = 1 THEN 'PF'
	WHEN D.TIPO = 2 THEN 'PJ'
	WHEN D.TIPO = 3 THEN 'PF'
	WHEN D.TIPO = 4 THEN 'PJ'
	ELSE ''
END AS TIPO_PESSOA,
CONCAT('(',E.DDD, ')', E.TELEFONE) AS FONE1,
D.TELEFONEEMPRESA	AS FONE2,

CASE
	WHEN A.STATUS = 1 THEN 'EM ELABORAÇÃO'
	WHEN A.STATUS = 2 THEN 'APROVADO'
	WHEN A.STATUS = 3 THEN 'ENCERRADO'
	WHEN A.STATUS = 4 THEN 'CANCELADO'
	WHEN A.STATUS = 5 THEN 'SUSPENSO'
	ELSE 'N IDENTIFICADO'
END AS STATUS_CONTRATO

FROM CN_CONTRATOS A
LEFT JOIN EMPRESAS B ON B.HANDLE = A.EMPRESA
LEFT JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PESSOA
LEFT JOIN GN_PESSOATELEFONES E ON E.PESSOA = D.HANDLE
WHERE 1=1
AND A.EMPRESA IN (1,2,18)
AND A.STATUS = 2
AND C.HANDLE IN (49, 55, 50, 54, 6, 7, 12, 47, 48)
--AND D.TIPO IN (1,3)
AND YEAR(A.DATAINICIO) IN (2021, 2022, 2023)

*/
