
SELECT
A.FILIAL AS FILIAL,
B.NOME AS PERFIL_CONTRATO,
A.NUMERO AS NUMERO,
A.HANDLE AS ID_BENNER,
C.NOME AS RAZAO_SOCIAL,
C.Z_NOME AS NOME_FANTASIA,
C.CGCCPF AS CPF_CNPJ,
A.STATUS,
CASE
 WHEN A.STATUS = 1 THEN 'EM ELABORAÇÃO'
 WHEN A.STATUS = 2 THEN 'APROVADO'
 WHEN A.STATUS = 3 THEN 'ENCERRADO'
 WHEN A.STATUS = 4 THEN 'CANCELADO'
 WHEN A.STATUS = 5 THEN 'SUSPENSO'
ELSE 'N IDENTIFICADO' END AS STATUS_DESC,
A.K_DTCANCELAMENTO AS DT_CANCELAMENTO,
A.TEXTOAVISOCANCELAMENTO
FROM CN_CONTRATOS A
/* TIPO DO CONTRADO */ LEFT JOIN CN_TIPOSCONTRATOS AS B ON B.HANDLE = A.TIPOCONTRATO
/* PESSOA DO CONTRATO */ LEFT JOIN GN_PESSOAS AS C ON C.HANDLE = A.PESSOA
WHERE
1=1
AND A.NUMERO = 'EF-00033487-CT'


SELECT
A.FILIAL AS FILIAL,
B.NOME AS PERFIL_CONTRATO,
A.NUMERO AS NUMERO,
A.HANDLE AS ID_BENNER,
C.NOME AS RAZAO_SOCIAL,
C.Z_NOME AS NOME_FANTASIA,
C.CGCCPF AS CPF_CNPJ,
A.STATUS,
A.SITUACAO,
A.K_DTCANCELAMENTO AS DT_CANCELAMENTO,
A.TEXTOAVISOCANCELAMENTO
FROM CN_CONTRATOS A
LEFT JOIN CN_TIPOSCONTRATOS AS B ON B.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOAS AS C ON C.HANDLE = A.PESSOA
WHERE
1=1
AND A.STATUS = 4
AND A.K_DTCANCELAMENTO IS NULL
AND A.NUMERO IN ('EF-00033487-CT', 'EF-00033484-CT')