
SELECT 
CONCAT(A.EMPRESA, ' - ', C.NOME) AS EMPRESA,
A.NUMERO		AS CONTRATO,
B.NOME			AS CLIENTE_PAGANTE,
CASE
	WHEN A.STATUS = 3 THEN '3 - ENCERRADO'
	WHEN A.STATUS = 5 THEN '5 - SUSPENSO'
ELSE ''
END AS STATUS_CONTRATO,	
CASE
	WHEN D.STATUS = 1 THEN '1 - ATIVO'
	WHEN D.STATUS = 2 THEN '2 - INATIVO'
ELSE ''
END AS STATUS_BENEFICIARIO,

COUNT(D.HANDLE) AS QTD_VIDAS,
SUM(E.VALOR)	AS VALOR,
F.NOME AS MOTIVO_CONTRATO,
D.MOTIVOCANCELAMENTO AS MOTIVO_BENEFICIARIO,
G.NOME			AS TIPO_CONTRATO
FROM CN_CONTRATOS A 
LEFT JOIN GN_PESSOAS B ON B.HANDLE = A.PESSOA 
LEFT JOIN EMPRESAS C ON C.HANDLE = A.EMPRESA
LEFT JOIN K_CN_CONTRATOBENEFICIARIOS D ON D.CONTRATO = A.HANDLE
LEFT JOIN K_CN_CONTRATOBENPRODUTOS E ON E.CONTRATOBENEFICIARIO = D.HANDLE
LEFT JOIN CN_MOTIVOS F ON F.HANDLE = A.MOTIVO
LEFT JOIN CN_TIPOSCONTRATOS AS G ON G.HANDLE = A.TIPOCONTRATO
WHERE 1=1
/* SOMENETE ENCERRAODS/SUSPENSOS */ AND A.STATUS IN (3,5)
/* SOMENTE PESSOA FISICA */			AND LEN(B.CGCCPF) >= 14
--AND A.EMPRESA = 1
--AND A.NUMERO = 'FN-00019356-CT'
GROUP BY
A.EMPRESA,
C.NOME,
A.NUMERO,
B.NOME,
B.CGCCPF,
A.STATUS,
D.STATUS,
F.NOME ,
D.MOTIVOCANCELAMENTO,
G.NOME
ORDER BY 1,2,4,7

