
/*FLUXO : CONTRATOS -> BENEFICIARIOS(DO CONTRATO) -> PRODUTOS(CONTEM O VALOR)*/


SELECT
D.NOME AS FILIAL_CONTRATO,
A.NUMERO AS NUMERO_CONTRATO,
C.NOME AS PERFIL_CONTRATO,
CASE
 WHEN A.STATUS = 1 THEN 'EM ELABORÇÃO'
 WHEN A.STATUS = 2 THEN 'APROVADO'
 WHEN A.STATUS = 3 THEN 'ENCERRADO'
 WHEN A.STATUS = 4 THEN 'CANCELADO'
 WHEN A.STATUS = 5 THEN 'SUSPENSO'
ELSE '' END AS STATUS_CONTRATO,
B.NOME AS BENEFICIARIO,
CASE
 WHEN B.K9_TIPOPESSOA = '1001' THEN 'TITULAR'
ELSE 'DEPENDENTE'
END AS TIPO_BENEFICIARIO
FROM CN_CONTRATOS A
/* BENEFICIARIO DOS CONTRATOS */ LEFT JOIN K_CN_CONTRATOBENEFICIARIOS AS B ON B.CONTRATO = A.HANDLE
/* TIPO DOS CONTRATOS */ LEFT JOIN CN_TIPOSCONTRATOS AS C ON C.HANDLE = A.TIPOCONTRATO
/* FILIAL DO CONTRADO */ LEFT JOIN FILIAIS AS D ON D.HANDLE = A.FILIAL
WHERE 1=1

