
/* ------------------------------- Documentos X Itens ------------------------------- */

SELECT
A.DOCUMENTODIGITADO AS DOCUMENTO,
A.NRNOTAFISCAL AS NOTA_FISCAL,
A.NUMEROPEDIDO AS CONTRATO,
CONCAT(C.CODIGOREFERENCIA, ' - ', C.NOME) AS PRODUTO,
B.QUANTIDADE,
B.VALORUNITARIO,
B.VALORTOTAL
FROM FN_DOCUMENTOS A
LEFT JOIN CM_ITENS B ON B.DOCUMENTO = A.HANDLE
LEFT JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
WHERE 1=1
AND A.DOCUMENTOORIGEM IS NOT NULL
--AND A.DOCUMENTODIGITADO = '133893'
ORDER BY A.HANDLE DESC



