
/* ------------------------------- Documentos Movimentado ------------------------------- */

SELECT
    B.NOME AS EMPRESA,
    C.NOME AS FILIAL,
    A.DOCUMENTODIGITADO AS DOC,
    A.SERIE AS SERIE,
    A.NRNOTAFISCAL AS NOTA_FISCAL,
    A.NUMEROPEDIDO AS CONTRATO,
    D.NOME AS PESSOA,
    A.VALORNOMINAL AS VALOR_BRUTO,
    A.VALORLIQUIDO AS VALOR_LIQ,
    CASE
        WHEN A.STATUS = 1 THEN 'CADASTRADA'
        WHEN A.STATUS = 2 THEN 'EMITIDA'
        WHEN A.STATUS = 3 THEN 'CANCELADA'
        WHEN A.STATUS = 4 THEN 'COM DIVERGENCIAS'
        WHEN A.STATUS = 5 THEN 'AGUARDANDO SERVIDOR'
    ELSE '' END AS STATUS,
    CASE
        WHEN A.STATUS = 1  THEN 'CADASTRADO'
        WHEN A.STATUS = 2  THEN 'AGUARDANDO RETORNO'
        WHEN A.STATUS = 3  THEN 'REJEITADO'
        WHEN A.STATUS = 4  THEN 'EM CONTIGENCIA'
        WHEN A.STATUS = 5  THEN 'USO DENEGADO'
        WHEN A.STATUS = 6  THEN 'AUTORIZADO'
        WHEN A.STATUS = 7  THEN 'CANCELADO'
        WHEN A.STATUS = 8  THEN 'INUTILIZADO'
        WHEN A.STATUS = 9  THEN 'AGUARDANDO RET CANCLNUT'
        WHEN A.STATUS = 10 THEN 'AUTORIZADO SUBISTITUIDO'
    ELSE '' END AS STATUSNFE
FROM FN_DOCUMENTOS A
    LEFT JOIN EMPRESAS B ON B.HANDLE = A.EMPRESA
    LEFT JOIN FILIAIS C ON C.HANDLE = A.FILIAL
    LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.PESSOA
WHERE 1=1
    AND A.DOCUMENTOORIGEM IS NOT NULL
    --AND A.DOCUMENTODIGITADO = '133889'
ORDER BY 
    A.HANDLE DESC
