SELECT 
      CASE
            WHEN  A.BENEFICIARIOTITULAR IS NULL THEN '1' 
            ELSE '2' 
      END AS 'TIPO',
      A.NOME,
      A.LOGRADOURO,
      A.COMPLEMENTO,
      A.BAIRRO,
      A.CEP,
      D.NOME MUNICIPIO,
      C.SIGLA UF,
      A.FONERESIDENCIAL,
      A.FONECOMERCIAL,
      A.PERTODE,
      A.ENTRERUAS,
      CONVERT(VARCHAR,A.DATANASCIMENTO,112) AS DATANASCIMENTO,
      A.SEXO,
      E.NOME ESTADOCIVIL,
      A.CPF,
      A.RG,
      CASE
            WHEN A.BENEFICIARIOTITULAR IS NULL THEN A.HANDLE
            ELSE A.BENEFICIARIOTITULAR
      END AS CODIGOTIT,
      CASE
            WHEN A.BENEFICIARIOTITULAR IS NOT NULL THEN A.HANDLE
            ELSE NULL
      END AS CODIGODEP,
      CASE 
            WHEN A.TEMATENDIMENTO = 'S' THEN '1' 
            ELSE '0' 
      END AS 'TEMATENDIMENTO',
      A.STATUS ACAO,
      CONVERT(VARCHAR,A.DATAVIGOR,112) DATA,
      A.OBSERVACAO
FROM K_CN_CONTRATOBENEFICIARIOS A
      LEFT JOIN CN_CONTRATOS B ON A.CONTRATO = B.HANDLE
      LEFT JOIN ESTADOS C ON C.HANDLE = A.ESTADO
      LEFT JOIN MUNICIPIOS D ON D.HANDLE = A.MUNICIPIO
      LEFT JOIN GN_ESTADOSCIVIS E ON E.HANDLE = A.ESTADOCIVIL
WHERE 1=1
      AND B.HANDLE = 1021427
      AND A.STATUS = 1