
SELECT
C.NOME			AS TIPOCONTRATO,
A.NUMERO		AS NUMERO,
B.NOME			AS PESSOA,
D.NOME			AS CONSULTOR,
E.NOME			AS AGRUP,
CONCAT(B.LOGRADOURO, ', ', B.NUMEROLOG) AS ENDERECO,
B.COMPLEMENTO	AS COMPLEMENTO,
B.BAIRRO		AS BAIRRO,
CONCAT('(',F.DDD, ') ', F.TELEFONE) AS TELEFONE,
ISNULL((SELECT SUM(C2.VALOR) FROM K_CN_CONTRATOBENEFICIARIOS C1 LEFT JOIN K_CN_CONTRATOBENPRODUTOS C2 ON C2.CONTRATOBENEFICIARIO = C1.HANDLE WHERE C1.CONTRATO = A.HANDLE AND C1.STATUS = 1), 0) AS VALORANTERIOS,
ISNULL((SELECT COUNT(HANDLE) FROM K_CN_CONTRATOBENEFICIARIOS C1 WHERE C1.CONTRATO = A.HANDLE AND C1.STATUS = 1), 0) AS QTDVIDAS,
A.K_DTBASE		AS DTBASE,
ISNULL((
SELECT COUNT(A3.HANDLE)
FROM K_CN_CONTRATOSYS4WEB A1 
LEFT JOIN K_CN_CONTRATOSYS4WEBSERVICOS A2 ON A2.CONTRATOSYS4WEB = A1.HANDLE 
LEFT JOIN K_CN_CONTRATOSYS4WEBSERVATENDI A3 ON A3.CONTRATOSYS4WEBSERVICO = A2.HANDLE 
WHERE A1.HANDLE = A.K_IDCONTRATOSYS4WEB
),0 )			AS ATENDT,	/* TOTAL DE ATENDIMENTOS */
ISNULL((
SELECT COUNT(A3.HANDLE)
FROM K_CN_CONTRATOSYS4WEB A1 
LEFT JOIN K_CN_CONTRATOSYS4WEBSERVICOS A2 ON A2.CONTRATOSYS4WEB = A1.HANDLE 
LEFT JOIN K_CN_CONTRATOSYS4WEBSERVATENDI A3 ON A3.CONTRATOSYS4WEBSERVICO = A2.HANDLE 
WHERE A1.HANDLE = A.K_IDCONTRATOSYS4WEB AND 
DATEDIFF(day,A3.DATAATENDIMENTO ,GETDATE())<=365
),0)			AS ATENDULT, /* TOTAL ATENDIMENTOS ULTIMOS 12 MESES*/
G.NOME			AS RESPONSAVEL
FROM CN_CONTRATOS A
LEFT JOIN GN_PESSOAS B ON B.HANDLE = A.PESSOA
LEFT JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = A.TIPOCONTRATO
LEFT JOIN GN_PESSOAS D ON D.HANDLE = A.K9_AGENTEVENDAS
LEFT JOIN K_CN_AGRUPAMENTOS E ON E.HANDLE = B.K_AGRUPAMENTO
LEFT JOIN GN_PESSOATELEFONES F ON F.PESSOA = B.HANDLE 
LEFT JOIN GN_PESSOAS G ON G.HANDLE = A.K9_AGENTEVENDAS
WHERE 1=1
AND A.STATUS = 2
AND A.FILIAL = 1
--AND A.NUMERO = 'TFA-00042324-CT'

/*


SELECT 
A.HANDLE, 
B.HANDLE HANDLEPESSOA, 
A.NUMERO, 
A.K_DTBASE DATA_BASE, 
B.NOME PESSOA
B.LOGRADOURO +', '+ B.NUMEROLOG ENDEREÇO, 
B.COMPLEMENTO, 
B.BAIRRO, 
UPPER (C.NOME) FORMAPAGAMENTO, 
D.NOME TIPOPARCELA,
E.NOME TIPOCONTRATO, 
G.LOGOTIPO, 
CAST(SUM(I.VALOR) AS DECIMAL(10,2)) AS VALORANTERIOR,
O.NOME AGRUP,
N.APELIDO,
CASE WHEN A.K_IDLEGADO IS NOT NULL THEN A.K_IDLEGADO ELSE A.HANDLE END HANDLESYS4WEB
FROM CN_CONTRATOS A
LEFT JOIN GN_PESSOAS B ON B.HANDLE = A.PESSOA
LEFT JOIN FN_FORMASPAGAMENTO C ON C.HANDLE = A.FORMAPAGAMENTO
LEFT JOIN K_CN_TIPOPARCELAS D ON D.HANDLE = A.K_TIPOPARCELA
LEFT JOIN CN_TIPOSCONTRATOS E ON E.HANDLE = A.TIPOCONTRATO
LEFT JOIN CT_CC F ON F.HANDLE = A.CENTROCUSTO
LEFT JOIN FILIAIS G ON G.HANDLE = A.FILIAL
INNER JOIN K_CN_CONTRATOBENEFICIARIOS H ON H.CONTRATO = A.HANDLE AND H.STATUS = 1
LEFT JOIN K_CN_CONTRATOBENPRODUTOS I ON I.CONTRATOBENEFICIARIO = H.HANDLE
LEFT JOIN K_CN_AGRUPAMENTOS O ON O.HANDLE = B.K_AGRUPAMENTO
--LEFT JOIN GN_PESSOATELEFONES P ON P.PESSOA = B.HANDLE
LEFT JOIN GN_PESSOAS N ON A.K9_AGENTEVENDAS = N.HANDLE
WHERE A.STATUS IN (1,2)
AND A.FILIAL = @FILIAL
GROUP BY A.HANDLE, A.NUMERO, A.K_DTBASE, B.NOME , UPPER(C.NOME), D.NOME, O.NOME, B.TELEFONEEMPRESA,N.APELIDO,
E.NOME, G.LOGOTIPO,B.LOGRADOURO, B.NUMEROLOG, B.COMPLEMENTO, B.BAIRRO, B.HANDLE,CASE WHEN A.K_IDLEGADO IS NOT NULL THEN A.K_IDLEGADO ELSE A.HANDLE END


*/