

/* ------------------ IMPORTAÇÃO CONTRATOS ------------------ */

SELECT '' AS ' ', '' AS ' ', '------------------ IMPORTAÇÃO CONTRATOS ------------------'

SELECT 
A.HANDLE 			AS CODIGO,
C.HANDLE 			AS COD_EMPRESA,
C.NOME				AS EMPRESA,
B.HANDLE 			AS ID_CONTRATO,
B.NUMERO 			AS CONTRADO,
D.NOME 				AS USUARIO_INCLUSAO,
A.ARQUIVO			AS ARQUIVO,
A.PERCENTUALCONCLUIDO AS PORCETAGEM,
(A.QTDELINHAS * A.PERCENTUALCONCLUIDO) / 100 AS LINHAS_CONCLUIDAS,
A.QTDELINHAS 		AS TOTAL_LINHAS,
A.DATAINCLUSAO 		AS DT_INCLUSAO,
A.TEXTO				AS TEXTO,
A.TEXTODIVERGENCIA 	AS TEXTO_DIVERGENCIA,
CASE
	WHEN A.STATUS = 1 THEN '1 - NÃO PROCESSADO'
	WHEN A.STATUS = 2 THEN '2 - EM PROCESSAMENTO'
	WHEN A.STATUS = 3 THEN '3 - CONCLUIDO COM SUCESSO'
	WHEN A.STATUS = 4 THEN '4 - CONCLUIDO COM ERRO'
	ELSE ''
END 				AS STATUS_IMPORTACAO,
E.HANDLE 			AS COD_PROCESSO,
E.NOME 				AS PROCESSO,
E.INICIO 			AS INICIO,
E.FIM 				AS FIM,
E.USUARIO 			AS USUARIO,
E.HOST				AS HOST,
CASE
	WHEN E.SITUACAO = 1 THEN '1 - PROCESSANDO'
	WHEN E.SITUACAO = 2 THEN '2 - CANCELAMENTO SOLICITADO'
	WHEN E.SITUACAO = 3 THEN '3 - CANCELADO'
	WHEN E.SITUACAO = 4 THEN '4 - FINALIZADO COM ERROS'
	WHEN E.SITUACAO = 5 THEN '5 - FINALIZADOS COM SUCESSO'
	WHEN E.SITUACAO = 6 THEN '6 - PENDENTE'
ELSE ''
END 				AS STATUS_PROCESSO,
SUBSTRING(CONVERT(VARCHAR, E.DURACAO,113), 12, 9) AS DURACAO
--UPDATE K_CN_CONTRATOIMPORTACAO SET STATUS = 4
FROM K_CN_CONTRATOIMPORTACAO A
LEFT JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
LEFT JOIN EMPRESAS C ON C.HANDLE = B.EMPRESA
LEFT JOIN Z_GRUPOUSUARIOS D ON D.HANDLE = A.USUARIOINCLUSAO
LEFT JOIN Z_PROCESSOS E ON E.HANDLE = A.PROCESSOHANDLE
WHERE 1=1
/* EM PROCESSAMENTO */AND A.STATUS = 2
ORDER BY A.DATAINCLUSAO ASC




/* ------------------ REQUISIÇÕES ------------------ */


SELECT '' AS ' ', '' AS ' ', '------------------ REQUISIÇÕES ------------------'

SELECT * 
FROM Z_BTLREQUISICOES
--DELETE FROM Z_BTLREQUISICOES
WHERE 1=1
AND EMPRESA = 18 
--/* PEDENTE */    AND STATUS = 1
/* EXECUTANDO */ AND STATUS = 2



/* ------------------ PROCESSOS ------------------ */


SELECT '' AS ' ','' AS ' ', '------------------ PROCESSOS ------------------'

SELECT * 
--DELETE FROM Z_PROCESSOS
FROM Z_PROCESSOS 
WHERE 1=1
/* PROCESSANDO */ AND SITUACAO = 1
--/* PEDENTE */     AND SITUACAO = 6
