SELECT 
B.HANDLE AS HNL_BENE, 
A.HANDLE AS HND_PROD  
FROM K_CN_CONTRATOBENPRODUTOS A 
INNER JOIN K_CN_CONTRATOBENEFICIARIOS B ON (A.CONTRATOBENEFICIARIO = B.HANDLE)
WHERE 1=1
AND B.STATUS  = 1 
AND B.CONTRATO  = 1002250
