

/*------------------- CRIAR TABELA TEMPORARIA -------------------*/


/* PEGAR O ULTIMO HANDLE DA TABELA */
SELECT MAX(HANDLE) +  1 FROM K_CN_CONTRATOBENPRODUTOS


CREATE TABLE #PROD_BENEFICIARIOS 
(
HANDLE 						INT IDENTITY(4202683,1) PRIMARY KEY,
Z_GRUPO 					INT,
CONTRATOBENEFICIARIO 		INT,
PRODUTO 					INT,
AGENTEVENDA 				INT,
VALOR 						FLOAT,
DATABASEEM 					DATE,
PARCELA 					INT,
TELEVENDAS 					INT,
USUARIOINCLUIU 				INT,
DATAINCLUIU 				DATETIME,
USUARIOALTEROU 				INT,
DATAALTEROU 				DATETIME,
VALORANTERIOR 				FLOAT,
PERCENTUALREAJUSTE 			FLOAT,
PROD32LEGADO 				INT,
PROD2LEGADO 				INT,
REGRACOMISSAO 				INT,
K9_CONTRATOBENEFICIARIOHIST INT,
K9_INATIVAPRODUTO 			CHAR(1),
K9_DATAINATIVACAO 			DATETIME,
K9_USUARIOINATIVOU 			INT,
K9_CONTRATOCARNE 			INT,
K9_ATUALIZARCARNE 			INT,
K9_TIPOCARNE 				INT,
K9_DATAREAJUSTE 			DATETIME,
K9_DATAINICIAL 				DATETIME,
K9_QTDEPARCELAS 			INT,
K9_DATAFINAL 				DATE
)

/*------------------- INSERIR NA TABELA TEMPORARIA -------------------*/


--INSERT INTO #PROD_BENEFICIARIOS
SELECT DISTINCT
NULL AS Z_GRUPO,
B.CONTRATOBENEFICIARIO,
269349 AS PRODUTO,
NULL AS AGENTEVENDA,
0 AS VALOR, 
GETDATE() AS DATABASEEM,
NULL AS PARCELA,
NULL AS TELEVENDAS,
1183 AS USUARIOINCLUIU,
GETDATE() AS DATAINCLUIU,
NULL AS USUARIOALTEROU,
GETDATE() AS DATAALTEROU,
NULL AS VALORANTERIOR,
NULL AS PERCENTUALREAJUSTE,
NULL AS PROD32LEGADO,
NULL AS PROD2LEGADO,
NULL AS REGRACOMISSAO,
NULL AS K9_CONTRATOBENEFICIARIOHIST,
NULL AS K9_INATIVAPRODUTO,
NULL AS K9_DATAINATIVACAO,
NULL AS K9_USUARIOINATIVOU,
NULL AS K9_CONTRATOCARNE,
NULL K9_ATUALIZARCARNE,
NULL AS K9_TIPOCARNE,
NULL AS K9_DATAREAJUSTE,
NULL AS K9_DATAINICIAL,
NULL AS K9_QTDEPARCELAS,
NULL AS K9_DATAFINAL
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN K_CN_CONTRATOBENPRODUTOS B ON B.CONTRATOBENEFICIARIO = A.HANDLE
INNER JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
WHERE 1=1
AND A.STATUS = 1
AND A.CONTRATO IN (19071)


/*------------------- INSERIR NA TABELA DE PRODUTOS -------------------*/


--INSERT INTO K_CN_CONTRATOBENPRODUTOS
SELECT * FROM #PROD_BENEFICIARIOS


/*------------------- VERIFICAR VALORES DOS PRODUTOS E DOS BENEFICIARIOS -------------------*/

-- * TABELA DOS BENEFICIARIOS

SELECT
A.CONTRATO,
A.NOME,
A.CPF,
CASE
 WHEN A.BENEFICIARIOTITULAR IS NULL THEN 'TITULAR'
ELSE 'DEPENDENTE'
END AS TIPO_BENEFICIARIO,
A.VALOR AS VALOR
--UPDATE K_CN_CONTRATOBENEFICIARIOS SET VALOR = A.VALOR + 2
FROM K_CN_CONTRATOBENEFICIARIOS A
WHERE 1=1
AND A.STATUS = 1
AND A.CONTRATO IN (19071)
--AND A.BENEFICIARIOTITULAR IS NOT NULL
--AND A.BENEFICIARIOTITULAR IS NULL


-- * TABELA DOS PRODUTOS (BENEFICIARIOS)


SELECT 
A.HANDLE AS ID,
A.NOME 	AS BENEFICIARIO,
A.CPF 	AS CPF,
CASE
WHEN A.BENEFICIARIOTITULAR IS NULL THEN 'TITULAR'
ELSE 'DEPENDENTE'
END AS TIPO_BENEFICIARIO,
C.HANDLE AS COD_PROD,
C.NOME 	AS PRODUTO,
B.VALOR AS VALOR
--UPDATE K_CN_CONTRATOBENPRODUTOS SET VALOR = 10.01
FROM K_CN_CONTRATOBENEFICIARIOS A
INNER JOIN K_CN_CONTRATOBENPRODUTOS B ON B.CONTRATOBENEFICIARIO = A.HANDLE
INNER JOIN PD_PRODUTOS C ON C.HANDLE = B.PRODUTO
WHERE 1=1
/* STATUS BENEFICIARIO */	AND A.STATUS = 1
/* CONTRATO */ 				AND A.CONTRATO IN (19071)
/* PRODUTO */ 				--AND C.HANDLE = 269349
/* SOMENTE TITULAR*/		--AND A.BENEFICIARIOTITULAR IS NOT NULL
/* SOMENTE DEPEDENTE */		--AND A.BENEFICIARIOTITULAR IS NULL


/*------------------- EXCLUIR TABELA TEMPORARIA -------------------*/

DROP TABLE #PROD_BENEFICIARIOS

/*------------------- PEGAR CAMPOS DA TABELA -------------------*/

/*

SELECT
    
    CASE	
    	WHEN A.system_type_id = 56 THEN CONCAT(A.NAME, ' ', 'INT,')
    	WHEN A.system_type_id = 61 THEN CONCAT(A.NAME, ' ', 'DATE,')
    	WHEN A.system_type_id = 62 THEN CONCAT(A.NAME, ' ', 'FLOAT,')
    	WHEN A.system_type_id = 175 THEN CONCAT(A.NAME, ' ', 'CHAR', '(', A.max_length, '),')
		WHEN A.system_type_id = 167 THEN CONCAT(A.NAME, ' ', 'VARCHAR', '(', A.max_length, '),')
    ELSE ''
   	END AS COLUNAS 	
FROM sys.COLUMNS A
    LEFT JOIN SYS.tables B ON B.object_id = A.object_id
WHERE 1=1
	AND B.name = 'K_CN_CONTRATOBENPRODUTOS'

*/

/*-------------------------------------- FIM -------------------------------------- */

