
/* FLUXO COMPLETO: CONTRATO -> BENEFICIARIO -> BENEFICIARIOPRODUTO -> PRODUTO*/ /*OBS: STACK OVERFLOW NA CONSULTA*/

/* FLUXO: CONTRATO -> BENEFICIARIOPRODUTO -> PRODUTO*/

/* FLUXO DE EXEMPLO: PRODUTOS -> BENEFCIIARIO -> CONTRATO*/


/* ------------------------------- Contratos X Beneficiario X Produtos ------------------------------- */

SELECT
    D.NUMERO AS CONTRATO,
    E.NOME AS PERFIL_CONTRATO,
    B.CODIGO AS COD_BENEFICIARIO,
    B.NOME AS BENEFICIARIO,
    CASE
        WHEN B.BENEFICIARIOTITULAR <> '' THEN "DEPENDENTE"
        ELSE 'TITULAR'
    END AS TIPO_BENEFICIARIO,
    CONCAT(C.CODIGO, " - ", C.NOME) AS PRODUTO,
    A.VALOR AS VALOR
FROM K_CN_CONTRATOBENPRODUTOS AS A
/* BENEFICIARIOS DO CONTRATO */ LEFT JOIN K_CN_CONTRATOBENEFICIARIOS AS B ON B.HANDLE = A.CONTRATOBENEFICIARIO
/* PRODUTOS DO BENEFICIARIOS */ LEFT JOIN PD_PRODUTOS AS C ON C.HANDLE = A.PRODUTO
/* CONTRATOS */                 LEFT JOIN CN_CONTRATOS AS D ON D.HANDLE = B.CONTRATO
/* PERFIL DO CONTRATO */        LEFT JOIN CN_TIPOSCONTRATOS AS E ON E.HANDLE = D.TIPOCONTRATO
WHERE 1=1
    AND D.NUMERO = 'EF-00040211-CT'

/* ------------------------------- Total Vlr e Qtd de Beneficiarios por Contrato ------------------------------- */

SELECT
	C.EMPRESA AS EMPRESA,
	C.NUMERO AS CONTRATO,
	COUNT(B.CODIGO) AS QTD_BEN,
	SUM(A.VALOR) AS VLR_TOTAL
FROM K_CN_CONTRATOBENPRODUTOS AS A
/* BENEFICIARIOS DO CONTRATO */ LEFT JOIN K_CN_CONTRATOBENEFICIARIOS AS B ON B.HANDLE = A.CONTRATOBENEFICIARIO
/* CONTRATOS */                 LEFT JOIN CN_CONTRATOS AS C ON C.HANDLE = B.CONTRATO
WHERE 1=1
    AND C.NUMERO IS NOT NULL
    --AND C.NUMERO = 'EF-00040211-CT'
GROUP BY
    C.EMPRESA,
    C.NUMERO
ORDER BY 
	VLR_TOTAL DESC
