
SELECT 
    Q1.COD_EMPRESA,
    Q1.EMPRESA,
    COUNT(Q1.CONTRATO) AS CONTRATOS,
    SUM(Q1.VIDAS) AS VIDAS
FROM
(
    SELECT
        A.EMPRESA AS COD_EMPRESA,
        C.NOME AS EMPRESA,
        A.NUMERO AS CONTRATO,
        COUNT(B.HANDLE) AS VIDAS
    FROM CN_CONTRATOS A
        LEFT JOIN EMPRESAS C ON C.HANDLE = A.EMPRESA
        LEFT JOIN K_CN_CONTRATOBENEFICIARIOS B ON B.CONTRATO = A.HANDLE
    WHERE 1=1
    GROUP BY 
        A.EMPRESA,
        C.NOME,
        A.NUMERO
) Q1
WHERE 1=1
    AND Q1.COD_EMPRESA IS NOT NULL
GROUP BY 
    Q1.COD_EMPRESA,
    Q1.EMPRESA 
ORDER BY
	Q1.COD_EMPRESA
