
/* -------------------------------- INCLUSAO ------------------------------------ */




SELECT
	D.NOME EMPRESA,
    B.K_APELIDO CONTRATO,
	B.CNPJ,
	C.NOME TIPOCONTRATO,
    A.NOME ASSOCIADO,
    A.CPF,
    LEN(A.CPF) AS QTD_CTR,
	CASE 
		WHEN LEN(A.CPF) = 11 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-',	SUBSTRING(A.CPF,10,2))
		WHEN LEN(A.CPF) = 10 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-0',	SUBSTRING(A.CPF,10,2))
		WHEN CHARINDEX('.', A.CPF) > 0 THEN A.CPF
		WHEN A.CPF IS NULL THEN ''
    ELSE ''
    END AS CPF_FORMATADO,
    B.STATUS STATUSCONTRATO,
    A.STATUS STATUSBEN,
    A.TEMATENDIMENTO,
	A.DATAVIGOR
FROM K_CN_CONTRATOBENEFICIARIOS A
	INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
    INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
    INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
    AND B.STATUS = 2
    AND A.STATUS = 1
    AND A.TEMATENDIMENTO = 'S'
    AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
    AND DATAVIGOR BETWEEN CONVERT(DATE,DATEADD(DAY,-4,GETDATE())) AND CONVERT(DATE,GETDATE())
	--AND DATAVIGOR BETWEEN CONVERT(DATE,'2022-12-11') AND CONVERT(DATE,'2022-12-18')
ORDER BY A.CONTRATO


   
/* -------------------------------- EXCLUSAO ------------------------------------ */

-- DATA SOURCE 1

SELECT 
	D.NOME EMPRESA,
    B.K_APELIDO CONTRATO,
	B.CNPJ,
	C.NOME TIPOCONTRATO,
	A.NOME ASSOCIADO,
    A.CPF,
    LEN(A.CPF) AS QTD_CTR,
	CASE 
		WHEN LEN(A.CPF) = 11 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-',	SUBSTRING(A.CPF,10,2))
		WHEN LEN(A.CPF) = 10 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-0', SUBSTRING(A.CPF,10,2))
		WHEN LEN(A.CPF) = 9 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-00', SUBSTRING(A.CPF,10,2))
		WHEN CHARINDEX('.', A.CPF) > 0 THEN A.CPF
		WHEN A.CPF IS NULL THEN ''
    ELSE ''
    END AS CPF_FORMATADO,
	B.STATUS STATUSCONTRATO,
	A.STATUS STATUSBEN,
	A.TEMATENDIMENTO,
	B.DATASUSPENSAO
FROM K_CN_CONTRATOBENEFICIARIOS A
	INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
	INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
	INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
WHERE 1=1
	AND C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55) AND (B.STATUS = 5 OR B.STATUS = 2 AND A.STATUS = 2)
    AND A.TEMATENDIMENTO = 'S'
	AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)
	AND B.DATASUSPENSAO BETWEEN CONVERT(DATE,DATEADD(DAY,-4,GETDATE())) AND CONVERT(DATE,GETDATE())



-- DATA SOURCE 2


SELECT 
	D.NOME EMPRESA,
    B.K_APELIDO CONTRATO,
	B.CNPJ,
    C.NOME TIPOCONTRATO,
    A.NOME ASSOCIADO,
    A.CPF,
    LEN(A.CPF) AS QTD_CTR,
	CASE 
		WHEN LEN(A.CPF) = 11 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-',	SUBSTRING(A.CPF,10,2))
		WHEN LEN(A.CPF) = 10 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-0', SUBSTRING(A.CPF,10,2))
		WHEN LEN(A.CPF) = 9 AND CHARINDEX('.', A.CPF) = 0 THEN CONCAT(SUBSTRING(A.CPF,1,3),'.',SUBSTRING(A.CPF,4,3),'.',SUBSTRING(A.CPF,7,3) ,'-00', SUBSTRING(A.CPF,10,2))
		WHEN CHARINDEX('.', A.CPF) > 0 THEN A.CPF
		WHEN A.CPF IS NULL THEN ''
    ELSE ''
    END AS CPF_FORMATADO,
    B.STATUS STATUSCONTRATO,
    A.STATUS STATUSBEN,
    A.TEMATENDIMENTO,
    C2.DATAINCLUSAO
FROM K_CN_CONTRATOBENEFICIARIOS A
    INNER JOIN CN_CONTRATOS B ON B.HANDLE = A.CONTRATO
    INNER JOIN CN_TIPOSCONTRATOS C ON C.HANDLE = B.TIPOCONTRATO
    INNER JOIN EMPRESAS D ON D.HANDLE = B.EMPRESA
    INNER JOIN PD_STATUS C2 ON C2.HANDLEREGISTROORIGEM = A.HANDLE AND HANDLETABELAORIGEM = 6687 AND C2.STATUS = 2 AND C2.HANDLE IN 
	(
		SELECT MAX(C1.HANDLE) FROM PD_STATUS C1
		INNER JOIN K_CN_CONTRATOBENEFICIARIOS L1 ON L1.HANDLE = C1.HANDLEREGISTROORIGEM
		WHERE C1.HANDLETABELAORIGEM = 6687 AND C1.STATUS = 2 AND C1.DATAINCLUSAO BETWEEN  CONVERT(DATE,DATEADD(DAY,-4,GETDATE())) AND CONVERT(DATE,GETDATE())
		GROUP BY C1.HANDLEREGISTROORIGEM
	)
WHERE 1=1
	AND C.HANDLE IN (11, 20, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55)
    AND (B.STATUS = 5 OR B.STATUS = 2 AND A.STATUS = 2)
    AND A.TEMATENDIMENTO = 'S'
    AND B.EMPRESA IN (1, 2, 3, 5, 17, 18)