

SELECT 
*
FROM
(
SELECT 
SUA.UA_FILIAL		AS FILIAL,
SUA.UA_NUM			AS ATENDIMENTO,
SUA.UA_CLIENTE		AS COD_CLI,
SA1.A1_NOME			AS CLIENTE,
SUA.UA_VEND			AS COD_VEND,
SA3.A3_NOME			AS VENDEDOR,
SUA.UA_EMISSAO		AS EMISSAO,
SUA.UA_OPER			AS OPER_SUA,
SUA.UA_ZMONTAG		AS MONTAGEM,
SUA.UA_ZPRDMLT		AS PROD_MULT,
SUA.UA_ZPRDRIB		AS PROD_RIB,
SUA.UA_TPFRETE		AS TIPO_FRETE,
SUA.UA_ZDTAENT		AS DT_ENTREGA_ATM,
RTRIM(SA1.A1_MUN) + '/' + SA1.A1_EST AS CIDADE_UF_CLIENTE
FROM SUA010 SUA
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND YEAR(SUA.UA_EMISSAO) = '2021'
AND SUA.UA_OPER = '4'
AND SA3.A3_ZLOCVND <> 'M'
) AS ATENDIMENTO

