

SELECT 
SUA.UA_FILIAL	AS FILIAL,
SUA.UA_NUM		AS NUM_ATEND,
--SUA.UA_EMISSAO	AS EMISSAO_ATEND,
CONVERT(VARCHAR,CAST(SUA.UA_EMISSAO AS DATETIME),103) AS EMISSAO_ATEND,
SA1.A1_COD		AS COD_CLI,
SA1.A1_NREDUZ	AS CLIENTE,
SU5.U5_DDD		AS DDD, 
SU5.U5_FONE		AS FONE, 
SU5.U5_CELULAR	AS CELULAR,
SA3.A3_COD		AS COD_VEND,
SA3.A3_NREDUZ	AS VENDEDOR,
--SL1.L1_EMISNF   AS DT_FATURAMENTO,
CONVERT(VARCHAR,CAST(SL1.L1_EMISNF AS DATETIME),103) AS DT_FATURAMENTO,
SUA.UA_VLRLIQ	AS VLR_ATEND
FROM SUA010 SUA
LEFT JOIN SA1010 SA1 ON SA1.D_E_L_E_T_ = '' AND SA1.A1_COD = SUA.UA_CLIENTE AND SA1.A1_LOJA = SUA.UA_LOJA
LEFT JOIN SA3010 SA3 ON SA3.D_E_L_E_T_ = '' AND SA3.A3_COD = SUA.UA_VEND
LEFT JOIN SL1010 SL1 ON SL1.D_E_L_E_T_ = '' AND SL1.L1_FILIAL = SUA.UA_FILIAL AND SL1.L1_NUMATEN = SUA.UA_NUM
LEFT JOIN SU5010 SU5 ON SU5.D_E_L_E_T_ = '' AND SU5.U5_CODCONT = SUA.UA_CODCONT 
WHERE 1=1
AND SUA.D_E_L_E_T_ = ''
AND YEAR(SUA.UA_EMISSAO) = 2020
AND MONTH(SUA.UA_EMISSAO) IN (3,4,5,6,7)
AND SL1.L1_NUM IS NOT NULL
AND SL1.L1_ORCRES = ''
AND SL1.L1_EMISNF <> ''
AND SA3.A3_ZLOCVND IN  ('Z', 'L')
ORDER BY SUA.UA_EMISSAO

