

SELECT
CAIXA.NOME,
CAIXA.PRODUTO,
CAIXA.A
FROM 
(
SELECT 
A.NOME,
A.ALTURA,
A.COMPRIMENTO,
A.LARGURA,
B.B5_COD	AS PRODUTO,
B5_ALTURA,
B5_COMPR,
B5_LARG,
A.ALTURA * A.COMPRIMENTO * A.LARGURA AS M3_CAIXA,
B5_ALTURA * B5_COMPR * B5_LARG AS M3_PRODUTO,
(A.ALTURA * A.COMPRIMENTO * A.LARGURA) - (B5_ALTURA * B5_COMPR * B5_LARG) AS A
FROM ZCAIXAS A
LEFT JOIN SB5010 B ON B.D_E_L_E_T_ = '' AND B5_ALTURA <= ALTURA AND B5_COMPR <= COMPRIMENTO AND B5_LARG <= LARGURA AND B5_ALTURA <> '' AND B5_COMPR <> '' AND B5_LARG <> ''
--AND B.B5_COD = 'IC431I'
) AS CAIXA
ORDER BY CAIXA.A




