


SELECT 
UB_NUM,
UB_PRODUTO,
UB_ITEM ,
B.B5_ALTURA,
B.B5_LARG,
B.B5_COMPR,
A.UB_QUANT,
(B.B5_LARG*B.B5_COMPR) M2,
(B.B5_ALTURA*B.B5_LARG*B.B5_COMPR) M3,


(B.B5_LARG*B.B5_COMPR) * A.UB_QUANT M2_TOTAL,
(B.B5_ALTURA*B.B5_LARG*B.B5_COMPR) * A.UB_QUANT M3_TOTAL

FROM SUB010 A
LEFT JOIN SB5010 B ON B.D_E_L_E_T_ = '' AND B.B5_COD = A.UB_PRODUTO 
WHERE UB_NUM = '030506'