
/*
	CONFERIR SE SC EST� CORRETA (DOM PREDRO)
	
	SEMPRE GRAVA 002127 MAS ELA GERA UMA CERTA NA FILIAL
	
	SOMENTE COMPARAR OS CAMPOS DE RELACIONAMENTO COM O CUBO
	
	
*/

SELECT L2_FILIAL, L2_SOLCOM, L2_NUM, L2_PRODUTO, L2_ITEM,'----CONFERENCIA----' AS CONFERENCIA, *
FROM SL2010 
WHERE 1=1
AND D_E_L_E_T_ = '' 
AND L2_FILIAL = '0103' 
AND L2_PRODUTO = 'EQ429'

SELECT C1_FILENT, C1_NUM, C1_ORCAM, C1_PRODUTO, C1_ZITMORC,'----CONFERENCIA----' AS CONFERENCIA, *
FROM SC1010 
WHERE 1=1
AND D_E_L_E_T_ = '' 
AND C1_NUM = '003230'

SELECT C6_FILIAL, C6_SOLCOM, C6_PRODUTO, * FROM SC6010 
WHERE 1=1
AND D_E_L_E_T_ = '' 
AND C6_NUM = '012841'

