DEFINE @VARIVAEL1 VARCHAR(30)
DEFINE @VARIAVEL2 VARCHAR(30)
DECLARE @VARIVAEL1 VARCHAR(30)
DECLARE @VARIAVEL2 VARCHAR(30)
SET @VARIVAEL1 = $(@VARIVAEL1)
SET @VARIAVEL2 = $(@VARIVAEL2)
SELECT
 * 
FROM 'TABLE_1', 'TABLE_2', 'TABLE_X'...
WHERE 
'TABLE_1 - CAMPO_A' = 'TABLE_2 - CAMPO_A' AND
'TABLE_X - CAMPO_X' LIKE @VARIVAEL1
'TABLE_X - CAMPO_Y' LIKE @VARIAVEL2