

CREATE TABLE #AUX
   	(
     AUX_FILIAL     VARCHAR(4),
     AUX_ANOMES     VARCHAR(6),
     AUX_CODPROD    VARCHAR(15),
     AUX_PRODUTO    VARCHAR(70),
     AUX_UND        VARCHAR(2),
     AUX_SLD_INI_B9  FLOAT,
     AUX_SLD_ENT_SD1 FLOAT,
     AUX_SLD_SAI_SD2 FLOAT,
     AUX_SLD_ENT_SD3 FLOAT,
     AUX_SLD_SAI_SD3 FLOAT,
     AUX_SLD_FINAL   FLOAT,   	
	)


SELECT * FROM #AUX



INSERT INTO #AUX (AUX_FILIAL, AUX_ANOMES, AUX_CODPROD, AUX_PRODUTO, AUX_UND, AUX_SLD_INI_B9, AUX_SLD_ENT_SD1, AUX_SLD_SAI_SD2, AUX_SLD_ENT_SD3, AUX_SLD_SAI_SD3, AUX_SLD_FINAL)


SELECT * FROM SB9010 WHERE B9_COD = 'LB016F' AND YEAR(B9_DATA) = 2017

 SELECT SUM(B9_QINI)  FROM SB9010 WHERE D_E_L_E_T_ =  '' AND YEAR(B9_DATA) = 2017 AND B9_COD = 'LB016F'
 