/*---------------------CASO PRECISE CRIAR A TABLE---------------------------*/

CREATE TABLE TMPAUXFILIAL
    (
     AUX_FILIAL VARCHAR(4),
     AUX_CODPROD VARCHAR(15),
   	 AUX_ANOMES VARCHAR(6),
   	 AUX_SLD_MES FLOAT,	 
   	 AUX_CUST_UNI FLOAT,   	
   	 AUX_CST_MES FLOAT,
	 R_E_C_N_O_ INT IDENTITY(1,1),
	 R_E_C_D_E_L_ INT,
	)

--CASO A TABLE TMPAUX ESTJA DROPADA CRIAR ELA PRIMEIRAMENTE ANTES DE EXECUTAR A PROCEDURE


/*---------------------------SELECTS TABLES DA PROCEDURE----------------------------------------------*/


SELECT * FROM TMPAUX		--A PROCEDURE INSERE NAS TABLES TMPAUX E ZZ4010 AUTOMATICAMENTE 

SELECT * FROM ZZ4010		--A PROCEDURE INSERE NAS TABLES TMPAUX E ZZ4010 AUTOMATICAMENTE 
	
SELECT * FROM ZZ5010		--A TABLE ZZ5 SERÁ PREECHIDA APÓS A EXECUÇÃO DA PROCEDURE NO ADVPL (ALEXANDRE) 

DROP TABLE TMPAUX

/*---------------------------DELETE TABLES DA PROCEDURE----------------------------------------------*/


DELETE FROM ZZ4010		--A PROCEDURE DELETA AUTOMATICAMENTE ESSAS TABELAS NAO É NECESSARIO DELETAR MANUALMENTE

DELETE FROM TMPAUX		--A PROCEDURE DELETA AUTOMATICAMENTE ESSAS TABELAS NAO É NECESSARIO DELETAR MANUALMENTE


/*---------------------------EXECUTE E DROP PROCEDURE----------------------------------------------*/


EXECUTE FECHAESTQ		

DROP PROCEDURE FECHAESTQ


